In [1]:
import sys
import os
import mysql.connector
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Ambil konfigurasi database dari folder utama project kalian
sys.path.append(os.path.abspath('..'))
from config import get_db_config

config = get_db_config()

# 1. Koneksi ke Database Baru (Fase Migrasi Sekarang)
db_new = mysql.connector.connect(**config['db_new'])
cursor_new = db_new.cursor(dictionary=True)

# 2. Koneksi ke Database Masa Depan (DB_FUTURE)
# Catatan: Pastikan di file config.py kalian sudah ada key 'db_future' ya!
db_future = mysql.connector.connect(**config['db_future'])
cursor_future = db_future.cursor(dictionary=True)

print(f"✅ Sukses Terhubung ke Database Baru : {config['db_new']['database']}")
print(f"🚀 Sukses Terhubung ke DB_FUTURE     : {config['db_future']['database']}")

✅ Sukses Terhubung ke Database Baru : 3
🚀 Sukses Terhubung ke DB_FUTURE     : 3

In [2]:
tables_to_check = [
    # --- Bagian Cimut ---
    "izin_karyawan", 
    "verifikasi_izin", 
    "absensi", 
    "verifikasi_absensi", 
    "karyawan_resign",
    
    # --- Bagian Afrida (Fokus Utama) ---
    "jadwal", 
    "jadwal_hari", 
    "jadwal_detail", 
    "jadwal_pengajar", 
    "jadwal_siswa", 
    "catatan_kelas", 
    "catatan_kelas_tag", 
    "catatan_mingguan",
    
    # --- Bagian Hanif (Fokus Utama) ---
    "siswa", 
    "kursus_siswa", 
    "siswa_keluar", 
    "mitra", 
    "mitra_progres", 
    "kemitraan_verifikator", 
    "siswa_mitra", 
    "siswa_mitra_keluar"
]

In [3]:
# === Cell 2: Inspeksi Detektor Pintar dengan Prioritas Target Revisi di Atas ===
import pandas as pd
import numpy as np

print("================================================================================")
print(" 🕵️‍♂️ FORENSIK ARSITEKTUR KONTROL: DETEKTOR AUTO-SMART COMPILER (REVISI PRIORITY) 🕵️‍♂️ ")
print("================================================================================")

# List penampung data di memori untuk keperluan sorting visualisasi
revisi_tables_queue = []
identical_tables_queue = []

# --- TAHAP A: PROSES PEN ARIKAN DATA & EVALUASI STRUKTUR DI BELAKANG LAYAR ---
for table in tables_to_check:
    try:
        # 1. Ambil data asli dari DB_NEW untuk kebutuhan .info() dan sampel isi data
        query = f"SELECT * FROM `{table}`"
        df_real_data = pd.read_sql(query, db_new)
        
        # 2. Tarik Struktur Fisik Kolom dari DB_NEW
        query_new_struct = f"""
        SELECT 
            c.COLUMN_NAME AS 'Nama Kolom',
            c.COLUMN_TYPE AS 'Tipe Data MySQL',
            CONCAT(
                CASE WHEN c.IS_NULLABLE = 'YES' THEN '✅ NULL (Boleh Kosong)' ELSE '🛑 NOT NULL (Wajib Isi)' END,
                CASE WHEN c.EXTRA = 'auto_increment' THEN '\\n🚀 AUTO_INCREMENT' ELSE '' END
            ) AS 'Aturan Nullability & Increment',
            CASE 
                WHEN c.COLUMN_KEY = 'PRI' THEN '🔑 PRIMARY KEY (PK)'
                WHEN c.COLUMN_KEY = 'MUL' AND k.REFERENCED_TABLE_NAME IS NOT NULL THEN '🔗 FOREIGN KEY (FK)'
                WHEN c.COLUMN_KEY = 'MUL' THEN 'INDEX'
                ELSE '-'
            END AS 'Status Kunci',
            CASE 
                WHEN k.REFERENCED_TABLE_NAME IS NOT NULL THEN CONCAT(k.REFERENCED_TABLE_NAME, ' (', k.REFERENCED_COLUMN_NAME, ')')
                ELSE '-'
            END AS 'Rujukan Induk (FK Origin)',
            CASE WHEN c.DATA_TYPE = 'enum' THEN REPLACE(REPLACE(REPLACE(c.COLUMN_TYPE, 'enum(', ''), ')', ''), "'", "") ELSE '-' END AS 'Daftar Pilihan ENUM'
        FROM INFORMATION_SCHEMA.COLUMNS c
        LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE k 
            ON c.TABLE_SCHEMA = k.TABLE_SCHEMA AND c.TABLE_NAME = k.TABLE_NAME AND c.COLUMN_NAME = k.COLUMN_NAME
        WHERE c.TABLE_SCHEMA = '{config['db_new']['database']}' AND c.TABLE_NAME = '{table}'
        ORDER BY c.ORDINAL_POSITION;
        """
        df_struct_new = pd.read_sql(query_new_struct, db_new).drop_duplicates(subset=['Nama Kolom'], keep='first').reset_index(drop=True)
        
        # Lacak tabel anak yang nge-FK ke PK tabel ini di DB_NEW
        pk_referenced_list = []
        for idx, row_skri in df_struct_new.iterrows():
            if row_skri['Status Kunci'] == '🔑 PRIMARY KEY (PK)':
                lookup_fk_query = f"""
                SELECT CONCAT(TABLE_NAME, ' (', COLUMN_NAME, ')') as relasi
                FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
                WHERE REFERENCED_TABLE_SCHEMA = '{config['db_new']['database']}'
                  AND REFERENCED_TABLE_NAME = '{table}'
                  AND REFERENCED_COLUMN_NAME = '{row_skri['Nama Kolom']}';
                """
                df_relasi_luar = pd.read_sql(lookup_fk_query, db_new)
                if not df_relasi_luar.empty:
                    pk_referenced_list.append("\n".join(df_relasi_luar['relasi'].tolist()))
                else:
                    pk_referenced_list.append("-")
            else:
                pk_referenced_list.append("-")
        df_struct_new['Tabel Yang nge-FK (DB_NEW)'] = pk_referenced_list

        # 3. Tarik Struktur Fisik Kolom dari DB_FUTURE
        query_future_struct = f"""
        SELECT 
            c.COLUMN_NAME AS 'Nama Kolom',
            c.COLUMN_TYPE AS 'Tipe Data MySQL',
            CONCAT(
                CASE WHEN c.IS_NULLABLE = 'YES' THEN '✅ NULL (Boleh Kosong)' ELSE '🛑 NOT NULL (Wajib Isi)' END,
                CASE WHEN c.EXTRA = 'auto_increment' THEN '\\n🚀 AUTO_INCREMENT' ELSE '' END
            ) AS 'Aturan Nullability & Increment',
            CASE 
                WHEN c.COLUMN_KEY = 'PRI' THEN '🔑 PRIMARY KEY (PK)'
                WHEN c.COLUMN_KEY = 'MUL' AND k.REFERENCED_TABLE_NAME IS NOT NULL THEN '🔗 FOREIGN KEY (FK)'
                WHEN c.COLUMN_KEY = 'MUL' THEN 'INDEX'
                ELSE '-'
            END AS 'Status Kunci',
            CASE 
                WHEN k.REFERENCED_TABLE_NAME IS NOT NULL THEN CONCAT(k.REFERENCED_TABLE_NAME, ' (', k.REFERENCED_COLUMN_NAME, ')')
                ELSE '-'
            END AS 'Rujukan Induk (FK Origin)',
            CASE WHEN c.DATA_TYPE = 'enum' THEN REPLACE(REPLACE(REPLACE(c.COLUMN_TYPE, 'enum(', ''), ')', ''), "'", "") ELSE '-' END AS 'Daftar Pilihan ENUM'
        FROM INFORMATION_SCHEMA.COLUMNS c
        LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE k 
            ON c.TABLE_SCHEMA = k.TABLE_SCHEMA AND c.TABLE_NAME = k.TABLE_NAME AND c.COLUMN_NAME = k.COLUMN_NAME
        WHERE c.TABLE_SCHEMA = '{config['db_future']['database']}' AND c.TABLE_NAME = '{table}'
        ORDER BY c.ORDINAL_POSITION;
        """
        df_struct_future = pd.read_sql(query_future_struct, db_future).drop_duplicates(subset=['Nama Kolom'], keep='first').reset_index(drop=True)
        
        # Lacak tabel anak yang nge-FK ke PK tabel ini di DB_FUTURE
        pk_referenced_list_future = []
        for idx, row_skri in df_struct_future.iterrows():
            if row_skri['Status Kunci'] == '🔑 PRIMARY KEY (PK)':
                lookup_fk_query_future = f"""
                SELECT CONCAT(TABLE_NAME, ' (', COLUMN_NAME, ')') as relasi
                FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
                WHERE REFERENCED_TABLE_SCHEMA = '{config['db_future']['database']}'
                  AND REFERENCED_TABLE_NAME = '{table}'
                  AND REFERENCED_COLUMN_NAME = '{row_skri['Nama Kolom']}';
                """
                df_relasi_luar_future = pd.read_sql(lookup_fk_query_future, db_future)
                if not df_relasi_luar_future.empty:
                    pk_referenced_list_future.append("\n".join(df_relasi_luar_future['relasi'].tolist()))
                else:
                    pk_referenced_list_future.append("-")
            else:
                pk_referenced_list_future.append("-")
        df_struct_future['Tabel Yang nge-FK (DB_FUTURE)'] = pk_referenced_list_future

        # 4. Deep Comparison Kesamaan Jeroan Kolom dasar
        cols_to_compare = ['Nama Kolom', 'Tipe Data MySQL', 'Aturan Nullability & Increment', 'Status Kunci', 'Rujukan Induk (FK Origin)', 'Daftar Pilihan ENUM']
        
        is_structure_identical = False
        if not df_struct_new.empty and not df_struct_future.empty:
            is_structure_identical = df_struct_new[cols_to_compare].equals(df_struct_future[cols_to_compare])

        # Wadah paket data tabel untuk di-render nanti
        table_package = {
            'name': table,
            'df_real_data': df_real_data,
            'df_struct_new': df_struct_new,
            'df_struct_future': df_struct_future,
            'is_identical': is_structure_identical
        }

        # 🔥 FILTER SAKTI CIMUT: Pisahkan antrean, utamakan yang bermasalah (revisi) ke atas!
        if is_structure_identical:
            identical_tables_queue.append(table_package)
        else:
            revisi_tables_queue.append(table_package)
            
    except Exception as e:
        print(f"❌ Gagal menganalisis awal tabel `{table}`: {e}")

# --- TAHAP B: MULAI PEN TAMPILAN VISUALISASI BERDASARKAN ANT REAN PRIORITAS ---

# 🚨 1. KELOMPOK UTAMA (PALING ATAS): DAFTAR TABEL YANG WAJIB DIREVISI 🚨
if revisi_tables_queue:
    print("\n" + "!"*80)
    print(f"🚨 [🔥 REVISI PRIORITY BOARD] TERDETEKSI {len(revisi_tables_queue)} TABEL BERBEDA - HARUS SEGERA DIPERBAIKI!")
    print("!"*80)
    
    for pkg in revisi_tables_queue:
        print(f"\n================================================================================")
        print(f"⚠️  [STATUS: TARGET REVISI] TABEL: {pkg['name'].upper()}")
        print(f"================================================================================")
        
        print(f"📋 1. Karakteristik Wadah Pandas Dataframe (.info()):")
        pkg['df_real_data'].info()
        print("\n" + "-"*60)
        
        print(f"🔍 2. [TABEL REAL SAAT INI] Arsitektur Fisik Kolom pada DB_NEW:")
        display(pkg['df_struct_new'].style.set_properties(**{'white-space': 'pre-wrap', 'text-align': 'left'}))
        print("\n" + "-"*60)
        
        print(f"🔮 3. [⚠️ TARGET BLUEPRINT RUJUKAN] Tinjau Struktur yang Benar pada DB_FUTURE di bawah:")
        if pkg['df_struct_future'].empty:
            print("❌ ERROR: Tabel ini tidak ditemukan / belum dibuat sama sekali di DB_FUTURE!")
        else:
            display(pkg['df_struct_future'].style.set_properties(**{'white-space': 'pre-wrap', 'text-align': 'left'}))
        print("\n" + "-"*60)
        
        print(f"📸 4. Sampel Isi Data Real di DB_NEW:")
        display(pkg['df_real_data'] if pkg['df_real_data'].empty else pkg['df_real_data'])
        print("\n" + "="*80)

# ✨ 2. KELOMPOK KEDUA (BAW AH): DAFTAR TABEL YANG SUDAH AMAN IDENTIK ✨
if identical_tables_queue:
    print("\n" + "="*80)
    print(f"✨ [🟢 PERFECTLY MATCHED BOARD] SEBANYAK {len(identical_tables_queue)} TABEL STRUKTURNYA SUDAH IDENTIK SAMA PERSIS!")
    print("="*80)
    
    for pkg in identical_tables_queue:
        print(f"\n================================================================================")
        print(f"✅ [STATUS: AMAN IDENTIK] TABEL: {pkg['name'].upper()}")
        print(f"================================================================================")
        
        print(f"📋 1. Karakteristik Wadah Pandas Dataframe (.info()):")
        pkg['df_real_data'].info()
        print("\n" + "-"*60)
        
        print(f"🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:")
        display(pkg['df_struct_new'].style.set_properties(**{'white-space': 'pre-wrap', 'text-align': 'left'}))
        print("\n" + "-"*60)
        
        print("✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨")
        print("ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.")
        print("\n" + "-"*60)
        
        print(f"📸 3. Sampel Isi Data Real di DB_NEW:")
        display(pkg['df_real_data'] if pkg['df_real_data'].empty else pkg['df_real_data'])
        print("\n" + "="*80)

================================================================================
 🕵️‍♂️ FORENSIK ARSITEKTUR KONTROL: DETEKTOR AUTO-SMART COMPILER (REVISI PRIORITY) 🕵️‍♂️
================================================================================

================================================================================
✨ [🟢 PERFECTLY MATCHED BOARD] SEBANYAK 21 TABEL STRUKTURNYA SUDAH IDENTIK SAMA PERSIS!
================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: IZIN_KARYAWAN
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1914 entries, 0 to 1913
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_izin           1914 non-null   int64
 1   id_karyawan       1914 non-null   int64
 2   jenis_izin        1914 non-null   object
 3   tanggal_mulai     1914 non-null   object
 4   tanggal_selesai   1914 non-null   object
 5   waktu_mulai       1914 non-null   timedelta64[ns]
 6   waktu_selesai     1914 non-null   timedelta64[ns]
 7   keterangan_izin   1914 non-null   object
 8   dokumen_lampiran  1914 non-null   object
 9   created_at        1914 non-null   datetime64[ns]
dtypes: datetime64[ns](1), int64(2), object(5), timedelta64[ns](2)
memory usage: 149.7+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

,id_izin,id_karyawan,jenis_izin,tanggal_mulai,tanggal_selesai,waktu_mulai,waktu_selesai,keterangan_izin,dokumen_lampiran,created_at
0,1,4,,2023-11-10,2023-11-10,0 days 15:30:00,0 days 17:00:00,Al muslin ekskul,,2023-11-13 07:34:57
1,2,4,,2023-11-13,2023-11-13,0 days 07:00:00,0 days 08:30:00,pengganti Al muslim,,2023-11-13 07:35:47
2,3,5,,2023-11-26,2023-11-26,0 days 16:00:00,0 days 18:00:00,Mengganti 2 jam kerja Senin 27 November 2023 j...,1701093214_10eabbf62174540924e1.jpeg,2023-11-27 20:53:34
3,4,5,,2023-12-02,2023-12-02,0 days 09:00:00,0 days 13:00:00,"Mengganti 4 jam kerja Kamis, 30 November 2023 ...",1701093670_6ed710a3b721f5b1b08d.pdf,2023-11-27 21:01:10
4,5,2,,2023-11-29,2023-11-29,0 days 13:00:00,0 days 15:00:00,Les Coding agnes,,2023-11-29 13:24:43
...,...,...,...,...,...,...,...,...,...,...
1909,1910,11,Ijin,2026-02-27,2026-02-27,0 days 07:00:00,0 days 16:05:00,Terlambat,,2026-04-06 17:01:49
1910,1911,11,Ijin,2026-03-31,2026-03-31,0 days 07:00:00,0 days 17:15:00,Terlambat,,2026-04-06 17:02:36
1911,1912,4,Ijin,2026-04-08,2026-04-08,0 days 18:15:00,0 days 19:15:00,"ijin pulang lebih cepat karena mau ke bengkel,...",,2026-04-08 11:40:20
1912,1913,18,Lembur,2026-03-31,2026-03-31,0 days 09:17:00,0 days 10:05:00,"tabungan jam maret, 58 menit",1775649994_ebf653ce91e06066e37c.jpg,2026-04-08 19:06:34
1913,1914,15,Ijin,2026-04-14,2026-04-14,0 days 10:00:00,0 days 17:00:00,"izin buat meeting job di tempat lain seharin, ...",,2026-04-13 16:21:39

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: VERIFIKASI_IZIN
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id_verifikasi_izin      0 non-null      object
 1   id_izin                 0 non-null      object
 2   status_verifikasi_izin  0 non-null      object
 3   catatan_verifikator     0 non-null      object
 4   status_baca             0 non-null      object
 5   id_division             0 non-null      object
 6   created_at              0 non-null      object
dtypes: object(7)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

Empty DataFrame
Columns: [id_verifikasi_izin, id_izin, status_verifikasi_izin, catatan_verifikator, status_baca, id_division, created_at]
Index: []

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: ABSENSI
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id_absensi             0 non-null      object
 1   id_karyawan            0 non-null      object
 2   id_izin                0 non-null      object
 3   tanggal                0 non-null      object
 4   jam_masuk              0 non-null      object
 5   jam_keluar             0 non-null      object
 6   catatan_masuk          0 non-null      object
 7   catatan_keluar         0 non-null      object
 8   status_absensi         0 non-null      object
 9   tipe_absensi           0 non-null      object
 10  id_verifikasi_absensi  0 non-null      object
 11  created_at             0 non-null      object
dtypes: object(12)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

Empty DataFrame
Columns: [id_absensi, id_karyawan, id_izin, tanggal, jam_masuk, jam_keluar, catatan_masuk, catatan_keluar, status_absensi, tipe_absensi, id_verifikasi_absensi, created_at]
Index: []

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: VERIFIKASI_ABSENSI
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 4 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id_verifikasi_absensi      11 non-null     int64
 1   status_verifikasi_absensi  11 non-null     object
 2   catatan_atasan             11 non-null     object
 3   created_at                 11 non-null     datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 484.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

,id_verifikasi_absensi,status_verifikasi_absensi,catatan_atasan,created_at
0,1,Disetujui,<p>dcvbhnjk</p>,2023-05-17 15:54:46
1,3,Disetujui,<p>sudah oke untuk absensi</p>,2023-07-18 18:21:38
2,4,Disetujui,<p>okee</p>,2024-11-30 00:00:00
3,5,Disetujui,,2024-10-01 00:00:00
4,6,Disetujui,<p>Sudah ACC</p>,2024-04-01 00:00:00
5,7,Disetujui,<p>Sudah ACC</p>,2024-06-01 00:00:00
6,8,Disetujui,<p>Sudah ACC</p>,2024-08-01 00:00:00
7,9,Disetujui,<p>Sudah ACC</p>,2024-08-01 00:00:00
8,10,Disetujui,<p>Sudah ACC</p>,2024-09-01 00:00:00
9,11,Disetujui,<p>Sudah ACC</p>,2024-05-01 00:00:00
10,12,Disetujui,<p>Sudah ACC</p>,2024-07-01 00:00:00

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: KARYAWAN_RESIGN
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_resign           51 non-null     int64
 1   id_karyawan         51 non-null     int64
 2   id_user             51 non-null     object
 3   alasan_resign       51 non-null     object
 4   dokumen_pendukung   51 non-null     object
 5   status_persetujuan  51 non-null     object
 6   status_pengiriman   51 non-null     object
 7   created_at          51 non-null     datetime64[ns]
dtypes: datetime64[ns](1), int64(2), object(5)
memory usage: 3.3+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

,id_resign,id_karyawan,id_user,alasan_resign,dokumen_pendukung,status_persetujuan,status_pengiriman,created_at
0,3,2,U00003,menikah dan fokus rumah tangga,1760930076_1c9467f497cf1dfb4157.pdf,,Terkirim,2023-04-05 16:18:11
1,4,1,U00001,Tidak ada keterangan,,,,2023-04-05 16:18:11
2,11,3,U00011,ikut suami,1764844234_16b2d6c6fe2b556d77c4.pdf,,Terkirim,2023-05-25 09:20:40
3,12,4,U00012,Tidak ada keterangan,,,,2023-05-29 13:48:56
4,14,5,U00014,Tidak ada keterangan,,,,2023-05-29 13:59:36
5,15,6,U00015,Tidak ada keterangan,,,,2023-05-29 14:06:46
6,18,7,U00016,Tidak ada keterangan,,,,2023-05-29 14:21:56
7,20,8,U00018,Tidak ada keterangan,,,,2023-05-30 06:11:17
8,21,9,U00019,Tidak ada keterangan,,,,2023-05-30 15:30:25
9,22,10,U00020,Tidak ada keterangan,,,,2023-05-30 15:32:59
10,25,11,U00023,Tidak ada keterangan,,,,2023-06-07 18:13:14
11,29,12,U00026,Tidak ada keterangan,,,,2023-06-08 09:26:59
12,30,13,U00027,Tidak ada keterangan,,,,2023-06-15 09:47:14
13,31,14,U00028,Tidak ada keterangan,,,,2023-06-19 09:21:38
14,33,15,U00030,test,,,,2023-06-27 10:19:07
15,41,16,U00031,Tidak ada keterangan,,,,2023-07-01 21:14:57
16,42,17,U00032,Tidak ada keterangan,,,,2023-07-01 21:36:06
17,43,18,U00033,Tidak ada keterangan,,,,2023-07-01 21:36:32
18,44,19,U00034,Tidak ada keterangan,,,,2023-07-01 21:37:01
19,45,20,U00035,Tidak ada keterangan,,,,2023-07-01 21:37:44
20,46,21,U00036,Akan melanjutkan studi S2,1721002416_35e91e07300d633001e9.docx,Disetujui,Terkirim,2023-07-01 21:37:54
21,47,22,U00037,Tidak ada keterangan,,,,2023-07-01 21:38:39
22,48,23,U00038,Tidak ada keterangan,,,,2023-07-01 21:38:52
23,50,24,U00040,Tidak ada keterangan,,,,2023-07-04 14:58:07
24,51,25,U00041,Tidak ada keterangan,,,,2023-07-06 15:39:18
25,52,26,U00042,Tidak ada keterangan,,,,2023-07-06 15:39:42
26,53,27,U00043,Tidak ada keterangan,,,,2023-08-15 09:31:16
27,56,28,U00044,Tidak ada keterangan,,,,2023-10-03 15:42:34
28,58,29,U00046,Tidak ada keterangan,,,,2023-11-29 11:44:51
29,59,30,U00047,Tidak ada keterangan,,,,2023-12-01 11:42:29
30,60,31,U00048,Tidak ada keterangan,,,,2023-12-21 13:05:57
31,61,32,U00049,Tidak ada keterangan,,,,2024-02-01 10:39:35
32,62,33,U00050,Tidak ada keterangan,,,,2024-02-02 10:02:51
33,64,34,U00052,Tidak ada keterangan,,,,2024-05-02 09:08:39
34,65,35,U00053,Tidak ada keterangan,,,,2024-05-24 10:52:29
35,66,36,U00054,Tidak ada keterangan,,,,2024-08-01 16:19:03
36,67,37,U00055,Tidak ada keterangan,,,,2024-09-06 12:16:59
37,68,38,U00056,Tidak ada keterangan,,,,2024-10-09 14:46:47
38,69,39,U00057,Tidak ada keterangan,,,,2025-06-24 11:19:24
39,70,40,U00058,Tidak ada keterangan,,,,2025-07-02 09:03:14
40,71,41,U00059,Tidak ada keterangan,,,,2025-07-14 16:41:17
41,72,42,U00060,Tidak ada keterangan,,,,2025-08-01 11:22:40
42,73,43,U00061,Tidak ada keterangan,,,,2025-08-13 14:52:52
43,74,44,U00062,Tidak ada keterangan,,,,2025-10-22 17:53:11
44,75,45,U00063,Tidak ada keterangan,,,,2025-10-30 16:50:15
45,76,46,U00064,Tidak ada keterangan,,,,2025-10-30 16:50:43
46,77,47,U00065,Tidak ada keterangan,,,,2025-10-30 16:50:56
47,78,48,U00066,Tidak ada keterangan,,,,2025-10-30 16:51:13
48,79,49,U00067,Tidak ada keterangan,,,,2025-11-26 15:13:57
49,80,50,U00068,Tidak ada keterangan,,,,2026-01-26 16:39:23
50,81,51,U00069,Tidak ada keterangan,,,,2026-04-09 12:46:35

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: JADWAL
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1098 entries, 0 to 1097
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id_jadwal              1098 non-null   int64
 1   id_kursus              1098 non-null   object
 2   id_periode             1098 non-null   object
 3   id_level               1098 non-null   object
 4   id_sesi                1098 non-null   object
 5   metode_belajar_jadwal  1098 non-null   object
 6   nama_rombel            1098 non-null   object
 7   status_arsip           1098 non-null   int64
 8   tempat                 1098 non-null   object
dtypes: int64(2), object(7)
memory usage: 77.3+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

,id_jadwal,id_kursus,id_periode,id_level,id_sesi,metode_belajar_jadwal,nama_rombel,status_arsip,tempat
0,1,K00001,P00006,L00017,S00002,Online,01 GOGO 3B SR2 (ERICA),1,Ruang Kelas 4
1,2,K00001,P00006,L00024,S00002,Offline,02 SO 1C SR2 (QORIN),1,Ruang Kelas 5
2,3,K00001,P00006,L00023,S00001,Offline,03 SO 1B SR1 (TATIK),1,Ruang Kelas 1
3,4,K00001,P00006,L00025,S00003,Offline,04 SO 2A SR3 (TATIK),1,Ruang Kelas 1
4,5,K00001,P00006,L00014,S00003,Offline,05 GOGO 1B SelK3 (ERICA),1,Ruang Kelas 4
...,...,...,...,...,...,...,...,...,...
1093,1094,K00004,P00081,L00136,S00005,Online,CC 6 Mon 4.30-5.30 (Agung) APR 26,0,zoom
1094,1095,K00004,P00081,L00136,S00006,Online,CC 3 Wed 7-8 (Agung) APR 26,0,ZOOM
1095,1096,K00004,P00081,L00136,S00042,Online,CC 1 Fri 7-8 (Agung) APR 26,0,
1096,1097,K00007,P00107,L00125,S00043,Offline,01 BEHCA PRE-BASIC MON 15-17 (Yerly),0,Offline (P.T. Holland Colours Asia)
1097,1098,K00007,P00107,L00126,S00043,Offline,02 BEHCA BASIC TUE 15-17 (Yerly),0,Offline (P.T. Holland Colours Asia)

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: JADWAL_HARI
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1950 entries, 0 to 1949
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_jadwal_hari  1950 non-null   int64
 1   id_jadwal       1950 non-null   int64
 2   nama_hari       1950 non-null   object
dtypes: int64(2), object(1)
memory usage: 45.8+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

      id_jadwal_hari  id_jadwal nama_hari
0                  1          1     Senin
1                  2          1      Rabu
2                  3          2     Senin
3                  4          2      Rabu
4                  5          3     Senin
...              ...        ...       ...
1945            1946       1094     Senin
1946            1947       1095      Rabu
1947            1948       1096     Jumat
1948            1949       1097     Senin
1949            1950       1098    Selasa

[1950 rows x 3 columns]

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: JADWAL_DETAIL
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34514 entries, 0 to 34513
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id_jadwal_detail           34514 non-null  int64
 1   id_jadwal                  34514 non-null  int64
 2   judul                      34514 non-null  object
 3   deskripsi                  34514 non-null  object
 4   url_jadwal_detail          34514 non-null  object
 5   penanda_mulai              34514 non-null  object
 6   penanda_selesai            34514 non-null  object
 7   label_warna                34514 non-null  object
 8   id_mitra                   0 non-null      object
 9   id_sesi_override           0 non-null      object
 10  status_detail              34514 non-null  object
 11  source_type                34514 non-null  object
 12  original_jadwal_detail_id  0 non-null      object
 13  has_operational_data       34514 non-null  int64
 14  presensi_disimpan_at       0 non-null      object
 15  last_generated_at          0 non-null      object
 16  created_at                 34514 non-null  datetime64[ns]
 17  updated_at                 34514 non-null  datetime64[ns]
dtypes: datetime64[ns](2), int64(3), object(13)
memory usage: 4.7+ MB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

,id_jadwal_detail,id_jadwal,judul,deskripsi,url_jadwal_detail,penanda_mulai,penanda_selesai,label_warna,id_mitra,id_sesi_override,status_detail,source_type,original_jadwal_detail_id,has_operational_data,presensi_disimpan_at,last_generated_at,created_at,updated_at
0,1,8,08 SO 2A SelK3 (GETA),Tidak ada deskripsi,https://us02web.zoom.us/j/5403514055?pwd=ZnZ2d...,2023-07-04,2023-07-05,fc-event-info,None,None,active,migrasi,None,0,None,None,2026-06-08 11:33:57,2026-06-08 11:33:57
1,2,8,08 SO 2A SelK3 (GETA),Tidak ada deskripsi,https://us02web.zoom.us/j/5403514055?pwd=ZnZ2d...,2023-07-06,2023-07-07,fc-event-info,None,None,active,migrasi,None,0,None,None,2026-06-08 11:33:57,2026-06-08 11:33:57
2,3,8,08 SO 2A SelK3 (GETA),Tidak ada deskripsi,https://us02web.zoom.us/j/5403514055?pwd=ZnZ2d...,2023-07-11,2023-07-12,fc-event-info,None,None,active,migrasi,None,0,None,None,2026-06-08 11:33:57,2026-06-08 11:33:57
3,4,8,08 SO 2A SelK3 (GETA),Tidak ada deskripsi,https://us02web.zoom.us/j/5403514055?pwd=ZnZ2d...,2023-07-13,2023-07-14,fc-event-info,None,None,active,migrasi,None,0,None,None,2026-06-08 11:33:57,2026-06-08 11:33:57
4,5,8,08 SO 2A SelK3 (GETA),Tidak ada deskripsi,https://us02web.zoom.us/j/5403514055?pwd=ZnZ2d...,2023-07-18,2023-07-19,fc-event-info,None,None,active,migrasi,None,0,None,None,2026-06-08 11:33:57,2026-06-08 11:33:57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34509,34510,1097,01 BEHCA PRE-BASIC MON 15-17 (Yerly),Tidak ada deskripsi,Link belum tersedia,2026-10-05,2026-10-06,fc-event-info,None,None,active,migrasi,None,0,None,None,2026-06-08 11:33:57,2026-06-08 11:33:57
34510,34511,1097,01 BEHCA PRE-BASIC MON 15-17 (Yerly),Tidak ada deskripsi,Link belum tersedia,2026-10-12,2026-10-13,fc-event-info,None,None,active,migrasi,None,0,None,None,2026-06-08 11:33:57,2026-06-08 11:33:57
34511,34512,1097,01 BEHCA PRE-BASIC MON 15-17 (Yerly),Tidak ada deskripsi,Link belum tersedia,2026-10-19,2026-10-20,fc-event-info,None,None,active,migrasi,None,0,None,None,2026-06-08 11:33:57,2026-06-08 11:33:57
34512,34513,1097,01 BEHCA PRE-BASIC MON 15-17 (Yerly),Tidak ada deskripsi,Link belum tersedia,2026-10-26,2026-10-27,fc-event-info,None,None,active,migrasi,None,0,None,None,2026-06-08 11:33:57,2026-06-08 11:33:57
34513,34514,1097,01 BEHCA PRE-BASIC MON 15-17 (Yerly),Tidak ada deskripsi,Link belum tersedia,2026-11-02,2026-11-03,fc-event-info,None,None,active,migrasi,None,0,None,None,2026-06-08 11:33:57,2026-06-08 11:33:57

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: JADWAL_PENGAJAR
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1280 entries, 0 to 1279
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_jadwal_pengajar  1280 non-null   int64
 1   id_jadwal           1280 non-null   int64
 2   id_user             1280 non-null   object
dtypes: int64(2), object(1)
memory usage: 30.1+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

      id_jadwal_pengajar  id_jadwal id_user
0                      1          3  U00019
1                      2          7  U00026
2                      3          9  U00035
3                      4         17  U00038
4                      5         21  U00019
...                  ...        ...     ...
1275                1276       1096  U00040
1276                1277       1097  U00048
1277                1278       1098  U00048
1278                1279       1097  U00026
1279                1280       1098  U00026

[1280 rows x 3 columns]

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: JADWAL_SISWA
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 15 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id_jadwal_siswa             0 non-null      object
 1   id_siswa                    0 non-null      object
 2   id_jadwal                   0 non-null      object
 3   tanggal_mulai               0 non-null      object
 4   tambahan_sesi               0 non-null      object
 5   tambahan_keterangan         0 non-null      object
 6   status_keluar               0 non-null      object
 7   is_acc_rapor                0 non-null      object
 8   status_ketuntasan           0 non-null      object
 9   catatan_ketuntasan_guru     0 non-null      object
 10  catatan_ketuntasan_admin    0 non-null      object
 11  ketuntasan_diperbarui_oleh  0 non-null      object
 12  ketuntasan_diperbarui_pada  0 non-null      object
 13  tanggal_keluar              0 non-null      object
 14  tanggal_aktif               0 non-null      object
dtypes: object(15)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

Empty DataFrame
Columns: [id_jadwal_siswa, id_siswa, id_jadwal, tanggal_mulai, tambahan_sesi, tambahan_keterangan, status_keluar, is_acc_rapor, status_ketuntasan, catatan_ketuntasan_guru, catatan_ketuntasan_admin, ketuntasan_diperbarui_oleh, ketuntasan_diperbarui_pada, tanggal_keluar, tanggal_aktif]
Index: []

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: CATATAN_KELAS
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25594 entries, 0 to 25593
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_ck               25594 non-null  int64
 1   id_jadwal           25594 non-null  int64
 2   id_jadwal_detail    25594 non-null  int64
 3   id_karyawan         0 non-null      object
 4   catatan_kelas       25594 non-null  object
 5   topik_diskusi       25594 non-null  object
 6   tanggal_konfirmasi  25594 non-null  datetime64[ns]
 7   hasil_konfirmasi    25594 non-null  object
dtypes: datetime64[ns](1), int64(3), object(4)
memory usage: 1.6+ MB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

,id_ck,id_jadwal,id_jadwal_detail,id_karyawan,catatan_kelas,topik_diskusi,tanggal_konfirmasi,hasil_konfirmasi
0,1,7,1231,None,1. Bya ijin tidak hadir karena masih perjalana...,,2026-06-08 11:33:57,
1,2,3,721,None,Kelas berjalan lancar. Valencia bisa mengikuti...,,2026-06-08 11:33:57,
2,3,9,1171,None,Elycia didn't come. Harits and Kinan came 15 m...,,2026-06-08 11:33:57,
3,4,22,331,None,Semua siswa hadir ada murid trial Kim suaranya...,,2026-06-08 11:33:57,
4,5,1,451,None,kelas berjalan dengan lancar elma & ghaus mema...,,2026-06-08 11:33:57,
...,...,...,...,...,...,...,...,...
25589,25590,1026,31605,None,<p>27) <strong>Sesi 27</strong> - Topik hari i...,,2026-06-08 11:33:57,
25590,25591,997,30938,None,<p>1. Sesi ke 25 pembelajaran dimulai tepat wa...,,2026-06-08 11:33:57,
25591,25592,1096,34464,None,<p>Sesi 2: Peserta datang tepat waktu. Interne...,,2026-06-08 11:33:57,
25592,25593,1021,31519,None,"<p style=""text-align: justify;""><strong>Pertem...",,2026-06-08 11:33:57,
25593,25594,1022,31562,None,"<p style=""text-align: justify;""><strong>Pertem...",,2026-06-08 11:33:57,

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: CATATAN_KELAS_TAG
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_ck_tag         0 non-null      object
 1   id_ck             0 non-null      object
 2   id_topik_diskusi  0 non-null      object
dtypes: object(3)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

Empty DataFrame
Columns: [id_ck_tag, id_ck, id_topik_diskusi]
Index: []

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: CATATAN_MINGGUAN
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id_cm                  0 non-null      object
 1   id_user                0 non-null      object
 2   tanggal_mulai_cm       0 non-null      object
 3   tanggal_selesai_cm     0 non-null      object
 4   keterangan_cm          0 non-null      object
 5   keputusan_cm           0 non-null      object
 6   tanggal_verifikasi_cm  0 non-null      object
dtypes: object(7)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

Empty DataFrame
Columns: [id_cm, id_user, tanggal_mulai_cm, tanggal_selesai_cm, keterangan_cm, keputusan_cm, tanggal_verifikasi_cm]
Index: []

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: SISWA
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 795 entries, 0 to 794
Data columns (total 50 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id_siswa              795 non-null    int64
 1   tanggal_registrasi    459 non-null    object
 2   domisili              795 non-null    object
 3   nama_lengkap          795 non-null    object
 4   nama_panggilan        795 non-null    object
 5   jenis_kelamin         795 non-null    object
 6   asal_sekolah          795 non-null    object
 7   tingkat_sekolah       795 non-null    object
 8   nama_orang_tua        795 non-null    object
 9   pekerjaan_orang_tua   795 non-null    object
 10  tempat_lahir          795 non-null    object
 11  tanggal_lahir         575 non-null    object
 12  nomor_induk           795 non-null    object
 13  email                 795 non-null    object
 14  id_calon              0 non-null      object
 15  id_provinsi           532 non-null    float64
 16  id_kabupaten          527 non-null    float64
 17  id_kecamatan          491 non-null    float64
 18  id_kelurahan          479 non-null    float64
 19  id_mitra              14 non-null     float64
 20  nisn                  641 non-null    object
 21  nik                   641 non-null    object
 22  kewarganegaraan       641 non-null    object
 23  agama                 795 non-null    object
 24  rt                    641 non-null    object
 25  rw                    641 non-null    object
 26  kode_pos              641 non-null    object
 27  rekomendasi           641 non-null    object
 28  sumber_info           641 non-null    object
 29  status_pendaftaran    641 non-null    object
 30  metode_pembayaran     0 non-null      object
 31  nama_ayah             641 non-null    object
 32  pekerjaan_ayah        795 non-null    object
 33  pendidikan_ayah       641 non-null    object
 34  penghasilan_ayah      461 non-null    object
 35  nama_ibu              641 non-null    object
 36  penghasilan_ibu       369 non-null    object
 37  pekerjaan_ibu         795 non-null    object
 38  pendidikan_ibu        641 non-null    object
 39  nama_wali             641 non-null    object
 40  pekerjaan_wali        795 non-null    object
 41  pendidikan_wali       641 non-null    object
 42  penghasilan_wali      86 non-null     object
 43  wa_siswa              641 non-null    object
 44  wa_ortu               641 non-null    object
 45  wa_administrasi       641 non-null    object
 46  status_pengisian      795 non-null    object
 47  path_bukti_bayar      9 non-null      object
 48  tanggal_upload_bukti  0 non-null      object
 49  deleted_at            0 non-null      object
dtypes: float64(5), int64(1), object(44)
memory usage: 310.7+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

,id_siswa,tanggal_registrasi,domisili,nama_lengkap,nama_panggilan,jenis_kelamin,asal_sekolah,tingkat_sekolah,nama_orang_tua,pekerjaan_orang_tua,...,pekerjaan_wali,pendidikan_wali,penghasilan_wali,wa_siswa,wa_ortu,wa_administrasi,status_pengisian,path_bukti_bayar,tanggal_upload_bukti,deleted_at
0,1,2022-07-01,Rungkut Barata VI/12-14,EZRA RAFA DANAR,RAFA,,MIN 1 Medokan Ayu,SD,IBU EZRA RAFA DANAR (Nur Arief),Belum/Tidak Bekerja,...,Belum/Tidak Bekerja,s1,kurang_1jt,,085230012257,085230012257,Sudah Lengkap,None,None,None
1,2,None,,SARAH MEDINA ISWALDI,SARAH,,,,IBU SARAH,Lainnya,...,Lainnya,None,None,None,None,None,Belum Lengkap,None,None,None
2,3,2021-07-01,0,ALIKA NAYYARA,ALIKA,Perempuan,0,,IBU ALIKA NAYYARA,Lainnya,...,Lainnya,None,None,None,None,None,Belum Lengkap,None,None,None
3,4,2022-07-01,rungkut asri timur 1 no.29,RAINZAR ARGHADANI,ARGHA,,SD budi mulia,SD,IBU ARGHA (Agustya permata),Wiraswasta,...,Lainnya,-,None,,085645678118,085645678118,Sudah Lengkap,None,None,None
4,5,None,,NADIN SYAFINA PUTRI ARDIANTI,NADIN,Perempuan,,,IBU NADIN,Lainnya,...,Lainnya,None,None,None,None,None,Belum Lengkap,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
790,791,None,Jl semolowaru tengah XVIII no 3 surabaya,CORINA MECCA,MECCA,Perempuan,Sdn semolowaru 1/261,SD,,Tenaga Kesehatan,...,Lainnya,-,None,0856 3074 997,0856 3074 997,0856 3074 997,Sudah Lengkap,None,None,None
791,792,2025-11-26,-,coba,raport 1,,-,TK,-,Lainnya,...,Lainnya,None,None,None,None,None,Belum Lengkap,None,None,None
792,793,2025-11-26,-,coba raport 2,raport 2,,-,TK,-,Lainnya,...,Lainnya,None,None,None,None,None,Belum Lengkap,None,None,None
793,794,2025-11-26,-,coba raport 3,raport 3,,-,TK,-,Lainnya,...,Lainnya,None,None,None,None,None,Belum Lengkap,None,None,None
794,795,2025-12-08,,qo coba upload,qo,Perempuan,,,,Lainnya,...,Lainnya,,None,,,,,None,None,None

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: KURSUS_SISWA
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_kursus_siswa  0 non-null      object
 1   id_siswa         0 non-null      object
 2   id_kursus        0 non-null      object
 3   tanggal_mulai    0 non-null      object
 4   metode_belajar   0 non-null      object
 5   status_aktif     0 non-null      object
 6   status_lulus     0 non-null      object
 7   catatan          0 non-null      object
dtypes: object(8)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

Empty DataFrame
Columns: [id_kursus_siswa, id_siswa, id_kursus, tanggal_mulai, metode_belajar, status_aktif, status_lulus, catatan]
Index: []

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: SISWA_KELUAR
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_keluar       0 non-null      object
 1   id_siswa        0 non-null      object
 2   id_kursus       0 non-null      object
 3   alasan_keluar   0 non-null      object
 4   tanggal_keluar  0 non-null      object
 5   id_tag_keluar   0 non-null      object
dtypes: object(6)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

Empty DataFrame
Columns: [id_keluar, id_siswa, id_kursus, alasan_keluar, tanggal_keluar, id_tag_keluar]
Index: []

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: MITRA
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_mitra             1 non-null      int64
 1   kode_mitra           1 non-null      object
 2   nama_mitra           1 non-null      object
 3   nama_instansi        1 non-null      object
 4   nama_sekolah         1 non-null      object
 5   alamat_mitra         1 non-null      object
 6   nama_pimpinan        1 non-null      object
 7   kontak_mitra         1 non-null      object
 8   status_mitra         1 non-null      object
 9   visi_misi            1 non-null      object
 10  program_mitra        1 non-null      object
 11  info_sdm             1 non-null      object
 12  info_kelemahan       1 non-null      object
 13  rekomendasi_program  1 non-null      object
 14  jenis_mitra          1 non-null      object
 15  provinsi_id          1 non-null      int64
 16  kabupaten_id         1 non-null      int64
 17  jumlah_siswa_mitra   1 non-null      int64
 18  bidang_usaha         1 non-null      object
 19  is_leapverse         1 non-null      int64
 20  status_kemitraan     1 non-null      int64
 21  tahun_bergabung      1 non-null      int64
 22  tipe_kerjasama       1 non-null      object
 23  is_elsa              1 non-null      int64
 24  is_classin           1 non-null      int64
 25  is_mitra_leap        1 non-null      int64
 26  created_at           1 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(10), object(16)
memory usage: 348.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

,id_mitra,kode_mitra,nama_mitra,nama_instansi,nama_sekolah,alamat_mitra,nama_pimpinan,kontak_mitra,status_mitra,visi_misi,...,jumlah_siswa_mitra,bidang_usaha,is_leapverse,status_kemitraan,tahun_bergabung,tipe_kerjasama,is_elsa,is_classin,is_mitra_leap,created_at
0,2,M,Fiona Febianita Sulistyo,PT Delta Jaya Mas,PT Delta Jaya Mas,Gresik,Fiona Febianita Sulistyo (HRD & GA),+6282141660768,Done,"<p><span style=""font-size: 10pt; font-family: ...",...,100,Manufacturing,0,0,2023,Perluasan Bisnis,0,0,1,2023-09-04 07:06:34

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: MITRA_PROGRES
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id_progres_mitra       0 non-null      object
 1   id_mitra               0 non-null      object
 2   catatan_progres_mitra  0 non-null      object
 3   id_user                0 non-null      object
 4   status_progres_mitra   0 non-null      object
 5   kemitraan_mulai        0 non-null      object
 6   kemitraan_berakhir     0 non-null      object
 7   created_at             0 non-null      object
dtypes: object(8)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

Empty DataFrame
Columns: [id_progres_mitra, id_mitra, catatan_progres_mitra, id_user, status_progres_mitra, kemitraan_mulai, kemitraan_berakhir, created_at]
Index: []

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: KEMITRAAN_VERIFIKATOR
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_kemitraan      0 non-null      object
 1   id_progres_mitra  0 non-null      object
 2   id_user           0 non-null      object
dtypes: object(3)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

Empty DataFrame
Columns: [id_kemitraan, id_progres_mitra, id_user]
Index: []

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: SISWA_MITRA
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_sm             0 non-null      object
 1   tanggal_daftar    0 non-null      object
 2   alamat_domisili   0 non-null      object
 3   nama_lengkap      0 non-null      object
 4   nama_panggilan    0 non-null      object
 5   jenis_kelamin     0 non-null      object
 6   nama_instansi     0 non-null      object
 7   tingkat_sekolah   0 non-null      object
 8   pekerjaan_sm      0 non-null      object
 9   tempat_lahir      0 non-null      object
 10  tanggal_lahir     0 non-null      object
 11  nomor_induk_sm    0 non-null      object
 12  email_sm          0 non-null      object
 13  wa_sm             0 non-null      object
 14  status_keluar_sm  0 non-null      object
 15  id_mitra          0 non-null      object
 16  sertifikat_sm     0 non-null      object
dtypes: object(17)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

Empty DataFrame
Columns: [id_sm, tanggal_daftar, alamat_domisili, nama_lengkap, nama_panggilan, jenis_kelamin, nama_instansi, tingkat_sekolah, pekerjaan_sm, tempat_lahir, tanggal_lahir, nomor_induk_sm, email_sm, wa_sm, status_keluar_sm, id_mitra, sertifikat_sm]
Index: []

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: SISWA_MITRA_KELUAR
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_sm_keluar       0 non-null      object
 1   id_sm              0 non-null      object
 2   alasan_keluar_sm   0 non-null      object
 3   tanggal_keluar_sm  0 non-null      object
dtypes: object(4)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

Empty DataFrame
Columns: [id_sm_keluar, id_sm, alasan_keluar_sm, tanggal_keluar_sm]
Index: []

================================================================================