In [1]:
import sys
import os
import mysql.connector
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Ambil konfigurasi database dari folder utama project kalian
sys.path.append(os.path.abspath('..'))
from config import get_db_config

config = get_db_config()

# 1. Koneksi ke Database Baru (Fase Migrasi Sekarang)
db_new = mysql.connector.connect(**config['db_new'])
cursor_new = db_new.cursor(dictionary=True)

# 2. Koneksi ke Database Masa Depan (DB_FUTURE)
# Catatan: Pastikan di file config.py kalian sudah ada key 'db_future' ya!
db_future = mysql.connector.connect(**config['db_future'])
cursor_future = db_future.cursor(dictionary=True)

print(f"✅ Sukses Terhubung ke Database Baru : {config['db_new']['database']}")
print(f"🚀 Sukses Terhubung ke DB_FUTURE     : {config['db_future']['database']}")

✅ Sukses Terhubung ke Database Baru : dataleap_v5_migration
🚀 Sukses Terhubung ke DB_FUTURE     : 2

In [2]:
tables_to_check = [
    # --- Bagian Cimut ---
    "karyawan", 
    "keluarga_karyawan", 
    "bidang_kategori", 
    "bidang_link",
    
    # --- Bagian Afrida ---
    "periode", 
    "parameter_nilai", 
    "kabupaten", 
    "kecamatan",
    
    # --- Bagian Hanif ---
    "division_user", 
    "model_has_roles", 
    "model_has_permissions", 
    "kelurahan"
]

In [3]:
# === Cell 2: Inspeksi Detektor Pintar dengan Prioritas Target Revisi di Atas ===
import pandas as pd
import numpy as np

print("================================================================================")
print(" 🕵️‍♂️ FORENSIK ARSITEKTUR KONTROL: DETEKTOR AUTO-SMART COMPILER (REVISI PRIORITY) 🕵️‍♂️ ")
print("================================================================================")

# List penampung data di memori untuk keperluan sorting visualisasi
revisi_tables_queue = []
identical_tables_queue = []

# --- TAHAP A: PROSES PEN ARIKAN DATA & EVALUASI STRUKTUR DI BELAKANG LAYAR ---
for table in tables_to_check:
    try:
        # 1. Ambil data asli dari DB_NEW untuk kebutuhan .info() dan sampel isi data
        query = f"SELECT * FROM `{table}`"
        df_real_data = pd.read_sql(query, db_new)
        
        # 2. Tarik Struktur Fisik Kolom dari DB_NEW
        query_new_struct = f"""
        SELECT 
            c.COLUMN_NAME AS 'Nama Kolom',
            c.COLUMN_TYPE AS 'Tipe Data MySQL',
            CONCAT(
                CASE WHEN c.IS_NULLABLE = 'YES' THEN '✅ NULL (Boleh Kosong)' ELSE '🛑 NOT NULL (Wajib Isi)' END,
                CASE WHEN c.EXTRA = 'auto_increment' THEN '\\n🚀 AUTO_INCREMENT' ELSE '' END
            ) AS 'Aturan Nullability & Increment',
            CASE 
                WHEN c.COLUMN_KEY = 'PRI' THEN '🔑 PRIMARY KEY (PK)'
                WHEN c.COLUMN_KEY = 'MUL' AND k.REFERENCED_TABLE_NAME IS NOT NULL THEN '🔗 FOREIGN KEY (FK)'
                WHEN c.COLUMN_KEY = 'MUL' THEN 'INDEX'
                ELSE '-'
            END AS 'Status Kunci',
            CASE 
                WHEN k.REFERENCED_TABLE_NAME IS NOT NULL THEN CONCAT(k.REFERENCED_TABLE_NAME, ' (', k.REFERENCED_COLUMN_NAME, ')')
                ELSE '-'
            END AS 'Rujukan Induk (FK Origin)',
            CASE WHEN c.DATA_TYPE = 'enum' THEN REPLACE(REPLACE(REPLACE(c.COLUMN_TYPE, 'enum(', ''), ')', ''), "'", "") ELSE '-' END AS 'Daftar Pilihan ENUM'
        FROM INFORMATION_SCHEMA.COLUMNS c
        LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE k 
            ON c.TABLE_SCHEMA = k.TABLE_SCHEMA AND c.TABLE_NAME = k.TABLE_NAME AND c.COLUMN_NAME = k.COLUMN_NAME
        WHERE c.TABLE_SCHEMA = '{config['db_new']['database']}' AND c.TABLE_NAME = '{table}'
        ORDER BY c.ORDINAL_POSITION;
        """
        df_struct_new = pd.read_sql(query_new_struct, db_new).drop_duplicates(subset=['Nama Kolom'], keep='first').reset_index(drop=True)
        
        # Lacak tabel anak yang nge-FK ke PK tabel ini di DB_NEW
        pk_referenced_list = []
        for idx, row_skri in df_struct_new.iterrows():
            if row_skri['Status Kunci'] == '🔑 PRIMARY KEY (PK)':
                lookup_fk_query = f"""
                SELECT CONCAT(TABLE_NAME, ' (', COLUMN_NAME, ')') as relasi
                FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
                WHERE REFERENCED_TABLE_SCHEMA = '{config['db_new']['database']}'
                  AND REFERENCED_TABLE_NAME = '{table}'
                  AND REFERENCED_COLUMN_NAME = '{row_skri['Nama Kolom']}';
                """
                df_relasi_luar = pd.read_sql(lookup_fk_query, db_new)
                if not df_relasi_luar.empty:
                    pk_referenced_list.append("\n".join(df_relasi_luar['relasi'].tolist()))
                else:
                    pk_referenced_list.append("-")
            else:
                pk_referenced_list.append("-")
        df_struct_new['Tabel Yang nge-FK (DB_NEW)'] = pk_referenced_list

        # 3. Tarik Struktur Fisik Kolom dari DB_FUTURE
        query_future_struct = f"""
        SELECT 
            c.COLUMN_NAME AS 'Nama Kolom',
            c.COLUMN_TYPE AS 'Tipe Data MySQL',
            CONCAT(
                CASE WHEN c.IS_NULLABLE = 'YES' THEN '✅ NULL (Boleh Kosong)' ELSE '🛑 NOT NULL (Wajib Isi)' END,
                CASE WHEN c.EXTRA = 'auto_increment' THEN '\\n🚀 AUTO_INCREMENT' ELSE '' END
            ) AS 'Aturan Nullability & Increment',
            CASE 
                WHEN c.COLUMN_KEY = 'PRI' THEN '🔑 PRIMARY KEY (PK)'
                WHEN c.COLUMN_KEY = 'MUL' AND k.REFERENCED_TABLE_NAME IS NOT NULL THEN '🔗 FOREIGN KEY (FK)'
                WHEN c.COLUMN_KEY = 'MUL' THEN 'INDEX'
                ELSE '-'
            END AS 'Status Kunci',
            CASE 
                WHEN k.REFERENCED_TABLE_NAME IS NOT NULL THEN CONCAT(k.REFERENCED_TABLE_NAME, ' (', k.REFERENCED_COLUMN_NAME, ')')
                ELSE '-'
            END AS 'Rujukan Induk (FK Origin)',
            CASE WHEN c.DATA_TYPE = 'enum' THEN REPLACE(REPLACE(REPLACE(c.COLUMN_TYPE, 'enum(', ''), ')', ''), "'", "") ELSE '-' END AS 'Daftar Pilihan ENUM'
        FROM INFORMATION_SCHEMA.COLUMNS c
        LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE k 
            ON c.TABLE_SCHEMA = k.TABLE_SCHEMA AND c.TABLE_NAME = k.TABLE_NAME AND c.COLUMN_NAME = k.COLUMN_NAME
        WHERE c.TABLE_SCHEMA = '{config['db_future']['database']}' AND c.TABLE_NAME = '{table}'
        ORDER BY c.ORDINAL_POSITION;
        """
        df_struct_future = pd.read_sql(query_future_struct, db_future).drop_duplicates(subset=['Nama Kolom'], keep='first').reset_index(drop=True)
        
        # Lacak tabel anak yang nge-FK ke PK tabel ini di DB_FUTURE
        pk_referenced_list_future = []
        for idx, row_skri in df_struct_future.iterrows():
            if row_skri['Status Kunci'] == '🔑 PRIMARY KEY (PK)':
                lookup_fk_query_future = f"""
                SELECT CONCAT(TABLE_NAME, ' (', COLUMN_NAME, ')') as relasi
                FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
                WHERE REFERENCED_TABLE_SCHEMA = '{config['db_future']['database']}'
                  AND REFERENCED_TABLE_NAME = '{table}'
                  AND REFERENCED_COLUMN_NAME = '{row_skri['Nama Kolom']}';
                """
                df_relasi_luar_future = pd.read_sql(lookup_fk_query_future, db_future)
                if not df_relasi_luar_future.empty:
                    pk_referenced_list_future.append("\n".join(df_relasi_luar_future['relasi'].tolist()))
                else:
                    pk_referenced_list_future.append("-")
            else:
                pk_referenced_list_future.append("-")
        df_struct_future['Tabel Yang nge-FK (DB_FUTURE)'] = pk_referenced_list_future

        # 4. Deep Comparison Kesamaan Jeroan Kolom dasar
        cols_to_compare = ['Nama Kolom', 'Tipe Data MySQL', 'Aturan Nullability & Increment', 'Status Kunci', 'Rujukan Induk (FK Origin)', 'Daftar Pilihan ENUM']
        
        is_structure_identical = False
        if not df_struct_new.empty and not df_struct_future.empty:
            is_structure_identical = df_struct_new[cols_to_compare].equals(df_struct_future[cols_to_compare])

        # Wadah paket data tabel untuk di-render nanti
        table_package = {
            'name': table,
            'df_real_data': df_real_data,
            'df_struct_new': df_struct_new,
            'df_struct_future': df_struct_future,
            'is_identical': is_structure_identical
        }

        # 🔥 FILTER SAKTI CIMUT: Pisahkan antrean, utamakan yang bermasalah (revisi) ke atas!
        if is_structure_identical:
            identical_tables_queue.append(table_package)
        else:
            revisi_tables_queue.append(table_package)
            
    except Exception as e:
        print(f"❌ Gagal menganalisis awal tabel `{table}`: {e}")

# --- TAHAP B: MULAI PEN TAMPILAN VISUALISASI BERDASARKAN ANT REAN PRIORITAS ---

# 🚨 1. KELOMPOK UTAMA (PALING ATAS): DAFTAR TABEL YANG WAJIB DIREVISI 🚨
if revisi_tables_queue:
    print("\n" + "!"*80)
    print(f"🚨 [🔥 REVISI PRIORITY BOARD] TERDETEKSI {len(revisi_tables_queue)} TABEL BERBEDA - HARUS SEGERA DIPERBAIKI!")
    print("!"*80)
    
    for pkg in revisi_tables_queue:
        print(f"\n================================================================================")
        print(f"⚠️  [STATUS: TARGET REVISI] TABEL: {pkg['name'].upper()}")
        print(f"================================================================================")
        
        print(f"📋 1. Karakteristik Wadah Pandas Dataframe (.info()):")
        pkg['df_real_data'].info()
        print("\n" + "-"*60)
        
        print(f"🔍 2. [TABEL REAL SAAT INI] Arsitektur Fisik Kolom pada DB_NEW:")
        display(pkg['df_struct_new'].style.set_properties(**{'white-space': 'pre-wrap', 'text-align': 'left'}))
        print("\n" + "-"*60)
        
        print(f"🔮 3. [⚠️ TARGET BLUEPRINT RUJUKAN] Tinjau Struktur yang Benar pada DB_FUTURE di bawah:")
        if pkg['df_struct_future'].empty:
            print("❌ ERROR: Tabel ini tidak ditemukan / belum dibuat sama sekali di DB_FUTURE!")
        else:
            display(pkg['df_struct_future'].style.set_properties(**{'white-space': 'pre-wrap', 'text-align': 'left'}))
        print("\n" + "-"*60)
        
        print(f"📸 4. Sampel Isi Data Real di DB_NEW:")
        display(pkg['df_real_data'] if pkg['df_real_data'].empty else pkg['df_real_data'])
        print("\n" + "="*80)

# ✨ 2. KELOMPOK KEDUA (BAW AH): DAFTAR TABEL YANG SUDAH AMAN IDENTIK ✨
if identical_tables_queue:
    print("\n" + "="*80)
    print(f"✨ [🟢 PERFECTLY MATCHED BOARD] SEBANYAK {len(identical_tables_queue)} TABEL STRUKTURNYA SUDAH IDENTIK SAMA PERSIS!")
    print("="*80)
    
    for pkg in identical_tables_queue:
        print(f"\n================================================================================")
        print(f"✅ [STATUS: AMAN IDENTIK] TABEL: {pkg['name'].upper()}")
        print(f"================================================================================")
        
        print(f"📋 1. Karakteristik Wadah Pandas Dataframe (.info()):")
        pkg['df_real_data'].info()
        print("\n" + "-"*60)
        
        print(f"🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:")
        display(pkg['df_struct_new'].style.set_properties(**{'white-space': 'pre-wrap', 'text-align': 'left'}))
        print("\n" + "-"*60)
        
        print("✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨")
        print("ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.")
        print("\n" + "-"*60)
        
        print(f"📸 3. Sampel Isi Data Real di DB_NEW:")
        display(pkg['df_real_data'] if pkg['df_real_data'].empty else pkg['df_real_data'])
        print("\n" + "="*80)

================================================================================
 🕵️‍♂️ FORENSIK ARSITEKTUR KONTROL: DETEKTOR AUTO-SMART COMPILER (REVISI PRIORITY) 🕵️‍♂️
================================================================================

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
🚨 [🔥 REVISI PRIORITY BOARD] TERDETEKSI 5 TABEL BERBEDA - HARUS SEGERA DIPERBAIKI!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

================================================================================
⚠️  [STATUS: TARGET REVISI] TABEL: KARYAWAN
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 36 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id_karyawan           0 non-null      object
 1   id_user               0 non-null      object
 2   nik_ktp               0 non-null      object
 3   nama_lengkap          0 non-null      object
 4   nama_panggilan        0 non-null      object
 5   tempat_lahir          0 non-null      object
 6   tanggal_lahir         0 non-null      object
 7   jenis_kelamin         0 non-null      object
 8   golongan_darah        0 non-null      object
 9   agama                 0 non-null      object
 10  status_pernikahan     0 non-null      object
 11  alamat_ktp            0 non-null      object
 12  alamat_domisili       0 non-null      object
 13  kewarganegaraan       0 non-null      object
 14  anak_ke               0 non-null      object
 15  jumlah_anak           0 non-null      object
 16  hobi                  0 non-null      object
 17  akun_linkedin         0 non-null      object
 18  email_pribadi         0 non-null      object
 19  email_kantor          0 non-null      object
 20  nomor_telepon         0 non-null      object
 21  nomor_npwp            0 non-null      object
 22  bpjs_ketenagakerjaan  0 non-null      object
 23  bpjs_kesehatan        0 non-null      object
 24  nomor_rekening        0 non-null      object
 25  moda_transportasi     0 non-null      object
 26  akun_instagram        0 non-null      object
 27  akun_facebook         0 non-null      object
 28  link_dokumen_pribadi  0 non-null      object
 29  riwayat_kesehatan     0 non-null      object
 30  tahun_mulai_kerja     0 non-null      object
 31  keahlian              0 non-null      object
 32  id_shift              0 non-null      object
 33  status_aktif          0 non-null      object
 34  foto_profile          0 non-null      object
 35  ttd_digital           0 non-null      object
dtypes: object(36)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL SAAT INI] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
🔮 3. [⚠️ TARGET BLUEPRINT RUJUKAN] Tinjau Struktur yang Benar pada DB_FUTURE di bawah:

------------------------------------------------------------
📸 4. Sampel Isi Data Real di DB_NEW:

Empty DataFrame
Columns: [id_karyawan, id_user, nik_ktp, nama_lengkap, nama_panggilan, tempat_lahir, tanggal_lahir, jenis_kelamin, golongan_darah, agama, status_pernikahan, alamat_ktp, alamat_domisili, kewarganegaraan, anak_ke, jumlah_anak, hobi, akun_linkedin, email_pribadi, email_kantor, nomor_telepon, nomor_npwp, bpjs_ketenagakerjaan, bpjs_kesehatan, nomor_rekening, moda_transportasi, akun_instagram, akun_facebook, link_dokumen_pribadi, riwayat_kesehatan, tahun_mulai_kerja, keahlian, id_shift, status_aktif, foto_profile, ttd_digital]
Index: []

[0 rows x 36 columns]

================================================================================

================================================================================
⚠️  [STATUS: TARGET REVISI] TABEL: KELUARGA_KARYAWAN
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_keluarga        0 non-null      object
 1   id_karyawan        0 non-null      object
 2   hubungan_keluarga  0 non-null      object
 3   nama_lengkap       0 non-null      object
 4   pekerjaan          0 non-null      object
 5   nomor_hp           0 non-null      object
dtypes: object(6)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL SAAT INI] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
🔮 3. [⚠️ TARGET BLUEPRINT RUJUKAN] Tinjau Struktur yang Benar pada DB_FUTURE di bawah:

------------------------------------------------------------
📸 4. Sampel Isi Data Real di DB_NEW:

Empty DataFrame
Columns: [id_keluarga, id_karyawan, hubungan_keluarga, nama_lengkap, pekerjaan, nomor_hp]
Index: []

================================================================================

================================================================================
⚠️  [STATUS: TARGET REVISI] TABEL: DIVISION_USER
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_division_user  0 non-null      object
 1   id_division       0 non-null      object
 2   id_role           0 non-null      object
 3   created_at        0 non-null      object
 4   updated_at        0 non-null      object
dtypes: object(5)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL SAAT INI] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
🔮 3. [⚠️ TARGET BLUEPRINT RUJUKAN] Tinjau Struktur yang Benar pada DB_FUTURE di bawah:

------------------------------------------------------------
📸 4. Sampel Isi Data Real di DB_NEW:

Empty DataFrame
Columns: [id_division_user, id_division, id_role, created_at, updated_at]
Index: []

================================================================================

================================================================================
⚠️  [STATUS: TARGET REVISI] TABEL: MODEL_HAS_ROLES
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   role_id     0 non-null      object
 1   model_type  0 non-null      object
 2   model_id    0 non-null      object
dtypes: object(3)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL SAAT INI] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
🔮 3. [⚠️ TARGET BLUEPRINT RUJUKAN] Tinjau Struktur yang Benar pada DB_FUTURE di bawah:

------------------------------------------------------------
📸 4. Sampel Isi Data Real di DB_NEW:

Empty DataFrame
Columns: [role_id, model_type, model_id]
Index: []

================================================================================

================================================================================
⚠️  [STATUS: TARGET REVISI] TABEL: MODEL_HAS_PERMISSIONS
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   permission_id  0 non-null      object
 1   model_type     0 non-null      object
 2   model_id       0 non-null      object
dtypes: object(3)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL SAAT INI] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
🔮 3. [⚠️ TARGET BLUEPRINT RUJUKAN] Tinjau Struktur yang Benar pada DB_FUTURE di bawah:

------------------------------------------------------------
📸 4. Sampel Isi Data Real di DB_NEW:

Empty DataFrame
Columns: [permission_id, model_type, model_id]
Index: []

================================================================================

================================================================================
✨ [🟢 PERFECTLY MATCHED BOARD] SEBANYAK 7 TABEL STRUKTURNYA SUDAH IDENTIK SAMA PERSIS!
================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: BIDANG_KATEGORI
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id_bidang_kategori    0 non-null      object
 1   nama_kategori_bidang  0 non-null      object
 2   id_bidang             0 non-null      object
dtypes: object(3)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

Empty DataFrame
Columns: [id_bidang_kategori, nama_kategori_bidang, id_bidang]
Index: []

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: BIDANG_LINK
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_bidang_link      0 non-null      object
 1   nama_form           0 non-null      object
 2   link_drive          0 non-null      object
 3   id_bidang_kategori  0 non-null      object
 4   status_share        0 non-null      object
dtypes: object(5)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

Empty DataFrame
Columns: [id_bidang_link, nama_form, link_drive, id_bidang_kategori, status_share]
Index: []

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: PERIODE
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_periode     0 non-null      object
 1   nama_periode   0 non-null      object
 2   tanggal_mulai  0 non-null      object
 3   id_kursus      0 non-null      object
 4   jumlah_sesi    0 non-null      object
 5   tahun_ajar     0 non-null      object
 6   status         0 non-null      object
 7   is_active      0 non-null      object
dtypes: object(8)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

Empty DataFrame
Columns: [id_periode, nama_periode, tanggal_mulai, id_kursus, jumlah_sesi, tahun_ajar, status, is_active]
Index: []

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: PARAMETER_NILAI
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_parameter_nilai  0 non-null      object
 1   id_level            0 non-null      object
 2   nama_parameter      0 non-null      object
 3   status_parameter    0 non-null      object
dtypes: object(4)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

Empty DataFrame
Columns: [id_parameter_nilai, id_level, nama_parameter, status_parameter]
Index: []

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: KABUPATEN
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 514 entries, 0 to 513
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_kabupaten    514 non-null    int64
 1   id_provinsi     514 non-null    int64
 2   nama_kabupaten  514 non-null    object
 3   code            514 non-null    object
dtypes: int64(2), object(2)
memory usage: 16.2+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

     id_kabupaten  id_provinsi  nama_kabupaten code
0               1            1    Kota Mataram   21
1               2            1   Sumbawa Barat   22
2               3            1         Sumbawa   23
3               4            1   Lombok Tengah   24
4               5            1    Lombok Timur   25
..            ...          ...             ...  ...
509           511           39         Maybrat  500
510           512           39  Sorong Selatan  501
511           513           39        Tambrauw  503
512           514           39          Sorong  504
513           515           39     Kota Sorong  506

[514 rows x 4 columns]

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: KECAMATAN
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7266 entries, 0 to 7265
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_kecamatan    7266 non-null   int64
 1   id_kabupaten    7266 non-null   int64
 2   nama_kecamatan  7266 non-null   object
 3   code            7266 non-null   object
dtypes: int64(2), object(2)
memory usage: 227.2+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

      id_kecamatan  id_kabupaten nama_kecamatan  code
0                1             1      Sandubaya   197
1                2             1        Ampenan   208
2                3             1    Cakranegara   252
3                4             1      Selaprang   258
4                5             1      Sekarbela   269
...            ...           ...            ...   ...
7261          7305           515   Sorong Timur  7088
7262          7306           515   Sorong Manoi  7095
7263          7307           515   Sorong Barat  7098
7264          7308           515   Sorong Utara  7102
7265          7309           515    Maladum Mes  7108

[7266 rows x 4 columns]

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: KELURAHAN
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83449 entries, 0 to 83448
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_kelurahan    83449 non-null  int64
 1   id_kecamatan    83449 non-null  int64
 2   nama_kelurahan  83449 non-null  object
 3   kode_pos        0 non-null      object
dtypes: int64(2), object(2)
memory usage: 2.5+ MB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

       id_kelurahan  id_kecamatan    nama_kelurahan kode_pos
0                 1             1  Abian Tubuh Baru     None
1                 2             1           Babakan     None
2                 3             1           Bertais     None
3                 4             1      Dasan Cermen     None
4                 5             1         Mandalika     None
...             ...           ...               ...      ...
83444         83803          7308          Sawagumu     None
83445         83804          7309             Saoka     None
83446         83805          7309            Suprau     None
83447         83806          7309       Tampa Garam     None
83448         83807          7309   Tanjung Kasuari     None

[83449 rows x 4 columns]

================================================================================