# fase_2 - script_cimut Migration

This notebook handles migration of database from old DB to new DB for fase 2.

**Purpose**: Benerin database lama ke database baru untuk bagian [NAMA TABEL]

In [1]:
import sys
import os
import mysql.connector
import pandas as pd
sys.path.append(os.path.abspath('..'))
from config import get_db_config
import warnings
warnings.filterwarnings('ignore')

## Connect ke Database

In [2]:
# Connect ke database config
config = get_db_config()
# Ambil host dari salah satu config (misal db_old)
print(f'Database config loaded: {config["db_old"]["host"]}')

# Connect ke DB Lama
db_old = mysql.connector.connect(**config['db_old'])
cursor_old = db_old.cursor(dictionary=True)
print(f'Connected to old database: {config["db_old"]["database"]}')

# Connect ke DB Baru
db_new = mysql.connector.connect(**config['db_new'])
cursor_new = db_new.cursor(dictionary=True)
print(f'Connected to new database: {config["db_new"]["database"]}')

Database config loaded: localhost
Connected to old database: dataleap_v6_example
Connected to new database: 1

## Ambil Data dari DB Lama

In [3]:
# ---------------------------------------------------------
# UPDATE: AMBIL DAFTAR TABEL SECARA DINAMIS
# ---------------------------------------------------------
cursor_old.execute("SHOW TABLES")
tables_data = cursor_old.fetchall()

# Mengambil nama tabel dari hasil query
# Note: Format output 'SHOW TABLES' biasanya {'Tables_in_dbname': 'tablename'}
target_tables = [list(t.values())[0] for t in tables_data]

print(f"\n--- Ditemukan {len(target_tables)} tabel di Database Lama ---")
print(target_tables)

# Dictionary untuk menyimpan data yang sudah di-load
df_old = {}

print("\n--- Memulai proses load semua data tabel ---")

for table in target_tables:
    try:
        # Load data menggunakan pandas langsung dari koneksi SQL
        query = f"SELECT * FROM `{table}`"
        df_old[table] = pd.read_sql(query, db_old)
        
        print(f"Berhasil load tabel: {table} | Jumlah baris: {len(df_old[table])}")
        
    except Exception as e:
        print(f"Gagal load tabel {table}: {e}")

print("\n--- Proses load selesai. Semua data tersimpan di 'df_old' ---")
print("Kamu sekarang bisa akses datanya dengan: df_old['nama_tabel']")

# Contoh akses data:
# print(df_old['users'].head())

# Tutup koneksi jika sudah tidak digunakan
# db_old.close()
# db_new.close()

--- Ditemukan 115 tabel di Database Lama ---
['absensi', 'absensi_note', 'bidang', 'bidangkategori', 'bidanglink', 'cache', 'cache_locks', 'calon', 'calon_detil', 'calon_pertanyaan', 'calon_pertanyaan_detil', 'catatan_kelas', 'catatan_kelas_tag', 'catatan_mingguan', 'catatan_siswa', 'catatan_siswa_follow_up', 'catatanawal_admin', 'catatanawal_datautama', 'catatanawal_infolain', 'catatanawal_tglpenting', 'divisi', 'docs', 'failed_jobs', 'file_rapor_siswa', 'form', 'form_calon', 'form_calon_detil1', 'form_calon_detil2', 'form_calon_detil3', 'form_calon_detil4', 'format_rapor', 'format_rapor_detil', 'format_rapor_detil_rumus', 'format_rapor_rumus', 'format_raport_level', 'hakakses', 'histori_pengajuan', 'history_rapor', 'identitas', 'infrastruktur', 'jabatan', 'jadwal', 'jadwal_detil', 'jadwal_pengajar', 'jadwal_siswa', 'jamkerja', 'job_batches', 'jobs', 'kabupaten', 'karyawan', 'kecamatan', 'keluar', 'keluarga', 'kelurahan', 'kurikulum', 'kurikulum_detil', 'kurikulum_detil_sub', 'kurikulum_kelas', 'kursus', 'leapprofil', 'leapverse', 'level', 'libur', 'libur_pendkursus', 'linkdrive', 'linkform', 'log', 'migrations', 'mitra', 'mitra_note', 'mitra_users', 'mou', 'mou_histori', 'nowag', 'parameter_nilai', 'pekerjaan', 'pelamar', 'pelamar_note', 'pelamar_submit', 'pelamar_users', 'pendidikan', 'pendidikankursus', 'pengajuan', 'pengumuman', 'perijinan', 'perijinan_note', 'periode', 'pinjam', 'presensi_siswa', 'problem', 'provinsi', 'purchase', 'purchase_link', 'rapor', 'role', 'role_users', 'sesi', 'sessions', 'siswa', 'siswa_keluar', 'siswa_keluar_mitra', 'siswa_keluar_tag', 'siswamitra', 'sop', 'sopkategori', 'suratkeluar', 'suratkeluar_histori', 'surattugas', 'surattugas_users', 'syarat', 'tag_keluar', 'tag_materi_diskusi', 'ttd', 'users', 'zoom']

--- Memulai proses load semua data tabel ---
Berhasil load tabel: absensi | Jumlah baris: 14385
Berhasil load tabel: absensi_note | Jumlah baris: 11
Berhasil load tabel: bidang | Jumlah baris: 4
Berhasil load tabel: bidangkategori | Jumlah baris: 12
Berhasil load tabel: bidanglink | Jumlah baris: 7
Berhasil load tabel: cache | Jumlah baris: 0
Berhasil load tabel: cache_locks | Jumlah baris: 0
Berhasil load tabel: calon | Jumlah baris: 4
Berhasil load tabel: calon_detil | Jumlah baris: 61
Berhasil load tabel: calon_pertanyaan | Jumlah baris: 229
Berhasil load tabel: calon_pertanyaan_detil | Jumlah baris: 4305
Berhasil load tabel: catatan_kelas | Jumlah baris: 13733
Berhasil load tabel: catatan_kelas_tag | Jumlah baris: 1067
Berhasil load tabel: catatan_mingguan | Jumlah baris: 0
Berhasil load tabel: catatan_siswa | Jumlah baris: 1535
Berhasil load tabel: catatan_siswa_follow_up | Jumlah baris: 22
Berhasil load tabel: catatanawal_admin | Jumlah baris: 64
Berhasil load tabel: catatanawal_datautama | Jumlah baris: 9
Berhasil load tabel: catatanawal_infolain | Jumlah baris: 64
Berhasil load tabel: catatanawal_tglpenting | Jumlah baris: 10
Berhasil load tabel: divisi | Jumlah baris: 6
Berhasil load tabel: docs | Jumlah baris: 0
Berhasil load tabel: failed_jobs | Jumlah baris: 2
Berhasil load tabel: file_rapor_siswa | Jumlah baris: 1532
Berhasil load tabel: form | Jumlah baris: 1
Berhasil load tabel: form_calon | Jumlah baris: 220
Berhasil load tabel: form_calon_detil1 | Jumlah baris: 77
Berhasil load tabel: form_calon_detil2 | Jumlah baris: 77
Berhasil load tabel: form_calon_detil3 | Jumlah baris: 77
Berhasil load tabel: form_calon_detil4 | Jumlah baris: 77
Berhasil load tabel: format_rapor | Jumlah baris: 45
Berhasil load tabel: format_rapor_detil | Jumlah baris: 129
Berhasil load tabel: format_rapor_detil_rumus | Jumlah baris: 1650
Berhasil load tabel: format_rapor_rumus | Jumlah baris: 3
Berhasil load tabel: format_raport_level | Jumlah baris: 348
Berhasil load tabel: hakakses | Jumlah baris: 6
Berhasil load tabel: histori_pengajuan | Jumlah baris: 80
Berhasil load tabel: history_rapor | Jumlah baris: 1402
Berhasil load tabel: identitas | Jumlah baris: 0
Berhasil load tabel: infrastruktur | Jumlah baris: 1
Berhasil load tabel: jabatan | Jumlah baris: 11
Berhasil load tabel: jadwal | Jumlah baris: 558
Berhasil load tabel: jadwal_detil | Jumlah baris: 17322
Berhasil load tabel: jadwal_pengajar | Jumlah baris: 651
Berhasil load tabel: jadwal_siswa | Jumlah baris: 3960
Berhasil load tabel: jamkerja | Jumlah baris: 3
Berhasil load tabel: job_batches | Jumlah baris: 0
Berhasil load tabel: jobs | Jumlah baris: 0
Berhasil load tabel: kabupaten | Jumlah baris: 522
Berhasil load tabel: karyawan | Jumlah baris: 52
Berhasil load tabel: kecamatan | Jumlah baris: 7269
Berhasil load tabel: keluar | Jumlah baris: 52
Berhasil load tabel: keluarga | Jumlah baris: 67
Berhasil load tabel: kelurahan | Jumlah baris: 83473
Berhasil load tabel: kurikulum | Jumlah baris: 0
Berhasil load tabel: kurikulum_detil | Jumlah baris: 0
Berhasil load tabel: kurikulum_detil_sub | Jumlah baris: 0
Berhasil load tabel: kurikulum_kelas | Jumlah baris: 0
Berhasil load tabel: kursus | Jumlah baris: 51
Berhasil load tabel: leapprofil | Jumlah baris: 0
Berhasil load tabel: leapverse | Jumlah baris: 365
Berhasil load tabel: level | Jumlah baris: 181
Berhasil load tabel: libur | Jumlah baris: 79
Berhasil load tabel: libur_pendkursus | Jumlah baris: 2
Berhasil load tabel: linkdrive | Jumlah baris: 0
Berhasil load tabel: linkform | Jumlah baris: 3
Berhasil load tabel: log | Jumlah baris: 23404
Berhasil load tabel: migrations | Jumlah baris: 5
Berhasil load tabel: mitra | Jumlah baris: 23
Berhasil load tabel: mitra_note | Jumlah baris: 318
Berhasil load tabel: mitra_users | Jumlah baris: 250
Berhasil load tabel: mou | Jumlah baris: 2
Berhasil load tabel: mou_histori | Jumlah baris: 10
Berhasil load tabel: nowag | Jumlah baris: 1
Berhasil load tabel: parameter_nilai | Jumlah baris: 1187
Berhasil load tabel: pekerjaan | Jumlah baris: 69
Berhasil load tabel: pelamar | Jumlah baris: 180
Berhasil load tabel: pelamar_note | Jumlah baris: 419
Berhasil load tabel: pelamar_submit | Jumlah baris: 0
Berhasil load tabel: pelamar_users | Jumlah baris: 289
Berhasil load tabel: pendidikan | Jumlah baris: 56
Berhasil load tabel: pendidikankursus | Jumlah baris: 21
Berhasil load tabel: pengajuan | Jumlah baris: 33
Berhasil load tabel: pengumuman | Jumlah baris: 0
Berhasil load tabel: perijinan | Jumlah baris: 970
Berhasil load tabel: perijinan_note | Jumlah baris: 2140
Berhasil load tabel: periode | Jumlah baris: 93
Berhasil load tabel: pinjam | Jumlah baris: 224
Berhasil load tabel: presensi_siswa | Jumlah baris: 108795
Berhasil load tabel: problem | Jumlah baris: 174
Berhasil load tabel: provinsi | Jumlah baris: 36
Berhasil load tabel: purchase | Jumlah baris: 120
Berhasil load tabel: purchase_link | Jumlah baris: 1
Berhasil load tabel: rapor | Jumlah baris: 23241
Berhasil load tabel: role | Jumlah baris: 9
Berhasil load tabel: role_users | Jumlah baris: 0
Berhasil load tabel: sesi | Jumlah baris: 43
Berhasil load tabel: sessions | Jumlah baris: 30
Berhasil load tabel: siswa | Jumlah baris: 1500
Berhasil load tabel: siswa_keluar | Jumlah baris: 598
Berhasil load tabel: siswa_keluar_mitra | Jumlah baris: 0
Berhasil load tabel: siswa_keluar_tag | Jumlah baris: 445
Berhasil load tabel: siswamitra | Jumlah baris: 0
Berhasil load tabel: sop | Jumlah baris: 4
Berhasil load tabel: sopkategori | Jumlah baris: 3
Berhasil load tabel: suratkeluar | Jumlah baris: 231
Berhasil load tabel: suratkeluar_histori | Jumlah baris: 513
Berhasil load tabel: surattugas | Jumlah baris: 139
Berhasil load tabel: surattugas_users | Jumlah baris: 319
Berhasil load tabel: syarat | Jumlah baris: 1
Berhasil load tabel: tag_keluar | Jumlah baris: 11
Berhasil load tabel: tag_materi_diskusi | Jumlah baris: 11
Berhasil load tabel: ttd | Jumlah baris: 1
Berhasil load tabel: users | Jumlah baris: 52
Berhasil load tabel: zoom | Jumlah baris: 14

--- Proses load selesai. Semua data tersimpan di 'df_old' ---
Kamu sekarang bisa akses datanya dengan: df_old['nama_tabel']

In [4]:
# ---------------------------------------------------------
# UPDATE: AMBIL DAFTAR TABEL SECARA DINAMIS (DATABASE BARU)
# ---------------------------------------------------------
# Menggunakan cursor dari database baru
cursor_new.execute("SHOW TABLES")
tables_data_new = cursor_new.fetchall()

# Mengambil nama tabel dari hasil query
target_tables_new = [list(t.values())[0] for t in tables_data_new]

print(f"\n--- Ditemukan {len(target_tables_new)} tabel di Database Baru ---")
print(target_tables_new)

# Dictionary untuk menyimpan data dari database baru (jika diperlukan untuk verifikasi)
df_new = {}

print("\n--- Memulai proses load semua data dari Database Baru ---")

for table in target_tables_new:
    try:
        # Load data menggunakan pandas dengan koneksi database baru
        query = f"SELECT * FROM `{table}`"
        df_new[table] = pd.read_sql(query, db_new)
        
        print(f"Berhasil load tabel: {table} | Jumlah baris: {len(df_new[table])}")
        
    except Exception as e:
        print(f"Gagal load tabel {table} dari DB Baru: {e}")

print("\n--- Proses load selesai. Data DB Baru tersimpan di 'df_new' ---")

--- Ditemukan 113 tabel di Database Baru ---
['absensi', 'activity_log', 'admin_sarpras', 'bidang_kategori', 'bidang_link', 'busdev_bidang', 'cache', 'cache_locks', 'calon_siswa', 'calon_siswa_akademik', 'calon_siswa_bayar', 'calon_siswa_fo_detail', 'calon_siswa_form_program_requirements', 'calon_siswa_form_programs', 'calon_siswa_jadwal', 'calon_siswa_kursus', 'calon_siswa_ortu', 'calon_siswa_proses', 'calon_siswa_proses_logs', 'calon_siswa_status_logs', 'catatan_kelas', 'catatan_kelas_tag', 'catatan_mingguan', 'catatan_remidi_siswa', 'catatan_siswa', 'division_user', 'divisions', 'failed_jobs', 'followup_cs', 'histori_pengajuan', 'izin_karyawan', 'jadwal', 'jadwal_detail', 'jadwal_detail_logs', 'jadwal_hari', 'jadwal_pengajar', 'jadwal_siswa', 'job_batches', 'jobs', 'kabupaten', 'karyawan', 'karyawan_resign', 'kecamatan', 'keluarga_karyawan', 'kelurahan', 'kemitraan_verifikator', 'kontak_prospek', 'kursus', 'kursus_level', 'kursus_libur', 'kursus_siswa', 'level', 'libur', 'log_aktivitas', 'migrations', 'mitra', 'mitra_progres', 'model_has_permissions', 'model_has_roles', 'mou', 'parameter_nilai', 'password_reset_tokens', 'pelamar', 'pelamar_kerja', 'pelamar_kursus', 'pelamar_sekolah', 'peminjaman', 'pengadaan', 'pengajuan_karyawan', 'penilaian_kinerja', 'periode', 'permissions', 'presensi_siswa', 'problem', 'progres_pelamar', 'provinsi', 'rapor_format', 'rapor_format_formula', 'rapor_format_formula_sub', 'rapor_format_sub', 'rapor_lacak', 'rapor_level_config', 'rapor_setting_kursus', 'rapor_siswa', 'rapor_siswa_file', 'rapor_sub_level', 'rekrutmen_pelamar', 'role_has_permissions', 'roles', 'sesi', 'sessions', 'shift_kerja', 'siswa', 'siswa_bulk_edit_logs', 'siswa_keluar', 'siswa_keluar_feedbacks', 'siswa_mitra', 'siswa_mitra_keluar', 'sop', 'sop_kategori', 'surat_keluar', 'surat_tugas', 'surat_tugas_anggota', 'syarat_resign', 'tag_siswa_keluar', 'topik_diskusi', 'ttd', 'users', 'verifikasi_absensi', 'verifikasi_izin', 'verifikasi_surat_keluar', 'web_berita', 'web_statistik']

--- Memulai proses load semua data dari Database Baru ---
Berhasil load tabel: absensi | Jumlah baris: 0
Berhasil load tabel: activity_log | Jumlah baris: 0
Berhasil load tabel: admin_sarpras | Jumlah baris: 1
Berhasil load tabel: bidang_kategori | Jumlah baris: 0
Berhasil load tabel: bidang_link | Jumlah baris: 0
Berhasil load tabel: busdev_bidang | Jumlah baris: 0
Berhasil load tabel: cache | Jumlah baris: 0
Berhasil load tabel: cache_locks | Jumlah baris: 0
Berhasil load tabel: calon_siswa | Jumlah baris: 0
Berhasil load tabel: calon_siswa_akademik | Jumlah baris: 0
Berhasil load tabel: calon_siswa_bayar | Jumlah baris: 0
Berhasil load tabel: calon_siswa_fo_detail | Jumlah baris: 0
Berhasil load tabel: calon_siswa_form_program_requirements | Jumlah baris: 0
Berhasil load tabel: calon_siswa_form_programs | Jumlah baris: 0
Berhasil load tabel: calon_siswa_jadwal | Jumlah baris: 0
Berhasil load tabel: calon_siswa_kursus | Jumlah baris: 0
Berhasil load tabel: calon_siswa_ortu | Jumlah baris: 0
Berhasil load tabel: calon_siswa_proses | Jumlah baris: 0
Berhasil load tabel: calon_siswa_proses_logs | Jumlah baris: 0
Berhasil load tabel: calon_siswa_status_logs | Jumlah baris: 0
Berhasil load tabel: catatan_kelas | Jumlah baris: 0
Berhasil load tabel: catatan_kelas_tag | Jumlah baris: 0
Berhasil load tabel: catatan_mingguan | Jumlah baris: 0
Berhasil load tabel: catatan_remidi_siswa | Jumlah baris: 0
Berhasil load tabel: catatan_siswa | Jumlah baris: 0
Berhasil load tabel: division_user | Jumlah baris: 0
Berhasil load tabel: divisions | Jumlah baris: 7
Berhasil load tabel: failed_jobs | Jumlah baris: 0
Berhasil load tabel: followup_cs | Jumlah baris: 0
Berhasil load tabel: histori_pengajuan | Jumlah baris: 0
Berhasil load tabel: izin_karyawan | Jumlah baris: 0
Berhasil load tabel: jadwal | Jumlah baris: 0
Berhasil load tabel: jadwal_detail | Jumlah baris: 0
Berhasil load tabel: jadwal_detail_logs | Jumlah baris: 0
Berhasil load tabel: jadwal_hari | Jumlah baris: 0
Berhasil load tabel: jadwal_pengajar | Jumlah baris: 0
Berhasil load tabel: jadwal_siswa | Jumlah baris: 0
Berhasil load tabel: job_batches | Jumlah baris: 0
Berhasil load tabel: jobs | Jumlah baris: 0
Berhasil load tabel: kabupaten | Jumlah baris: 514
Berhasil load tabel: karyawan | Jumlah baris: 0
Berhasil load tabel: karyawan_resign | Jumlah baris: 0
Berhasil load tabel: kecamatan | Jumlah baris: 7266
Berhasil load tabel: keluarga_karyawan | Jumlah baris: 0
Berhasil load tabel: kelurahan | Jumlah baris: 83449
Berhasil load tabel: kemitraan_verifikator | Jumlah baris: 0
Berhasil load tabel: kontak_prospek | Jumlah baris: 0
Berhasil load tabel: kursus | Jumlah baris: 20
Berhasil load tabel: kursus_level | Jumlah baris: 177
Berhasil load tabel: kursus_libur | Jumlah baris: 1
Berhasil load tabel: kursus_siswa | Jumlah baris: 0
Berhasil load tabel: level | Jumlah baris: 181
Berhasil load tabel: libur | Jumlah baris: 78
Berhasil load tabel: log_aktivitas | Jumlah baris: 0
Berhasil load tabel: migrations | Jumlah baris: 0
Berhasil load tabel: mitra | Jumlah baris: 0
Berhasil load tabel: mitra_progres | Jumlah baris: 0
Berhasil load tabel: model_has_permissions | Jumlah baris: 0
Berhasil load tabel: model_has_roles | Jumlah baris: 0
Berhasil load tabel: mou | Jumlah baris: 0
Berhasil load tabel: parameter_nilai | Jumlah baris: 0
Berhasil load tabel: password_reset_tokens | Jumlah baris: 0
Berhasil load tabel: pelamar | Jumlah baris: 0
Berhasil load tabel: pelamar_kerja | Jumlah baris: 0
Berhasil load tabel: pelamar_kursus | Jumlah baris: 0
Berhasil load tabel: pelamar_sekolah | Jumlah baris: 0
Berhasil load tabel: peminjaman | Jumlah baris: 0
Berhasil load tabel: pengadaan | Jumlah baris: 0
Berhasil load tabel: pengajuan_karyawan | Jumlah baris: 0
Berhasil load tabel: penilaian_kinerja | Jumlah baris: 0
Berhasil load tabel: periode | Jumlah baris: 0
Berhasil load tabel: permissions | Jumlah baris: 0
Berhasil load tabel: presensi_siswa | Jumlah baris: 0
Berhasil load tabel: problem | Jumlah baris: 0
Berhasil load tabel: progres_pelamar | Jumlah baris: 0
Berhasil load tabel: provinsi | Jumlah baris: 38
Berhasil load tabel: rapor_format | Jumlah baris: 0
Berhasil load tabel: rapor_format_formula | Jumlah baris: 0
Berhasil load tabel: rapor_format_formula_sub | Jumlah baris: 0
Berhasil load tabel: rapor_format_sub | Jumlah baris: 0
Berhasil load tabel: rapor_lacak | Jumlah baris: 0
Berhasil load tabel: rapor_level_config | Jumlah baris: 0
Berhasil load tabel: rapor_setting_kursus | Jumlah baris: 0
Berhasil load tabel: rapor_siswa | Jumlah baris: 0
Berhasil load tabel: rapor_siswa_file | Jumlah baris: 0
Berhasil load tabel: rapor_sub_level | Jumlah baris: 0
Berhasil load tabel: rekrutmen_pelamar | Jumlah baris: 0
Berhasil load tabel: role_has_permissions | Jumlah baris: 0
Berhasil load tabel: roles | Jumlah baris: 0
Berhasil load tabel: sesi | Jumlah baris: 43
Berhasil load tabel: sessions | Jumlah baris: 0
Berhasil load tabel: shift_kerja | Jumlah baris: 3
Berhasil load tabel: siswa | Jumlah baris: 0
Berhasil load tabel: siswa_bulk_edit_logs | Jumlah baris: 0
Berhasil load tabel: siswa_keluar | Jumlah baris: 0
Berhasil load tabel: siswa_keluar_feedbacks | Jumlah baris: 0
Berhasil load tabel: siswa_mitra | Jumlah baris: 0
Berhasil load tabel: siswa_mitra_keluar | Jumlah baris: 0
Berhasil load tabel: sop | Jumlah baris: 0
Berhasil load tabel: sop_kategori | Jumlah baris: 0
Berhasil load tabel: surat_keluar | Jumlah baris: 0
Berhasil load tabel: surat_tugas | Jumlah baris: 0
Berhasil load tabel: surat_tugas_anggota | Jumlah baris: 0
Berhasil load tabel: syarat_resign | Jumlah baris: 0
Berhasil load tabel: tag_siswa_keluar | Jumlah baris: 0
Berhasil load tabel: topik_diskusi | Jumlah baris: 11
Berhasil load tabel: ttd | Jumlah baris: 0
Berhasil load tabel: users | Jumlah baris: 52
Berhasil load tabel: verifikasi_absensi | Jumlah baris: 0
Berhasil load tabel: verifikasi_izin | Jumlah baris: 0
Berhasil load tabel: verifikasi_surat_keluar | Jumlah baris: 0
Berhasil load tabel: web_berita | Jumlah baris: 0
Berhasil load tabel: web_statistik | Jumlah baris: 0

--- Proses load selesai. Data DB Baru tersimpan di 'df_new' ---

# Fixing Tabel Kariawan

## Merge df_old[users] dan df_new[users]

karyawan, keluarga_karyawan, bidang_kategori, bidang_link.

In [5]:
id_karyawan_lama = df_old['karyawan']['idkaryawan'].astype(str).str.strip()

In [6]:
df_old['users'].head()

,idusers,email,pass,nama,foto,idrole,wa,thnbekerja,idjabatan,idjamkerja,...,ispurchase,isteaching,ishr,isga,isit,ispdd,isbusdev,ispimpinan,ttd,expertise
0,U00001,ditari@leapsurabaya.sch.id,aGtq,ADMINISTRATOR,logo.png,R00001,0851-7438-7539,2023-06-02,J00005,2.0,...,0.0,0.0,0,1,0,0,0,0,None,None
1,U00003,graciela@leapsurabaya.sch.id,qWmlbcVjYmo%3D,"Graciela Evanda Ronadi, S.Kom.",1707279559_ec864cc58f50e8b890d5.jpg,R00003,0812-3447-7137,2023-03-13,J00006,2.0,...,0.0,1.0,0,0,0,0,0,0,1702002184_d82747bcbd0f2bdab0a7.png,None
2,U00011,daniar.rizki@leapsurabaya.sch.id,aGtq,DANIAR AULIA RIZKI,1692700456_2d6352eb557d734e53b7.jpeg,R00006,0896-9632-0278,2020-12-01,J00010,2.0,...,0.0,0.0,0,0,0,0,1,0,None,
3,U00012,habibah.elfiani@leapsurabaya.sch.id,o56YqZJkZA%3D%3D,Habibah Melyna,1686127161_1ec3d11da554fb668e7c.jpg,R00003,0857-3093-3317,2020-03-02,J00002,3.0,...,0.0,1.0,0,0,0,1,1,0,1702892302_89507e3f2d87fb0dfdee.png,desain grafis
4,U00014,laksmi.p@leapsurabaya.sch.id,aWlpbw%3D%3D,Laksmi Puspitowardhani,1696338938_2a535db26e3f89919325.jpg,R00008,0821-3996-6817,2018-07-31,J00004,3.0,...,0.0,0.0,0,0,0,1,0,0,None,

In [7]:
df_new['users'].head()

,id_user,name,email,email_verified_at,password,remember_token,created_at,updated_at
0,U00001,ADMINISTRATOR,ditari@leapsurabaya.sch.id,2026-06-23 21:40:16,aGtq,None,2026-06-23 21:40:16,2026-06-23 21:40:16
1,U00003,"Graciela Evanda Ronadi, S.Kom.",graciela@leapsurabaya.sch.id,2026-06-23 21:40:16,qWmlbcVjYmo%3D,None,2026-06-23 21:40:16,2026-06-23 21:40:16
2,U00011,DANIAR AULIA RIZKI,daniar.rizki@leapsurabaya.sch.id,2026-06-23 21:40:16,aGtq,None,2026-06-23 21:40:16,2026-06-23 21:40:16
3,U00012,Habibah Melyna,habibah.elfiani@leapsurabaya.sch.id,2026-06-23 21:40:16,o56YqZJkZA%3D%3D,None,2026-06-23 21:40:16,2026-06-23 21:40:16
4,U00014,Laksmi Puspitowardhani,laksmi.p@leapsurabaya.sch.id,2026-06-23 21:40:16,aWlpbw%3D%3D,None,2026-06-23 21:40:16,2026-06-23 21:40:16

In [8]:
df_old['karyawan'].head()

,idkaryawan,ktp,nickname,kota,tgl,jk,goldar,agama,status,alamatktp,...,bpjskerja,bpjssehat,idusers,nama,anak,rekening,moda,ig,fb,link
0,LEAP001VI02,None,None,None,None,Wanita,None,None,None,None,...,None,None,U00001,None,None,None,None,None,None,
1,LEAP003III2023,3514186411980002,Graciela,Sidoarjo,11/24/1998,Wanita,-,Islam,Belum Kawin,"Ranggeh, Gondangwetan, Pasuruan",...,,,U00003,Graciela Evanda Ronadi,,0140881385821,Motor Pribadi,https://www.instagram.com/gracielaevr/,,https://drive.google.com/drive/folders/1alw9Su...
2,LEAP011XII01,3515135105910001,DANIAR,SURABAYA,05/11/1991,Wanita,B,ISLAM,KAWIN,"PONDOK TROSOBO INDAH L-5, RT 003 RW 009, TROSO...",...,21034278636,0002319622514,U00011,DANIAR AULIA RIZKI,1,1410022279715,SEPEDA MOTOR,@dar.od,tidak ada,https://drive.google.com/drive/u/0/folders/1va...
3,LEAP012III02,3578106705930001,Habibah,Semarang,05/27/1993,Wanita,AB,Islam,Belum menikah,Jl Pacar Kembang Vc No 22,...,21034278651,0002999218792,U00012,Habibah Melyna Elfiani,,1420018314442,Sepeda Motor Pribadi,https://instagram.com/habibahmelyna?igshid=MzN...,,None
4,LEAP014VII31,3578035706820005,Laksmi,Surabaya,06/17/1982,Wanita,O,ISLAM,Single,Rungkut Asri Barat XIII no 17,...,18088838356,00015384308,U00014,Laksmi Puspitowardhani,,1420016807967,Motor,https://www.instagram.com/laksmi_purplespace/?...,-,https://drive.google.com/drive/folders/1-7iI4-...

In [9]:
# Gabungin df_old['users'] dengan df_new['users'] berdasarkan ID, tapi hanya untuk kolom yang ada di df_old dan tidak ada di df_new
cols_to_keep_from_old = [col for col in df_old['users'].columns 
                        if col not in ['nama', 'pass'] 
                        and col not in df_new['users'].columns]

# Merge berdasarkan id_user (new) dan idusers (old)
df_merged_users = df_new['users'].merge(
    df_old['users'][['idusers'] + [c for c in cols_to_keep_from_old if c != 'idusers']],
    left_on='id_user',
    right_on='idusers',
    how='left'
)

df_merged_users.head()

,id_user,name,email,email_verified_at,password,remember_token,created_at,updated_at,idusers,foto,...,ispurchase,isteaching,ishr,isga,isit,ispdd,isbusdev,ispimpinan,ttd,expertise
0,U00001,ADMINISTRATOR,ditari@leapsurabaya.sch.id,2026-06-23 21:40:16,aGtq,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00001,logo.png,...,0.0,0.0,0,1,0,0,0,0,None,None
1,U00003,"Graciela Evanda Ronadi, S.Kom.",graciela@leapsurabaya.sch.id,2026-06-23 21:40:16,qWmlbcVjYmo%3D,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00003,1707279559_ec864cc58f50e8b890d5.jpg,...,0.0,1.0,0,0,0,0,0,0,1702002184_d82747bcbd0f2bdab0a7.png,None
2,U00011,DANIAR AULIA RIZKI,daniar.rizki@leapsurabaya.sch.id,2026-06-23 21:40:16,aGtq,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00011,1692700456_2d6352eb557d734e53b7.jpeg,...,0.0,0.0,0,0,0,0,1,0,None,
3,U00012,Habibah Melyna,habibah.elfiani@leapsurabaya.sch.id,2026-06-23 21:40:16,o56YqZJkZA%3D%3D,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00012,1686127161_1ec3d11da554fb668e7c.jpg,...,0.0,1.0,0,0,0,1,1,0,1702892302_89507e3f2d87fb0dfdee.png,desain grafis
4,U00014,Laksmi Puspitowardhani,laksmi.p@leapsurabaya.sch.id,2026-06-23 21:40:16,aWlpbw%3D%3D,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00014,1696338938_2a535db26e3f89919325.jpg,...,0.0,0.0,0,0,0,1,0,0,None,

In [10]:
# Analisis df_merged_users untuk duplicate columns, null values, dan informasi lainnya

print("="*80)
print("ANALISIS df_merged_users")
print("="*80)

# 1. Info umum dataframe
print("\n1. INFORMASI UMUM:")
print(f"   Shape: {df_merged_users.shape}")
print(f"   Total Rows: {len(df_merged_users)}")
print(f"   Total Columns: {len(df_merged_users.columns)}")

# 2. Cek duplicate columns
print("\n2. DUPLICATE COLUMNS:")
duplicate_cols = df_merged_users.columns[df_merged_users.columns.duplicated()]
if len(duplicate_cols) > 0:
    print(f"   ⚠️  Ditemukan {len(duplicate_cols)} duplicate column(s):")
    for col in duplicate_cols.unique():
        print(f"      - {col}")
else:
    print("   ✓ Tidak ada duplicate columns")

# 3. Cek null values per column
print("\n3. NULL VALUES PER COLUMN:")
null_counts = df_merged_users.isnull().sum()
null_percentage = (null_counts / len(df_merged_users)) * 100
null_info = pd.DataFrame({
    'Column': null_counts.index,
    'Null_Count': null_counts.values,
    'Null_Percentage': null_percentage.values
}).sort_values('Null_Count', ascending=False)

null_info_display = null_info[null_info['Null_Count'] > 0]
if len(null_info_display) > 0:
    print(null_info_display.to_string(index=False))
else:
    print("   ✓ Tidak ada null values")

# 4. Data types
print("\n4. DATA TYPES:")
# Display data types with a more detailed summary
dtype_summary = pd.DataFrame({
    'Column': df_merged_users.dtypes.index,
    'Data_Type': df_merged_users.dtypes.values
})
print(dtype_summary.to_string(index=False))


print("\n5. VALUE COUNTS PER COLUMN:")
print("=" * 80)

for col in df_merged_users.columns:
    print(f"\n{col}:")
    print(f"  Unique values: {df_merged_users[col].nunique()}")
    if df_merged_users[col].dtype in ['object', 'str', 'int64', 'float64']:
        # Untuk kolom string/object, tampilkan value counts
        value_counts = df_merged_users[col].value_counts(dropna=False)
        if len(value_counts) <= 10:
            print(value_counts)
        else:
            print(value_counts.head(10))
            print(f"  ... dan {len(value_counts) - 10} nilai lainnya")
    else:
        # Untuk kolom numerik, tampilkan statistik
        print(f"  Min: {df_merged_users[col].min()}")
        print(f"  Max: {df_merged_users[col].max()}")
        print(f"  Mean: {df_merged_users[col].mean():.2f}")

================================================================================
ANALISIS df_merged_users
================================================================================

1. INFORMASI UMUM:
   Shape: (52, 28)
   Total Rows: 52
   Total Columns: 28

2. DUPLICATE COLUMNS:
   ✓ Tidak ada duplicate columns

3. NULL VALUES PER COLUMN:
        Column  Null_Count  Null_Percentage
remember_token          52       100.000000
      idbidang          41        78.846154
    idjamkerja          38        73.076923
           ttd          37        71.153846
     expertise          11        21.153846
          foto           8        15.384615
         minat           1         1.923077
    isteaching           1         1.923077
            wa           1         1.923077
    ispurchase           1         1.923077

4. DATA TYPES:
           Column      Data_Type
          id_user         object
             name         object
            email         object
email_verified_at datetime64[ns]
         password         object
   remember_token         object
       created_at datetime64[ns]
       updated_at datetime64[ns]
          idusers         object
             foto         object
           idrole         object
               wa         object
       thnbekerja         object
        idjabatan         object
       idjamkerja        float64
            minat         object
           status         object
         idbidang        float64
       ispurchase        float64
       isteaching        float64
             ishr          int64
             isga          int64
             isit          int64
            ispdd          int64
         isbusdev          int64
       ispimpinan          int64
              ttd         object
        expertise         object

5. VALUE COUNTS PER COLUMN:
================================================================================

id_user:
  Unique values: 52
id_user
U00001    1
U00003    1
U00011    1
U00012    1
U00014    1
U00015    1
U00016    1
U00018    1
U00019    1
U00020    1
Name: count, dtype: int64
  ... dan 42 nilai lainnya

name:
  Unique values: 52
name
ADMINISTRATOR                     1
Graciela Evanda Ronadi, S.Kom.    1
DANIAR AULIA RIZKI                1
Habibah Melyna                    1
Laksmi Puspitowardhani            1
Ika Asriani Yadin                 1
Luluk Fatikah Sari, S.Pd.         1
Ditari Kurnia                     1
Hartatik, S.S.                    1
Juni Arlianto                     1
Name: count, dtype: int64
  ... dan 42 nilai lainnya

email:
  Unique values: 52
email
ditari@leapsurabaya.sch.id             1
graciela@leapsurabaya.sch.id           1
daniar.rizki@leapsurabaya.sch.id       1
habibah.elfiani@leapsurabaya.sch.id    1
laksmi.p@leapsurabaya.sch.id           1
ikayadin@leapsurabaya.sch.id           1
luluk.sari@leapsurabaya.sch.id         1
admin@gmail.com                        1
hartatik@leapsurabaya.sch.id           1
juni.arlianto@leapsurabaya.sch.id      1
Name: count, dtype: int64
  ... dan 42 nilai lainnya

email_verified_at:
  Unique values: 1
  Min: 2026-06-23 21:40:16
  Max: 2026-06-23 21:40:16
  Mean: .2f

password:
  Unique values: 21
password
aGtq                    31
o56YqZJkZGw%3D           2
qWmlbcVjYmo%3D           1
aWlpbw%3D%3D             1
o56YqZJkZA%3D%3D         1
o66jrsxjY2s%3D           1
p5qenpJkZA%3D%3D         1
bnFw                     1
fKSYp9akqJnNqauhm5WZ     1
sKimp9STn6DGYGY%3D       1
Name: count, dtype: int64
  ... dan 11 nilai lainnya

remember_token:
  Unique values: 0
remember_token
None    52
Name: count, dtype: int64

created_at:
  Unique values: 1
  Min: 2026-06-23 21:40:16
  Max: 2026-06-23 21:40:16
  Mean: .2f

updated_at:
  Unique values: 1
  Min: 2026-06-23 21:40:16
  Max: 2026-06-23 21:40:16
  Mean: .2f

idusers:
  Unique values: 52
idusers
U00001    1
U00003    1
U00011    1
U00012    1
U00014    1
U00015    1
U00016    1
U00018    1
U00019    1
U00020    1
Name: count, dtype: int64
  ... dan 42 nilai lainnya

foto:
  Unique values: 44
foto
None                                     8
1707279559_ec864cc58f50e8b890d5.jpg      1
1692700456_2d6352eb557d734e53b7.jpeg     1
1686127161_1ec3d11da554fb668e7c.jpg      1
logo.png                                 1
1694397431_30b88a94a51ff7c8024e.png      1
1688370880_b894a9a6a8aa56770eaf.jpeg     1
1742411840_4c3bd3fb30f609808130.shtml    1
1690430190_e05a6e1833612e00b30a.jpeg     1
1688629580_4df06718a9d1efc1946a.jpeg     1
Name: count, dtype: int64
  ... dan 35 nilai lainnya

idrole:
  Unique values: 8
idrole
R00005    24
R00008     8
R00006     6
R00003     5
R00002     5
R00001     2
R00004     1
R00007     1
Name: count, dtype: int64

wa:
  Unique values: 48
wa
0851-7438-7539    2
0812-3447-7137    2
0000-0000-0000    2
0857-3093-3317    1
0896-9632-0278    1
0852-1124-3425    1
0857-8546-7685    1
0852-3471-6582    1
0821-3996-6817    1
0881-0264-0001    1
Name: count, dtype: int64
  ... dan 39 nilai lainnya

thnbekerja:
  Unique values: 45
thnbekerja
2025-11-03    4
2023-07-04    2
2023-03-25    2
2023-01-02    2
2025-07-14    2
14-2-2011     1
2017-06-19    1
2021-04-20    1
2023-06-02    1
2023-03-13    1
Name: count, dtype: int64
  ... dan 35 nilai lainnya

idjabatan:
  Unique values: 9
idjabatan
J00010    30
J00008     9
J00006     5
J00005     2
J00009     2
J00004     1
J00002     1
J00007     1
J00013     1
Name: count, dtype: int64

idjamkerja:
  Unique values: 2
idjamkerja
NaN    38
3.0     8
2.0     6
Name: count, dtype: int64

minat:
  Unique values: 41
minat
-                          10
Mengajar                    2
Web, php, CI4, database     1
BERNYANYI                   1
Belajar dan bertumbuh       1
Psikologi & Bisnis          1
Edu                         1
bahagia dunia akhirat       1
Coffee and Game             1
bekerja                     1
Name: count, dtype: int64
  ... dan 32 nilai lainnya

status:
  Unique values: 2
status
Aktif        40
Non Aktif    12
Name: count, dtype: int64

idbidang:
  Unique values: 3
idbidang
NaN     41
7.0      5
11.0     3
9.0      3
Name: count, dtype: int64

ispurchase:
  Unique values: 2
ispurchase
0.0    48
1.0     3
NaN     1
Name: count, dtype: int64

isteaching:
  Unique values: 2
isteaching
0.0    42
1.0     9
NaN     1
Name: count, dtype: int64

ishr:
  Unique values: 2
ishr
0    50
1     2
Name: count, dtype: int64

isga:
  Unique values: 2
isga
0    49
1     3
Name: count, dtype: int64

isit:
  Unique values: 1
isit
0    52
Name: count, dtype: int64

ispdd:
  Unique values: 2
ispdd
0    44
1     8
Name: count, dtype: int64

isbusdev:
  Unique values: 2
isbusdev
0    50
1     2
Name: count, dtype: int64

ispimpinan:
  Unique values: 1
ispimpinan
0    52
Name: count, dtype: int64

ttd:
  Unique values: 15
ttd
None                                   37
1702002184_d82747bcbd0f2bdab0a7.png     1
1702892302_89507e3f2d87fb0dfdee.png     1
1708307211_3e160b7a0d1560febc2c.png     1
1708311112_ea63d8f1f2fb12dc6dbe.png     1
1708306240_0064c7d03c77638eb889.png     1
1708353208_d07b06675d1e5fa23383.png     1
1708324727_7d2882c04c6ff75ad399.png     1
1708658996_306c792c8c264fa46529.png     1
1708311420_9f19bdbeef8ddeb7c9dd.png     1
Name: count, dtype: int64
  ... dan 6 nilai lainnya

expertise:
  Unique values: 2
expertise
                 40
None             11
desain grafis     1
Name: count, dtype: int64

## Benerin nama dan nickname

nama_lengkap di tabel kariawan tidak digunakan.

In [11]:
# ---------------------------------------------------------
# CEK KESAMAAN NAMA: df_old['karyawan'] vs df_new['users']
# ---------------------------------------------------------

# 1. Ambil kolom yang diperlukan
old_karyawan = df_old['karyawan'][['idusers', 'nama']].copy()
new_users = df_new['users'][['id_user', 'name']].copy()

# 2. Gabungkan data berdasarkan acuan ID
comparison = pd.merge(
    old_karyawan, 
    new_users, 
    left_on='idusers', 
    right_on='id_user', 
    how='inner'
)

# 3. Bandingkan kolom nama dan name (gunakan strip untuk akurasi)
comparison['is_same'] = comparison['nama'].str.strip() == comparison['name'].str.strip()

# 4. Tampilkan ringkasan hasil
total_data = len(comparison)
total_sama = comparison['is_same'].sum()
total_beda = total_data - total_sama

print(f"Total data yang dicek: {total_data}")
print(f"Data yang sama: {total_sama}")
print(f"Data yang berbeda: {total_beda}")

# 5. Tampilkan daftar yang berbeda jika ada
if total_beda > 0:
    print("\n--- Daftar Perbedaan (Mismatches) ---")
    mismatches = comparison[comparison['is_same'] == False]
    display(mismatches[['id_user', 'nama', 'name']])
else:
    print("\n✅ Semua nama sudah sesuai antara df_old['karyawan'] dan df_new['users']!")

Total data yang dicek: 52
Data yang sama: 22
Data yang berbeda: 30

--- Daftar Perbedaan (Mismatches) ---

,id_user,nama,name
0,U00001,None,ADMINISTRATOR
1,U00003,Graciela Evanda Ronadi,"Graciela Evanda Ronadi, S.Kom."
3,U00012,Habibah Melyna Elfiani,Habibah Melyna
5,U00015,None,Ika Asriani Yadin
6,U00016,Luluk Fatikah Sari,"Luluk Fatikah Sari, S.Pd."
7,U00018,Ditari Kurnia Damayanti,Ditari Kurnia
8,U00019,Hartatik,"Hartatik, S.S."
10,U00023,Titi Hapsari Retnaningtias,Titi Hapsari
11,U00026,Qorin Rahmaniyah,"Qorin Rahmaniyah, S.Pd."
12,U00027,fgz,Test
13,U00028,None,pengajar
14,U00030,Admin Pendidikan,Akun Data PPDK
15,U00031,Eka Nur Wahyuni,"Eka Nur Wahyuni, S. Pd."
16,U00032,GETARI ADYAGARINI,"Getari Adyagarini, M.Pd"
17,U00033,Maria Florencia Erica Susanto,"Maria Florencia Erica Susanto, A.Md."
18,U00034,Mieke Puspita,"Mieke Puspita, S.Pd"
19,U00035,MIFTAKHUL JANNAH,"Miftakhul Jannah, S.Pd"
20,U00036,Rr. Nisrina Dea Rahma,"Rr. Nisrina Dea Rahma, S.Hum"
22,U00038,Rini Budi Rahayu,"Rini Budi Rahayu, S.Pd."
23,U00040,Agung Wijayanto,"Agung Wijayanto, S.T."
28,U00046,None,sosialmedia1
30,U00048,None,"Yerly A Datu, S.Pd, M.Pd, CT.ACT, C.PS"
34,U00053,None,Ann Clariss Agbalog Amora
36,U00055,MUHAMMAD JEFRY MULYANTO,Muhammad Jefry Mulyanto
38,U00057,Ulfasiyah,"Ulfasiyah, S.S."
42,U00061,Veronica Febriyanti Adam,"Veronica Febriyanti Adam, S.S."
44,U00063,Aulia Ratna Meilinda,"Aulia Ratna Meilinda, S.Pd."
46,U00065,Retno Wulandari,"Retno Wulandari, S.Pd."
47,U00066,Risma Dwi Aryanti,"Risma Dwi Aryanti, S.Pd."
48,U00067,Moh Rafli Wahyudi,"Moh Rafli Wahyudi, S.Pd."

In [12]:
# ---------------------------------------------------------
# BANDINGKAN NAMA (BARU) DENGAN NICKNAME (LAMA)
# ---------------------------------------------------------

comparison_nickname = pd.merge(
    df_old['karyawan'][['idusers', 'nickname']].copy(),
    df_new['users'][['id_user', 'name']].copy(),
    left_on='idusers',
    right_on='id_user',
    how='inner'
)

print("--- Hasil Perbandingan: Users Name vs Old Nickname ---")
display(comparison_nickname[['id_user', 'name', 'nickname']])

--- Hasil Perbandingan: Users Name vs Old Nickname ---

   id_user                                    name      nickname
0   U00001                           ADMINISTRATOR          None
1   U00003          Graciela Evanda Ronadi, S.Kom.      Graciela
2   U00011                      DANIAR AULIA RIZKI        DANIAR
3   U00012                          Habibah Melyna       Habibah
4   U00014                  Laksmi Puspitowardhani        Laksmi
5   U00015                       Ika Asriani Yadin          None
6   U00016               Luluk Fatikah Sari, S.Pd.         Luluk
7   U00018                           Ditari Kurnia          Tari
8   U00019                          Hartatik, S.S.         Tatik
9   U00020                           Juni Arlianto            MJ
10  U00023                            Titi Hapsari          Titi
11  U00026                 Qorin Rahmaniyah, S.Pd.            Qo
12  U00027                                    Test         fgsxd
13  U00028                                pengajar          None
14  U00030                          Akun Data PPDK     adminppdk
15  U00031                 Eka Nur Wahyuni, S. Pd.          Yuni
16  U00032                 Getari Adyagarini, M.Pd        GETARI
17  U00033    Maria Florencia Erica Susanto, A.Md.         Erica
18  U00034                     Mieke Puspita, S.Pd         Mieke
19  U00035                  Miftakhul Jannah, S.Pd          Tata
20  U00036            Rr. Nisrina Dea Rahma, S.Hum           Dea
21  U00037                   Siti Uswatun Khasanah          Uswa
22  U00038                 Rini Budi Rahayu, S.Pd.          Rini
23  U00040                   Agung Wijayanto, S.T.  083115270222
24  U00041                 Vivi Pramitha Wulandari          Vivi
25  U00042          Cantika Swasti Sumarsono Putri           Ica
26  U00043                     Trio Fajar Cahyanto          Trio
27  U00044                       Muifatul Febriani           Ifa
28  U00046                            sosialmedia1          None
29  U00047                   Muhamad Haykal Roziqi        Haykal
30  U00048  Yerly A Datu, S.Pd, M.Pd, CT.ACT, C.PS          None
31  U00049                             Ana Puspita           Ana
32  U00050              Peni Puspa Indarwati, S.S.          Peni
33  U00052                         Ratna Febrianti         Ratna
34  U00053               Ann Clariss Agbalog Amora          None
35  U00054                Bryant Frederico Sutanto        Bryant
36  U00055                 Muhammad Jefry Mulyanto         Jefry
37  U00056                            Amat Kasiyan          Amat
38  U00057                         Ulfasiyah, S.S.          Ulfa
39  U00058                        Piotr Pawel Sopa         Peter
40  U00059                 Amilia Khasanah Marzuki    Amel / Lia
41  U00060               Muhammad Yusril Romadhoni        Yusril
42  U00061          Veronica Febriyanti Adam, S.S.          Vero
43  U00062                             La Erpiadin      Erfiadyn
44  U00063             Aulia Ratna Meilinda, S.Pd.         Aulia
45  U00064          PINANGGIH DIMAS PERMANA, S.Kom     Pinanggih
46  U00065                  Retno Wulandari, S.Pd.         Retno
47  U00066                Risma Dwi Aryanti, S.Pd.         Risma
48  U00067                Moh Rafli Wahyudi, S.Pd.         Rafli
49  U00068               Mochammad Rahmat Muttaqin        Rahmat
50  U00069                    Zaskya Ayra Sinatrya         Zasha
51  U00070               Zumrotul Fatma Rahmayanti         Rahma

In [13]:
# ---------------------------------------------------------
# 1. IDENTIFIKASI NICKNAME BERMASALAH (NULL ATAU NO. HP)
# ---------------------------------------------------------
import re

def is_phone_number(val):
    if pd.isna(val) or val is None:
        return True # Anggap bermasalah jika null
    return bool(re.search(r'[0-9]{8,}', str(val)))

# Merge dulu agar bisa membandingkan Name (Baru) dan Nickname (Lama)
df_nick_check = pd.merge(
    df_old['karyawan'][['idusers', 'nickname']].copy(),
    df_new['users'][['id_user', 'name']].copy(),
    left_on='idusers',
    right_on='id_user',
    how='inner'
)

# Filter yang bermasalah
mask_problem = df_nick_check['nickname'].apply(is_phone_number)
problem_nicknames = df_nick_check[mask_problem].copy()

print(f"Ditemukan {len(problem_nicknames)} nickname bermasalah.\n")
if not problem_nicknames.empty:
    print("--- Tabel Pengecekan: Name (Baru) vs Nickname (Bermasalah) ---")
    display(problem_nicknames[['id_user', 'name', 'nickname']])
else:
    print("✅ Tidak ada nickname yang NULL atau berupa Nomor HP.")

Ditemukan 7 nickname bermasalah.

--- Tabel Pengecekan: Name (Baru) vs Nickname (Bermasalah) ---

   id_user                                    name      nickname
0   U00001                           ADMINISTRATOR          None
5   U00015                       Ika Asriani Yadin          None
13  U00028                                pengajar          None
23  U00040                   Agung Wijayanto, S.T.  083115270222
28  U00046                            sosialmedia1          None
30  U00048  Yerly A Datu, S.Pd, M.Pd, CT.ACT, C.PS          None
34  U00053               Ann Clariss Agbalog Amora          None

In [14]:
# ---------------------------------------------------------
# 3. INPUT NICKNAME MANUAL UNTUK ID SPESIFIK
# ---------------------------------------------------------
# Silakan isi nama di dalam tanda kutip '', lalu jalankan sel ini.

nickname_fixes = {
    'U00001': 'ADMINISTRATOR',  # Isi nickname baru di sini
    'U00015': 'Ika',
    'U00028': 'pengajar',
    'U00040': 'Agung',
    'U00046': 'sosmed',
    'U00048': 'Yerly',
    'U00053': 'Ann'
}

for id_user, new_nick in nickname_fixes.items():
    if new_nick.strip(): # Hanya update jika tidak kosong
        df_old['karyawan'].loc[df_old['karyawan']['idusers'] == id_user, 'nickname'] = new_nick
        print(f"✓ Nickname untuk {id_user} berhasil diupdate menjadi: {new_nick}")

print("\n--- Selesai. Silakan cek kembali data Anda ---")

✓ Nickname untuk U00001 berhasil diupdate menjadi: ADMINISTRATOR
✓ Nickname untuk U00015 berhasil diupdate menjadi: Ika
✓ Nickname untuk U00028 berhasil diupdate menjadi: pengajar
✓ Nickname untuk U00040 berhasil diupdate menjadi: Agung
✓ Nickname untuk U00046 berhasil diupdate menjadi: sosmed
✓ Nickname untuk U00048 berhasil diupdate menjadi: Yerly
✓ Nickname untuk U00053 berhasil diupdate menjadi: Ann

--- Selesai. Silakan cek kembali data Anda ---

In [15]:
# ---------------------------------------------------------
# VERIFIKASI PERUBAHAN NICKNAME MANUAL
# ---------------------------------------------------------
# Jalankan sel ini untuk melihat hasil input manualmu tadi

target_ids = ['U00001', 'U00015', 'U00028', 'U00040', 'U00046', 'U00048', 'U00053']

# Ambil data terbaru dari df_old dan sandingkan dengan df_new
verification_df = pd.merge(
    df_old['karyawan'][df_old['karyawan']['idusers'].isin(target_ids)][['idusers', 'nickname']].copy(),
    df_new['users'][['id_user', 'name']].copy(),
    left_on='idusers',
    right_on='id_user',
    how='inner'
)

print("--- Hasil Verifikasi Nickname Manual ---")
display(verification_df[['id_user', 'name', 'nickname']])

--- Hasil Verifikasi Nickname Manual ---

  id_user                                    name       nickname
0  U00001                           ADMINISTRATOR  ADMINISTRATOR
1  U00015                       Ika Asriani Yadin            Ika
2  U00028                                pengajar       pengajar
3  U00040                   Agung Wijayanto, S.T.          Agung
4  U00046                            sosialmedia1         sosmed
5  U00048  Yerly A Datu, S.Pd, M.Pd, CT.ACT, C.PS          Yerly
6  U00053               Ann Clariss Agbalog Amora            Ann

## Benerin struktur idkariawan

In [16]:
# Create a new dictionary with the updated 'idusers' values
df_new_users_dict = df_merged_users.set_index('id_user')['thnbekerja'].to_dict()

# Replace the 'idusers' values in df_old['karyawan'] with the corresponding values from df_new_users_dict
df_old['karyawan']['thnbekerja'] = df_old['karyawan']['idusers'].map(df_new_users_dict)

# Display semua baris dan kolom
print("\n5. TAMPILAN SEMUA DATA:")
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)
display(df_old['karyawan'])

5. TAMPILAN SEMUA DATA:

,idkaryawan,ktp,nickname,kota,tgl,jk,goldar,agama,status,alamatktp,domisili,warga,anakke,hobi,linkedin,riwayat,email,emailkantor,telp,npwp,bpjskerja,bpjssehat,idusers,nama,anak,rekening,moda,ig,fb,link,thnbekerja
0,LEAP001VI02,None,ADMINISTRATOR,None,None,Wanita,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,U00001,None,None,None,None,None,None,,2023-06-02
1,LEAP003III2023,3514186411980002,Graciela,Sidoarjo,11/24/1998,Wanita,-,Islam,Belum Kawin,"Ranggeh, Gondangwetan, Pasuruan","Lebak Indah Regency B40, Surabaya",Indonesia,1,Membaca,https://www.linkedin.com/in/graciela-evanda-ronadi-b134221a3/?originalSubdomain=id,"Maag, tipes",graciela.ronadi12@gmail.com,graciela@leapsurabaya.sch.id,0812-3447-7137,53.856.239.8-619.000,,,U00003,Graciela Evanda Ronadi,,0140881385821,Motor Pribadi,https://www.instagram.com/gracielaevr/,,https://drive.google.com/drive/folders/1alw9SubNFKSs40YOrz36JlZCGj7T8waC?usp=sharing,2023-03-13
2,LEAP011XII01,3515135105910001,DANIAR,SURABAYA,05/11/1991,Wanita,B,ISLAM,KAWIN,"PONDOK TROSOBO INDAH L-5, RT 003 RW 009, TROSOBO, TAMAN, SIDOARJO, JAWA TIMUR, INDONESIA.",GUNUNGANYAR LOR GG 3A NO 9A,INDONESIA,1,"MAIN GAME, NONTON",https://www.linkedin.com/in/daniar-aulia-rizki-28b8a4250/,PREKLAMSIA,daniarodriscoll@gmail.com,daniar.rizki@leapsurabaya.sch.id,0896-9632-0278,46.770.512.5-603.000,21034278636,0002319622514,U00011,DANIAR AULIA RIZKI,1,1410022279715,SEPEDA MOTOR,@dar.od,tidak ada,https://drive.google.com/drive/u/0/folders/1va7B0PtK57XOZrl-1nvu1n3Wz1jOj75r,2020-12-01
3,LEAP012III02,3578106705930001,Habibah,Semarang,05/27/1993,Wanita,AB,Islam,Belum menikah,Jl Pacar Kembang Vc No 22,Jl Pacar Kembang Vc No 22,Indonesia,1,Mereview berbagai jenis makanan,https://www.linkedin.com/in/habibah-melyna/,"Alergi udang, pengawet makanan dan micin",habibahmelyna@gmail.com,habibah.elfiani@leapsurabaya.sch.id,0857-3093-3317,96.917.411.9-619.000,21034278651,0002999218792,U00012,Habibah Melyna Elfiani,,1420018314442,Sepeda Motor Pribadi,https://instagram.com/habibahmelyna?igshid=MzNlNGNkZWQ4Mg==,,None,2020-03-02
4,LEAP014VII31,3578035706820005,Laksmi,Surabaya,06/17/1982,Wanita,O,ISLAM,Single,Rungkut Asri Barat XIII no 17,Rungkut Asri Barat XIII no 17,WNI,2,"Hiking, Reading, Traveling, Attending Concert",https://www.linkedin.com/in/laksmi-puspitowardhani-ab1a1336,Liver,laksmi.p@leapsurabaya.sch.id,laksmi.p@leapsurabaya.sch.id,6282-1399-6681,35.227.276.9-615.000,18088838356,00015384308,U00014,Laksmi Puspitowardhani,,1420016807967,Motor,https://www.instagram.com/laksmi_purplespace/?hl=en,-,https://drive.google.com/drive/folders/1-7iI4-phQIGBra_G-bekA_2Fuu_-nAiu?usp=drive_link,2018-07-31
5,LEAP015II2011,None,Ika,None,None,Wanita,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,U00015,None,None,None,None,None,None,None,14-2-2011
6,LEAP016VI2017,3524035806960001,Luluk,Lamongan,06/18/1996,Wanita,-,Islam,Belum Kawin,"RT 001/RW 002, Ngangkrok, Medalem, Modo, Lamongan","Jalan Pabrik Kulit Gg. 2 Gg. Buntu No.24, Jemur Wonosari, Wonocolo, Surabaya",Indonesia,satu,Menonton Drama/Film,https://www.linkedin.com/in/luluk-fatikah-sari-a74001252/,Tipes dan sakit lambung,lulukfatikahsari@gmail.com,luluk.sari@leapsurabaya.sch.id,0857-8546-7685,81.269.150.9-645.000,21034278685,0002226118184,U00016,Luluk Fatikah Sari,,1420015479032,Motor Pribadi,https://www.instagram.com/lulukfatikah/,-,https://drive.google.com/drive/folders/1CF3rrcfAQzTvTxqt64FWdYP6meSOesBW?usp=sharing,2017-06-19
7,LEAP018IV20,3515165701920002,Tari,Surabaya,01/17/1992,Wanita,B,Islam,Lajang,"Tebel Timur 004/006, TEBEL, GEDANGAN, SIDOARJO","Tebel Timur JL. RA Mustika III 004/006 No. 64, TEBEL, GEDANGAN, SIDOARJO",Indonesia,1,Memasak dan membuat kerajinan tangan,ww,Maag dan darah rendah,ditari@leapsurabaya.sch.id,,0813-5966-3659,,,,U00018,Ditari Kurnia Damayanti,,1410022278949,Motor Pribadi,ww,,None,2021-04-20
8,LEAP019VI2019,3524094707820003,Tatik,Lamongan,07/07/1982,Wanita,O,Islam,Menikah,"Kebalan Kulon Rt 10 RW 02, Sekaran - Lamongan",Grand Surya blok A6 - 17 Buduran Sidoarjo,Indonesia,1,Memasak,-,Tidak ada,hartatik8282@gmail.com,hartatik@leapsurabaya.sch.id,0852-3101-7799,55.860.888.1-645.000,,,U00019,Hartatik,0,1420009706010,Motor pribadi,tati_bj (lupa password tidak bisa masuk ig melalui laptop jadi tidak bisa kasih link),Tati ((lupa password tidak bisa masuk facebook melalui laptop jadi tidak bisa kasih link),https://drive.google.com/drive/folders/1xy6IGdCMFEbMCO127hwFvvH_I45TuZzQ,2019-06-01
9,LEAP020IV30,3578170506820004,MJ,Surabaya,06/05/1982,Pria,B,Islam,Menikah,Amir Mahmud IV No.9-C,Amir Mahmud IV No.9-C,Indonesia,1,-,-,-,7uni.arlianto@gmail.com,juni.arlianto@leapsurabaya.sch.id,0881-0264-0001,81.277.051.9-615.000,17008686762,,U00020,Juni Arlianto,1,140015278772,Motor,7inchuuriki,,https://drive.google.com/drive/folders/1-ZWjsg38cDKBwBmUkYDLqsdCWkZrsq8V?usp=sharing,2009-04-30
10,LEAP023XI2019,3578035305910002,Titi,Surabaya,05/13/1991,Wanita,O,Islam,Kawin,Rungkut Asri Barat XIII-17,Rungkut Asri Barat XIII-17,WNI,3,Main Game,https://www.linkedin.com/in/titi-hapsari-retnaningtias/,"Maag, Patah Tulang, Sinusitis",titi.hapsari@leapsurabaya.sch.id,titi.hapsari@leapsurabaya.sch.id,0822-4516-6547,86.802.833.3-615.000,21034278669,0000102317062,U00023,Titi Hapsari Retnaningtias,0,1420017951251,Motor Pribadi,https://www.instagram.com/titihapsarir,,https://drive.google.com/drive/folders/1k266j11p7CTcHciFGyrVpbHOISOC5dki?usp=sharing,2019-10-01
11,LEAP026VIII2021,3578084710960004,Qo,Surabaya,10/07/1996,Wanita,O,Islam,Belum,JL. Gubeng Kertajaya IX D No. 6,JL. Gubeng Kertajaya IX D No. 6,Indonesia,1,"Makan, Gambar, Uji coba makanan",https://id.linkedin.com/in/qorinrhmnyh,"Demam berdarah, tumor",qorinrahmaniyah@gmail.com,qorin.rahmaniah@leapsurabaya.sch.id,0882-1710-5936,90.493.623.4-606.000,21056548478,0001880401408,U00026,Qorin Rahmaniyah,0,1420020131214,Motor Pribadi,https://www.instagram.com/_cmdt/,https://m.facebook.com/QorinR/,https://drive.google.com/drive/folders/1or0AUFoMimPSWW1hTdqwMDXaZs9oLBEr?usp=sharing,2021-08-02
12,LEAP027VI15,43656,fgsxd,fgb,06/27/2023,Wanita,fg,djhxt,dxhj,dgfhj,gfhdj,fghn,1,fjy,kjuhm,jgh,df@dg._,,4324-3546-577_,,,,U00027,fgz,,353,ghj,kgm,,,2023-06-15
13,LEAP028VI2023,None,pengajar,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,U00028,None,None,None,None,None,None,None,2023-06-01
14,LEAP030VI27,1234567891011121,adminppdk,surabaya,04/01/2024,Wanita,-,-,-,-,-,-,-,-,-,--,data@gmail.com,,0812-3457-890_,,,,U00030,Admin Pendidikan,,12345678985,-,-,-,None,2023-06-27
15,LEAP031VI2018,3524205306950001,Yuni,Gresik,06/13/1995,Wanita,Ti,Islam,Belum menikah,Desa Pengangsalan RT 03 RW 02 Kecamatan Kalitengah Lamongan,"Pabrik Kulit Gang 2 Gang Buntu no. 24 Jemursari, Surabaya",Indonesia,1,Mendengarkan musik,Belum,Perna sakit gigi dan maag,ekanur.wahyuni26@gmail.com,eka.wahyuni@leapsurabaya.sch.id,0813-1347-1713,42.825.961.8-608.000,,0002211312025,U00031,Eka Nur Wahyuni,,EKA NUR WAHYUNI Bank Mandiri 1420016380346,Sepeda motor,https://instagram.com/ekanurwahyuni13?igshid=MzNlNGNkZWQ4Mg==,,https://drive.google.com/drive/folders/12vXsyitqeyGazttmlQI9OFkXYM_x-zob,2018-06-08
16,LEAP032I02,3515146212940001,GETARI,MADIUN,12/22/1994,Wanita,O,ISLAM,BELUM KAWIN,"Jl. Ketapang III, RT 04, RW 02, Ds. Suko, Sukodono, Sidoarjo","Jl. Ketapang III, RT 04, RW 02, Ds. Suko, Sukodono, Sidoarjo",Indonesia,1,"I don't have hobbies, I have moods",https://www.linkedin.com/in/getari-adyagarini-071598258?trk=contact-info,Tidak ada,getari.teachlish@gmail.com,getari@leapsurabaya.sch.id,0878-5668-0404,95.824.727.2-603.000,,0000102024764,U00032,GETARI ADYAGARINI,,1410023228554,Mobil,getari.adya,,https://drive.google.com/drive/folders/1xAhqwJ3tmWN3kQQGS4YVIa4prG9RscxD?usp=sharing,2023-01-02
17,LEAP033VIII05,3518054105000002,Erica,Surabaya,05/18/2000,Wanita,O,Katholik,Single,Jl. M Yusuf RT 012 RW 003 Kel. Kecubung Kec. Pace,Perumahan Grand Eastern JL. Taman Timur Sukolilo II NO. 18 Blok AE-2,WNI,1,Nonton Drama & Scroll Tiktok,https://www.linkedin.com/in/maria-florencia-erica-susanto-81a900227,Patah tulang kaki kanan,ericasusanto1805@gmail.com,ericasusanto@leapsurabaya.sch.id,0851-5721-7422,60.469.638.5-615.000,23182511560,0002479768389,U00033,Maria Florencia Erica Susanto,,140020550777,Motor Pribadi,https://instagram.com/ericachouw,,https://drive.google.com/drive/folders/1BsoRjVlW0QHOkAD-npM175jsOdBErdYl?usp=sharing,2022-08-05
18,LEAP034II16,3578256604800002,Mieke,Malang,04/26/1980,Wanita,O+,Katolik,Kawin,Perum Green Lake Wonorejo Timur Baru XVII H5/26,Perum Green Lake Wonorejo Timur Baru XVII H5/26,WNI,1,"Membaca, Menulis, Pergi pergi :P",https://www.linkedin.com/in/mieke-puspita-b01175259,bapil,miekedatu@gmail.com,miekepuspita@leapsurabaya.sch.id,0838-4989-5079,47.962.870.3-615.000,35782566048,0001536484331,U00034,Mieke Puspita,1,1420020132329,sepeda motor,https://instagram.com/miekepuspita?igshid=ZDc4ODBmNjlmNQ==,https://www.facebook.com/mieke.puspita.7?mibextid=ZbWKwL,https://drive.google.com/drive/folders/10QGgWRKucYxs5RfV-OGgxc3pplpi7hrK?usp=sharing,2022-02-16
19,LEAP035VIII2012,3578256602930001,Tata,Magelang,02/26/1993,Wanita,B,Islam,Kawin,Jl. Amir Mahmud IV 9-C,Permata Kwangsan Residence C1-10,Indonesia,1,"Memasak, make up, Jalan-jalan",-,-,miptha26@gmail.com,Miftakhul.jannah @leapsurabaya.sch.id,0881-0264-0002,,17008687224,0001908364386,U00035,MIFTAKHUL JANNAH,1,1420015278772,Motor pribadi,miptha__,-,https://drive.google.com/drive/folders/1oeKwMA32povscLhSdyCTe6sxJ6DFxDGH?usp=sharing,2012-08-07
20,LEAP036I02,1671070811000012,Dea,Surabaya,11/08/2000,Wanita,B,Islam,Belum Kawin,"Jl. Pucang Asri I no.11, Kertajaya, Gubeng, Surabaya","Jl. Pucang Asri I no.11, Kertajaya, Gubeng, Surabaya",Indonesia,1,Musik,https://www.linkedin.com/in/rr-nisrina-dea-rahma-3389ba204/,0,nisrinadearahma@gmail.com,nisrina.dea@leapsurabaya.sch.id,0821-7616-1260,61.902.080.3-606.000,23074206378,0001107009641,U00036,Rr. Nisrina Dea Rahma,0,1420016746702,Transportasi umum,www.instagram.com/ndearhm,0,https://drive.google.com/drive/folders/1GZ6DYfo-qGvBa9bONymUVqTjM20i6N5A?usp=sharing,2023-01-02
21,LEAP037VII04,3523176705990001,Uswa,Tuban,05/27/1999,Wanita,0,Islam,Belum Kawin,"Dusun Sisir, RT 04, RW 05, Desa Kedungsoko, Plumpang, Tuban","Margorejo, Wonocolo",Indonesia,2,"Mendengarkan Musik, Membaca",-,-,sitiuswatunkha@gmail.com,siti.uswatun@leapsurabaya.sch.id,0857-4595-2525,61.719.186.1-648.000,,,U00037,Siti Uswatun Khasanah,,1420021927123,Motor pribadi,-,-,https://drive.google.com/drive/folders/1I775kRo3-5i1EfeslG6ub0zfIsNgf61I?usp=sharing,2023-07-04
22,LEAP038VI07,3522146808900002,Rini,Bojonegoro,08/28/1990,Wanita,B,Islam,Kawin,Ds. Klampok No.5 Kec. Kapas Kab. Bojonegoro,Perumahan Sentra Point Blok AD No.21 Surabaya,WNI,4,"membaca buku fiksi, menonton film",https://www.linkedin.com/in/rini-rahayu-91b7b1259/,-,riniey.buddy@gmail.com,rini.rahayu@leapsurabaya.sch.id,0851-6314-1616,42.366.046.8-615.000,17008685640,0003003442593,U00038,Rini Budi Rahayu,1,1420015505729,Motor pribadi,https://www.instagram.com/rini.cy/,,https://drive.google.com/drive/folders/1HIhzTwz_akP85pFjnw4wHNnS-VK8jLI6?usp=sharing,2011-06-07
23,LEAP040VII04,3525011107855000,Agung,Gresik,07/11/1985,Pria,-,-,Single,"Gresik, Kec. Dukun, Des. Petiyintunggal 001/001",Asem Payung I/25,Surabaya,-,Reading,-,-,agungwijayanto1107@gmail.com,agungwijayanto1107@gmail.com,0831-1527-0222,,,,U00040,Agung Wijayanto,,1780000459418,Personal Motor,https://instagram.com/agungwijayanto_ec?igshid=MzNlNGNkZWQ4Mg==,https://www.facebook.com/profile.php?id=100009927274040&mibextid=ZbWKwL,https://drive.google.com/folderview?id=1JScNiC-Vt51o1nfW-cB-9ivY3EEzjoPO,2023-07-04
24,LEAP041III25,3578246111990003,Vivi,Surabaya,11/21/1999,Wanita,B,Islam,Belum menikah,Jl. Kutisari Utara II D/17 d,Jl. Kutisari Indah Barat IX No. 11,Indonesia,1,"Menggambar, mewarnai, bersepda, mendengarkan musik",viviwulandari,Tidak memiliki riwayat penyakit,viviwulandari43@gmail.com,,0812-1722-2294,40.206.847.2-615.000,,,U00041,Vivi Pramitha Wulandari,,014001234634830,Motor pribadi,@_viviwulandari,,https://drive.google.com/drive/folders/1jC7Xp9bZ3TS6WvO4FYrOogVhHEzwVBPF?usp=sharing,2023-03-25
25,LEAP042III25,3516154706990003,Ica,Mojokerto,06/07/1999,Wanita,O,Islam,Belum Menikah,"Jompong, Mojokerto","Jalan Kutisari Utara 1 No. 54, Tenggilis Mejoyo, Surabaya",Indonesia,2,"menonton series/ film, karaoke, jalan-jalan",www.linkedin.com/in/cantika-swasti,"Cacar, flu",cantikaswasti76@gmail.com,,0858-0626-8098,62.655.312.7-615.000,,0002611267672,U00042,Cantika Swasti Sumarsono Putri,,014,Motor Pribadi,www.instagram.com/cantikaswasti/,,None,2023-03-25
26,LEAP043VIII01,3504160901970002,Trio,Tulungagung,01/09/1997,Pria,O+,Islam,Belum Menikah,"Dsn, Sawo RT/RW 007/002, Ds. Sawo, Kec. Campurdarat, Kab. Tulungagung","Jl. Keputih Makam Blok D No.5, Keputih, Sukolilo, Surabaya",Indonesia,3,Menonton Anime dan Olahraga,Tidak Ada,Tidak Ada (100% Sehat),cahyanto931@gmail.com,staffga@leapsurabaya.sch.id,0878-8306-175_,62.703.897.9-629.000,21012951303,0000666642172,U00043,Trio Fajar Cahyanto,,0140481790254,Motor,https://instagram.com/_triofajar?utm_source=qr&igshid=OGU0MmVlOWVjOQ==,https://www.facebook.com/waluyondoko?mibextid=ZbWKwL,https://drive.google.com/drive/folders/1hUPWYSsUT7vP8In6h_2x-_mPYuAdADVO?usp=sharing,2023-08-01
27,LEAP044X2023,3526014802900001,Ifa,Bangkalan,02/08/1990,Wanita,B,Islam,Menikah,Jl. KH. Kholil V No.49B Demangan Bangkalan,Jl. KH. Kholil V No.49B Demangan Bangkalan,Indonesia,1,Travelling,linkedin.com/in/muifatul-febriani-5840451ab,Tidak Ada,muifatulfebriani@gmail.com,,0819-3932-0162,,,,U00044,Muifatul Febriani,2,1400018055013,Motor Pribadi,@muifatul,,None,2023-10-02
28,LEAP046X2023,None,sosmed,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,U00046,None,None,None,None,None,None,None,2023-10-01
29,LEAP047XII01,3575021903990005,Haykal,Kota Pasuruan,03/19/1999,Pria,-,Islam,Belum nikah,JL.KH.ACHMAD DAHLAN XIII/7,JL.KH.ACHMAD DAHLAN XIII/3,Indonesia,Pertama,Traveling,Haykal Roziqi,-,haykalroziqi33@gmail.com,Muhammad.haykal@leapsurabaya.sch.id,0878-8799-2703,,,0001197706397,U00047,Muhamad Haykal Roziqi,,5360700017684,Motor Pribadi,haykalroziqi,Haikal Roziki,https://drive.google.com/drive/folders/1BKtcXkLyr7kf4DOCehJRKqpO5AveOj-p?usp=drive_link,2023-12-01
30,LEAP048XII2023,None,Yerly,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,U00048,None,None,None,None,None,None,None,2023-12-21
31,LEAP049II01,3519136702980002,Ana,Madiun,02/27/2024,Wanita,B,Islam,Menikah,"Jl. Kav Mentari 02 no.45 , Tambak Rejo, Waru, Sidoarjo","Jl. Kav Mentari 02 no.45 , Tambak Rejo, Waru, Sidoarjo",Indonesia,1,Olahraga dan Menggambar,https://www.linkedin.com/in/ana-puspita-529419222?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app,Gerd,anapuspita1@gmail.com,Ana.puspita@leapsurabaya.sch.id,0812-3128-4882,,,,U00049,Ana Puspita,0,0142160829578,Motor Pribadi,https://www.instagram.com/anasta.id?igsh=MXdlZXV3d2RqMnJ0dQ==,,None,2024-02-01
32,LEAP050II2024,3578034505870001,Peni,Surabaya,05/05/1987,Wanita,O,Islam,Single,Penjaringansari Baru I-A/Kav.5 Rungkut Surabaya,Penjaringansari Baru I-A/Kav.5 Rungkut Surabaya,Indonesia,1,"membaca, menonton film",https://www.linkedin.com/in/peni-puspa-2793151a8/,-,pennypuspa55@gmail.com,peni.indarwati@leapsurabaya.sch.id,0812-1635-3322,35.780.345.0-587.000,,0001849925428,U00050,"Peni Puspa Indarwati, S.S.",,0146750644161,Motor pribadi,https://www.instagram.com/puepuen55/?hl=en,,https://drive.google.com/file/d/1CXkd0zUfmQsZidPinfLE7Lh1q1iTxUfJ/view?usp=drive_link,2024-02-19
33,LEAP052V02,3578244602850001,Ratna,Surabaya,02/06/1985,Wanita,O,-,Belum Menikah,Kutisari Indah Utara 7/20 Surabaya,Kutisari Indah Utara 7/20 Surabaya,Indonesia,3,Jalan-jalan,https://www.linkedin.com/in/ratna-febrianti-b71382301,flu,ratnabrail@gmail.com,febrianti.ratna@leapsurabaya.sch.id,0812-3222-789_,34.003.500.5-615.000,,2271484124,U00052,Ratna Febrianti,,0148221109341,Motor Pribadi,https://www.instagram.com/ratnabrail/?hl=en,,https://drive.google.com/drive/folders/1KQugWew6s7u3K_Fho2WhPaZRa_f3QX7H?usp=sharing,2024-05-02
34,LEAP053VII01,None,Ann,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,U00053,None,None,None,None,None,None,None,2024-07-01
35,LEAP054VII2024,3578250605060001,Bryant,Surabaya,05/06/2006,Pria,O,Katholik,Belum kawin,Jl. Medayu Selatan IV/57,Jl. Medayu Selatan IV/57,Indonesia,1,mendengarkan musik,www.linkedin.com/in/bryant-frederico-sutanto,Tidak ada riwayat penyakit,bryantfrederico@gmail.com,bryant.f@leapsurabaya.sch.id,0813-5844-4457,,,,U00054,Bryant Frederico Sutanto,,1420024514654,Motor pribadi,https://www.instagram.com/frdrc_0?igsh=bDZlOGdmcGo5cnVm,,https://drive.google.com/drive/folders/1Sqej9z744y6XHwC3kEyHskg8QNdPrsT0?usp=sharing,2024-07-31
36,LEAP055VIII2024,3212131506050001,Jefry,INDRAMAYU,06/15/2005,Pria,A,ISLAM,BELUM KAWIN,BLOK KARANG BARU BARAT,INDRAMAYU,INDONESIA,3,"Futsal, Badminton",https://www.linkedin.com/in/muhammad-jefry-b8513a294/,Tidak Ada,muhammad7efry@gmail.com,muhammad.jefry@leapsurabaya.sch.id,0812-2450-6675,19.939.122.8-437.000,,,U00055,MUHAMMAD JEFRY MULYANTO,,654901040798538,Jalan Kaki,https://www.instagram.com/fry025/,https://www.facebook.com/profile.php?id=100077922831795&locale=id_ID,https://drive.google.com/drive/folders/1lhGD5wTIMARtL7l2x2bjQRFMmVyg8G84?usp=sharing,2024-08-26
37,LEAP056VIII2022,3517181502670002,Amat,Jombang,02/15/1967,Pria,-,Islam,Kawin,"Dsn. Semelo 004/002, Ds. Kayen, Kec. Bandar Kedungmulyo, Kab. Jombang","Candi, Sidoarjo",Indonesia,-,-,-,Tidak Ada,amat@leap.surabaya.sch.id,amat@leap.surabaya.sch.id,0823-3083-0666,73.114.549.6-602.000,0,0001900751297,U00056,Amat Kasiyan,1,1131166988,Motor Pribadi,-,-,https://drive.google.com/drive/folders/1BcGhrDmBljk1xhv-2FITf9rX7IYr_FDe?usp=sharing,2022-08-01
38,LEAP057VII2025,5326015003020001,Ulfa,Jeddah,03/10/2002,Wanita,O,Islam,Belum Menikah,"Jl. Kh. Moch. Cholil gg. IX, RT. 03, RW. 07, No. 07, Bangkalan, Madura","Jl. Kav. Mentari 3, Tambaksumur, Waru, Sidoarjo",Indonesia,2,nonton film dan bikin design / ngedit,https://www.linkedin.com/in/ulfasiyahzm,tidak ada,ulfasiyah@gmail.com,ulfasiyah@leapsurabaya.sch.id,0813-5708-7801,,,,U00057,Ulfasiyah,,1400025052599,Motor Pribadi,https://www.instagram.com/ulfazmrkn,,None,2025-07-14
39,LEAP058VI09,1231231231231233,Peter,-,07/01/2025,Pria,-,-,-,-,-,-,-,-,-,-,aaa@gmail.com,piotr.pawel@leapsurabaya.sch.id,0000-0000-0000,,,,U00058,Piotr Pawel Sopa,,654654645456464654,-,-,-,None,2025-06-09
40,LEAP059VII14,3578175309830012,Amel / Lia,Mojokerto,09/13/1983,Wanita,O,Islam,Menikah,"Kalibutuh Barat 3/51-A, Surabaya","Delta Harmoni No 35. Deltasari,Waru,Sidoarjo",Indonesia,1,"Membaca,menulis, mendengarkan musik",tidak ada,Endometriosis,amiliamarzuki83@gmail.com,Amilia.Khasanah@leapsurabaya.sch.id,0821-4267-6635,,,,U00059,Amilia Khasanah Marzuki,0,0146105026785,grab / mobil pribadi,https://www.instagram.com/amyleeamarzuki?igsh=MWJxb29rdDRnb2Q1ZA==,,https://drive.google.com/drive/folders/1Hg65GaQBhw0Hu-_D3y-lenqazmzMQgGj?usp=sharing,2025-07-14
41,LEAP060VIII2025,3507080701990001,Yusril,Malang,01/07/1999,Pria,B,Islam,Single,"Dusun Baran RT.003 RW. 019, Desa Wajak, Kec. Wajak","Jl. Rungkut Menanggal Harapan W-12 Rungkut, Rungkut Menanggal, Kec. Gn. Anyar, Surabaya, Jawa Timur 60294",Indonesia,1,Melihat drama korea dan mendengarkan musik,https://www.linkedin.com/in/myusrilr/,tidak ada,adicita700@gmail.com,Muhammad.Yusril@leapsurabaya.sch.id,0857-7509-3865,,,,U00060,Muhammad Yusril Romadhoni,0,1400025340283,Sepeda kayuh,https://www.instagram.com/m.yusril.r_/,https://www.facebook.com/myusrilroma,https://drive.google.com/drive/folders/15n5TFOJMGsb8omDHyFNHvlMgtkpc7v19?usp=sharing,2025-08-01

In [17]:
import pandas as pd

# Membuat kolom baru untuk konversi bulan menjadi angka romawi
df_old['karyawan']['bulan_romawi'] = df_old['karyawan']['thnbekerja'].apply(lambda x: pd.Period(x).strftime('%B').upper())

# Merubah setiap bulan menjadi angka romawi
bulan_romawi_mapping = {
    'JANUARY': 'I',
    'FEBRUARY': 'II',
    'MARCH': 'III',
    'APRIL': 'IV',
    'MAY': 'V',
    'JUNE': 'VI',
    'JULY': 'VII',
    'AUGUST': 'VIII',
    'SEPTEMBER': 'IX',
    'OCTOBER': 'X',
    'NOVEMBER': 'XI',
    'DECEMBER': 'XII'
}

df_old['karyawan']['bulan_romawi'] = df_old['karyawan']['bulan_romawi'].replace(bulan_romawi_mapping)

# Membuat kolom baru untuk tanggal dan tahun
df_old['karyawan']['tanggal'] = df_old['karyawan']['thnbekerja'].apply(lambda x: pd.Period(x).strftime('%d'))
df_old['karyawan']['tahun'] = df_old['karyawan']['thnbekerja'].apply(lambda x: pd.Period(x).year)

# Update df_old['karyawan']['idkaryawan'] dengan struktur penamaan yang diinginkan

df_old['karyawan']['idkaryawan'] = df_old['karyawan']['idkaryawan'].str[:7] + df_old['karyawan']['tanggal'] + df_old['karyawan']['bulan_romawi'] + df_old['karyawan']['tahun'].astype(str).str[-2:]

# Display only the 'id_karyawan' and 'nama_karyawan' columns
print("\n5. TAMPILAN SEMUA DATA:")
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)
display(df_old['karyawan'][['idkaryawan', 'nickname', 'thnbekerja']])

5. TAMPILAN SEMUA DATA:

         idkaryawan       nickname  thnbekerja
0     LEAP00102VI23  ADMINISTRATOR  2023-06-02
1    LEAP00313III23       Graciela  2023-03-13
2    LEAP01101XII20         DANIAR  2020-12-01
3    LEAP01202III20        Habibah  2020-03-02
4    LEAP01431VII18         Laksmi  2018-07-31
5     LEAP01514II11            Ika   14-2-2011
6     LEAP01619VI17          Luluk  2017-06-19
7     LEAP01820IV21           Tari  2021-04-20
8     LEAP01901VI19          Tatik  2019-06-01
9     LEAP02030IV09             MJ  2009-04-30
10     LEAP02301X19           Titi  2019-10-01
11  LEAP02602VIII21             Qo  2021-08-02
12    LEAP02715VI23          fgsxd  2023-06-15
13    LEAP02801VI23       pengajar  2023-06-01
14    LEAP03027VI23      adminppdk  2023-06-27
15    LEAP03108VI18           Yuni  2018-06-08
16     LEAP03202I23         GETARI  2023-01-02
17  LEAP03305VIII22          Erica  2022-08-05
18    LEAP03416II22          Mieke  2022-02-16
19  LEAP03507VIII12           Tata  2012-08-07
20     LEAP03602I23            Dea  2023-01-02
21   LEAP03704VII23           Uswa  2023-07-04
22    LEAP03807VI11           Rini  2011-06-07
23   LEAP04004VII23          Agung  2023-07-04
24   LEAP04125III23           Vivi  2023-03-25
25   LEAP04225III23            Ica  2023-03-25
26  LEAP04301VIII23           Trio  2023-08-01
27     LEAP04402X23            Ifa  2023-10-02
28     LEAP04601X23         sosmed  2023-10-01
29   LEAP04701XII23         Haykal  2023-12-01
30   LEAP04821XII23          Yerly  2023-12-21
31    LEAP04901II24            Ana  2024-02-01
32    LEAP05019II24           Peni  2024-02-19
33     LEAP05202V24          Ratna  2024-05-02
34   LEAP05301VII24            Ann  2024-07-01
35   LEAP05431VII24         Bryant  2024-07-31
36  LEAP05526VIII24          Jefry  2024-08-26
37  LEAP05601VIII22           Amat  2022-08-01
38   LEAP05714VII25           Ulfa  2025-07-14
39    LEAP05809VI25          Peter  2025-06-09
40   LEAP05914VII25     Amel / Lia  2025-07-14
41  LEAP06001VIII25         Yusril  2025-08-01
42  LEAP06119VIII25           Vero  2025-08-19
43     LEAP06223X25       Erfiadyn  2025-10-23
44    LEAP06303XI25          Aulia  2025-11-03
45    LEAP06403XI25      Pinanggih  2025-11-03
46    LEAP06503XI25          Retno  2025-11-03
47    LEAP06603XI25          Risma  2025-11-03
48    LEAP06726XI25          Rafli  2025-11-26
49     LEAP06826I26         Rahmat  2026-01-26
50    LEAP06915IV26          Zasha  2026-04-15
51    LEAP07030IV26          Rahma  2026-04-30

## Benerin Enum dan missing value or error value

In [18]:
# Define a dictionary mapping the provided options to their corresponding values
bpjskerja_mapping = {
    '21034278636': '21034278636',
    '21034278651': '21034278651',
    '18088838356': '18088838356',
    '21034278685': '21034278685',
    '17008686762': '17008686762',
    '21034278669': '21034278669',
    '21056548478': '21056548478',
    '23182511560': '23182511560',
    '35782566048': '35782566048',
    '17008687224': '17008687224',
    '23074206378': '23074206378',
    '17008685640': '17008685640',
    '21012951303': '21012951303',
    '23153213873': '23153213873'
}

# Create a new column 'bpjskerja_mapped' with the mapped values
df_old['karyawan']['bpjskerja'] = df_old['karyawan']['bpjskerja'].map(bpjskerja_mapping)

# Verifikasi hasil
df_old['karyawan']['bpjskerja']

0             NaN
1             NaN
2     21034278636
3     21034278651
4     18088838356
5             NaN
6     21034278685
7             NaN
8             NaN
9     17008686762
10    21034278669
11    21056548478
12            NaN
13            NaN
14            NaN
15            NaN
16            NaN
17    23182511560
18    35782566048
19    17008687224
20    23074206378
21            NaN
22    17008685640
23            NaN
24            NaN
25            NaN
26    21012951303
27            NaN
28            NaN
29            NaN
30            NaN
31            NaN
32            NaN
33            NaN
34            NaN
35            NaN
36            NaN
37            NaN
38            NaN
39            NaN
40            NaN
41            NaN
42    23153213873
43            NaN
44            NaN
45            NaN
46            NaN
47            NaN
48            NaN
49            NaN
50            NaN
51            NaN
Name: bpjskerja, dtype: object

In [19]:
# Define a dictionary mapping the provided options to their corresponding values
anakke_mapping = {
    '1': 1,
    '2': 2,
    'NaN': None,
    '3': 3,
    '-': None,
    'satu': 1,
    '4': 4,
    'Pertama ': 1
}

# Create a new column 'anakke' in df_old['karyawan'] with the provided options
df_old['karyawan']['anakke'] = df_old['karyawan']['anakke'].replace(anakke_mapping)

# Verifikasi hasil
print(df_old['karyawan']['anakke'].value_counts())

anakke
1.0    28
2.0     9
3.0     4
4.0     1
Name: count, dtype: int64

In [20]:
# Define a dictionary mapping the provided options to their corresponding values
warga_mapping = {
    'Indonesia ': 'WNI',
    'Indonesia': 'WNI',
    'NaN': None,
    'WNI': 'WNI',
    'INDONESIA': 'WNI',
    '-': None,
    'fghn': None,
    'Surabaya': 'WNI'
}

# Create a new column 'warga' in df_old['karyawan'] with the provided options
df_old['karyawan']['warga'] = df_old['karyawan']['warga'].replace(warga_mapping)

# Verifikasi hasil
print(df_old['karyawan']['warga'].value_counts())

warga
WNI    43
Name: count, dtype: int64

In [21]:
# Define a dictionary mapping the provided options to their corresponding values
goldar_mapping = {
    'O': 'O',
    'B': 'B',
    '-': None,
    'AB': 'AB',
    'Ti': None,
    'O+': 'O+',
    '0': None,
    'A': 'A',
    'fg': None
}

# Create a new column 'goldar' in df_old['karyawan'] with the provided options
df_old['karyawan']['goldar'] = df_old['karyawan']['goldar'].replace(goldar_mapping)

# Verifikasi hasil
print(df_old['karyawan']['goldar'].value_counts())

goldar
O     16
B     10
AB     2
O+     2
A      2
Name: count, dtype: int64

In [22]:
# a ini mau penggolongannya seperti apa?

display(df_old['karyawan']['moda'].value_counts())
# Define a dictionary mapping old values to new values
moda_mapping = {
    'Motor Pribadi':  'Sepeda Motor',
    'Motor pribadi':  'Sepeda Motor',
    'Motor':  'Sepeda Motor',
    '-': None,
    'SEPEDA MOTOR': 'Sepeda Motor',
    'Sepeda Motor Pribadi': 'Sepeda Motor',
    'ghj': None,
    'Sepeda motor': 'Sepeda Motor',
    'Mobil': 'Mobil',
    'sepeda motor': 'Sepeda Motor',
    'Transportasi umum': 'Transportasi Umum',
    'Personal Motor':  'Sepeda Motor',
    'Motor Pribadi':  'Sepeda Motor',
    'Jalan Kaki': 'Jalan Kaki',
    'grab / mobil pribadi': 'Grab / Mobil Pribadi',
    'Sepeda kayuh': 'Sepeda Kayuh',
    'Grab Bike / Car': 'Grab',
    'Tidak ada': None
}

# Use replace() to fix the values in 'moda' column
df_old['karyawan']['moda'] = df_old['karyawan']['moda'].replace(moda_mapping)

# Verifikasi hasil
display(df_old['karyawan']['moda'].value_counts())

moda
Motor Pribadi           17
Motor pribadi            8
Motor                    4
-                        2
SEPEDA MOTOR             1
Sepeda Motor Pribadi     1
ghj                      1
Sepeda motor             1
Mobil                    1
sepeda motor             1
Transportasi umum        1
Personal Motor           1
Motor Pribadi            1
Jalan Kaki               1
grab / mobil pribadi     1
Sepeda kayuh             1
Grab Bike / Car          1
Tidak ada                1
motor pribadi            1
Name: count, dtype: int64

moda
Sepeda Motor            34
Mobil                    1
Transportasi Umum        1
Motor Pribadi            1
Jalan Kaki               1
Grab / Mobil Pribadi     1
Sepeda Kayuh             1
Grab                     1
motor pribadi            1
Name: count, dtype: int64

In [23]:
# Menggunakan replace()
df_old['karyawan']['jk'] = df_old['karyawan']['jk'].replace({
    'Wanita': 'Perempuan',
    'Pria': 'Laki laki',
    'Laki - Laki': 'Laki laki'
})

# Verifikasi hasil
print(df_old['karyawan']['jk'].value_counts())

jk
Perempuan    35
Laki laki    13
Name: count, dtype: int64

In [24]:
# Standardize agama (religion) values
agama_mapping = {
    'Islam': 'Islam',
    'ISLAM': 'Islam',
    'Kristen': 'Kristen Protestan',
    'Katholik': 'Katolik',
    'Katolik': 'Katolik',
    'Hindu': 'Hindu',
    'djhxt': None,
    'Buddha': 'Buddha',
    'Konghucu': 'Konghucu',
    '-': None,  # Convert '-' to NaN
}

df_old['karyawan']['agama'] = df_old['karyawan']['agama'].replace(agama_mapping)

# Map any remaining values to None (NaN)
df_old['karyawan']['agama'] = df_old['karyawan']['agama'].apply(
    lambda x: x if x in agama_mapping.values() else None
)

df_old['karyawan']['agama'].value_counts()

agama
Islam                35
Katolik               3
Kristen Protestan     1
Hindu                 1
Name: count, dtype: int64

In [25]:
# Standardize status pernikahan (marital status) values
status_mapping = {
    'Menikah': 'Menikah',
    'KAWIN': 'Menikah',
    'Kawin': 'Menikah',
    'Belum Menikah': 'Belum Menikah',
    'Belum menikah': 'Belum Menikah',
    'BELUM KAWIN': 'Belum Menikah',
    'Belum Kawin': 'Belum Menikah',
    'Belum kawin': 'Belum Menikah',
    'Single ': 'Belum Menikah',
    'Single': 'Belum Menikah',
    'Lajang': 'Belum Menikah',
    'Belum': 'Belum Menikah',
    'Belum nikah ': 'Belum Menikah',
    '-': None,
    'dxhj': None,
}

df_old['karyawan']['status'] = df_old['karyawan']['status'].replace(status_mapping)

# Verify results
df_old['karyawan']['status'].value_counts()

status
Belum Menikah    31
Menikah          12
Name: count, dtype: int64

In [26]:
# Standardize status values (Aktif -> 1, Non Aktif -> 0)
df_merged_users['status'] = df_merged_users['status'].replace({
    'Aktif': 1,
    'Non Aktif': 0
})

# Verify results
df_merged_users['status'].value_counts()

status
1    40
0    12
Name: count, dtype: int64

In [27]:
display(df_old['karyawan'])
display(df_merged_users)
# Display semua baris dan kolom
print("\n5. TAMPILAN SEMUA DATA:")
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)
display(df_old['karyawan'][['idkaryawan', 'alamatktp', 'domisili', 'kota', ]])

,idkaryawan,ktp,nickname,kota,tgl,jk,goldar,agama,status,alamatktp,domisili,warga,anakke,hobi,linkedin,riwayat,email,emailkantor,telp,npwp,bpjskerja,bpjssehat,idusers,nama,anak,rekening,moda,ig,fb,link,thnbekerja,bulan_romawi,tanggal,tahun
0,LEAP00102VI23,None,ADMINISTRATOR,None,None,Perempuan,None,None,None,None,None,None,NaN,None,None,None,None,None,None,None,NaN,None,U00001,None,None,None,None,None,None,,2023-06-02,VI,02,2023
1,LEAP00313III23,3514186411980002,Graciela,Sidoarjo,11/24/1998,Perempuan,None,Islam,Belum Menikah,"Ranggeh, Gondangwetan, Pasuruan","Lebak Indah Regency B40, Surabaya",WNI,1.0,Membaca,https://www.linkedin.com/in/graciela-evanda-ronadi-b134221a3/?originalSubdomain=id,"Maag, tipes",graciela.ronadi12@gmail.com,graciela@leapsurabaya.sch.id,0812-3447-7137,53.856.239.8-619.000,NaN,,U00003,Graciela Evanda Ronadi,,0140881385821,Sepeda Motor,https://www.instagram.com/gracielaevr/,,https://drive.google.com/drive/folders/1alw9SubNFKSs40YOrz36JlZCGj7T8waC?usp=sharing,2023-03-13,III,13,2023
2,LEAP01101XII20,3515135105910001,DANIAR,SURABAYA,05/11/1991,Perempuan,B,Islam,Menikah,"PONDOK TROSOBO INDAH L-5, RT 003 RW 009, TROSOBO, TAMAN, SIDOARJO, JAWA TIMUR, INDONESIA.",GUNUNGANYAR LOR GG 3A NO 9A,WNI,1.0,"MAIN GAME, NONTON",https://www.linkedin.com/in/daniar-aulia-rizki-28b8a4250/,PREKLAMSIA,daniarodriscoll@gmail.com,daniar.rizki@leapsurabaya.sch.id,0896-9632-0278,46.770.512.5-603.000,21034278636,0002319622514,U00011,DANIAR AULIA RIZKI,1,1410022279715,Sepeda Motor,@dar.od,tidak ada,https://drive.google.com/drive/u/0/folders/1va7B0PtK57XOZrl-1nvu1n3Wz1jOj75r,2020-12-01,XII,01,2020
3,LEAP01202III20,3578106705930001,Habibah,Semarang,05/27/1993,Perempuan,AB,Islam,Belum Menikah,Jl Pacar Kembang Vc No 22,Jl Pacar Kembang Vc No 22,WNI,1.0,Mereview berbagai jenis makanan,https://www.linkedin.com/in/habibah-melyna/,"Alergi udang, pengawet makanan dan micin",habibahmelyna@gmail.com,habibah.elfiani@leapsurabaya.sch.id,0857-3093-3317,96.917.411.9-619.000,21034278651,0002999218792,U00012,Habibah Melyna Elfiani,,1420018314442,Sepeda Motor,https://instagram.com/habibahmelyna?igshid=MzNlNGNkZWQ4Mg==,,None,2020-03-02,III,02,2020
4,LEAP01431VII18,3578035706820005,Laksmi,Surabaya,06/17/1982,Perempuan,O,Islam,Belum Menikah,Rungkut Asri Barat XIII no 17,Rungkut Asri Barat XIII no 17,WNI,2.0,"Hiking, Reading, Traveling, Attending Concert",https://www.linkedin.com/in/laksmi-puspitowardhani-ab1a1336,Liver,laksmi.p@leapsurabaya.sch.id,laksmi.p@leapsurabaya.sch.id,6282-1399-6681,35.227.276.9-615.000,18088838356,00015384308,U00014,Laksmi Puspitowardhani,,1420016807967,Sepeda Motor,https://www.instagram.com/laksmi_purplespace/?hl=en,-,https://drive.google.com/drive/folders/1-7iI4-phQIGBra_G-bekA_2Fuu_-nAiu?usp=drive_link,2018-07-31,VII,31,2018
5,LEAP01514II11,None,Ika,None,None,Perempuan,None,None,None,None,None,None,NaN,None,None,None,None,None,None,None,NaN,None,U00015,None,None,None,None,None,None,None,14-2-2011,II,14,2011
6,LEAP01619VI17,3524035806960001,Luluk,Lamongan,06/18/1996,Perempuan,None,Islam,Belum Menikah,"RT 001/RW 002, Ngangkrok, Medalem, Modo, Lamongan","Jalan Pabrik Kulit Gg. 2 Gg. Buntu No.24, Jemur Wonosari, Wonocolo, Surabaya",WNI,1.0,Menonton Drama/Film,https://www.linkedin.com/in/luluk-fatikah-sari-a74001252/,Tipes dan sakit lambung,lulukfatikahsari@gmail.com,luluk.sari@leapsurabaya.sch.id,0857-8546-7685,81.269.150.9-645.000,21034278685,0002226118184,U00016,Luluk Fatikah Sari,,1420015479032,Sepeda Motor,https://www.instagram.com/lulukfatikah/,-,https://drive.google.com/drive/folders/1CF3rrcfAQzTvTxqt64FWdYP6meSOesBW?usp=sharing,2017-06-19,VI,19,2017
7,LEAP01820IV21,3515165701920002,Tari,Surabaya,01/17/1992,Perempuan,B,Islam,Belum Menikah,"Tebel Timur 004/006, TEBEL, GEDANGAN, SIDOARJO","Tebel Timur JL. RA Mustika III 004/006 No. 64, TEBEL, GEDANGAN, SIDOARJO",WNI,1.0,Memasak dan membuat kerajinan tangan,ww,Maag dan darah rendah,ditari@leapsurabaya.sch.id,,0813-5966-3659,,NaN,,U00018,Ditari Kurnia Damayanti,,1410022278949,Sepeda Motor,ww,,None,2021-04-20,IV,20,2021
8,LEAP01901VI19,3524094707820003,Tatik,Lamongan,07/07/1982,Perempuan,O,Islam,Menikah,"Kebalan Kulon Rt 10 RW 02, Sekaran - Lamongan",Grand Surya blok A6 - 17 Buduran Sidoarjo,WNI,1.0,Memasak,-,Tidak ada,hartatik8282@gmail.com,hartatik@leapsurabaya.sch.id,0852-3101-7799,55.860.888.1-645.000,NaN,,U00019,Hartatik,0,1420009706010,Sepeda Motor,tati_bj (lupa password tidak bisa masuk ig melalui laptop jadi tidak bisa kasih link),Tati ((lupa password tidak bisa masuk facebook melalui laptop jadi tidak bisa kasih link),https://drive.google.com/drive/folders/1xy6IGdCMFEbMCO127hwFvvH_I45TuZzQ,2019-06-01,VI,01,2019
9,LEAP02030IV09,3578170506820004,MJ,Surabaya,06/05/1982,Laki laki,B,Islam,Menikah,Amir Mahmud IV No.9-C,Amir Mahmud IV No.9-C,WNI,1.0,-,-,-,7uni.arlianto@gmail.com,juni.arlianto@leapsurabaya.sch.id,0881-0264-0001,81.277.051.9-615.000,17008686762,,U00020,Juni Arlianto,1,140015278772,Sepeda Motor,7inchuuriki,,https://drive.google.com/drive/folders/1-ZWjsg38cDKBwBmUkYDLqsdCWkZrsq8V?usp=sharing,2009-04-30,IV,30,2009
10,LEAP02301X19,3578035305910002,Titi,Surabaya,05/13/1991,Perempuan,O,Islam,Menikah,Rungkut Asri Barat XIII-17,Rungkut Asri Barat XIII-17,WNI,3.0,Main Game,https://www.linkedin.com/in/titi-hapsari-retnaningtias/,"Maag, Patah Tulang, Sinusitis",titi.hapsari@leapsurabaya.sch.id,titi.hapsari@leapsurabaya.sch.id,0822-4516-6547,86.802.833.3-615.000,21034278669,0000102317062,U00023,Titi Hapsari Retnaningtias,0,1420017951251,Sepeda Motor,https://www.instagram.com/titihapsarir,,https://drive.google.com/drive/folders/1k266j11p7CTcHciFGyrVpbHOISOC5dki?usp=sharing,2019-10-01,X,01,2019
11,LEAP02602VIII21,3578084710960004,Qo,Surabaya,10/07/1996,Perempuan,O,Islam,Belum Menikah,JL. Gubeng Kertajaya IX D No. 6,JL. Gubeng Kertajaya IX D No. 6,WNI,1.0,"Makan, Gambar, Uji coba makanan",https://id.linkedin.com/in/qorinrhmnyh,"Demam berdarah, tumor",qorinrahmaniyah@gmail.com,qorin.rahmaniah@leapsurabaya.sch.id,0882-1710-5936,90.493.623.4-606.000,21056548478,0001880401408,U00026,Qorin Rahmaniyah,0,1420020131214,Sepeda Motor,https://www.instagram.com/_cmdt/,https://m.facebook.com/QorinR/,https://drive.google.com/drive/folders/1or0AUFoMimPSWW1hTdqwMDXaZs9oLBEr?usp=sharing,2021-08-02,VIII,02,2021
12,LEAP02715VI23,43656,fgsxd,fgb,06/27/2023,Perempuan,None,None,None,dgfhj,gfhdj,None,1.0,fjy,kjuhm,jgh,df@dg._,,4324-3546-577_,,NaN,,U00027,fgz,,353,None,kgm,,,2023-06-15,VI,15,2023
13,LEAP02801VI23,None,pengajar,None,None,None,None,None,None,None,None,None,NaN,None,None,None,None,None,None,None,NaN,None,U00028,None,None,None,None,None,None,None,2023-06-01,VI,01,2023
14,LEAP03027VI23,1234567891011121,adminppdk,surabaya,04/01/2024,Perempuan,None,None,None,-,-,None,NaN,-,-,--,data@gmail.com,,0812-3457-890_,,NaN,,U00030,Admin Pendidikan,,12345678985,None,-,-,None,2023-06-27,VI,27,2023
15,LEAP03108VI18,3524205306950001,Yuni,Gresik,06/13/1995,Perempuan,None,Islam,Belum Menikah,Desa Pengangsalan RT 03 RW 02 Kecamatan Kalitengah Lamongan,"Pabrik Kulit Gang 2 Gang Buntu no. 24 Jemursari, Surabaya",WNI,1.0,Mendengarkan musik,Belum,Perna sakit gigi dan maag,ekanur.wahyuni26@gmail.com,eka.wahyuni@leapsurabaya.sch.id,0813-1347-1713,42.825.961.8-608.000,NaN,0002211312025,U00031,Eka Nur Wahyuni,,EKA NUR WAHYUNI Bank Mandiri 1420016380346,Sepeda Motor,https://instagram.com/ekanurwahyuni13?igshid=MzNlNGNkZWQ4Mg==,,https://drive.google.com/drive/folders/12vXsyitqeyGazttmlQI9OFkXYM_x-zob,2018-06-08,VI,08,2018
16,LEAP03202I23,3515146212940001,GETARI,MADIUN,12/22/1994,Perempuan,O,Islam,Belum Menikah,"Jl. Ketapang III, RT 04, RW 02, Ds. Suko, Sukodono, Sidoarjo","Jl. Ketapang III, RT 04, RW 02, Ds. Suko, Sukodono, Sidoarjo",WNI,1.0,"I don't have hobbies, I have moods",https://www.linkedin.com/in/getari-adyagarini-071598258?trk=contact-info,Tidak ada,getari.teachlish@gmail.com,getari@leapsurabaya.sch.id,0878-5668-0404,95.824.727.2-603.000,NaN,0000102024764,U00032,GETARI ADYAGARINI,,1410023228554,Mobil,getari.adya,,https://drive.google.com/drive/folders/1xAhqwJ3tmWN3kQQGS4YVIa4prG9RscxD?usp=sharing,2023-01-02,I,02,2023
17,LEAP03305VIII22,3518054105000002,Erica,Surabaya,05/18/2000,Perempuan,O,Katolik,Belum Menikah,Jl. M Yusuf RT 012 RW 003 Kel. Kecubung Kec. Pace,Perumahan Grand Eastern JL. Taman Timur Sukolilo II NO. 18 Blok AE-2,WNI,1.0,Nonton Drama & Scroll Tiktok,https://www.linkedin.com/in/maria-florencia-erica-susanto-81a900227,Patah tulang kaki kanan,ericasusanto1805@gmail.com,ericasusanto@leapsurabaya.sch.id,0851-5721-7422,60.469.638.5-615.000,23182511560,0002479768389,U00033,Maria Florencia Erica Susanto,,140020550777,Sepeda Motor,https://instagram.com/ericachouw,,https://drive.google.com/drive/folders/1BsoRjVlW0QHOkAD-npM175jsOdBErdYl?usp=sharing,2022-08-05,VIII,05,2022
18,LEAP03416II22,3578256604800002,Mieke,Malang,04/26/1980,Perempuan,O+,Katolik,Menikah,Perum Green Lake Wonorejo Timur Baru XVII H5/26,Perum Green Lake Wonorejo Timur Baru XVII H5/26,WNI,1.0,"Membaca, Menulis, Pergi pergi :P",https://www.linkedin.com/in/mieke-puspita-b01175259,bapil,miekedatu@gmail.com,miekepuspita@leapsurabaya.sch.id,0838-4989-5079,47.962.870.3-615.000,35782566048,0001536484331,U00034,Mieke Puspita,1,1420020132329,Sepeda Motor,https://instagram.com/miekepuspita?igshid=ZDc4ODBmNjlmNQ==,https://www.facebook.com/mieke.puspita.7?mibextid=ZbWKwL,https://drive.google.com/drive/folders/10QGgWRKucYxs5RfV-OGgxc3pplpi7hrK?usp=sharing,2022-02-16,II,16,2022
19,LEAP03507VIII12,3578256602930001,Tata,Magelang,02/26/1993,Perempuan,B,Islam,Menikah,Jl. Amir Mahmud IV 9-C,Permata Kwangsan Residence C1-10,WNI,1.0,"Memasak, make up, Jalan-jalan",-,-,miptha26@gmail.com,Miftakhul.jannah @leapsurabaya.sch.id,0881-0264-0002,,17008687224,0001908364386,U00035,MIFTAKHUL JANNAH,1,1420015278772,Sepeda Motor,miptha__,-,https://drive.google.com/drive/folders/1oeKwMA32povscLhSdyCTe6sxJ6DFxDGH?usp=sharing,2012-08-07,VIII,07,2012
20,LEAP03602I23,1671070811000012,Dea,Surabaya,11/08/2000,Perempuan,B,Islam,Belum Menikah,"Jl. Pucang Asri I no.11, Kertajaya, Gubeng, Surabaya","Jl. Pucang Asri I no.11, Kertajaya, Gubeng, Surabaya",WNI,1.0,Musik,https://www.linkedin.com/in/rr-nisrina-dea-rahma-3389ba204/,0,nisrinadearahma@gmail.com,nisrina.dea@leapsurabaya.sch.id,0821-7616-1260,61.902.080.3-606.000,23074206378,0001107009641,U00036,Rr. Nisrina Dea Rahma,0,1420016746702,Transportasi Umum,www.instagram.com/ndearhm,0,https://drive.google.com/drive/folders/1GZ6DYfo-qGvBa9bONymUVqTjM20i6N5A?usp=sharing,2023-01-02,I,02,2023
21,LEAP03704VII23,3523176705990001,Uswa,Tuban,05/27/1999,Perempuan,None,Islam,Belum Menikah,"Dusun Sisir, RT 04, RW 05, Desa Kedungsoko, Plumpang, Tuban","Margorejo, Wonocolo",WNI,2.0,"Mendengarkan Musik, Membaca",-,-,sitiuswatunkha@gmail.com,siti.uswatun@leapsurabaya.sch.id,0857-4595-2525,61.719.186.1-648.000,NaN,,U00037,Siti Uswatun Khasanah,,1420021927123,Sepeda Motor,-,-,https://drive.google.com/drive/folders/1I775kRo3-5i1EfeslG6ub0zfIsNgf61I?usp=sharing,2023-07-04,VII,04,2023
22,LEAP03807VI11,3522146808900002,Rini,Bojonegoro,08/28/1990,Perempuan,B,Islam,Menikah,Ds. Klampok No.5 Kec. Kapas Kab. Bojonegoro,Perumahan Sentra Point Blok AD No.21 Surabaya,WNI,4.0,"membaca buku fiksi, menonton film",https://www.linkedin.com/in/rini-rahayu-91b7b1259/,-,riniey.buddy@gmail.com,rini.rahayu@leapsurabaya.sch.id,0851-6314-1616,42.366.046.8-615.000,17008685640,0003003442593,U00038,Rini Budi Rahayu,1,1420015505729,Sepeda Motor,https://www.instagram.com/rini.cy/,,https://drive.google.com/drive/folders/1HIhzTwz_akP85pFjnw4wHNnS-VK8jLI6?usp=sharing,2011-06-07,VI,07,2011
23,LEAP04004VII23,3525011107855000,Agung,Gresik,07/11/1985,Laki laki,None,None,Belum Menikah,"Gresik, Kec. Dukun, Des. Petiyintunggal 001/001",Asem Payung I/25,WNI,NaN,Reading,-,-,agungwijayanto1107@gmail.com,agungwijayanto1107@gmail.com,0831-1527-0222,,NaN,,U00040,Agung Wijayanto,,1780000459418,Sepeda Motor,https://instagram.com/agungwijayanto_ec?igshid=MzNlNGNkZWQ4Mg==,https://www.facebook.com/profile.php?id=100009927274040&mibextid=ZbWKwL,https://drive.google.com/folderview?id=1JScNiC-Vt51o1nfW-cB-9ivY3EEzjoPO,2023-07-04,VII,04,2023
24,LEAP04125III23,3578246111990003,Vivi,Surabaya,11/21/1999,Perempuan,B,Islam,Belum Menikah,Jl. Kutisari Utara II D/17 d,Jl. Kutisari Indah Barat IX No. 11,WNI,1.0,"Menggambar, mewarnai, bersepda, mendengarkan musik",viviwulandari,Tidak memiliki riwayat penyakit,viviwulandari43@gmail.com,,0812-1722-2294,40.206.847.2-615.000,NaN,,U00041,Vivi Pramitha Wulandari,,014001234634830,Sepeda Motor,@_viviwulandari,,https://drive.google.com/drive/folders/1jC7Xp9bZ3TS6WvO4FYrOogVhHEzwVBPF?usp=sharing,2023-03-25,III,25,2023
25,LEAP04225III23,3516154706990003,Ica,Mojokerto,06/07/1999,Perempuan,O,Islam,Belum Menikah,"Jompong, Mojokerto","Jalan Kutisari Utara 1 No. 54, Tenggilis Mejoyo, Surabaya",WNI,2.0,"menonton series/ film, karaoke, jalan-jalan",www.linkedin.com/in/cantika-swasti,"Cacar, flu",cantikaswasti76@gmail.com,,0858-0626-8098,62.655.312.7-615.000,NaN,0002611267672,U00042,Cantika Swasti Sumarsono Putri,,014,Sepeda Motor,www.instagram.com/cantikaswasti/,,None,2023-03-25,III,25,2023
26,LEAP04301VIII23,3504160901970002,Trio,Tulungagung,01/09/1997,Laki laki,O+,Islam,Belum Menikah,"Dsn, Sawo RT/RW 007/002, Ds. Sawo, Kec. Campurdarat, Kab. Tulungagung","Jl. Keputih Makam Blok D No.5, Keputih, Sukolilo, Surabaya",WNI,3.0,Menonton Anime dan Olahraga,Tidak Ada,Tidak Ada (100% Sehat),cahyanto931@gmail.com,staffga@leapsurabaya.sch.id,0878-8306-175_,62.703.897.9-629.000,21012951303,0000666642172,U00043,Trio Fajar Cahyanto,,0140481790254,Sepeda Motor,https://instagram.com/_triofajar?utm_source=qr&igshid=OGU0MmVlOWVjOQ==,https://www.facebook.com/waluyondoko?mibextid=ZbWKwL,https://drive.google.com/drive/folders/1hUPWYSsUT7vP8In6h_2x-_mPYuAdADVO?usp=sharing,2023-08-01,VIII,01,2023
27,LEAP04402X23,3526014802900001,Ifa,Bangkalan,02/08/1990,Perempuan,B,Islam,Menikah,Jl. KH. Kholil V No.49B Demangan Bangkalan,Jl. KH. Kholil V No.49B Demangan Bangkalan,WNI,1.0,Travelling,linkedin.com/in/muifatul-febriani-5840451ab,Tidak Ada,muifatulfebriani@gmail.com,,0819-3932-0162,,NaN,,U00044,Muifatul Febriani,2,1400018055013,Sepeda Motor,@muifatul,,None,2023-10-02,X,02,2023
28,LEAP04601X23,None,sosmed,None,None,None,None,None,None,None,None,None,NaN,None,None,None,None,None,None,None,NaN,None,U00046,None,None,None,None,None,None,None,2023-10-01,X,01,2023
29,LEAP04701XII23,3575021903990005,Haykal,Kota Pasuruan,03/19/1999,Laki laki,None,None,Belum Menikah,JL.KH.ACHMAD DAHLAN XIII/7,JL.KH.ACHMAD DAHLAN XIII/3,WNI,1.0,Traveling,Haykal Roziqi,-,haykalroziqi33@gmail.com,Muhammad.haykal@leapsurabaya.sch.id,0878-8799-2703,,NaN,0001197706397,U00047,Muhamad Haykal Roziqi,,5360700017684,Motor Pribadi,haykalroziqi,Haikal Roziki,https://drive.google.com/drive/folders/1BKtcXkLyr7kf4DOCehJRKqpO5AveOj-p?usp=drive_link,2023-12-01,XII,01,2023
30,LEAP04821XII23,None,Yerly,None,None,None,None,None,None,None,None,None,NaN,None,None,None,None,None,None,None,NaN,None,U00048,None,None,None,None,None,None,None,2023-12-21,XII,21,2023
31,LEAP04901II24,3519136702980002,Ana,Madiun,02/27/2024,Perempuan,B,Islam,Menikah,"Jl. Kav Mentari 02 no.45 , Tambak Rejo, Waru, Sidoarjo","Jl. Kav Mentari 02 no.45 , Tambak Rejo, Waru, Sidoarjo",WNI,1.0,Olahraga dan Menggambar,https://www.linkedin.com/in/ana-puspita-529419222?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app,Gerd,anapuspita1@gmail.com,Ana.puspita@leapsurabaya.sch.id,0812-3128-4882,,NaN,,U00049,Ana Puspita,0,0142160829578,Sepeda Motor,https://www.instagram.com/anasta.id?igsh=MXdlZXV3d2RqMnJ0dQ==,,None,2024-02-01,II,01,2024
32,LEAP05019II24,3578034505870001,Peni,Surabaya,05/05/1987,Perempuan,O,Islam,Belum Menikah,Penjaringansari Baru I-A/Kav.5 Rungkut Surabaya,Penjaringansari Baru I-A/Kav.5 Rungkut Surabaya,WNI,1.0,"membaca, menonton film",https://www.linkedin.com/in/peni-puspa-2793151a8/,-,pennypuspa55@gmail.com,peni.indarwati@leapsurabaya.sch.id,0812-1635-3322,35.780.345.0-587.000,NaN,0001849925428,U00050,"Peni Puspa Indarwati, S.S.",,0146750644161,Sepeda Motor,https://www.instagram.com/puepuen55/?hl=en,,https://drive.google.com/file/d/1CXkd0zUfmQsZidPinfLE7Lh1q1iTxUfJ/view?usp=drive_link,2024-02-19,II,19,2024
33,LEAP05202V24,3578244602850001,Ratna,Surabaya,02/06/1985,Perempuan,O,None,Belum Menikah,Kutisari Indah Utara 7/20 Surabaya,Kutisari Indah Utara 7/20 Surabaya,WNI,3.0,Jalan-jalan,https://www.linkedin.com/in/ratna-febrianti-b71382301,flu,ratnabrail@gmail.com,febrianti.ratna@leapsurabaya.sch.id,0812-3222-789_,34.003.500.5-615.000,NaN,2271484124,U00052,Ratna Febrianti,,0148221109341,Sepeda Motor,https://www.instagram.com/ratnabrail/?hl=en,,https://drive.google.com/drive/folders/1KQugWew6s7u3K_Fho2WhPaZRa_f3QX7H?usp=sharing,2024-05-02,V,02,2024
34,LEAP05301VII24,None,Ann,None,None,None,None,None,None,None,None,None,NaN,None,None,None,None,None,None,None,NaN,None,U00053,None,None,None,None,None,None,None,2024-07-01,VII,01,2024
35,LEAP05431VII24,3578250605060001,Bryant,Surabaya,05/06/2006,Laki laki,O,Katolik,Belum Menikah,Jl. Medayu Selatan IV/57,Jl. Medayu Selatan IV/57,WNI,1.0,mendengarkan musik,www.linkedin.com/in/bryant-frederico-sutanto,Tidak ada riwayat penyakit,bryantfrederico@gmail.com,bryant.f@leapsurabaya.sch.id,0813-5844-4457,,NaN,,U00054,Bryant Frederico Sutanto,,1420024514654,Sepeda Motor,https://www.instagram.com/frdrc_0?igsh=bDZlOGdmcGo5cnVm,,https://drive.google.com/drive/folders/1Sqej9z744y6XHwC3kEyHskg8QNdPrsT0?usp=sharing,2024-07-31,VII,31,2024
36,LEAP05526VIII24,3212131506050001,Jefry,INDRAMAYU,06/15/2005,Laki laki,A,Islam,Belum Menikah,BLOK KARANG BARU BARAT,INDRAMAYU,WNI,3.0,"Futsal, Badminton",https://www.linkedin.com/in/muhammad-jefry-b8513a294/,Tidak Ada,muhammad7efry@gmail.com,muhammad.jefry@leapsurabaya.sch.id,0812-2450-6675,19.939.122.8-437.000,NaN,,U00055,MUHAMMAD JEFRY MULYANTO,,654901040798538,Jalan Kaki,https://www.instagram.com/fry025/,https://www.facebook.com/profile.php?id=100077922831795&locale=id_ID,https://drive.google.com/drive/folders/1lhGD5wTIMARtL7l2x2bjQRFMmVyg8G84?usp=sharing,2024-08-26,VIII,26,2024
37,LEAP05601VIII22,3517181502670002,Amat,Jombang,02/15/1967,Laki laki,None,Islam,Menikah,"Dsn. Semelo 004/002, Ds. Kayen, Kec. Bandar Kedungmulyo, Kab. Jombang","Candi, Sidoarjo",WNI,NaN,-,-,Tidak Ada,amat@leap.surabaya.sch.id,amat@leap.surabaya.sch.id,0823-3083-0666,73.114.549.6-602.000,NaN,0001900751297,U00056,Amat Kasiyan,1,1131166988,Sepeda Motor,-,-,https://drive.google.com/drive/folders/1BcGhrDmBljk1xhv-2FITf9rX7IYr_FDe?usp=sharing,2022-08-01,VIII,01,2022
38,LEAP05714VII25,5326015003020001,Ulfa,Jeddah,03/10/2002,Perempuan,O,Islam,Belum Menikah,"Jl. Kh. Moch. Cholil gg. IX, RT. 03, RW. 07, No. 07, Bangkalan, Madura","Jl. Kav. Mentari 3, Tambaksumur, Waru, Sidoarjo",WNI,2.0,nonton film dan bikin design / ngedit,https://www.linkedin.com/in/ulfasiyahzm,tidak ada,ulfasiyah@gmail.com,ulfasiyah@leapsurabaya.sch.id,0813-5708-7801,,NaN,,U00057,Ulfasiyah,,1400025052599,Sepeda Motor,https://www.instagram.com/ulfazmrkn,,None,2025-07-14,VII,14,2025
39,LEAP05809VI25,1231231231231233,Peter,-,07/01/2025,Laki laki,None,None,None,-,-,None,NaN,-,-,-,aaa@gmail.com,piotr.pawel@leapsurabaya.sch.id,0000-0000-0000,,NaN,,U00058,Piotr Pawel Sopa,,654654645456464654,None,-,-,None,2025-06-09,VI,09,2025
40,LEAP05914VII25,3578175309830012,Amel / Lia,Mojokerto,09/13/1983,Perempuan,O,Islam,Menikah,"Kalibutuh Barat 3/51-A, Surabaya","Delta Harmoni No 35. Deltasari,Waru,Sidoarjo",WNI,1.0,"Membaca,menulis, mendengarkan musik",tidak ada,Endometriosis,amiliamarzuki83@gmail.com,Amilia.Khasanah@leapsurabaya.sch.id,0821-4267-6635,,NaN,,U00059,Amilia Khasanah Marzuki,0,0146105026785,Grab / Mobil Pribadi,https://www.instagram.com/amyleeamarzuki?igsh=MWJxb29rdDRnb2Q1ZA==,,https://drive.google.com/drive/folders/1Hg65GaQBhw0Hu-_D3y-lenqazmzMQgGj?usp=sharing,2025-07-14,VII,14,2025

,id_user,name,email,email_verified_at,password,remember_token,created_at,updated_at,idusers,foto,idrole,wa,thnbekerja,idjabatan,idjamkerja,minat,status,idbidang,ispurchase,isteaching,ishr,isga,isit,ispdd,isbusdev,ispimpinan,ttd,expertise
0,U00001,ADMINISTRATOR,ditari@leapsurabaya.sch.id,2026-06-23 21:40:16,aGtq,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00001,logo.png,R00001,0851-7438-7539,2023-06-02,J00005,2.0,bekerja,1,NaN,0.0,0.0,0,1,0,0,0,0,None,None
1,U00003,"Graciela Evanda Ronadi, S.Kom.",graciela@leapsurabaya.sch.id,2026-06-23 21:40:16,qWmlbcVjYmo%3D,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00003,1707279559_ec864cc58f50e8b890d5.jpg,R00003,0812-3447-7137,2023-03-13,J00006,2.0,"Web, php, CI4, database",1,NaN,0.0,1.0,0,0,0,0,0,0,1702002184_d82747bcbd0f2bdab0a7.png,None
2,U00011,DANIAR AULIA RIZKI,daniar.rizki@leapsurabaya.sch.id,2026-06-23 21:40:16,aGtq,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00011,1692700456_2d6352eb557d734e53b7.jpeg,R00006,0896-9632-0278,2020-12-01,J00010,2.0,BERNYANYI,0,7.0,0.0,0.0,0,0,0,0,1,0,None,
3,U00012,Habibah Melyna,habibah.elfiani@leapsurabaya.sch.id,2026-06-23 21:40:16,o56YqZJkZA%3D%3D,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00012,1686127161_1ec3d11da554fb668e7c.jpg,R00003,0857-3093-3317,2020-03-02,J00002,3.0,Belajar dan bertumbuh,1,NaN,0.0,1.0,0,0,0,1,1,0,1702892302_89507e3f2d87fb0dfdee.png,desain grafis
4,U00014,Laksmi Puspitowardhani,laksmi.p@leapsurabaya.sch.id,2026-06-23 21:40:16,aWlpbw%3D%3D,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00014,1696338938_2a535db26e3f89919325.jpg,R00008,0821-3996-6817,2018-07-31,J00004,3.0,Psikologi & Bisnis,1,NaN,0.0,0.0,0,0,0,1,0,0,None,
5,U00015,Ika Asriani Yadin,ikayadin@leapsurabaya.sch.id,2026-06-23 21:40:16,aGtq,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00015,1694397431_30b88a94a51ff7c8024e.png,R00004,0852-1124-3425,14-2-2011,J00013,3.0,-,1,NaN,NaN,NaN,0,0,0,0,0,0,None,None
6,U00016,"Luluk Fatikah Sari, S.Pd.",luluk.sari@leapsurabaya.sch.id,2026-06-23 21:40:16,o66jrsxjY2s%3D,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00016,1688370880_b894a9a6a8aa56770eaf.jpeg,R00006,0857-8546-7685,2017-06-19,J00007,3.0,Edu,1,NaN,0.0,1.0,0,0,0,0,0,0,1708307211_3e160b7a0d1560febc2c.png,None
7,U00018,Ditari Kurnia,admin@gmail.com,2026-06-23 21:40:16,aGtq,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00018,1742411840_4c3bd3fb30f609808130.shtml,R00001,0851-7438-7539,2021-04-20,J00005,3.0,bahagia dunia akhirat,1,NaN,1.0,0.0,0,1,0,0,0,0,None,None
8,U00019,"Hartatik, S.S.",hartatik@leapsurabaya.sch.id,2026-06-23 21:40:16,p5qenpJkZA%3D%3D,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00019,1690430190_e05a6e1833612e00b30a.jpeg,R00005,0852-3471-6582,2019-06-01,J00010,2.0,-,1,NaN,0.0,0.0,0,0,0,0,0,0,1708311112_ea63d8f1f2fb12dc6dbe.png,None
9,U00020,Juni Arlianto,juni.arlianto@leapsurabaya.sch.id,2026-06-23 21:40:16,aGtq,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00020,1688629580_4df06718a9d1efc1946a.jpeg,R00002,0881-0264-0001,2009-04-30,J00010,2.0,-,1,NaN,0.0,0.0,0,0,0,1,0,0,None,
10,U00023,Titi Hapsari,titi.hapsari@leapsurabaya.sch.id,2026-06-23 21:40:16,aGtq,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00023,1727774521_de1ee7419b75c6523475.png,R00002,0822-4516-6547,2019-10-01,J00010,3.0,Coffee and Game,1,NaN,1.0,1.0,0,0,0,0,0,0,None,
11,U00026,"Qorin Rahmaniyah, S.Pd.",qorin.rahmaniah@leapsurabaya.sch.id,2026-06-23 21:40:16,bnFw,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00026,1694500023_799059f427489e12a9e7.png,R00006,0882-1710-5936,2021-08-02,J00010,3.0,"Food, Drawing,",1,NaN,0.0,1.0,0,0,0,0,0,0,1708306240_0064c7d03c77638eb889.png,None
12,U00027,Test,test@gmail.com,2026-06-23 21:40:16,aGtq,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00027,1686800811_656587646951ad5ec76e.jpg,R00002,0821-4646-4533,2023-06-15,J00006,2.0,Coding,1,NaN,0.0,0.0,0,0,0,0,0,0,None,
13,U00028,pengajar,pengajar@gmail.com,2026-06-23 21:40:16,aGtq,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00028,None,R00005,9876-5543-3222,2023-06-01,J00010,3.0,6tidur,1,NaN,0.0,0.0,0,0,0,0,0,0,None,None
14,U00030,Akun Data PPDK,data@gmail.com,2026-06-23 21:40:16,o56YqZJkZGw%3D,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00030,None,R00006,0000-0000-0000,2023-06-27,J00010,NaN,-,1,NaN,0.0,1.0,0,0,0,1,0,0,None,
15,U00031,"Eka Nur Wahyuni, S. Pd.",eka.wahyuni@leapsurabaya.sch.id,2026-06-23 21:40:16,fKSYp9akqJnNqauhm5WZ,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00031,1688371516_f8e3cb495a6602957e96.jpg,R00005,0813-1347-1713,2018-06-08,J00010,NaN,-,1,NaN,0.0,0.0,0,0,0,0,0,0,None,None
16,U00032,"Getari Adyagarini, M.Pd",getari@leapsurabaya.sch.id,2026-06-23 21:40:16,aGtq,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00032,1688369673_889db0f1267d89fe7ae4.jpeg,R00005,0878-5668-0404,2023-01-02,J00010,NaN,Memberikan dedikasi ke dunia pendidikan bahasa Inggris melalui peran pengajar,0,NaN,0.0,0.0,0,0,0,0,0,0,1708353208_d07b06675d1e5fa23383.png,
17,U00033,"Maria Florencia Erica Susanto, A.Md.",ericasusanto@leapsurabaya.sch.id,2026-06-23 21:40:16,sKimp9STn6DGYGY%3D,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00033,1688370640_434abe3fd75a3d6709f8.jpeg,R00006,0851-5721-7422,2022-08-05,J00010,NaN,-,1,11.0,0.0,1.0,1,1,0,0,0,0,1708324727_7d2882c04c6ff75ad399.png,
18,U00034,"Mieke Puspita, S.Pd",miekepuspita@leapsurabaya.sch.id,2026-06-23 21:40:16,o56YqZJkZGw%3D,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00034,1688370596_5d157f2a824cbfffc9c0.jpg,R00006,0838-4989-5079,2022-02-16,J00008,NaN,"-Reading, Writing, Travelling",1,11.0,0.0,1.0,0,0,0,0,0,0,1708658996_306c792c8c264fa46529.png,
19,U00035,"Miftakhul Jannah, S.Pd",miftakhul.jannah@leapsurabaya.sch.id,2026-06-23 21:40:16,aGtq,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00035,1690348208_aa0194bbe37e887d04c5.png,R00005,0881-0264-0002,2012-08-07,J00010,NaN,"-Cooking, traveling, doing make up",1,NaN,0.0,0.0,0,0,0,0,0,0,1708311420_9f19bdbeef8ddeb7c9dd.png,None
20,U00036,"Rr. Nisrina Dea Rahma, S.Hum",nisrina.dea@leapsurabaya.sch.id,2026-06-23 21:40:16,pZ2cmtOaYmmT,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00036,1688370707_4f82feba07d331ac440f.jpg,R00005,0821-7616-1260,2023-01-02,J00010,NaN,Musik,0,NaN,0.0,0.0,0,0,0,0,0,0,1708311115_cd2260deb2d58d4146b1.png,
21,U00037,Siti Uswatun Khasanah,siti.uswatun@leapsurabaya.sch.id,2026-06-23 21:40:16,aGtq,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00037,1688372130_e01ff4f038b7bae7029d.jpeg,R00005,0857-4595-2525,2023-07-04,J00010,NaN,Membaca,0,NaN,0.0,0.0,0,0,0,0,0,0,None,
22,U00038,"Rini Budi Rahayu, S.Pd.",rini.rahayu@leapsurabaya.sch.id,2026-06-23 21:40:16,o56YqZNiY2s%3D,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00038,1688370886_98f7bfba3590ca021bd4.jpg,R00005,0851-6314-1616,2011-06-07,J00010,NaN,-,1,NaN,0.0,0.0,0,0,0,1,0,0,1707990713_4e97cffbee1938a3c5c0.png,
23,U00040,"Agung Wijayanto, S.T.",agung.wijayanto@leapsurabaya.sch.id,2026-06-23 21:40:16,aGtq,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00040,1690477143_9c6782184cac165c2b0f.jpeg,R00005,0831-1527-0222,2023-07-04,J00010,NaN,Reading and Songwriting,1,NaN,0.0,0.0,0,0,0,0,0,0,1712272386_b9becdba820e59218d87.png,None
24,U00041,Vivi Pramitha Wulandari,vivi.wulandari@leapsurabaya.sch.id,2026-06-23 21:40:16,aGtq,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00041,1688711260_556a4a91325635c55a1a.jpg,R00008,0812-1722-2294,2023-03-25,J00008,NaN,"Fotografi, Social Media, Desain Grafis",1,9.0,0.0,0.0,0,0,0,0,0,0,None,
25,U00042,Cantika Swasti Sumarsono Putri,cantikaswasti76@gmail.com,2026-06-23 21:40:16,aGtq,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00042,1688701716_c0099248b9cea8e57e8b.png,R00002,0858-0626-8098,2023-03-25,J00008,NaN,"Copywriting, Persuasi, Edukasi",0,11.0,0.0,0.0,0,0,0,0,0,0,None,
26,U00043,Trio Fajar Cahyanto,generalaffair@gmail.com,2026-06-23 21:40:16,aGtq,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00043,1694501101_eb7a9452f5d7069e2d05.jpeg,R00007,0878-8730-6175,2023-08-01,J00009,NaN,"Sleep, Sleep and Sleep",1,NaN,1.0,0.0,1,0,0,1,0,0,None,
27,U00044,Muifatul Febriani,muifatul@leapsurabaya.sch.id,2026-06-23 21:40:16,aGtq,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00044,1697605800_1c209604feebb43aea57.jpeg,R00005,0819-3932-0162,2023-10-02,J00010,NaN,I am a sunset seeker,0,NaN,0.0,0.0,0,0,0,0,0,0,1708938634_e0891560dfe70ac20cdd.png,
28,U00046,sosialmedia1,sosialmedia1@gmail.com,2026-06-23 21:40:16,aGtq,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00046,None,R00008,None,2023-10-01,J00008,NaN,None,1,NaN,0.0,0.0,0,0,0,0,0,0,None,
29,U00047,Muhamad Haykal Roziqi,Muhammad.haykal@leapsurabaya.sch.id,2026-06-23 21:40:16,i6Kkp8KlYmqYZGs%3D,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00047,1701413223_0ad0b6e85cf61cb96a29.jpeg,R00005,0878-8799-2703,2023-12-01,J00010,NaN,Busdev,0,7.0,0.0,0.0,0,0,0,0,0,0,None,
30,U00048,"Yerly A Datu, S.Pd, M.Pd, CT.ACT, C.PS",pengajar1@leapsurabaya.sch.id,2026-06-23 21:40:16,aGtq,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00048,None,R00005,0812-3447-7137,2023-12-21,J00010,NaN,Mengajar,1,NaN,0.0,0.0,0,0,0,0,0,0,1705635412_63253866271a8b6fe62c.png,
31,U00049,Ana Puspita,ana.puspita@leapsurabaya.sch.id,2026-06-23 21:40:16,aGtq,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00049,1707216719_23e8d54bc0ee23db70f7.jpeg,R00008,0812-3128-4882,2024-02-01,J00008,NaN,Konten Kreator,0,9.0,0.0,0.0,0,0,0,0,0,0,None,
32,U00050,"Peni Puspa Indarwati, S.S.",peni.indarwati@leapsurabaya.sch.id,2026-06-23 21:40:16,pJqkptCmZm0%3D,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00050,1707113938_3f8f1d86bc8fa7c21626.jpg,R00005,0812-1635-3322,2024-02-19,J00010,NaN,"reading, watching film",1,NaN,0.0,0.0,0,0,0,0,0,0,1707119676_d6c58fb6bb36ffc05cbc.png,
33,U00052,Ratna Febrianti,febrianti.ratna@leapsurabaya.sch.id,2026-06-23 21:40:16,aGtq,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00052,1716221191_e94b670798bb2696d03d.jpg,R00008,0812-3222-789_,2024-05-02,J00008,NaN,Jalan-jalan,1,7.0,0.0,0.0,0,0,0,1,0,0,None,
34,U00053,Ann Clariss Agbalog Amora,edgetutor1@leapsurabaya.sch.id,2026-06-23 21:40:16,o56YqdWnpafXYWhm,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00053,1716522842_b8a66f29051db6e6a30f.png,R00005,0812-3456-7890,2024-07-01,J00010,NaN,Mengajar,0,NaN,0.0,0.0,0,0,0,0,0,0,None,
35,U00054,Bryant Frederico Sutanto,Bryant.f@leapsurabaya.sch.id,2026-06-23 21:40:16,aGtq,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00054,1722917861_0ee847a25351751385f7.jpg,R00008,0813-5844-4457,2024-07-31,J00008,NaN,Bahasa dan budaya Jepang,1,9.0,0.0,0.0,0,0,0,0,0,0,None,
36,U00055,Muhammad Jefry Mulyanto,muhammad.jefry@leapsurabaya.sch.id,2026-06-23 21:40:16,oZ%2BpsqGelpnVYWtjaJSb,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00055,1773135932_67f2904210ccaf98ae5c.jpg,R00003,0812-2450-6675,2024-08-26,J00006,NaN,Programmer,1,NaN,0.0,0.0,0,0,0,0,0,0,None,
37,U00056,Amat Kasiyan,Amat@leap.surabaya.sch.id,2026-06-23 21:40:16,aGtq,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00056,None,R00002,0823-3083-0666,2022-08-01,J00009,NaN,-,1,NaN,0.0,0.0,0,0,0,0,0,0,None,
38,U00057,"Ulfasiyah, S.S.",ulfasiyah@leapsurabaya.sch.id,2026-06-23 21:40:16,aGtq,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00057,1750844720_4f07e83b71026e70d649.jpg,R00005,0813-5708-7801,2025-07-14,J00010,NaN,watching movies,1,NaN,0.0,0.0,0,0,0,0,0,0,None,
39,U00058,Piotr Pawel Sopa,piotr.pawel@leapsurabaya.sch.id,2026-06-23 21:40:16,aGtq,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00058,1751421912_794219fd3b3a81826b1c.png,R00005,0000-0000-0000,2025-06-09,J00010,NaN,-,0,NaN,0.0,0.0,0,0,0,0,0,0,None,
40,U00059,Amilia Khasanah Marzuki,Amilia.Khasanah@leapsurabaya.sch.id,2026-06-23 21:40:16,aGtq,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00059,1752555257_97357c08ebc0392ac2d7.jpeg,R00003,0821-4267-6635,2025-07-14,J00006,NaN,"Teknologi, membaca, menulis",1,NaN,0.0,1.0,0,0,0,1,0,0,None,
41,U00060,Muhammad Yusril Romadhoni,Muhammad.Yusril@leapsurabaya.sch.id,2026-06-23 21:40:16,aGtq,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00060,1754980098_55dca9a0b0e9990ca869.jpg,R00005,0857-7509-3865,2025-08-01,J00010,NaN,Menonton Drama Korea dan mendengarkan musik,1,NaN,0.0,0.0,0,0,0,0,0,0,None,
42,U00061,"Veronica Febriyanti Adam, S.S.",veronica.febriyanti@leapsurabaya.sch.id,2026-06-23 21:40:16,iqGgp8Z0o6HMmKpkaZSe,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00061,None,R00005,0812-1615-9545,2025-08-19,J00010,NaN,"Cats, Reading, Writing, Deep Talks",1,NaN,0.0,0.0,0,0,0,0,0,0,None,
43,U00062,La Erpiadin,la.erpiadin@leapsurabaya.sch.id,2026-06-23 21:40:16,aGtq,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00062,1761248806_6b8c2da1c58192d201a3.jpg,R00008,0838-7547-2022,2025-10-23,J00008,NaN,"Badminton, etc!",0,7.0,0.0,0.0,0,0,0,0,0,0,None,
44,U00063,"Aulia Ratna Meilinda, S.Pd.",Aulia.Ratna@leapsurabaya.sch.id,2026-06-23 21:40:16,aGtq,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00063,1764051278_f0b0b3fd6a63aec6c545.jpg,R00005,0822-4666-9172,2025-11-03,J00010,NaN,Teaching and Hospitality,0,NaN,0.0,0.0,0,0,0,0,0,0,None,
45,U00064,"PINANGGIH DIMAS PERMANA, S.Kom",Pinanggih.Dimas@leapsurabaya.sch.id,2026-06-23 21:40:16,aGtq,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00064,1761894217_d2d9db0138452815cccb.jpg,R00005,0821-3161-2092,2025-11-03,J00010,NaN,Desain Grafis,1,NaN,0.0,0.0,0,0,0,0,0,0,None,
46,U00065,"Retno Wulandari, S.Pd.",Retno.Wulandari@leapsurabaya.sch.id,2026-06-23 21:40:16,aGtq,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00065,1761894718_609b779afda9d054759a.jpg,R00005,0856-0483-4631,2025-11-03,J00010,NaN,Pendidikan dan Pelatihan,1,NaN,0.0,0.0,0,0,0,0,0,0,None,
47,U00066,"Risma Dwi Aryanti, S.Pd.",Risma.Dwi@leapsurabaya.sch.id,2026-06-23 21:40:16,n26ua5WLaZ0%3D,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00066,1761899138_26ac9bbda74de43457d5.jpeg,R00005,0831-1429-5984,2025-11-03,J00010,NaN,Photography,1,NaN,0.0,0.0,0,0,0,0,0,0,None,
48,U00067,"Moh Rafli Wahyudi, S.Pd.",Moh.Rafli@leapsurabaya.sch.id,2026-06-23 21:40:16,g56YqaihnKHRYWg%3D,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00067,1764417943_4ef0754f62e2225958a0.jpg,R00005,0878-5054-1006,2025-11-26,J00010,NaN,Motorsport,1,NaN,0.0,0.0,0,0,0,0,0,0,None,
49,U00068,Mochammad Rahmat Muttaqin,rahmat.muttaqin@leapsurabaya.sch.id,2026-06-23 21:40:16,aGtq,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00068,1772512035_1e7431474e054579a781.jpeg,R00003,0851-8212-0736,2026-01-26,J00006,NaN,Rebahan,1,NaN,0.0,0.0,0,0,0,0,0,0,None,
50,U00069,Zaskya Ayra Sinatrya,zaskya.Ayra@leapsurabaya.sch.id,2026-06-23 21:40:16,sZqqocJiYmmWYGo%3D,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00069,None,R00005,0897-2151-222_,2026-04-15,J00010,NaN,-,1,NaN,0.0,0.0,0,0,0,0,0,0,None,
51,U00070,Zumrotul Fatma Rahmayanti,zumrotul.fatma@leapsurabaya.sch.id,2026-06-23 21:40:16,h6Kjec2XkqiaYQ%3D%3D,None,2026-06-23 21:40:16,2026-06-23 21:40:16,U00070,None,R00008,0812-3253-9817,2026-04-30,J00008,NaN,learning,1,7.0,0.0,0.0,0,0,0,0,0,0,None,

5. TAMPILAN SEMUA DATA:

,idkaryawan,alamatktp,domisili,kota
0,LEAP00102VI23,None,None,None
1,LEAP00313III23,"Ranggeh, Gondangwetan, Pasuruan","Lebak Indah Regency B40, Surabaya",Sidoarjo
2,LEAP01101XII20,"PONDOK TROSOBO INDAH L-5, RT 003 RW 009, TROSOBO, TAMAN, SIDOARJO, JAWA TIMUR, INDONESIA.",GUNUNGANYAR LOR GG 3A NO 9A,SURABAYA
3,LEAP01202III20,Jl Pacar Kembang Vc No 22,Jl Pacar Kembang Vc No 22,Semarang
4,LEAP01431VII18,Rungkut Asri Barat XIII no 17,Rungkut Asri Barat XIII no 17,Surabaya
5,LEAP01514II11,None,None,None
6,LEAP01619VI17,"RT 001/RW 002, Ngangkrok, Medalem, Modo, Lamongan","Jalan Pabrik Kulit Gg. 2 Gg. Buntu No.24, Jemur Wonosari, Wonocolo, Surabaya",Lamongan
7,LEAP01820IV21,"Tebel Timur 004/006, TEBEL, GEDANGAN, SIDOARJO","Tebel Timur JL. RA Mustika III 004/006 No. 64, TEBEL, GEDANGAN, SIDOARJO",Surabaya
8,LEAP01901VI19,"Kebalan Kulon Rt 10 RW 02, Sekaran - Lamongan",Grand Surya blok A6 - 17 Buduran Sidoarjo,Lamongan
9,LEAP02030IV09,Amir Mahmud IV No.9-C,Amir Mahmud IV No.9-C,Surabaya
10,LEAP02301X19,Rungkut Asri Barat XIII-17,Rungkut Asri Barat XIII-17,Surabaya
11,LEAP02602VIII21,JL. Gubeng Kertajaya IX D No. 6,JL. Gubeng Kertajaya IX D No. 6,Surabaya
12,LEAP02715VI23,dgfhj,gfhdj,fgb
13,LEAP02801VI23,None,None,None
14,LEAP03027VI23,-,-,surabaya
15,LEAP03108VI18,Desa Pengangsalan RT 03 RW 02 Kecamatan Kalitengah Lamongan,"Pabrik Kulit Gang 2 Gang Buntu no. 24 Jemursari, Surabaya",Gresik
16,LEAP03202I23,"Jl. Ketapang III, RT 04, RW 02, Ds. Suko, Sukodono, Sidoarjo","Jl. Ketapang III, RT 04, RW 02, Ds. Suko, Sukodono, Sidoarjo",MADIUN
17,LEAP03305VIII22,Jl. M Yusuf RT 012 RW 003 Kel. Kecubung Kec. Pace,Perumahan Grand Eastern JL. Taman Timur Sukolilo II NO. 18 Blok AE-2,Surabaya
18,LEAP03416II22,Perum Green Lake Wonorejo Timur Baru XVII H5/26,Perum Green Lake Wonorejo Timur Baru XVII H5/26,Malang
19,LEAP03507VIII12,Jl. Amir Mahmud IV 9-C,Permata Kwangsan Residence C1-10,Magelang
20,LEAP03602I23,"Jl. Pucang Asri I no.11, Kertajaya, Gubeng, Surabaya","Jl. Pucang Asri I no.11, Kertajaya, Gubeng, Surabaya",Surabaya
21,LEAP03704VII23,"Dusun Sisir, RT 04, RW 05, Desa Kedungsoko, Plumpang, Tuban","Margorejo, Wonocolo",Tuban
22,LEAP03807VI11,Ds. Klampok No.5 Kec. Kapas Kab. Bojonegoro,Perumahan Sentra Point Blok AD No.21 Surabaya,Bojonegoro
23,LEAP04004VII23,"Gresik, Kec. Dukun, Des. Petiyintunggal 001/001",Asem Payung I/25,Gresik
24,LEAP04125III23,Jl. Kutisari Utara II D/17 d,Jl. Kutisari Indah Barat IX No. 11,Surabaya
25,LEAP04225III23,"Jompong, Mojokerto","Jalan Kutisari Utara 1 No. 54, Tenggilis Mejoyo, Surabaya",Mojokerto
26,LEAP04301VIII23,"Dsn, Sawo RT/RW 007/002, Ds. Sawo, Kec. Campurdarat, Kab. Tulungagung","Jl. Keputih Makam Blok D No.5, Keputih, Sukolilo, Surabaya",Tulungagung
27,LEAP04402X23,Jl. KH. Kholil V No.49B Demangan Bangkalan,Jl. KH. Kholil V No.49B Demangan Bangkalan,Bangkalan
28,LEAP04601X23,None,None,None
29,LEAP04701XII23,JL.KH.ACHMAD DAHLAN XIII/7,JL.KH.ACHMAD DAHLAN XIII/3,Kota Pasuruan
30,LEAP04821XII23,None,None,None
31,LEAP04901II24,"Jl. Kav Mentari 02 no.45 , Tambak Rejo, Waru, Sidoarjo","Jl. Kav Mentari 02 no.45 , Tambak Rejo, Waru, Sidoarjo",Madiun
32,LEAP05019II24,Penjaringansari Baru I-A/Kav.5 Rungkut Surabaya,Penjaringansari Baru I-A/Kav.5 Rungkut Surabaya,Surabaya
33,LEAP05202V24,Kutisari Indah Utara 7/20 Surabaya,Kutisari Indah Utara 7/20 Surabaya,Surabaya
34,LEAP05301VII24,None,None,None
35,LEAP05431VII24,Jl. Medayu Selatan IV/57,Jl. Medayu Selatan IV/57,Surabaya
36,LEAP05526VIII24,BLOK KARANG BARU BARAT,INDRAMAYU,INDRAMAYU
37,LEAP05601VIII22,"Dsn. Semelo 004/002, Ds. Kayen, Kec. Bandar Kedungmulyo, Kab. Jombang","Candi, Sidoarjo",Jombang
38,LEAP05714VII25,"Jl. Kh. Moch. Cholil gg. IX, RT. 03, RW. 07, No. 07, Bangkalan, Madura","Jl. Kav. Mentari 3, Tambaksumur, Waru, Sidoarjo",Jeddah
39,LEAP05809VI25,-,-,-
40,LEAP05914VII25,"Kalibutuh Barat 3/51-A, Surabaya","Delta Harmoni No 35. Deltasari,Waru,Sidoarjo",Mojokerto
41,LEAP06001VIII25,"Dusun Baran RT.003 RW. 019, Desa Wajak, Kec. Wajak","Jl. Rungkut Menanggal Harapan W-12 Rungkut, Rungkut Menanggal, Kec. Gn. Anyar, Surabaya, Jawa Timur 60294",Malang
42,LEAP06119VIII25,Medayu Selatan 4/36,"Jalan Baruk Utara Blok CC No.49, Kedung Baruk",Surabaya
43,LEAP06223X25,"Dusun Gu, Desa Batuatas Liwu, Kec. Batuatas, Kab. Buton Selatan, Sulawesi Tenggara","Jl. Manyar Sambongan, Kertajaya, Gubeng, Surabaya, Jawa Timur",Buton Selatan
44,LEAP06303XI25,"Kaliagung, Rt 001/ Rw 001, Ds. Kendalrejo, Kec. Tegaldlimo, Kab. Banyuwangi, 68484.","Kaliagung, Rt 001/ Rw 001, Ds. Kendalrejo, Kec. Tegaldlimo, Kab. Banyuwangi, 68484.",Banyuwangi
45,LEAP06403XI25,"Dusun Jatiluhur Rt 10 Rw 01 Desa Glagahagung, Purwoharjo, Banyuwangi","Dusun Jatiluhur Rt 10 Rw 01 Desa Glagahagung, Purwoharjo, Banyuwangi",Banyuwangi
46,LEAP06503XI25,"Dsn.Gumukrejo, RT 02/ RW 03, Ds. Purwoharjo, Kec. Purwoharjo, Kab. Banyuwangi","Dsn.Gumukrejo, RT 02/ RW 03, Ds. Purwoharjo, Kec. Purwoharjo, Kab. Banyuwangi",Banyuwangi
47,LEAP06603XI25,Banjar Tengah,"Perumahan Griya, Jalan Raja Wali, Tegal Badeng Barat, Negara (Blok. A No.1), KAB. JEMBRANA, NEGARA, BALI, ID, 82213",JEMBRANA
48,LEAP06726XI25,"Jalan Pulau Obi, Gang Purna Jiwa No. 8","Jalan Pulau Obi, Gang Purna Jiwa No. 8",Singaraja
49,LEAP06826I26,JL. SWASEMBADA BARAT XVI NO. 42,"Jalan Rungkut Menanggal Harapan Blok W No. W 12, Rungkut Menanggal",Jakarta
50,LEAP06915IV26,"Jl. Ploso Timur 1/57, Kel. Ploso, Kec. Tambaksari","Jl. Ploso Timur 1/57, Kel. Ploso, Kec. Tambaksari",Surabaya
51,LEAP07030IV26,"Dusun Bonagung, RT 002/RW 005, Kabalan, Kanor, Bojonegoro","Jl. Kalidami VIII/2, Kel. Mojo, Kec. Gubeng, Surabaya 60285",Bojonegoro

In [28]:
df_new['karyawan'].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 37 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id_karyawan           0 non-null      object
 1   id_user               0 non-null      object
 2   kode_karyawan         0 non-null      object
 3   nik_ktp               0 non-null      object
 4   nama_lengkap          0 non-null      object
 5   nama_panggilan        0 non-null      object
 6   tempat_lahir          0 non-null      object
 7   tanggal_lahir         0 non-null      object
 8   jenis_kelamin         0 non-null      object
 9   golongan_darah        0 non-null      object
 10  agama                 0 non-null      object
 11  status_pernikahan     0 non-null      object
 12  alamat_ktp            0 non-null      object
 13  alamat_domisili       0 non-null      object
 14  kewarganegaraan       0 non-null      object
 15  anak_ke               0 non-null      object
 16  jumlah_anak           0 non-null      object
 17  hobi                  0 non-null      object
 18  akun_linkedin         0 non-null      object
 19  email_pribadi         0 non-null      object
 20  email_kantor          0 non-null      object
 21  nomor_telepon         0 non-null      object
 22  nomor_npwp            0 non-null      object
 23  bpjs_ketenagakerjaan  0 non-null      object
 24  bpjs_kesehatan        0 non-null      object
 25  nomor_rekening        0 non-null      object
 26  moda_transportasi     0 non-null      object
 27  akun_instagram        0 non-null      object
 28  akun_facebook         0 non-null      object
 29  link_dokumen_pribadi  0 non-null      object
 30  riwayat_kesehatan     0 non-null      object
 31  tanggal_bergabung     0 non-null      object
 32  keahlian              0 non-null      object
 33  id_shift              0 non-null      object
 34  status_aktif          0 non-null      object
 35  foto_profile          0 non-null      object
 36  ttd_digital           0 non-null      object
dtypes: object(37)
memory usage: 132.0+ bytes

## Pindah ke df_new[karyawan]
Section ini digunakan untuk menganalisis pemetaan kolom dari `df_old['karyawan']` dan `df_merged_users` ke target `df_new['karyawan']`.

In [29]:
import pandas as pd

def analyze_migration_readiness(df_old_k, df_old_u, df_new_target):
    old_cols = set(df_old_k.columns)
    user_cols = set(df_old_u.columns)
    new_cols = set(df_new_target.columns)
    
    print("=== ANALISIS MAPPING KOLOM KARYAWAN ===\n") 
    
    # 1. Direct Match
    direct_matches = old_cols.intersection(new_cols)
    print(f"[DIRECT MATCH] Ada {len(direct_matches)} kolom yang namanya sama:")
    print(f"{list(direct_matches)}\n")
    
    # 2. Missing in Old (Need to find source or fill with default)
    missing_in_old = new_cols - old_cols
    
    # Check if they exist in user table
    from_user = missing_in_old.intersection(user_cols)
    still_missing = missing_in_old - from_user
    
    print(f"[FROM USER DATA] {len(from_user)} kolom target ada di data users:")
    print(f"{list(from_user)}\n")
    
    print(f"[STILL MISSING] {len(still_missing)} kolom target tidak ada di data karyawan lama maupun users:")
    print(f"{list(still_missing)}\n")
    
    # 3. Potential Mappings (Fuzzy matching names)
    print("[POTENTIAL MAPPINGS] Mencoba mencocokkan nama kolom (case-insensitive/underscore):")
    potential = []
    for m in still_missing:
        normalized_m = m.lower().replace('_', '').replace(' ', '')
        for o in old_cols:
            normalized_o = o.lower().replace('_', '').replace(' ', '')
            if normalized_m == normalized_o or normalized_m in normalized_o or normalized_o in normalized_m:
                potential.append(f"{o} -> {m}")
    
    if potential:
        for p in set(potential):
            print(f"  - {p}")
    else:
        print("  - Tidak ditemukan kecocokan otomatis.")

analyze_migration_readiness(df_old['karyawan'], df_merged_users, df_new['karyawan'])

=== ANALISIS MAPPING KOLOM KARYAWAN ===

[DIRECT MATCH] Ada 2 kolom yang namanya sama:
['hobi', 'agama']

[FROM USER DATA] 1 kolom target ada di data users:
['id_user']

[STILL MISSING] 34 kolom target tidak ada di data karyawan lama maupun users:
['status_aktif', 'nomor_telepon', 'nomor_npwp', 'nomor_rekening', 'id_shift', 'akun_linkedin', 'foto_profile', 'moda_transportasi', 'akun_instagram', 'status_pernikahan', 'id_karyawan', 'ttd_digital', 'tanggal_lahir', 'anak_ke', 'nik_ktp', 'golongan_darah', 'link_dokumen_pribadi', 'akun_facebook', 'nama_panggilan', 'alamat_ktp', 'nama_lengkap', 'tempat_lahir', 'keahlian', 'jenis_kelamin', 'tanggal_bergabung', 'email_pribadi', 'riwayat_kesehatan', 'kode_karyawan', 'alamat_domisili', 'kewarganegaraan', 'email_kantor', 'bpjs_ketenagakerjaan', 'bpjs_kesehatan', 'jumlah_anak']

[POTENTIAL MAPPINGS] Mencoba mencocokkan nama kolom (case-insensitive/underscore):
  - anakke -> anak_ke
  - ktp -> alamat_ktp
  - npwp -> nomor_npwp
  - nama -> nama_panggilan
  - email -> email_pribadi
  - ig -> ttd_digital
  - nama -> nama_lengkap
  - ktp -> nik_ktp
  - domisili -> alamat_domisili
  - link -> akun_linkedin
  - idkaryawan -> id_karyawan
  - moda -> moda_transportasi
  - tanggal -> tanggal_lahir
  - anak -> jumlah_anak
  - tanggal -> tanggal_bergabung
  - alamatktp -> alamat_ktp
  - riwayat -> riwayat_kesehatan
  - email -> email_kantor
  - emailkantor -> email_kantor
  - link -> link_dokumen_pribadi
  - rekening -> nomor_rekening
  - warga -> kewarganegaraan
  - status -> status_pernikahan
  - status -> status_aktif
  - linkedin -> akun_linkedin
  - anak -> anak_ke

In [30]:
# 1. Ambil kolom yang diperlukan dari df_merged_users sebagai referensi update
# Pastikan menggunakan kolom 'nama' (atau 'name' jika 'nama' tidak ada) dan 'email'
cols_to_use = ['idusers', 'email']
if 'nama' in df_merged_users.columns:
    cols_to_use.append('nama')
elif 'name' in df_merged_users.columns:
    # Jika di df_merged_users namanya 'name', kita rename jadi 'nama' agar sesuai target
    df_update_ref = df_merged_users[['idusers', 'name', 'email']].rename(columns={'name': 'nama'})
    cols_to_use = None # Sudah dihandle di baris atas

if cols_to_use:
    df_update_ref = df_merged_users[cols_to_use]

# 2. Hapus kolom 'nama' dan 'email' lama di df_old['karyawan'] 
# agar tidak terjadi duplikasi kolom saat merge
df_old['karyawan'] = df_old['karyawan'].drop(columns=['nama', 'email'])

# 3. Merge df_old['karyawan'] dengan data referensi berdasarkan 'idusers'
df_old['karyawan'] = df_old['karyawan'].merge(
    df_update_ref, 
    on='idusers', 
    how='left'
)

# Opsional: Cek hasil merge
print("Update selesai. Preview df_old['karyawan']:")
display(df_old['karyawan'])

Update selesai. Preview df_old['karyawan']:

,idkaryawan,ktp,nickname,kota,tgl,jk,goldar,agama,status,alamatktp,domisili,warga,anakke,hobi,linkedin,riwayat,emailkantor,telp,npwp,bpjskerja,bpjssehat,idusers,anak,rekening,moda,ig,fb,link,thnbekerja,bulan_romawi,tanggal,tahun,nama,email
0,LEAP00102VI23,None,ADMINISTRATOR,None,None,Perempuan,None,None,None,None,None,None,NaN,None,None,None,None,None,None,NaN,None,U00001,None,None,None,None,None,,2023-06-02,VI,02,2023,ADMINISTRATOR,ditari@leapsurabaya.sch.id
1,LEAP00313III23,3514186411980002,Graciela,Sidoarjo,11/24/1998,Perempuan,None,Islam,Belum Menikah,"Ranggeh, Gondangwetan, Pasuruan","Lebak Indah Regency B40, Surabaya",WNI,1.0,Membaca,https://www.linkedin.com/in/graciela-evanda-ronadi-b134221a3/?originalSubdomain=id,"Maag, tipes",graciela@leapsurabaya.sch.id,0812-3447-7137,53.856.239.8-619.000,NaN,,U00003,,0140881385821,Sepeda Motor,https://www.instagram.com/gracielaevr/,,https://drive.google.com/drive/folders/1alw9SubNFKSs40YOrz36JlZCGj7T8waC?usp=sharing,2023-03-13,III,13,2023,"Graciela Evanda Ronadi, S.Kom.",graciela@leapsurabaya.sch.id
2,LEAP01101XII20,3515135105910001,DANIAR,SURABAYA,05/11/1991,Perempuan,B,Islam,Menikah,"PONDOK TROSOBO INDAH L-5, RT 003 RW 009, TROSOBO, TAMAN, SIDOARJO, JAWA TIMUR, INDONESIA.",GUNUNGANYAR LOR GG 3A NO 9A,WNI,1.0,"MAIN GAME, NONTON",https://www.linkedin.com/in/daniar-aulia-rizki-28b8a4250/,PREKLAMSIA,daniar.rizki@leapsurabaya.sch.id,0896-9632-0278,46.770.512.5-603.000,21034278636,0002319622514,U00011,1,1410022279715,Sepeda Motor,@dar.od,tidak ada,https://drive.google.com/drive/u/0/folders/1va7B0PtK57XOZrl-1nvu1n3Wz1jOj75r,2020-12-01,XII,01,2020,DANIAR AULIA RIZKI,daniar.rizki@leapsurabaya.sch.id
3,LEAP01202III20,3578106705930001,Habibah,Semarang,05/27/1993,Perempuan,AB,Islam,Belum Menikah,Jl Pacar Kembang Vc No 22,Jl Pacar Kembang Vc No 22,WNI,1.0,Mereview berbagai jenis makanan,https://www.linkedin.com/in/habibah-melyna/,"Alergi udang, pengawet makanan dan micin",habibah.elfiani@leapsurabaya.sch.id,0857-3093-3317,96.917.411.9-619.000,21034278651,0002999218792,U00012,,1420018314442,Sepeda Motor,https://instagram.com/habibahmelyna?igshid=MzNlNGNkZWQ4Mg==,,None,2020-03-02,III,02,2020,Habibah Melyna,habibah.elfiani@leapsurabaya.sch.id
4,LEAP01431VII18,3578035706820005,Laksmi,Surabaya,06/17/1982,Perempuan,O,Islam,Belum Menikah,Rungkut Asri Barat XIII no 17,Rungkut Asri Barat XIII no 17,WNI,2.0,"Hiking, Reading, Traveling, Attending Concert",https://www.linkedin.com/in/laksmi-puspitowardhani-ab1a1336,Liver,laksmi.p@leapsurabaya.sch.id,6282-1399-6681,35.227.276.9-615.000,18088838356,00015384308,U00014,,1420016807967,Sepeda Motor,https://www.instagram.com/laksmi_purplespace/?hl=en,-,https://drive.google.com/drive/folders/1-7iI4-phQIGBra_G-bekA_2Fuu_-nAiu?usp=drive_link,2018-07-31,VII,31,2018,Laksmi Puspitowardhani,laksmi.p@leapsurabaya.sch.id
5,LEAP01514II11,None,Ika,None,None,Perempuan,None,None,None,None,None,None,NaN,None,None,None,None,None,None,NaN,None,U00015,None,None,None,None,None,None,14-2-2011,II,14,2011,Ika Asriani Yadin,ikayadin@leapsurabaya.sch.id
6,LEAP01619VI17,3524035806960001,Luluk,Lamongan,06/18/1996,Perempuan,None,Islam,Belum Menikah,"RT 001/RW 002, Ngangkrok, Medalem, Modo, Lamongan","Jalan Pabrik Kulit Gg. 2 Gg. Buntu No.24, Jemur Wonosari, Wonocolo, Surabaya",WNI,1.0,Menonton Drama/Film,https://www.linkedin.com/in/luluk-fatikah-sari-a74001252/,Tipes dan sakit lambung,luluk.sari@leapsurabaya.sch.id,0857-8546-7685,81.269.150.9-645.000,21034278685,0002226118184,U00016,,1420015479032,Sepeda Motor,https://www.instagram.com/lulukfatikah/,-,https://drive.google.com/drive/folders/1CF3rrcfAQzTvTxqt64FWdYP6meSOesBW?usp=sharing,2017-06-19,VI,19,2017,"Luluk Fatikah Sari, S.Pd.",luluk.sari@leapsurabaya.sch.id
7,LEAP01820IV21,3515165701920002,Tari,Surabaya,01/17/1992,Perempuan,B,Islam,Belum Menikah,"Tebel Timur 004/006, TEBEL, GEDANGAN, SIDOARJO","Tebel Timur JL. RA Mustika III 004/006 No. 64, TEBEL, GEDANGAN, SIDOARJO",WNI,1.0,Memasak dan membuat kerajinan tangan,ww,Maag dan darah rendah,,0813-5966-3659,,NaN,,U00018,,1410022278949,Sepeda Motor,ww,,None,2021-04-20,IV,20,2021,Ditari Kurnia,admin@gmail.com
8,LEAP01901VI19,3524094707820003,Tatik,Lamongan,07/07/1982,Perempuan,O,Islam,Menikah,"Kebalan Kulon Rt 10 RW 02, Sekaran - Lamongan",Grand Surya blok A6 - 17 Buduran Sidoarjo,WNI,1.0,Memasak,-,Tidak ada,hartatik@leapsurabaya.sch.id,0852-3101-7799,55.860.888.1-645.000,NaN,,U00019,0,1420009706010,Sepeda Motor,tati_bj (lupa password tidak bisa masuk ig melalui laptop jadi tidak bisa kasih link),Tati ((lupa password tidak bisa masuk facebook melalui laptop jadi tidak bisa kasih link),https://drive.google.com/drive/folders/1xy6IGdCMFEbMCO127hwFvvH_I45TuZzQ,2019-06-01,VI,01,2019,"Hartatik, S.S.",hartatik@leapsurabaya.sch.id
9,LEAP02030IV09,3578170506820004,MJ,Surabaya,06/05/1982,Laki laki,B,Islam,Menikah,Amir Mahmud IV No.9-C,Amir Mahmud IV No.9-C,WNI,1.0,-,-,-,juni.arlianto@leapsurabaya.sch.id,0881-0264-0001,81.277.051.9-615.000,17008686762,,U00020,1,140015278772,Sepeda Motor,7inchuuriki,,https://drive.google.com/drive/folders/1-ZWjsg38cDKBwBmUkYDLqsdCWkZrsq8V?usp=sharing,2009-04-30,IV,30,2009,Juni Arlianto,juni.arlianto@leapsurabaya.sch.id
10,LEAP02301X19,3578035305910002,Titi,Surabaya,05/13/1991,Perempuan,O,Islam,Menikah,Rungkut Asri Barat XIII-17,Rungkut Asri Barat XIII-17,WNI,3.0,Main Game,https://www.linkedin.com/in/titi-hapsari-retnaningtias/,"Maag, Patah Tulang, Sinusitis",titi.hapsari@leapsurabaya.sch.id,0822-4516-6547,86.802.833.3-615.000,21034278669,0000102317062,U00023,0,1420017951251,Sepeda Motor,https://www.instagram.com/titihapsarir,,https://drive.google.com/drive/folders/1k266j11p7CTcHciFGyrVpbHOISOC5dki?usp=sharing,2019-10-01,X,01,2019,Titi Hapsari,titi.hapsari@leapsurabaya.sch.id
11,LEAP02602VIII21,3578084710960004,Qo,Surabaya,10/07/1996,Perempuan,O,Islam,Belum Menikah,JL. Gubeng Kertajaya IX D No. 6,JL. Gubeng Kertajaya IX D No. 6,WNI,1.0,"Makan, Gambar, Uji coba makanan",https://id.linkedin.com/in/qorinrhmnyh,"Demam berdarah, tumor",qorin.rahmaniah@leapsurabaya.sch.id,0882-1710-5936,90.493.623.4-606.000,21056548478,0001880401408,U00026,0,1420020131214,Sepeda Motor,https://www.instagram.com/_cmdt/,https://m.facebook.com/QorinR/,https://drive.google.com/drive/folders/1or0AUFoMimPSWW1hTdqwMDXaZs9oLBEr?usp=sharing,2021-08-02,VIII,02,2021,"Qorin Rahmaniyah, S.Pd.",qorin.rahmaniah@leapsurabaya.sch.id
12,LEAP02715VI23,43656,fgsxd,fgb,06/27/2023,Perempuan,None,None,None,dgfhj,gfhdj,None,1.0,fjy,kjuhm,jgh,,4324-3546-577_,,NaN,,U00027,,353,None,kgm,,,2023-06-15,VI,15,2023,Test,test@gmail.com
13,LEAP02801VI23,None,pengajar,None,None,None,None,None,None,None,None,None,NaN,None,None,None,None,None,None,NaN,None,U00028,None,None,None,None,None,None,2023-06-01,VI,01,2023,pengajar,pengajar@gmail.com
14,LEAP03027VI23,1234567891011121,adminppdk,surabaya,04/01/2024,Perempuan,None,None,None,-,-,None,NaN,-,-,--,,0812-3457-890_,,NaN,,U00030,,12345678985,None,-,-,None,2023-06-27,VI,27,2023,Akun Data PPDK,data@gmail.com
15,LEAP03108VI18,3524205306950001,Yuni,Gresik,06/13/1995,Perempuan,None,Islam,Belum Menikah,Desa Pengangsalan RT 03 RW 02 Kecamatan Kalitengah Lamongan,"Pabrik Kulit Gang 2 Gang Buntu no. 24 Jemursari, Surabaya",WNI,1.0,Mendengarkan musik,Belum,Perna sakit gigi dan maag,eka.wahyuni@leapsurabaya.sch.id,0813-1347-1713,42.825.961.8-608.000,NaN,0002211312025,U00031,,EKA NUR WAHYUNI Bank Mandiri 1420016380346,Sepeda Motor,https://instagram.com/ekanurwahyuni13?igshid=MzNlNGNkZWQ4Mg==,,https://drive.google.com/drive/folders/12vXsyitqeyGazttmlQI9OFkXYM_x-zob,2018-06-08,VI,08,2018,"Eka Nur Wahyuni, S. Pd.",eka.wahyuni@leapsurabaya.sch.id
16,LEAP03202I23,3515146212940001,GETARI,MADIUN,12/22/1994,Perempuan,O,Islam,Belum Menikah,"Jl. Ketapang III, RT 04, RW 02, Ds. Suko, Sukodono, Sidoarjo","Jl. Ketapang III, RT 04, RW 02, Ds. Suko, Sukodono, Sidoarjo",WNI,1.0,"I don't have hobbies, I have moods",https://www.linkedin.com/in/getari-adyagarini-071598258?trk=contact-info,Tidak ada,getari@leapsurabaya.sch.id,0878-5668-0404,95.824.727.2-603.000,NaN,0000102024764,U00032,,1410023228554,Mobil,getari.adya,,https://drive.google.com/drive/folders/1xAhqwJ3tmWN3kQQGS4YVIa4prG9RscxD?usp=sharing,2023-01-02,I,02,2023,"Getari Adyagarini, M.Pd",getari@leapsurabaya.sch.id
17,LEAP03305VIII22,3518054105000002,Erica,Surabaya,05/18/2000,Perempuan,O,Katolik,Belum Menikah,Jl. M Yusuf RT 012 RW 003 Kel. Kecubung Kec. Pace,Perumahan Grand Eastern JL. Taman Timur Sukolilo II NO. 18 Blok AE-2,WNI,1.0,Nonton Drama & Scroll Tiktok,https://www.linkedin.com/in/maria-florencia-erica-susanto-81a900227,Patah tulang kaki kanan,ericasusanto@leapsurabaya.sch.id,0851-5721-7422,60.469.638.5-615.000,23182511560,0002479768389,U00033,,140020550777,Sepeda Motor,https://instagram.com/ericachouw,,https://drive.google.com/drive/folders/1BsoRjVlW0QHOkAD-npM175jsOdBErdYl?usp=sharing,2022-08-05,VIII,05,2022,"Maria Florencia Erica Susanto, A.Md.",ericasusanto@leapsurabaya.sch.id
18,LEAP03416II22,3578256604800002,Mieke,Malang,04/26/1980,Perempuan,O+,Katolik,Menikah,Perum Green Lake Wonorejo Timur Baru XVII H5/26,Perum Green Lake Wonorejo Timur Baru XVII H5/26,WNI,1.0,"Membaca, Menulis, Pergi pergi :P",https://www.linkedin.com/in/mieke-puspita-b01175259,bapil,miekepuspita@leapsurabaya.sch.id,0838-4989-5079,47.962.870.3-615.000,35782566048,0001536484331,U00034,1,1420020132329,Sepeda Motor,https://instagram.com/miekepuspita?igshid=ZDc4ODBmNjlmNQ==,https://www.facebook.com/mieke.puspita.7?mibextid=ZbWKwL,https://drive.google.com/drive/folders/10QGgWRKucYxs5RfV-OGgxc3pplpi7hrK?usp=sharing,2022-02-16,II,16,2022,"Mieke Puspita, S.Pd",miekepuspita@leapsurabaya.sch.id
19,LEAP03507VIII12,3578256602930001,Tata,Magelang,02/26/1993,Perempuan,B,Islam,Menikah,Jl. Amir Mahmud IV 9-C,Permata Kwangsan Residence C1-10,WNI,1.0,"Memasak, make up, Jalan-jalan",-,-,Miftakhul.jannah @leapsurabaya.sch.id,0881-0264-0002,,17008687224,0001908364386,U00035,1,1420015278772,Sepeda Motor,miptha__,-,https://drive.google.com/drive/folders/1oeKwMA32povscLhSdyCTe6sxJ6DFxDGH?usp=sharing,2012-08-07,VIII,07,2012,"Miftakhul Jannah, S.Pd",miftakhul.jannah@leapsurabaya.sch.id
20,LEAP03602I23,1671070811000012,Dea,Surabaya,11/08/2000,Perempuan,B,Islam,Belum Menikah,"Jl. Pucang Asri I no.11, Kertajaya, Gubeng, Surabaya","Jl. Pucang Asri I no.11, Kertajaya, Gubeng, Surabaya",WNI,1.0,Musik,https://www.linkedin.com/in/rr-nisrina-dea-rahma-3389ba204/,0,nisrina.dea@leapsurabaya.sch.id,0821-7616-1260,61.902.080.3-606.000,23074206378,0001107009641,U00036,0,1420016746702,Transportasi Umum,www.instagram.com/ndearhm,0,https://drive.google.com/drive/folders/1GZ6DYfo-qGvBa9bONymUVqTjM20i6N5A?usp=sharing,2023-01-02,I,02,2023,"Rr. Nisrina Dea Rahma, S.Hum",nisrina.dea@leapsurabaya.sch.id
21,LEAP03704VII23,3523176705990001,Uswa,Tuban,05/27/1999,Perempuan,None,Islam,Belum Menikah,"Dusun Sisir, RT 04, RW 05, Desa Kedungsoko, Plumpang, Tuban","Margorejo, Wonocolo",WNI,2.0,"Mendengarkan Musik, Membaca",-,-,siti.uswatun@leapsurabaya.sch.id,0857-4595-2525,61.719.186.1-648.000,NaN,,U00037,,1420021927123,Sepeda Motor,-,-,https://drive.google.com/drive/folders/1I775kRo3-5i1EfeslG6ub0zfIsNgf61I?usp=sharing,2023-07-04,VII,04,2023,Siti Uswatun Khasanah,siti.uswatun@leapsurabaya.sch.id
22,LEAP03807VI11,3522146808900002,Rini,Bojonegoro,08/28/1990,Perempuan,B,Islam,Menikah,Ds. Klampok No.5 Kec. Kapas Kab. Bojonegoro,Perumahan Sentra Point Blok AD No.21 Surabaya,WNI,4.0,"membaca buku fiksi, menonton film",https://www.linkedin.com/in/rini-rahayu-91b7b1259/,-,rini.rahayu@leapsurabaya.sch.id,0851-6314-1616,42.366.046.8-615.000,17008685640,0003003442593,U00038,1,1420015505729,Sepeda Motor,https://www.instagram.com/rini.cy/,,https://drive.google.com/drive/folders/1HIhzTwz_akP85pFjnw4wHNnS-VK8jLI6?usp=sharing,2011-06-07,VI,07,2011,"Rini Budi Rahayu, S.Pd.",rini.rahayu@leapsurabaya.sch.id
23,LEAP04004VII23,3525011107855000,Agung,Gresik,07/11/1985,Laki laki,None,None,Belum Menikah,"Gresik, Kec. Dukun, Des. Petiyintunggal 001/001",Asem Payung I/25,WNI,NaN,Reading,-,-,agungwijayanto1107@gmail.com,0831-1527-0222,,NaN,,U00040,,1780000459418,Sepeda Motor,https://instagram.com/agungwijayanto_ec?igshid=MzNlNGNkZWQ4Mg==,https://www.facebook.com/profile.php?id=100009927274040&mibextid=ZbWKwL,https://drive.google.com/folderview?id=1JScNiC-Vt51o1nfW-cB-9ivY3EEzjoPO,2023-07-04,VII,04,2023,"Agung Wijayanto, S.T.",agung.wijayanto@leapsurabaya.sch.id
24,LEAP04125III23,3578246111990003,Vivi,Surabaya,11/21/1999,Perempuan,B,Islam,Belum Menikah,Jl. Kutisari Utara II D/17 d,Jl. Kutisari Indah Barat IX No. 11,WNI,1.0,"Menggambar, mewarnai, bersepda, mendengarkan musik",viviwulandari,Tidak memiliki riwayat penyakit,,0812-1722-2294,40.206.847.2-615.000,NaN,,U00041,,014001234634830,Sepeda Motor,@_viviwulandari,,https://drive.google.com/drive/folders/1jC7Xp9bZ3TS6WvO4FYrOogVhHEzwVBPF?usp=sharing,2023-03-25,III,25,2023,Vivi Pramitha Wulandari,vivi.wulandari@leapsurabaya.sch.id
25,LEAP04225III23,3516154706990003,Ica,Mojokerto,06/07/1999,Perempuan,O,Islam,Belum Menikah,"Jompong, Mojokerto","Jalan Kutisari Utara 1 No. 54, Tenggilis Mejoyo, Surabaya",WNI,2.0,"menonton series/ film, karaoke, jalan-jalan",www.linkedin.com/in/cantika-swasti,"Cacar, flu",,0858-0626-8098,62.655.312.7-615.000,NaN,0002611267672,U00042,,014,Sepeda Motor,www.instagram.com/cantikaswasti/,,None,2023-03-25,III,25,2023,Cantika Swasti Sumarsono Putri,cantikaswasti76@gmail.com
26,LEAP04301VIII23,3504160901970002,Trio,Tulungagung,01/09/1997,Laki laki,O+,Islam,Belum Menikah,"Dsn, Sawo RT/RW 007/002, Ds. Sawo, Kec. Campurdarat, Kab. Tulungagung","Jl. Keputih Makam Blok D No.5, Keputih, Sukolilo, Surabaya",WNI,3.0,Menonton Anime dan Olahraga,Tidak Ada,Tidak Ada (100% Sehat),staffga@leapsurabaya.sch.id,0878-8306-175_,62.703.897.9-629.000,21012951303,0000666642172,U00043,,0140481790254,Sepeda Motor,https://instagram.com/_triofajar?utm_source=qr&igshid=OGU0MmVlOWVjOQ==,https://www.facebook.com/waluyondoko?mibextid=ZbWKwL,https://drive.google.com/drive/folders/1hUPWYSsUT7vP8In6h_2x-_mPYuAdADVO?usp=sharing,2023-08-01,VIII,01,2023,Trio Fajar Cahyanto,generalaffair@gmail.com
27,LEAP04402X23,3526014802900001,Ifa,Bangkalan,02/08/1990,Perempuan,B,Islam,Menikah,Jl. KH. Kholil V No.49B Demangan Bangkalan,Jl. KH. Kholil V No.49B Demangan Bangkalan,WNI,1.0,Travelling,linkedin.com/in/muifatul-febriani-5840451ab,Tidak Ada,,0819-3932-0162,,NaN,,U00044,2,1400018055013,Sepeda Motor,@muifatul,,None,2023-10-02,X,02,2023,Muifatul Febriani,muifatul@leapsurabaya.sch.id
28,LEAP04601X23,None,sosmed,None,None,None,None,None,None,None,None,None,NaN,None,None,None,None,None,None,NaN,None,U00046,None,None,None,None,None,None,2023-10-01,X,01,2023,sosialmedia1,sosialmedia1@gmail.com
29,LEAP04701XII23,3575021903990005,Haykal,Kota Pasuruan,03/19/1999,Laki laki,None,None,Belum Menikah,JL.KH.ACHMAD DAHLAN XIII/7,JL.KH.ACHMAD DAHLAN XIII/3,WNI,1.0,Traveling,Haykal Roziqi,-,Muhammad.haykal@leapsurabaya.sch.id,0878-8799-2703,,NaN,0001197706397,U00047,,5360700017684,Motor Pribadi,haykalroziqi,Haikal Roziki,https://drive.google.com/drive/folders/1BKtcXkLyr7kf4DOCehJRKqpO5AveOj-p?usp=drive_link,2023-12-01,XII,01,2023,Muhamad Haykal Roziqi,Muhammad.haykal@leapsurabaya.sch.id
30,LEAP04821XII23,None,Yerly,None,None,None,None,None,None,None,None,None,NaN,None,None,None,None,None,None,NaN,None,U00048,None,None,None,None,None,None,2023-12-21,XII,21,2023,"Yerly A Datu, S.Pd, M.Pd, CT.ACT, C.PS",pengajar1@leapsurabaya.sch.id
31,LEAP04901II24,3519136702980002,Ana,Madiun,02/27/2024,Perempuan,B,Islam,Menikah,"Jl. Kav Mentari 02 no.45 , Tambak Rejo, Waru, Sidoarjo","Jl. Kav Mentari 02 no.45 , Tambak Rejo, Waru, Sidoarjo",WNI,1.0,Olahraga dan Menggambar,https://www.linkedin.com/in/ana-puspita-529419222?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app,Gerd,Ana.puspita@leapsurabaya.sch.id,0812-3128-4882,,NaN,,U00049,0,0142160829578,Sepeda Motor,https://www.instagram.com/anasta.id?igsh=MXdlZXV3d2RqMnJ0dQ==,,None,2024-02-01,II,01,2024,Ana Puspita,ana.puspita@leapsurabaya.sch.id
32,LEAP05019II24,3578034505870001,Peni,Surabaya,05/05/1987,Perempuan,O,Islam,Belum Menikah,Penjaringansari Baru I-A/Kav.5 Rungkut Surabaya,Penjaringansari Baru I-A/Kav.5 Rungkut Surabaya,WNI,1.0,"membaca, menonton film",https://www.linkedin.com/in/peni-puspa-2793151a8/,-,peni.indarwati@leapsurabaya.sch.id,0812-1635-3322,35.780.345.0-587.000,NaN,0001849925428,U00050,,0146750644161,Sepeda Motor,https://www.instagram.com/puepuen55/?hl=en,,https://drive.google.com/file/d/1CXkd0zUfmQsZidPinfLE7Lh1q1iTxUfJ/view?usp=drive_link,2024-02-19,II,19,2024,"Peni Puspa Indarwati, S.S.",peni.indarwati@leapsurabaya.sch.id
33,LEAP05202V24,3578244602850001,Ratna,Surabaya,02/06/1985,Perempuan,O,None,Belum Menikah,Kutisari Indah Utara 7/20 Surabaya,Kutisari Indah Utara 7/20 Surabaya,WNI,3.0,Jalan-jalan,https://www.linkedin.com/in/ratna-febrianti-b71382301,flu,febrianti.ratna@leapsurabaya.sch.id,0812-3222-789_,34.003.500.5-615.000,NaN,2271484124,U00052,,0148221109341,Sepeda Motor,https://www.instagram.com/ratnabrail/?hl=en,,https://drive.google.com/drive/folders/1KQugWew6s7u3K_Fho2WhPaZRa_f3QX7H?usp=sharing,2024-05-02,V,02,2024,Ratna Febrianti,febrianti.ratna@leapsurabaya.sch.id
34,LEAP05301VII24,None,Ann,None,None,None,None,None,None,None,None,None,NaN,None,None,None,None,None,None,NaN,None,U00053,None,None,None,None,None,None,2024-07-01,VII,01,2024,Ann Clariss Agbalog Amora,edgetutor1@leapsurabaya.sch.id
35,LEAP05431VII24,3578250605060001,Bryant,Surabaya,05/06/2006,Laki laki,O,Katolik,Belum Menikah,Jl. Medayu Selatan IV/57,Jl. Medayu Selatan IV/57,WNI,1.0,mendengarkan musik,www.linkedin.com/in/bryant-frederico-sutanto,Tidak ada riwayat penyakit,bryant.f@leapsurabaya.sch.id,0813-5844-4457,,NaN,,U00054,,1420024514654,Sepeda Motor,https://www.instagram.com/frdrc_0?igsh=bDZlOGdmcGo5cnVm,,https://drive.google.com/drive/folders/1Sqej9z744y6XHwC3kEyHskg8QNdPrsT0?usp=sharing,2024-07-31,VII,31,2024,Bryant Frederico Sutanto,Bryant.f@leapsurabaya.sch.id
36,LEAP05526VIII24,3212131506050001,Jefry,INDRAMAYU,06/15/2005,Laki laki,A,Islam,Belum Menikah,BLOK KARANG BARU BARAT,INDRAMAYU,WNI,3.0,"Futsal, Badminton",https://www.linkedin.com/in/muhammad-jefry-b8513a294/,Tidak Ada,muhammad.jefry@leapsurabaya.sch.id,0812-2450-6675,19.939.122.8-437.000,NaN,,U00055,,654901040798538,Jalan Kaki,https://www.instagram.com/fry025/,https://www.facebook.com/profile.php?id=100077922831795&locale=id_ID,https://drive.google.com/drive/folders/1lhGD5wTIMARtL7l2x2bjQRFMmVyg8G84?usp=sharing,2024-08-26,VIII,26,2024,Muhammad Jefry Mulyanto,muhammad.jefry@leapsurabaya.sch.id
37,LEAP05601VIII22,3517181502670002,Amat,Jombang,02/15/1967,Laki laki,None,Islam,Menikah,"Dsn. Semelo 004/002, Ds. Kayen, Kec. Bandar Kedungmulyo, Kab. Jombang","Candi, Sidoarjo",WNI,NaN,-,-,Tidak Ada,amat@leap.surabaya.sch.id,0823-3083-0666,73.114.549.6-602.000,NaN,0001900751297,U00056,1,1131166988,Sepeda Motor,-,-,https://drive.google.com/drive/folders/1BcGhrDmBljk1xhv-2FITf9rX7IYr_FDe?usp=sharing,2022-08-01,VIII,01,2022,Amat Kasiyan,Amat@leap.surabaya.sch.id
38,LEAP05714VII25,5326015003020001,Ulfa,Jeddah,03/10/2002,Perempuan,O,Islam,Belum Menikah,"Jl. Kh. Moch. Cholil gg. IX, RT. 03, RW. 07, No. 07, Bangkalan, Madura","Jl. Kav. Mentari 3, Tambaksumur, Waru, Sidoarjo",WNI,2.0,nonton film dan bikin design / ngedit,https://www.linkedin.com/in/ulfasiyahzm,tidak ada,ulfasiyah@leapsurabaya.sch.id,0813-5708-7801,,NaN,,U00057,,1400025052599,Sepeda Motor,https://www.instagram.com/ulfazmrkn,,None,2025-07-14,VII,14,2025,"Ulfasiyah, S.S.",ulfasiyah@leapsurabaya.sch.id
39,LEAP05809VI25,1231231231231233,Peter,-,07/01/2025,Laki laki,None,None,None,-,-,None,NaN,-,-,-,piotr.pawel@leapsurabaya.sch.id,0000-0000-0000,,NaN,,U00058,,654654645456464654,None,-,-,None,2025-06-09,VI,09,2025,Piotr Pawel Sopa,piotr.pawel@leapsurabaya.sch.id

In [31]:
import pandas as pd
import numpy as np
import datetime

# --- ANALISA DAN MIGRASI df_old['karyawan'] KE df_new['karyawan'] (FIXED DB_FUTURE) ---

# 1. Persiapkan data tambahan dari df_merged_users (seperti thnbekerja, expertise, dll)
user_cols_to_add = [
    'idusers', 'expertise', 'idjamkerja', 
    'status', 'foto', 'ttd'
]
df_user_info = df_merged_users[user_cols_to_add].rename(columns={'status': 'status_user_active'})

# Gabungkan data user ke df_old['karyawan'] agar semua data source terkumpul di satu tempat
if 'status_user_active' not in df_old['karyawan'].columns:
    df_old['karyawan'] = df_old['karyawan'].merge(df_user_info, on='idusers', how='left')

# 🆕 PEMBARUAN DATA INDUK (PRE-CLEANING SENSOR)
# Memastikan nama_lengkap tidak kosong (Guard NOT NULL)
if 'nama' in df_old['karyawan'].columns:
    df_old['karyawan']['nama'] = df_old['karyawan']['nama'].fillna('Tanpa Nama Resmi')

# Menyamakan ENUM Jenis Kelamin (Laki-laki -> Laki laki)
if 'jk' in df_old['karyawan'].columns:
    df_old['karyawan']['jk'] = df_old['karyawan']['jk'].astype(str).str.replace('-', ' ')

# 2. DEFINISI PEMETAAN KOLOM (SUDAH DISESUAIKAN KE DB_FUTURE)
column_mapping = {
    'id_karyawan': 'idkaryawan',
    'id_user': 'idusers',
    'kode_karyawan': 'idkaryawan',        # 🎯 BARU: Pindahkan idkaryawan lama ke kode_karyawan
    'nik_ktp': 'ktp',
    'nama_lengkap': 'nama',               # 🎯 BARU: Menambahkan kolom nama_lengkap yang wajib diisi
    'nama_panggilan': 'nickname',
    'tempat_lahir': 'kota',
    'tanggal_lahir': 'tgl',
    'jenis_kelamin': 'jk',
    'golongan_darah': 'goldar',
    'agama': 'agama',
    'status_pernikahan': 'status', 
    'alamat_ktp': 'alamatktp',
    'alamat_domisili': 'domisili',
    'kewarganegaraan': 'warga',
    'anak_ke': 'anakke',
    'jumlah_anak': 'anak',
    'hobi': 'hobi',
    'akun_linkedin': 'linkedin',
    'email_pribadi': 'email',
    'email_kantor': 'emailkantor',
    'nomor_telepon': 'telp',
    'nomor_npwp': 'npwp',
    'bpjs_ketenagakerjaan': 'bpjskerja',
    'bpjs_kesehatan': 'bpjssehat',
    'nomor_rekening': 'rekening',
    'moda_transportasi': 'moda',
    'akun_instagram': 'ig',
    'akun_facebook': 'fb',
    'link_dokumen_pribadi': 'link',
    'riwayat_kesehatan': 'riwayat',
    'tanggal_bergabung': 'thnbekerja',    # 🎯 BARU: thnbekerja lama dipetakan ke tanggal_bergabung (Bukan tahun_mulai_kerja)
    'keahlian': 'expertise',
    'id_shift': 'idjamkerja',
    'status_aktif': 'status_user_active', 
    'foto_profile': 'foto',
    'ttd_digital': 'ttd'
}

# 3. PROSES PEMBENTUKAN DATAFRAME BARU
df_migration = pd.DataFrame()

for target_col, source_col in column_mapping.items():
    if source_col in df_old['karyawan'].columns:
        df_migration[target_col] = df_old['karyawan'][source_col]
    else:
        print(f"Peringatan: Kolom '{source_col}' tidak ditemukan di source. Diisi NULL.")
        df_migration[target_col] = None

# 4. SIMPAN KE df_new['karyawan']
df_new['karyawan'] = df_migration

# 5. CLEANING DATA (Kosong atau '-' menjadi None)
df_new['karyawan'] = df_new['karyawan'].replace(['', '-'], None)

# 6. FORMATTING TANGGAL LAHIR & TANGGAL BERGABUNG (Menyesuaikan tipe Date MySQL)
df_new['karyawan']['tanggal_lahir'] = pd.to_datetime(df_new['karyawan']['tanggal_lahir'], errors='coerce').dt.date

# 🎯 BARU: thnbekerja dikonversi ke tipe Date penuh (YYYY-MM-DD), default ke awal tahun jika kosong
df_new['karyawan']['tanggal_bergabung'] = pd.to_numeric(df_new['karyawan']['tanggal_bergabung'], errors='coerce')
df_new['karyawan']['tanggal_bergabung'] = df_new['karyawan']['tanggal_bergabung'].apply(
    lambda x: f"{int(x)}-01-01" if pd.notna(x) else '2026-01-01'
)
df_new['karyawan']['tanggal_bergabung'] = pd.to_datetime(df_new['karyawan']['tanggal_bergabung']).dt.date

# ... (Poin 1 sampai 6 di dalam kode lambat/lama kamu tetap biarkan sama) ...

# 7. 🎯 PERBAIKAN CIMUT: CONVERT KE INTEGER MURNI & JINAKKAN FLOAT .0
# Kita paksa kolom id_shift dan anak_ke menjadi Int64 Nullable murni
df_new['karyawan']['id_shift'] = pd.to_numeric(df_new['karyawan']['id_shift'], errors='coerce').astype('Int64')
df_new['karyawan']['anak_ke'] = pd.to_numeric(df_new['karyawan']['anak_ke'], errors='coerce').astype('Int64')
df_new['karyawan']['jumlah_anak'] = pd.to_numeric(df_new['karyawan']['jumlah_anak'], errors='coerce').astype('Int64')

# 🆕 SUNTIKAN LOOPING AUTO-INCREMENT UNTUK id_karyawan 🆕
# Kita buat penomoran urut murni bawaan Python (1 sampai jumlah baris data)
# Taktik ini otomatis merontokkan float ghaib bertipe desimal .0
total_baris_karyawan = len(df_new['karyawan'])
df_new['karyawan']['id_karyawan'] = range(1, total_baris_karyawan + 1)

# Pastikan dikunci ke tipe Int64 murni agar aman terbaca oleh mysql-connector
df_new['karyawan']['id_karyawan'] = df_new['karyawan']['id_karyawan'].astype('Int64')

# 🆕 SENSOR TAMBAHAN GUNA MENJAGA ATURAN NOT NULL FIELD
df_new['karyawan']['status_pernikahan'] = df_new['karyawan']['status_pernikahan'].apply(
    lambda x: 'Belum Menikah' if pd.isna(x) or str(x).strip() in ["", "None", "nan"] else str(x).strip()
)

# 8. FINAL CLEANUP: Ganti NaN/NaT/pd.NA ke None
# Kita konversi ke .astype(object) dulu agar bisa menampung 'None' standar Python alih-alih pd.NA.
df_new['karyawan'] = df_new['karyawan'].astype(object).where(pd.notnull(df_new['karyawan']), None)

print(f"✓ Berhasil membuat looping auto-increment untuk {len(df_new['karyawan'])} data karyawan!")
print("--- Preview data hasil adaptasi id_karyawan murni (INT TANPA .0) ---")
df_new['karyawan'].info()
display(df_new['karyawan'][['id_karyawan', 'id_user', 'kode_karyawan', 'nama_lengkap']].head(5))

✓ Berhasil membuat looping auto-increment untuk 52 data karyawan!
--- Preview data hasil adaptasi id_karyawan murni (INT TANPA .0) ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 37 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id_karyawan           52 non-null     object
 1   id_user               52 non-null     object
 2   kode_karyawan         52 non-null     object
 3   nik_ktp               46 non-null     object
 4   nama_lengkap          52 non-null     object
 5   nama_panggilan        52 non-null     object
 6   tempat_lahir          45 non-null     object
 7   tanggal_lahir         46 non-null     object
 8   jenis_kelamin         52 non-null     object
 9   golongan_darah        32 non-null     object
 10  agama                 40 non-null     object
 11  status_pernikahan     52 non-null     object
 12  alamat_ktp            44 non-null     object
 13  alamat_domisili       44 non-null     object
 14  kewarganegaraan       43 non-null     object
 15  anak_ke               42 non-null     object
 16  jumlah_anak           16 non-null     object
 17  hobi                  41 non-null     object
 18  akun_linkedin         38 non-null     object
 19  email_pribadi         52 non-null     object
 20  email_kantor          39 non-null     object
 21  nomor_telepon         46 non-null     object
 22  nomor_npwp            27 non-null     object
 23  bpjs_ketenagakerjaan  14 non-null     object
 24  bpjs_kesehatan        24 non-null     object
 25  nomor_rekening        46 non-null     object
 26  moda_transportasi     42 non-null     object
 27  akun_instagram        42 non-null     object
 28  akun_facebook         11 non-null     object
 29  link_dokumen_pribadi  33 non-null     object
 30  riwayat_kesehatan     35 non-null     object
 31  tanggal_bergabung     52 non-null     object
 32  keahlian              1 non-null      object
 33  id_shift              14 non-null     object
 34  status_aktif          52 non-null     object
 35  foto_profile          44 non-null     object
 36  ttd_digital           15 non-null     object
dtypes: object(37)
memory usage: 15.2+ KB

  id_karyawan id_user   kode_karyawan                    nama_lengkap
0           1  U00001   LEAP00102VI23                   ADMINISTRATOR
1           2  U00003  LEAP00313III23  Graciela Evanda Ronadi, S.Kom.
2           3  U00011  LEAP01101XII20              DANIAR AULIA RIZKI
3           4  U00012  LEAP01202III20                  Habibah Melyna
4           5  U00014  LEAP01431VII18          Laksmi Puspitowardhani

In [32]:
print("\n--- Migrasi Selesai ---")
print(f"Jumlah baris yang dipindahkan: {len(df_new['karyawan'])}")
display(df_new['karyawan'])

--- Migrasi Selesai ---
Jumlah baris yang dipindahkan: 52

,id_karyawan,id_user,kode_karyawan,nik_ktp,nama_lengkap,nama_panggilan,tempat_lahir,tanggal_lahir,jenis_kelamin,golongan_darah,agama,status_pernikahan,alamat_ktp,alamat_domisili,kewarganegaraan,anak_ke,jumlah_anak,hobi,akun_linkedin,email_pribadi,email_kantor,nomor_telepon,nomor_npwp,bpjs_ketenagakerjaan,bpjs_kesehatan,nomor_rekening,moda_transportasi,akun_instagram,akun_facebook,link_dokumen_pribadi,riwayat_kesehatan,tanggal_bergabung,keahlian,id_shift,status_aktif,foto_profile,ttd_digital
0,1,U00001,LEAP00102VI23,None,ADMINISTRATOR,ADMINISTRATOR,None,None,Perempuan,None,None,Belum Menikah,None,None,None,None,None,None,None,ditari@leapsurabaya.sch.id,None,None,None,None,None,None,None,None,None,None,None,2026-01-01,None,2,1,logo.png,None
1,2,U00003,LEAP00313III23,3514186411980002,"Graciela Evanda Ronadi, S.Kom.",Graciela,Sidoarjo,1998-11-24,Perempuan,None,Islam,Belum Menikah,"Ranggeh, Gondangwetan, Pasuruan","Lebak Indah Regency B40, Surabaya",WNI,1,None,Membaca,https://www.linkedin.com/in/graciela-evanda-ronadi-b134221a3/?originalSubdomain=id,graciela@leapsurabaya.sch.id,graciela@leapsurabaya.sch.id,0812-3447-7137,53.856.239.8-619.000,None,None,0140881385821,Sepeda Motor,https://www.instagram.com/gracielaevr/,None,https://drive.google.com/drive/folders/1alw9SubNFKSs40YOrz36JlZCGj7T8waC?usp=sharing,"Maag, tipes",2026-01-01,None,2,1,1707279559_ec864cc58f50e8b890d5.jpg,1702002184_d82747bcbd0f2bdab0a7.png
2,3,U00011,LEAP01101XII20,3515135105910001,DANIAR AULIA RIZKI,DANIAR,SURABAYA,1991-05-11,Perempuan,B,Islam,Menikah,"PONDOK TROSOBO INDAH L-5, RT 003 RW 009, TROSOBO, TAMAN, SIDOARJO, JAWA TIMUR, INDONESIA.",GUNUNGANYAR LOR GG 3A NO 9A,WNI,1,1,"MAIN GAME, NONTON",https://www.linkedin.com/in/daniar-aulia-rizki-28b8a4250/,daniar.rizki@leapsurabaya.sch.id,daniar.rizki@leapsurabaya.sch.id,0896-9632-0278,46.770.512.5-603.000,21034278636,0002319622514,1410022279715,Sepeda Motor,@dar.od,tidak ada,https://drive.google.com/drive/u/0/folders/1va7B0PtK57XOZrl-1nvu1n3Wz1jOj75r,PREKLAMSIA,2026-01-01,None,2,0,1692700456_2d6352eb557d734e53b7.jpeg,None
3,4,U00012,LEAP01202III20,3578106705930001,Habibah Melyna,Habibah,Semarang,1993-05-27,Perempuan,AB,Islam,Belum Menikah,Jl Pacar Kembang Vc No 22,Jl Pacar Kembang Vc No 22,WNI,1,None,Mereview berbagai jenis makanan,https://www.linkedin.com/in/habibah-melyna/,habibah.elfiani@leapsurabaya.sch.id,habibah.elfiani@leapsurabaya.sch.id,0857-3093-3317,96.917.411.9-619.000,21034278651,0002999218792,1420018314442,Sepeda Motor,https://instagram.com/habibahmelyna?igshid=MzNlNGNkZWQ4Mg==,None,None,"Alergi udang, pengawet makanan dan micin",2026-01-01,desain grafis,3,1,1686127161_1ec3d11da554fb668e7c.jpg,1702892302_89507e3f2d87fb0dfdee.png
4,5,U00014,LEAP01431VII18,3578035706820005,Laksmi Puspitowardhani,Laksmi,Surabaya,1982-06-17,Perempuan,O,Islam,Belum Menikah,Rungkut Asri Barat XIII no 17,Rungkut Asri Barat XIII no 17,WNI,2,None,"Hiking, Reading, Traveling, Attending Concert",https://www.linkedin.com/in/laksmi-puspitowardhani-ab1a1336,laksmi.p@leapsurabaya.sch.id,laksmi.p@leapsurabaya.sch.id,6282-1399-6681,35.227.276.9-615.000,18088838356,00015384308,1420016807967,Sepeda Motor,https://www.instagram.com/laksmi_purplespace/?hl=en,None,https://drive.google.com/drive/folders/1-7iI4-phQIGBra_G-bekA_2Fuu_-nAiu?usp=drive_link,Liver,2026-01-01,None,3,1,1696338938_2a535db26e3f89919325.jpg,None
5,6,U00015,LEAP01514II11,None,Ika Asriani Yadin,Ika,None,None,Perempuan,None,None,Belum Menikah,None,None,None,None,None,None,None,ikayadin@leapsurabaya.sch.id,None,None,None,None,None,None,None,None,None,None,None,2026-01-01,None,3,1,1694397431_30b88a94a51ff7c8024e.png,None
6,7,U00016,LEAP01619VI17,3524035806960001,"Luluk Fatikah Sari, S.Pd.",Luluk,Lamongan,1996-06-18,Perempuan,None,Islam,Belum Menikah,"RT 001/RW 002, Ngangkrok, Medalem, Modo, Lamongan","Jalan Pabrik Kulit Gg. 2 Gg. Buntu No.24, Jemur Wonosari, Wonocolo, Surabaya",WNI,1,None,Menonton Drama/Film,https://www.linkedin.com/in/luluk-fatikah-sari-a74001252/,luluk.sari@leapsurabaya.sch.id,luluk.sari@leapsurabaya.sch.id,0857-8546-7685,81.269.150.9-645.000,21034278685,0002226118184,1420015479032,Sepeda Motor,https://www.instagram.com/lulukfatikah/,None,https://drive.google.com/drive/folders/1CF3rrcfAQzTvTxqt64FWdYP6meSOesBW?usp=sharing,Tipes dan sakit lambung,2026-01-01,None,3,1,1688370880_b894a9a6a8aa56770eaf.jpeg,1708307211_3e160b7a0d1560febc2c.png
7,8,U00018,LEAP01820IV21,3515165701920002,Ditari Kurnia,Tari,Surabaya,1992-01-17,Perempuan,B,Islam,Belum Menikah,"Tebel Timur 004/006, TEBEL, GEDANGAN, SIDOARJO","Tebel Timur JL. RA Mustika III 004/006 No. 64, TEBEL, GEDANGAN, SIDOARJO",WNI,1,None,Memasak dan membuat kerajinan tangan,ww,admin@gmail.com,None,0813-5966-3659,None,None,None,1410022278949,Sepeda Motor,ww,None,None,Maag dan darah rendah,2026-01-01,None,3,1,1742411840_4c3bd3fb30f609808130.shtml,None
8,9,U00019,LEAP01901VI19,3524094707820003,"Hartatik, S.S.",Tatik,Lamongan,1982-07-07,Perempuan,O,Islam,Menikah,"Kebalan Kulon Rt 10 RW 02, Sekaran - Lamongan",Grand Surya blok A6 - 17 Buduran Sidoarjo,WNI,1,0,Memasak,None,hartatik@leapsurabaya.sch.id,hartatik@leapsurabaya.sch.id,0852-3101-7799,55.860.888.1-645.000,None,None,1420009706010,Sepeda Motor,tati_bj (lupa password tidak bisa masuk ig melalui laptop jadi tidak bisa kasih link),Tati ((lupa password tidak bisa masuk facebook melalui laptop jadi tidak bisa kasih link),https://drive.google.com/drive/folders/1xy6IGdCMFEbMCO127hwFvvH_I45TuZzQ,Tidak ada,2026-01-01,None,2,1,1690430190_e05a6e1833612e00b30a.jpeg,1708311112_ea63d8f1f2fb12dc6dbe.png
9,10,U00020,LEAP02030IV09,3578170506820004,Juni Arlianto,MJ,Surabaya,1982-06-05,Laki laki,B,Islam,Menikah,Amir Mahmud IV No.9-C,Amir Mahmud IV No.9-C,WNI,1,1,None,None,juni.arlianto@leapsurabaya.sch.id,juni.arlianto@leapsurabaya.sch.id,0881-0264-0001,81.277.051.9-615.000,17008686762,None,140015278772,Sepeda Motor,7inchuuriki,None,https://drive.google.com/drive/folders/1-ZWjsg38cDKBwBmUkYDLqsdCWkZrsq8V?usp=sharing,None,2026-01-01,None,2,1,1688629580_4df06718a9d1efc1946a.jpeg,None
10,11,U00023,LEAP02301X19,3578035305910002,Titi Hapsari,Titi,Surabaya,1991-05-13,Perempuan,O,Islam,Menikah,Rungkut Asri Barat XIII-17,Rungkut Asri Barat XIII-17,WNI,3,0,Main Game,https://www.linkedin.com/in/titi-hapsari-retnaningtias/,titi.hapsari@leapsurabaya.sch.id,titi.hapsari@leapsurabaya.sch.id,0822-4516-6547,86.802.833.3-615.000,21034278669,0000102317062,1420017951251,Sepeda Motor,https://www.instagram.com/titihapsarir,None,https://drive.google.com/drive/folders/1k266j11p7CTcHciFGyrVpbHOISOC5dki?usp=sharing,"Maag, Patah Tulang, Sinusitis",2026-01-01,None,3,1,1727774521_de1ee7419b75c6523475.png,None
11,12,U00026,LEAP02602VIII21,3578084710960004,"Qorin Rahmaniyah, S.Pd.",Qo,Surabaya,1996-10-07,Perempuan,O,Islam,Belum Menikah,JL. Gubeng Kertajaya IX D No. 6,JL. Gubeng Kertajaya IX D No. 6,WNI,1,0,"Makan, Gambar, Uji coba makanan",https://id.linkedin.com/in/qorinrhmnyh,qorin.rahmaniah@leapsurabaya.sch.id,qorin.rahmaniah@leapsurabaya.sch.id,0882-1710-5936,90.493.623.4-606.000,21056548478,0001880401408,1420020131214,Sepeda Motor,https://www.instagram.com/_cmdt/,https://m.facebook.com/QorinR/,https://drive.google.com/drive/folders/1or0AUFoMimPSWW1hTdqwMDXaZs9oLBEr?usp=sharing,"Demam berdarah, tumor",2026-01-01,None,3,1,1694500023_799059f427489e12a9e7.png,1708306240_0064c7d03c77638eb889.png
12,13,U00027,LEAP02715VI23,43656,Test,fgsxd,fgb,2023-06-27,Perempuan,None,None,Belum Menikah,dgfhj,gfhdj,None,1,None,fjy,kjuhm,test@gmail.com,None,4324-3546-577_,None,None,None,353,None,kgm,None,None,jgh,2026-01-01,None,2,1,1686800811_656587646951ad5ec76e.jpg,None
13,14,U00028,LEAP02801VI23,None,pengajar,pengajar,None,None,None,None,None,Belum Menikah,None,None,None,None,None,None,None,pengajar@gmail.com,None,None,None,None,None,None,None,None,None,None,None,2026-01-01,None,3,1,None,None
14,15,U00030,LEAP03027VI23,1234567891011121,Akun Data PPDK,adminppdk,surabaya,2024-04-01,Perempuan,None,None,Belum Menikah,None,None,None,None,None,None,None,data@gmail.com,None,0812-3457-890_,None,None,None,12345678985,None,None,None,None,--,2026-01-01,None,None,1,None,None
15,16,U00031,LEAP03108VI18,3524205306950001,"Eka Nur Wahyuni, S. Pd.",Yuni,Gresik,1995-06-13,Perempuan,None,Islam,Belum Menikah,Desa Pengangsalan RT 03 RW 02 Kecamatan Kalitengah Lamongan,"Pabrik Kulit Gang 2 Gang Buntu no. 24 Jemursari, Surabaya",WNI,1,None,Mendengarkan musik,Belum,eka.wahyuni@leapsurabaya.sch.id,eka.wahyuni@leapsurabaya.sch.id,0813-1347-1713,42.825.961.8-608.000,None,0002211312025,EKA NUR WAHYUNI Bank Mandiri 1420016380346,Sepeda Motor,https://instagram.com/ekanurwahyuni13?igshid=MzNlNGNkZWQ4Mg==,None,https://drive.google.com/drive/folders/12vXsyitqeyGazttmlQI9OFkXYM_x-zob,Perna sakit gigi dan maag,2026-01-01,None,None,1,1688371516_f8e3cb495a6602957e96.jpg,None
16,17,U00032,LEAP03202I23,3515146212940001,"Getari Adyagarini, M.Pd",GETARI,MADIUN,1994-12-22,Perempuan,O,Islam,Belum Menikah,"Jl. Ketapang III, RT 04, RW 02, Ds. Suko, Sukodono, Sidoarjo","Jl. Ketapang III, RT 04, RW 02, Ds. Suko, Sukodono, Sidoarjo",WNI,1,None,"I don't have hobbies, I have moods",https://www.linkedin.com/in/getari-adyagarini-071598258?trk=contact-info,getari@leapsurabaya.sch.id,getari@leapsurabaya.sch.id,0878-5668-0404,95.824.727.2-603.000,None,0000102024764,1410023228554,Mobil,getari.adya,None,https://drive.google.com/drive/folders/1xAhqwJ3tmWN3kQQGS4YVIa4prG9RscxD?usp=sharing,Tidak ada,2026-01-01,None,None,0,1688369673_889db0f1267d89fe7ae4.jpeg,1708353208_d07b06675d1e5fa23383.png
17,18,U00033,LEAP03305VIII22,3518054105000002,"Maria Florencia Erica Susanto, A.Md.",Erica,Surabaya,2000-05-18,Perempuan,O,Katolik,Belum Menikah,Jl. M Yusuf RT 012 RW 003 Kel. Kecubung Kec. Pace,Perumahan Grand Eastern JL. Taman Timur Sukolilo II NO. 18 Blok AE-2,WNI,1,None,Nonton Drama & Scroll Tiktok,https://www.linkedin.com/in/maria-florencia-erica-susanto-81a900227,ericasusanto@leapsurabaya.sch.id,ericasusanto@leapsurabaya.sch.id,0851-5721-7422,60.469.638.5-615.000,23182511560,0002479768389,140020550777,Sepeda Motor,https://instagram.com/ericachouw,None,https://drive.google.com/drive/folders/1BsoRjVlW0QHOkAD-npM175jsOdBErdYl?usp=sharing,Patah tulang kaki kanan,2026-01-01,None,None,1,1688370640_434abe3fd75a3d6709f8.jpeg,1708324727_7d2882c04c6ff75ad399.png
18,19,U00034,LEAP03416II22,3578256604800002,"Mieke Puspita, S.Pd",Mieke,Malang,1980-04-26,Perempuan,O+,Katolik,Menikah,Perum Green Lake Wonorejo Timur Baru XVII H5/26,Perum Green Lake Wonorejo Timur Baru XVII H5/26,WNI,1,1,"Membaca, Menulis, Pergi pergi :P",https://www.linkedin.com/in/mieke-puspita-b01175259,miekepuspita@leapsurabaya.sch.id,miekepuspita@leapsurabaya.sch.id,0838-4989-5079,47.962.870.3-615.000,35782566048,0001536484331,1420020132329,Sepeda Motor,https://instagram.com/miekepuspita?igshid=ZDc4ODBmNjlmNQ==,https://www.facebook.com/mieke.puspita.7?mibextid=ZbWKwL,https://drive.google.com/drive/folders/10QGgWRKucYxs5RfV-OGgxc3pplpi7hrK?usp=sharing,bapil,2026-01-01,None,None,1,1688370596_5d157f2a824cbfffc9c0.jpg,1708658996_306c792c8c264fa46529.png
19,20,U00035,LEAP03507VIII12,3578256602930001,"Miftakhul Jannah, S.Pd",Tata,Magelang,1993-02-26,Perempuan,B,Islam,Menikah,Jl. Amir Mahmud IV 9-C,Permata Kwangsan Residence C1-10,WNI,1,1,"Memasak, make up, Jalan-jalan",None,miftakhul.jannah@leapsurabaya.sch.id,Miftakhul.jannah @leapsurabaya.sch.id,0881-0264-0002,None,17008687224,0001908364386,1420015278772,Sepeda Motor,miptha__,None,https://drive.google.com/drive/folders/1oeKwMA32povscLhSdyCTe6sxJ6DFxDGH?usp=sharing,None,2026-01-01,None,None,1,1690348208_aa0194bbe37e887d04c5.png,1708311420_9f19bdbeef8ddeb7c9dd.png
20,21,U00036,LEAP03602I23,1671070811000012,"Rr. Nisrina Dea Rahma, S.Hum",Dea,Surabaya,2000-11-08,Perempuan,B,Islam,Belum Menikah,"Jl. Pucang Asri I no.11, Kertajaya, Gubeng, Surabaya","Jl. Pucang Asri I no.11, Kertajaya, Gubeng, Surabaya",WNI,1,0,Musik,https://www.linkedin.com/in/rr-nisrina-dea-rahma-3389ba204/,nisrina.dea@leapsurabaya.sch.id,nisrina.dea@leapsurabaya.sch.id,0821-7616-1260,61.902.080.3-606.000,23074206378,0001107009641,1420016746702,Transportasi Umum,www.instagram.com/ndearhm,0,https://drive.google.com/drive/folders/1GZ6DYfo-qGvBa9bONymUVqTjM20i6N5A?usp=sharing,0,2026-01-01,None,None,0,1688370707_4f82feba07d331ac440f.jpg,1708311115_cd2260deb2d58d4146b1.png
21,22,U00037,LEAP03704VII23,3523176705990001,Siti Uswatun Khasanah,Uswa,Tuban,1999-05-27,Perempuan,None,Islam,Belum Menikah,"Dusun Sisir, RT 04, RW 05, Desa Kedungsoko, Plumpang, Tuban","Margorejo, Wonocolo",WNI,2,None,"Mendengarkan Musik, Membaca",None,siti.uswatun@leapsurabaya.sch.id,siti.uswatun@leapsurabaya.sch.id,0857-4595-2525,61.719.186.1-648.000,None,None,1420021927123,Sepeda Motor,None,None,https://drive.google.com/drive/folders/1I775kRo3-5i1EfeslG6ub0zfIsNgf61I?usp=sharing,None,2026-01-01,None,None,0,1688372130_e01ff4f038b7bae7029d.jpeg,None
22,23,U00038,LEAP03807VI11,3522146808900002,"Rini Budi Rahayu, S.Pd.",Rini,Bojonegoro,1990-08-28,Perempuan,B,Islam,Menikah,Ds. Klampok No.5 Kec. Kapas Kab. Bojonegoro,Perumahan Sentra Point Blok AD No.21 Surabaya,WNI,4,1,"membaca buku fiksi, menonton film",https://www.linkedin.com/in/rini-rahayu-91b7b1259/,rini.rahayu@leapsurabaya.sch.id,rini.rahayu@leapsurabaya.sch.id,0851-6314-1616,42.366.046.8-615.000,17008685640,0003003442593,1420015505729,Sepeda Motor,https://www.instagram.com/rini.cy/,None,https://drive.google.com/drive/folders/1HIhzTwz_akP85pFjnw4wHNnS-VK8jLI6?usp=sharing,None,2026-01-01,None,None,1,1688370886_98f7bfba3590ca021bd4.jpg,1707990713_4e97cffbee1938a3c5c0.png
23,24,U00040,LEAP04004VII23,3525011107855000,"Agung Wijayanto, S.T.",Agung,Gresik,1985-07-11,Laki laki,None,None,Belum Menikah,"Gresik, Kec. Dukun, Des. Petiyintunggal 001/001",Asem Payung I/25,WNI,None,None,Reading,None,agung.wijayanto@leapsurabaya.sch.id,agungwijayanto1107@gmail.com,0831-1527-0222,None,None,None,1780000459418,Sepeda Motor,https://instagram.com/agungwijayanto_ec?igshid=MzNlNGNkZWQ4Mg==,https://www.facebook.com/profile.php?id=100009927274040&mibextid=ZbWKwL,https://drive.google.com/folderview?id=1JScNiC-Vt51o1nfW-cB-9ivY3EEzjoPO,None,2026-01-01,None,None,1,1690477143_9c6782184cac165c2b0f.jpeg,1712272386_b9becdba820e59218d87.png
24,25,U00041,LEAP04125III23,3578246111990003,Vivi Pramitha Wulandari,Vivi,Surabaya,1999-11-21,Perempuan,B,Islam,Belum Menikah,Jl. Kutisari Utara II D/17 d,Jl. Kutisari Indah Barat IX No. 11,WNI,1,None,"Menggambar, mewarnai, bersepda, mendengarkan musik",viviwulandari,vivi.wulandari@leapsurabaya.sch.id,None,0812-1722-2294,40.206.847.2-615.000,None,None,014001234634830,Sepeda Motor,@_viviwulandari,None,https://drive.google.com/drive/folders/1jC7Xp9bZ3TS6WvO4FYrOogVhHEzwVBPF?usp=sharing,Tidak memiliki riwayat penyakit,2026-01-01,None,None,1,1688711260_556a4a91325635c55a1a.jpg,None
25,26,U00042,LEAP04225III23,3516154706990003,Cantika Swasti Sumarsono Putri,Ica,Mojokerto,1999-06-07,Perempuan,O,Islam,Belum Menikah,"Jompong, Mojokerto","Jalan Kutisari Utara 1 No. 54, Tenggilis Mejoyo, Surabaya",WNI,2,None,"menonton series/ film, karaoke, jalan-jalan",www.linkedin.com/in/cantika-swasti,cantikaswasti76@gmail.com,None,0858-0626-8098,62.655.312.7-615.000,None,0002611267672,014,Sepeda Motor,www.instagram.com/cantikaswasti/,None,None,"Cacar, flu",2026-01-01,None,None,0,1688701716_c0099248b9cea8e57e8b.png,None
26,27,U00043,LEAP04301VIII23,3504160901970002,Trio Fajar Cahyanto,Trio,Tulungagung,1997-01-09,Laki laki,O+,Islam,Belum Menikah,"Dsn, Sawo RT/RW 007/002, Ds. Sawo, Kec. Campurdarat, Kab. Tulungagung","Jl. Keputih Makam Blok D No.5, Keputih, Sukolilo, Surabaya",WNI,3,None,Menonton Anime dan Olahraga,Tidak Ada,generalaffair@gmail.com,staffga@leapsurabaya.sch.id,0878-8306-175_,62.703.897.9-629.000,21012951303,0000666642172,0140481790254,Sepeda Motor,https://instagram.com/_triofajar?utm_source=qr&igshid=OGU0MmVlOWVjOQ==,https://www.facebook.com/waluyondoko?mibextid=ZbWKwL,https://drive.google.com/drive/folders/1hUPWYSsUT7vP8In6h_2x-_mPYuAdADVO?usp=sharing,Tidak Ada (100% Sehat),2026-01-01,None,None,1,1694501101_eb7a9452f5d7069e2d05.jpeg,None
27,28,U00044,LEAP04402X23,3526014802900001,Muifatul Febriani,Ifa,Bangkalan,1990-02-08,Perempuan,B,Islam,Menikah,Jl. KH. Kholil V No.49B Demangan Bangkalan,Jl. KH. Kholil V No.49B Demangan Bangkalan,WNI,1,2,Travelling,linkedin.com/in/muifatul-febriani-5840451ab,muifatul@leapsurabaya.sch.id,None,0819-3932-0162,None,None,None,1400018055013,Sepeda Motor,@muifatul,None,None,Tidak Ada,2026-01-01,None,None,0,1697605800_1c209604feebb43aea57.jpeg,1708938634_e0891560dfe70ac20cdd.png
28,29,U00046,LEAP04601X23,None,sosialmedia1,sosmed,None,None,None,None,None,Belum Menikah,None,None,None,None,None,None,None,sosialmedia1@gmail.com,None,None,None,None,None,None,None,None,None,None,None,2026-01-01,None,None,1,None,None
29,30,U00047,LEAP04701XII23,3575021903990005,Muhamad Haykal Roziqi,Haykal,Kota Pasuruan,1999-03-19,Laki laki,None,None,Belum Menikah,JL.KH.ACHMAD DAHLAN XIII/7,JL.KH.ACHMAD DAHLAN XIII/3,WNI,1,None,Traveling,Haykal Roziqi,Muhammad.haykal@leapsurabaya.sch.id,Muhammad.haykal@leapsurabaya.sch.id,0878-8799-2703,None,None,0001197706397,5360700017684,Motor Pribadi,haykalroziqi,Haikal Roziki,https://drive.google.com/drive/folders/1BKtcXkLyr7kf4DOCehJRKqpO5AveOj-p?usp=drive_link,None,2026-01-01,None,None,0,1701413223_0ad0b6e85cf61cb96a29.jpeg,None
30,31,U00048,LEAP04821XII23,None,"Yerly A Datu, S.Pd, M.Pd, CT.ACT, C.PS",Yerly,None,None,None,None,None,Belum Menikah,None,None,None,None,None,None,None,pengajar1@leapsurabaya.sch.id,None,None,None,None,None,None,None,None,None,None,None,2026-01-01,None,None,1,None,1705635412_63253866271a8b6fe62c.png
31,32,U00049,LEAP04901II24,3519136702980002,Ana Puspita,Ana,Madiun,2024-02-27,Perempuan,B,Islam,Menikah,"Jl. Kav Mentari 02 no.45 , Tambak Rejo, Waru, Sidoarjo","Jl. Kav Mentari 02 no.45 , Tambak Rejo, Waru, Sidoarjo",WNI,1,0,Olahraga dan Menggambar,https://www.linkedin.com/in/ana-puspita-529419222?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app,ana.puspita@leapsurabaya.sch.id,Ana.puspita@leapsurabaya.sch.id,0812-3128-4882,None,None,None,0142160829578,Sepeda Motor,https://www.instagram.com/anasta.id?igsh=MXdlZXV3d2RqMnJ0dQ==,None,None,Gerd,2026-01-01,None,None,0,1707216719_23e8d54bc0ee23db70f7.jpeg,None
32,33,U00050,LEAP05019II24,3578034505870001,"Peni Puspa Indarwati, S.S.",Peni,Surabaya,1987-05-05,Perempuan,O,Islam,Belum Menikah,Penjaringansari Baru I-A/Kav.5 Rungkut Surabaya,Penjaringansari Baru I-A/Kav.5 Rungkut Surabaya,WNI,1,None,"membaca, menonton film",https://www.linkedin.com/in/peni-puspa-2793151a8/,peni.indarwati@leapsurabaya.sch.id,peni.indarwati@leapsurabaya.sch.id,0812-1635-3322,35.780.345.0-587.000,None,0001849925428,0146750644161,Sepeda Motor,https://www.instagram.com/puepuen55/?hl=en,None,https://drive.google.com/file/d/1CXkd0zUfmQsZidPinfLE7Lh1q1iTxUfJ/view?usp=drive_link,None,2026-01-01,None,None,1,1707113938_3f8f1d86bc8fa7c21626.jpg,1707119676_d6c58fb6bb36ffc05cbc.png
33,34,U00052,LEAP05202V24,3578244602850001,Ratna Febrianti,Ratna,Surabaya,1985-02-06,Perempuan,O,None,Belum Menikah,Kutisari Indah Utara 7/20 Surabaya,Kutisari Indah Utara 7/20 Surabaya,WNI,3,None,Jalan-jalan,https://www.linkedin.com/in/ratna-febrianti-b71382301,febrianti.ratna@leapsurabaya.sch.id,febrianti.ratna@leapsurabaya.sch.id,0812-3222-789_,34.003.500.5-615.000,None,2271484124,0148221109341,Sepeda Motor,https://www.instagram.com/ratnabrail/?hl=en,None,https://drive.google.com/drive/folders/1KQugWew6s7u3K_Fho2WhPaZRa_f3QX7H?usp=sharing,flu,2026-01-01,None,None,1,1716221191_e94b670798bb2696d03d.jpg,None
34,35,U00053,LEAP05301VII24,None,Ann Clariss Agbalog Amora,Ann,None,None,None,None,None,Belum Menikah,None,None,None,None,None,None,None,edgetutor1@leapsurabaya.sch.id,None,None,None,None,None,None,None,None,None,None,None,2026-01-01,None,None,0,1716522842_b8a66f29051db6e6a30f.png,None

In [33]:
import pandas as pd
import pickle

print("================================================================================")
print(" 📦 MEMBUAT & MENGEKSPOR KAMUS SAKTI RELASI KARYAWAN (MAPPING TABLE) 📦 ")
print("================================================================================")

df_karyawan_mapping_table = pd.DataFrame()

# 1. ID Karyawan Baru (Integer Auto-Increment)
df_karyawan_mapping_table['id_karyawan'] = df_new['karyawan']['id_karyawan'].astype('Int64')

# 2. Kode Karyawan Baru (Hasil dari pemindahan NIK/ID lama)
df_karyawan_mapping_table['kode_karyawan'] = df_new['karyawan']['kode_karyawan'].astype(str).str.strip()

# 3. ID Karyawan Lama (Varchar Mentah Langsung dari df_old) -> INI YANG DIPERBAIKI (TIDAK PAKAI UNDERSCORE)
df_karyawan_mapping_table['id_karyawan_lama'] = id_karyawan_lama.astype(str).str.strip()

# 4. ID User (Jika diperlukan untuk cross-check)
df_karyawan_mapping_table['id_user'] = df_new['karyawan']['id_user'].astype(str).str.strip()

# Tampilkan preview tabel pemetaan 
print("--- Preview Kamus Sakti Pemetaan Karyawan ---")
df_karyawan_mapping_table.info()
display(df_karyawan_mapping_table.head())

# Ekspor tabel pemetaan ini menjadi file pickle (.pkl)
mapping_file_name = 'mapping_id_karyawan.pkl'
with open(mapping_file_name, 'wb') as f:
    pickle.dump(df_karyawan_mapping_table, f)

print(f"\n💾 🎉 BERHASIL! Kamus sakti berhasil diekspor menjadi '{mapping_file_name}'!")

================================================================================
 📦 MEMBUAT & MENGEKSPOR KAMUS SAKTI RELASI KARYAWAN (MAPPING TABLE) 📦
================================================================================
--- Preview Kamus Sakti Pemetaan Karyawan ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_karyawan       52 non-null     Int64
 1   kode_karyawan     52 non-null     object
 2   id_karyawan_lama  52 non-null     object
 3   id_user           52 non-null     object
dtypes: Int64(1), object(3)
memory usage: 1.8+ KB

   id_karyawan   kode_karyawan id_karyawan_lama id_user
0            1   LEAP00102VI23      LEAP001VI02  U00001
1            2  LEAP00313III23   LEAP003III2023  U00003
2            3  LEAP01101XII20     LEAP011XII01  U00011
3            4  LEAP01202III20     LEAP012III02  U00012
4            5  LEAP01431VII18     LEAP014VII31  U00014

💾 🎉 BERHASIL! Kamus sakti berhasil diekspor menjadi 'mapping_id_karyawan.pkl'!

# Fixing Tabel keluarga_karyawan

In [34]:
import pandas as pd
import numpy as np

# ================================================================================
# 🚀 FASE 2 - STEP 2: REKAYASA RELASI & NORMALISASI KELUARGA KARYAWAN 🚀
# ================================================================================

# 1. Persiapkan mapping id_karyawan asli (ID Auto-Increment Baru) dari df_new['karyawan']
# Kita ambil jembatan id_user dan id_karyawan barunya
df_karyawan_map = df_new['karyawan'][['id_user', 'id_karyawan']].copy()

# 2. Gabungkan id_karyawan baru ke dalam df_old['keluarga'] dengan mengawinkan id_user lewat idusers lama
df_keluarga_source = df_old['keluarga'].merge(
    df_karyawan_map, 
    left_on='idusers', 
    right_on='id_user', 
    how='left'
)

# 3. DEFINISI PEMETAAN KOLOM (STRUKTUR LAMA DIADAPTASIKAN KE DB_FUTURE)
keluarga_mapping = {
    'id_keluarga': 'idkeluarga_ghaib',    # 🎯 BARU: Diarahkan ke kolom ghaib karena di MySQL baru sudah AUTO_INCREMENT
    'id_karyawan': 'id_karyawan',         # 🎯 BARU: Mengunci ID Karyawan Baru hasil perkawinan merge di atas
    'hubungan_keluarga': 'hubungan',
    'nama_lengkap': 'namalengkap',
    'pekerjaan': 'pekerjaan',
    'nomor_hp': 'hp'
}

# 3.1. NORMALISASI HUBUNGAN KELUARGA (100% AKURAT MENGGUNAKAN KAMUS ORIGINAL CIMUT)
hubungan_map = {
    'Ibu Kandung': 'Ibu', 'Ibu': 'Ibu', 
    'Ayah Kandung': 'Ayah', 'Ayah': 'Ayah', 'Bapak': 'Ayah',
    'Suami Tercintah': 'Suami', 'Suami': 'Suami', 'suami': 'Suami', 'SUAMI': 'Suami',
    'Istri': 'Istri', 'istri': 'Istri', 'ISTRI': 'Istri',
    'Adik Perempuan': 'Adik', 'Adik Laki-laki': 'Adik', 'Adik kandung': 'Adik', 'Adik': 'Adik', 'Adek Kandung': 'Adik', 'adek': 'Adik', 'adik': 'Adik',
    'Kakak Kandung': 'Kakak', 'Kaka Kandung Pertama': 'Kakak', 'Kaka Kandung Kedua': 'Kakak', 'Kakak': 'Kakak', 'kakak': 'Kakak',
    'anak': 'Anak', 'Anak': 'Anak',
    'Saudra Kandung': 'Saudara', 'Saudara Kandung': 'Saudara', 'Saudara': 'Saudara', 'Orang Tua': 'Ibu'
}

# 4. PROSES MIGRASI MENGGUNAKAN LOOPING POLA ORIGINAL CIMUT
df_keluarga_new = pd.DataFrame()
for target_col, source_col in keluarga_mapping.items():
    if source_col in df_keluarga_source.columns:
        if target_col == 'hubungan_keluarga':
            df_keluarga_new[target_col] = df_keluarga_source[source_col].map(hubungan_map).fillna('Saudara')
        else:
            df_keluarga_new[target_col] = df_keluarga_source[source_col]
    else:
        # 🎯 BARU: Jika targetnya id_keluarga, otomatis diset None agar diisi AUTO_INCREMENT oleh MySQL
        df_keluarga_new[target_col] = None

# 5. SIMPAN KE df_new['keluarga_karyawan'] DAN MEMBERSIHKAN STRING KOSONG
df_new['keluarga_karyawan'] = df_keluarga_new.replace(['', '-'], None)

# 🎯 BARU: Paksa tipe data id_karyawan menjadi Int64 bulat murni (Menjinakkan Float .0)
df_new['keluarga_karyawan']['id_karyawan'] = pd.to_numeric(df_new['keluarga_karyawan']['id_karyawan'], errors='coerce').astype('Int64')

# 🎯 BARU: Final Cleanup agar objek NaN/NaT diratakan menjadi None yang ramah dengan mysql-connector
df_new['keluarga_karyawan'] = df_new['keluarga_karyawan'].astype(object).where(pd.notnull(df_new['keluarga_karyawan']), None)

# 6. PRINT METADATA OUTPUT SEPERTI LOG LAMA KAMU
print(f"✓ Berhasil memindahkan {len(df_new['keluarga_karyawan'])} data keluarga")
display(df_new['keluarga_karyawan'])
print("\n--- Value Counts Hubungan Keluarga ---")
display(df_new['keluarga_karyawan']['hubungan_keluarga'].value_counts())
df_new['keluarga_karyawan'].info()

✓ Berhasil memindahkan 67 data keluarga

,id_keluarga,id_karyawan,hubungan_keluarga,nama_lengkap,pekerjaan,nomor_hp
0,None,2,Ibu,Nur Fatmawati,Wiraswasta,081234477137
1,None,9,Suami,Fathul Kirom,Suami,0852-3101-7799
2,None,12,Ayah,"Suwandi, S.Pd.",Guru Matematika SMAN 17 Surabaya,087853591616
3,None,12,Ibu,"Ir. Hj. Erhasyati Islamiyah, M.M.",(Pensiun) Guru Biologi SMA Muhammadiyah 2 Surabaya,08179365966
4,None,3,Suami,JONATHAN O'DRISCOLL,TIDAK BEKERJA,089696320278
5,None,12,Adik,Fahada Akbariyah,Pekerja Laboratoriumm RS Soewandhi,088801762951
6,None,12,Adik,Rafi Arif Billah,Mahasiswa S1 Manajemen Undika,08563002290
7,None,18,Ayah,Herrie Susanto,Wiraswasta,08123429138
8,None,18,Ibu,Juliani,tidak bekerja,081911541719
9,None,17,Saudara,AGUS DJOKO PRANOWO,KARYAWAN SWASTA,087852999236
10,None,19,Suami,Yerly A. Datu,Dosen,082146921559
11,None,19,Anak,Yonathan Yerly Datu,mahasiswa,083832072043
12,None,23,Suami,Chusnul Yakin,Wiraswasta,085158789353
13,None,20,Suami,Juni Arlianto,Pegawai Swasta,0881026400010
14,None,21,Ayah,"R. Ponco Suryono, SH. MM.",TNI-AD,085232001833
15,None,21,Ibu,"Sri Wahyuni Andajani, SH",None,085230218640
16,None,21,Adik,R. Sulthan Rafi Athallah,None,None
17,None,10,Istri,Miftakhul Jannah,Pengajar/ Guru,0881026400020
18,None,25,Ayah,Sali,Wiraswasta,081217222286
19,None,25,Ibu,Suhartini,Tidak bekerja,081331914377
20,None,5,Adik,Titi Hapsari Retnaningtias,Swasta,082245166547
21,None,7,Ayah,Sariman,Petani,082132967221
22,None,22,Ayah,Sukawan,Petani,None
23,None,22,Ibu,Sumarini,Ibu rumah tangga,None
24,None,10,Anak,Arshaka Keanu Arlianto,None,None
25,None,24,Ayah,Nasripan,Swasta,None
26,None,24,Adik,Nur Asyiah,Admin,085812449976
27,None,6,Suami,Fransiscus Arifin,Dokter PNS,0811375636
28,None,6,Anak,Clarissa Franka Arifin,Pelajar,+62 822-4596-0614
29,None,6,Anak,Agnesia Friska Arifin,Pelajar,+62 851-7169-5123
30,None,27,Saudara,Lifan Gusjianto,Freelance,082334958166
31,None,30,Saudara,M.Fauzi A.S,Staff PMI,082147782070
32,None,30,Saudara,Henny P.A,Reseller lipstik,085732512347
33,None,30,Adik,Naflah zahiyah maharani,SMA,0882009260421
34,None,30,Adik,M.abrizam reynan,TK A,None
35,None,33,Saudara,Suwadji,Wiraswasta,081331089339
36,None,32,Suami,Dhodik Bima Arjiansyah,Streaming,089510510030
37,None,34,Kakak,Sandra Restu Ariyani,Wiraswasta,0817599707
38,None,37,Kakak,Suci Nur Hasanah,Ibu Rumah Tangga,085797184443
39,None,37,Kakak,Siti Fatimah,Ibu Rumah Tangga,087724926657
40,None,37,Adik,Kanza Azzahra,Pelajar,083134684428
41,None,18,Saudara,Stefanus Erico Susanto,Karyawan Swasta,085161776657
42,None,18,Saudara,Giovano Laurentius Evan Susanto,Pelajar,085156506694
43,None,11,Suami,Dimas Sakti Mahardika Putra,Wiraswasta,087853172361
44,None,38,Istri,Nunuk,Ibu Rumah Tanga,085336874050
45,None,41,Suami,M Afghani Wardhana Setiyasa,PNS Pemkot Surabaya,+62 822-3185-5518
46,None,42,Ayah,Nur Hasim,Petani,085343916217
47,None,42,Adik,Arif al-Aziz,Mahasiswa,085655282437
48,None,43,Ibu,Helen Rosdiana Gultom,Guru TK,082233333219
49,None,46,Ayah,Suprayitno,Petani,082234399512
50,None,46,Ibu,Suwati,Petani,082234399512
51,None,46,Adik,Sifa Dwi Meisyahrani,Pelajar,085656504253
52,None,47,Ayah,Sukijan,Wiraswasta,082141452234
53,None,47,Ibu,Sri Ekorini,Ibu Rumah tangga,081249769300
54,None,48,Ayah,Marwito,Petani,081779437967
55,None,48,Ibu,Ayu Aryawati,Ibu Rumah Tangga,0881081081819
56,None,48,Kakak,Erik Aryanto Hidayat,Backend Developer,08551151105
57,None,49,Ayah,Amir,Pengusaha,---
58,None,49,Ibu,Sri Wahyuni,Ibu rumah tangga,087840782568
59,None,36,Ibu,Sylvia Widyastuti,Pekerja swasta,082142995636
60,None,50,Ibu,Siti Rokhani,Kerja di toko kelontong,085775734255
61,None,51,Ibu,Ratri Widorini,School Accounting,+62 822-6433-4296
62,None,51,Ayah,Agung Yuniarti Akhirin,Accounting,+62 813-3022-2722
63,None,51,Saudara,Zakeia Ayra Sinatrya,Mahasiswa,+62 895-3670-88279
64,None,52,Saudara,Nursahid,Tukang,085232118082
65,None,52,Ibu,Isro'ati,karyawan toko,085231063005
66,None,52,Saudara,Ach. Muchndori Lucmana,Staf sarana prasarana,081216216848

--- Value Counts Hubungan Keluarga ---

hubungan_keluarga
Ibu        15
Ayah       13
Adik       10
Saudara    10
Suami       9
Anak        4
Kakak       4
Istri       2
Name: count, dtype: int64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_keluarga        0 non-null      object
 1   id_karyawan        67 non-null     object
 2   hubungan_keluarga  67 non-null     object
 3   nama_lengkap       67 non-null     object
 4   pekerjaan          64 non-null     object
 5   nomor_hp           61 non-null     object
dtypes: object(6)
memory usage: 3.3+ KB

In [35]:
df_new['keluarga_karyawan']['hubungan_keluarga'].value_counts()

hubungan_keluarga
Ibu        15
Ayah       13
Adik       10
Saudara    10
Suami       9
Anak        4
Kakak       4
Istri       2
Name: count, dtype: int64

# Fixing table bidang_kategori, bidang_link.

In [36]:
# ---------------------------------------------------------
# MIGRASI TABEL bidang_kategori
# ---------------------------------------------------------

# 1. Definisi Mapping
bidang_kategori_mapping = {
    'id_bidang_kategori': 'idkatbid',
    'nama_kategori_bidang': 'namakatbid',
    'id_bidang': 'idbidang'
}

# 2. Proses Migrasi
df_bidang_kategori_new = pd.DataFrame()
for target_col, source_col in bidang_kategori_mapping.items():
    if source_col in df_old['bidangkategori'].columns:
        df_bidang_kategori_new[target_col] = df_old['bidangkategori'][source_col]
    else:
        df_bidang_kategori_new[target_col] = None

# 3. Simpan ke df_new
df_new['bidang_kategori'] = df_bidang_kategori_new

print(f"✓ Berhasil memindahkan {len(df_new['bidang_kategori'])} data bidang_kategori")
display(df_new['bidang_kategori'].head())
df_new['bidang_kategori'].info()

✓ Berhasil memindahkan 12 data bidang_kategori

   id_bidang_kategori nama_kategori_bidang  id_bidang
0                   7       Brand Identity          7
1                  13             Training          9
2                  14            Referensi          9
3                  16             Training          8
4                  17             Training         11

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id_bidang_kategori    12 non-null     int64
 1   nama_kategori_bidang  12 non-null     object
 2   id_bidang             12 non-null     int64
dtypes: int64(2), object(1)
memory usage: 420.0+ bytes

In [37]:
# ---------------------------------------------------------
# MIGRASI TABEL bidang_link
# ---------------------------------------------------------

# 1. Definisi Mapping
bidang_link_mapping = {
    'id_bidang_link': 'idformbid',
    'nama_form': 'namaformbid',
    'link_drive': 'link',
    'id_bidang_kategori': 'idkatbid',
    'status_share': 'share'
}

# 2. Proses Migrasi
df_bidang_link_new = pd.DataFrame()
for target_col, source_col in bidang_link_mapping.items():
    if source_col in df_old['bidanglink'].columns:
        if target_col == 'status_share':
            # Convert '0'/'1' or other values to int
            df_bidang_link_new[target_col] = pd.to_numeric(df_old['bidanglink'][source_col], errors='coerce').fillna(0).astype(int)
        else:
            df_bidang_link_new[target_col] = df_old['bidanglink'][source_col]
    else:
        df_bidang_link_new[target_col] = None

# 3. Simpan ke df_new
df_new['bidang_link'] = df_bidang_link_new

print(f"✓ Berhasil memindahkan {len(df_new['bidang_link'])} data bidang_link")
display(df_new['bidang_link'].head())
df_new['bidang_link'].info()

✓ Berhasil memindahkan 7 data bidang_link

,id_bidang_link,nama_form,link_drive,id_bidang_kategori,status_share
0,16,Daftar Training,https://drive.google.com/drive/folders/1BCPhp6eG5mNeWyTZS8i4xHEor-zgeyJu?usp=drive_link,13,0
1,17,Referensi,https://drive.google.com/drive/folders/1Lo6hzugBnuacIyHPF6nef-9BV1O9mnCQ?usp=drive_link,14,0
2,18,Dokumentasi,https://drive.google.com/drive/folders/14ieegP1eR_Vdj-QCOhevVeKR2DOaQ5_w?usp=drive_link,24,0
3,19,List Training,https://drive.google.com/drive/folders/1yivPYk3nJ3XmRZ5Np3S7d30AK3yw14GJ?usp=drive_link,16,0
4,20,Referensi,https://drive.google.com/drive/folders/1ah2G3XtafGmA3B1V01Np8rmv8lZrUmKl?usp=drive_link,19,0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_bidang_link      7 non-null      int64
 1   nama_form           7 non-null      object
 2   link_drive          7 non-null      object
 3   id_bidang_kategori  7 non-null      int64
 4   status_share        7 non-null      int64
dtypes: int64(3), object(2)
memory usage: 412.0+ bytes

In [38]:
# Review the processed data for karyawan table
print("Processed Data for karyawan table:")
display(df_new['karyawan'])

# Review the processed data for keluarga_karyawan table
print("Processed Data for keluarga_karyawan table:")
display(df_new['keluarga_karyawan'])

# Review the processed data for bidang_kategori table
print("Processed Data for bidang_kategori table:")
display(df_new['bidang_kategori'])
display(df_old['bidang'])

# Review the processed data for bidang_link table
print("Processed Data for bidang_link table:")
display(df_new['bidang_link'])

Processed Data for karyawan table:

,id_karyawan,id_user,kode_karyawan,nik_ktp,nama_lengkap,nama_panggilan,tempat_lahir,tanggal_lahir,jenis_kelamin,golongan_darah,agama,status_pernikahan,alamat_ktp,alamat_domisili,kewarganegaraan,anak_ke,jumlah_anak,hobi,akun_linkedin,email_pribadi,email_kantor,nomor_telepon,nomor_npwp,bpjs_ketenagakerjaan,bpjs_kesehatan,nomor_rekening,moda_transportasi,akun_instagram,akun_facebook,link_dokumen_pribadi,riwayat_kesehatan,tanggal_bergabung,keahlian,id_shift,status_aktif,foto_profile,ttd_digital
0,1,U00001,LEAP00102VI23,None,ADMINISTRATOR,ADMINISTRATOR,None,None,Perempuan,None,None,Belum Menikah,None,None,None,None,None,None,None,ditari@leapsurabaya.sch.id,None,None,None,None,None,None,None,None,None,None,None,2026-01-01,None,2,1,logo.png,None
1,2,U00003,LEAP00313III23,3514186411980002,"Graciela Evanda Ronadi, S.Kom.",Graciela,Sidoarjo,1998-11-24,Perempuan,None,Islam,Belum Menikah,"Ranggeh, Gondangwetan, Pasuruan","Lebak Indah Regency B40, Surabaya",WNI,1,None,Membaca,https://www.linkedin.com/in/graciela-evanda-ronadi-b134221a3/?originalSubdomain=id,graciela@leapsurabaya.sch.id,graciela@leapsurabaya.sch.id,0812-3447-7137,53.856.239.8-619.000,None,None,0140881385821,Sepeda Motor,https://www.instagram.com/gracielaevr/,None,https://drive.google.com/drive/folders/1alw9SubNFKSs40YOrz36JlZCGj7T8waC?usp=sharing,"Maag, tipes",2026-01-01,None,2,1,1707279559_ec864cc58f50e8b890d5.jpg,1702002184_d82747bcbd0f2bdab0a7.png
2,3,U00011,LEAP01101XII20,3515135105910001,DANIAR AULIA RIZKI,DANIAR,SURABAYA,1991-05-11,Perempuan,B,Islam,Menikah,"PONDOK TROSOBO INDAH L-5, RT 003 RW 009, TROSOBO, TAMAN, SIDOARJO, JAWA TIMUR, INDONESIA.",GUNUNGANYAR LOR GG 3A NO 9A,WNI,1,1,"MAIN GAME, NONTON",https://www.linkedin.com/in/daniar-aulia-rizki-28b8a4250/,daniar.rizki@leapsurabaya.sch.id,daniar.rizki@leapsurabaya.sch.id,0896-9632-0278,46.770.512.5-603.000,21034278636,0002319622514,1410022279715,Sepeda Motor,@dar.od,tidak ada,https://drive.google.com/drive/u/0/folders/1va7B0PtK57XOZrl-1nvu1n3Wz1jOj75r,PREKLAMSIA,2026-01-01,None,2,0,1692700456_2d6352eb557d734e53b7.jpeg,None
3,4,U00012,LEAP01202III20,3578106705930001,Habibah Melyna,Habibah,Semarang,1993-05-27,Perempuan,AB,Islam,Belum Menikah,Jl Pacar Kembang Vc No 22,Jl Pacar Kembang Vc No 22,WNI,1,None,Mereview berbagai jenis makanan,https://www.linkedin.com/in/habibah-melyna/,habibah.elfiani@leapsurabaya.sch.id,habibah.elfiani@leapsurabaya.sch.id,0857-3093-3317,96.917.411.9-619.000,21034278651,0002999218792,1420018314442,Sepeda Motor,https://instagram.com/habibahmelyna?igshid=MzNlNGNkZWQ4Mg==,None,None,"Alergi udang, pengawet makanan dan micin",2026-01-01,desain grafis,3,1,1686127161_1ec3d11da554fb668e7c.jpg,1702892302_89507e3f2d87fb0dfdee.png
4,5,U00014,LEAP01431VII18,3578035706820005,Laksmi Puspitowardhani,Laksmi,Surabaya,1982-06-17,Perempuan,O,Islam,Belum Menikah,Rungkut Asri Barat XIII no 17,Rungkut Asri Barat XIII no 17,WNI,2,None,"Hiking, Reading, Traveling, Attending Concert",https://www.linkedin.com/in/laksmi-puspitowardhani-ab1a1336,laksmi.p@leapsurabaya.sch.id,laksmi.p@leapsurabaya.sch.id,6282-1399-6681,35.227.276.9-615.000,18088838356,00015384308,1420016807967,Sepeda Motor,https://www.instagram.com/laksmi_purplespace/?hl=en,None,https://drive.google.com/drive/folders/1-7iI4-phQIGBra_G-bekA_2Fuu_-nAiu?usp=drive_link,Liver,2026-01-01,None,3,1,1696338938_2a535db26e3f89919325.jpg,None
5,6,U00015,LEAP01514II11,None,Ika Asriani Yadin,Ika,None,None,Perempuan,None,None,Belum Menikah,None,None,None,None,None,None,None,ikayadin@leapsurabaya.sch.id,None,None,None,None,None,None,None,None,None,None,None,2026-01-01,None,3,1,1694397431_30b88a94a51ff7c8024e.png,None
6,7,U00016,LEAP01619VI17,3524035806960001,"Luluk Fatikah Sari, S.Pd.",Luluk,Lamongan,1996-06-18,Perempuan,None,Islam,Belum Menikah,"RT 001/RW 002, Ngangkrok, Medalem, Modo, Lamongan","Jalan Pabrik Kulit Gg. 2 Gg. Buntu No.24, Jemur Wonosari, Wonocolo, Surabaya",WNI,1,None,Menonton Drama/Film,https://www.linkedin.com/in/luluk-fatikah-sari-a74001252/,luluk.sari@leapsurabaya.sch.id,luluk.sari@leapsurabaya.sch.id,0857-8546-7685,81.269.150.9-645.000,21034278685,0002226118184,1420015479032,Sepeda Motor,https://www.instagram.com/lulukfatikah/,None,https://drive.google.com/drive/folders/1CF3rrcfAQzTvTxqt64FWdYP6meSOesBW?usp=sharing,Tipes dan sakit lambung,2026-01-01,None,3,1,1688370880_b894a9a6a8aa56770eaf.jpeg,1708307211_3e160b7a0d1560febc2c.png
7,8,U00018,LEAP01820IV21,3515165701920002,Ditari Kurnia,Tari,Surabaya,1992-01-17,Perempuan,B,Islam,Belum Menikah,"Tebel Timur 004/006, TEBEL, GEDANGAN, SIDOARJO","Tebel Timur JL. RA Mustika III 004/006 No. 64, TEBEL, GEDANGAN, SIDOARJO",WNI,1,None,Memasak dan membuat kerajinan tangan,ww,admin@gmail.com,None,0813-5966-3659,None,None,None,1410022278949,Sepeda Motor,ww,None,None,Maag dan darah rendah,2026-01-01,None,3,1,1742411840_4c3bd3fb30f609808130.shtml,None
8,9,U00019,LEAP01901VI19,3524094707820003,"Hartatik, S.S.",Tatik,Lamongan,1982-07-07,Perempuan,O,Islam,Menikah,"Kebalan Kulon Rt 10 RW 02, Sekaran - Lamongan",Grand Surya blok A6 - 17 Buduran Sidoarjo,WNI,1,0,Memasak,None,hartatik@leapsurabaya.sch.id,hartatik@leapsurabaya.sch.id,0852-3101-7799,55.860.888.1-645.000,None,None,1420009706010,Sepeda Motor,tati_bj (lupa password tidak bisa masuk ig melalui laptop jadi tidak bisa kasih link),Tati ((lupa password tidak bisa masuk facebook melalui laptop jadi tidak bisa kasih link),https://drive.google.com/drive/folders/1xy6IGdCMFEbMCO127hwFvvH_I45TuZzQ,Tidak ada,2026-01-01,None,2,1,1690430190_e05a6e1833612e00b30a.jpeg,1708311112_ea63d8f1f2fb12dc6dbe.png
9,10,U00020,LEAP02030IV09,3578170506820004,Juni Arlianto,MJ,Surabaya,1982-06-05,Laki laki,B,Islam,Menikah,Amir Mahmud IV No.9-C,Amir Mahmud IV No.9-C,WNI,1,1,None,None,juni.arlianto@leapsurabaya.sch.id,juni.arlianto@leapsurabaya.sch.id,0881-0264-0001,81.277.051.9-615.000,17008686762,None,140015278772,Sepeda Motor,7inchuuriki,None,https://drive.google.com/drive/folders/1-ZWjsg38cDKBwBmUkYDLqsdCWkZrsq8V?usp=sharing,None,2026-01-01,None,2,1,1688629580_4df06718a9d1efc1946a.jpeg,None
10,11,U00023,LEAP02301X19,3578035305910002,Titi Hapsari,Titi,Surabaya,1991-05-13,Perempuan,O,Islam,Menikah,Rungkut Asri Barat XIII-17,Rungkut Asri Barat XIII-17,WNI,3,0,Main Game,https://www.linkedin.com/in/titi-hapsari-retnaningtias/,titi.hapsari@leapsurabaya.sch.id,titi.hapsari@leapsurabaya.sch.id,0822-4516-6547,86.802.833.3-615.000,21034278669,0000102317062,1420017951251,Sepeda Motor,https://www.instagram.com/titihapsarir,None,https://drive.google.com/drive/folders/1k266j11p7CTcHciFGyrVpbHOISOC5dki?usp=sharing,"Maag, Patah Tulang, Sinusitis",2026-01-01,None,3,1,1727774521_de1ee7419b75c6523475.png,None
11,12,U00026,LEAP02602VIII21,3578084710960004,"Qorin Rahmaniyah, S.Pd.",Qo,Surabaya,1996-10-07,Perempuan,O,Islam,Belum Menikah,JL. Gubeng Kertajaya IX D No. 6,JL. Gubeng Kertajaya IX D No. 6,WNI,1,0,"Makan, Gambar, Uji coba makanan",https://id.linkedin.com/in/qorinrhmnyh,qorin.rahmaniah@leapsurabaya.sch.id,qorin.rahmaniah@leapsurabaya.sch.id,0882-1710-5936,90.493.623.4-606.000,21056548478,0001880401408,1420020131214,Sepeda Motor,https://www.instagram.com/_cmdt/,https://m.facebook.com/QorinR/,https://drive.google.com/drive/folders/1or0AUFoMimPSWW1hTdqwMDXaZs9oLBEr?usp=sharing,"Demam berdarah, tumor",2026-01-01,None,3,1,1694500023_799059f427489e12a9e7.png,1708306240_0064c7d03c77638eb889.png
12,13,U00027,LEAP02715VI23,43656,Test,fgsxd,fgb,2023-06-27,Perempuan,None,None,Belum Menikah,dgfhj,gfhdj,None,1,None,fjy,kjuhm,test@gmail.com,None,4324-3546-577_,None,None,None,353,None,kgm,None,None,jgh,2026-01-01,None,2,1,1686800811_656587646951ad5ec76e.jpg,None
13,14,U00028,LEAP02801VI23,None,pengajar,pengajar,None,None,None,None,None,Belum Menikah,None,None,None,None,None,None,None,pengajar@gmail.com,None,None,None,None,None,None,None,None,None,None,None,2026-01-01,None,3,1,None,None
14,15,U00030,LEAP03027VI23,1234567891011121,Akun Data PPDK,adminppdk,surabaya,2024-04-01,Perempuan,None,None,Belum Menikah,None,None,None,None,None,None,None,data@gmail.com,None,0812-3457-890_,None,None,None,12345678985,None,None,None,None,--,2026-01-01,None,None,1,None,None
15,16,U00031,LEAP03108VI18,3524205306950001,"Eka Nur Wahyuni, S. Pd.",Yuni,Gresik,1995-06-13,Perempuan,None,Islam,Belum Menikah,Desa Pengangsalan RT 03 RW 02 Kecamatan Kalitengah Lamongan,"Pabrik Kulit Gang 2 Gang Buntu no. 24 Jemursari, Surabaya",WNI,1,None,Mendengarkan musik,Belum,eka.wahyuni@leapsurabaya.sch.id,eka.wahyuni@leapsurabaya.sch.id,0813-1347-1713,42.825.961.8-608.000,None,0002211312025,EKA NUR WAHYUNI Bank Mandiri 1420016380346,Sepeda Motor,https://instagram.com/ekanurwahyuni13?igshid=MzNlNGNkZWQ4Mg==,None,https://drive.google.com/drive/folders/12vXsyitqeyGazttmlQI9OFkXYM_x-zob,Perna sakit gigi dan maag,2026-01-01,None,None,1,1688371516_f8e3cb495a6602957e96.jpg,None
16,17,U00032,LEAP03202I23,3515146212940001,"Getari Adyagarini, M.Pd",GETARI,MADIUN,1994-12-22,Perempuan,O,Islam,Belum Menikah,"Jl. Ketapang III, RT 04, RW 02, Ds. Suko, Sukodono, Sidoarjo","Jl. Ketapang III, RT 04, RW 02, Ds. Suko, Sukodono, Sidoarjo",WNI,1,None,"I don't have hobbies, I have moods",https://www.linkedin.com/in/getari-adyagarini-071598258?trk=contact-info,getari@leapsurabaya.sch.id,getari@leapsurabaya.sch.id,0878-5668-0404,95.824.727.2-603.000,None,0000102024764,1410023228554,Mobil,getari.adya,None,https://drive.google.com/drive/folders/1xAhqwJ3tmWN3kQQGS4YVIa4prG9RscxD?usp=sharing,Tidak ada,2026-01-01,None,None,0,1688369673_889db0f1267d89fe7ae4.jpeg,1708353208_d07b06675d1e5fa23383.png
17,18,U00033,LEAP03305VIII22,3518054105000002,"Maria Florencia Erica Susanto, A.Md.",Erica,Surabaya,2000-05-18,Perempuan,O,Katolik,Belum Menikah,Jl. M Yusuf RT 012 RW 003 Kel. Kecubung Kec. Pace,Perumahan Grand Eastern JL. Taman Timur Sukolilo II NO. 18 Blok AE-2,WNI,1,None,Nonton Drama & Scroll Tiktok,https://www.linkedin.com/in/maria-florencia-erica-susanto-81a900227,ericasusanto@leapsurabaya.sch.id,ericasusanto@leapsurabaya.sch.id,0851-5721-7422,60.469.638.5-615.000,23182511560,0002479768389,140020550777,Sepeda Motor,https://instagram.com/ericachouw,None,https://drive.google.com/drive/folders/1BsoRjVlW0QHOkAD-npM175jsOdBErdYl?usp=sharing,Patah tulang kaki kanan,2026-01-01,None,None,1,1688370640_434abe3fd75a3d6709f8.jpeg,1708324727_7d2882c04c6ff75ad399.png
18,19,U00034,LEAP03416II22,3578256604800002,"Mieke Puspita, S.Pd",Mieke,Malang,1980-04-26,Perempuan,O+,Katolik,Menikah,Perum Green Lake Wonorejo Timur Baru XVII H5/26,Perum Green Lake Wonorejo Timur Baru XVII H5/26,WNI,1,1,"Membaca, Menulis, Pergi pergi :P",https://www.linkedin.com/in/mieke-puspita-b01175259,miekepuspita@leapsurabaya.sch.id,miekepuspita@leapsurabaya.sch.id,0838-4989-5079,47.962.870.3-615.000,35782566048,0001536484331,1420020132329,Sepeda Motor,https://instagram.com/miekepuspita?igshid=ZDc4ODBmNjlmNQ==,https://www.facebook.com/mieke.puspita.7?mibextid=ZbWKwL,https://drive.google.com/drive/folders/10QGgWRKucYxs5RfV-OGgxc3pplpi7hrK?usp=sharing,bapil,2026-01-01,None,None,1,1688370596_5d157f2a824cbfffc9c0.jpg,1708658996_306c792c8c264fa46529.png
19,20,U00035,LEAP03507VIII12,3578256602930001,"Miftakhul Jannah, S.Pd",Tata,Magelang,1993-02-26,Perempuan,B,Islam,Menikah,Jl. Amir Mahmud IV 9-C,Permata Kwangsan Residence C1-10,WNI,1,1,"Memasak, make up, Jalan-jalan",None,miftakhul.jannah@leapsurabaya.sch.id,Miftakhul.jannah @leapsurabaya.sch.id,0881-0264-0002,None,17008687224,0001908364386,1420015278772,Sepeda Motor,miptha__,None,https://drive.google.com/drive/folders/1oeKwMA32povscLhSdyCTe6sxJ6DFxDGH?usp=sharing,None,2026-01-01,None,None,1,1690348208_aa0194bbe37e887d04c5.png,1708311420_9f19bdbeef8ddeb7c9dd.png
20,21,U00036,LEAP03602I23,1671070811000012,"Rr. Nisrina Dea Rahma, S.Hum",Dea,Surabaya,2000-11-08,Perempuan,B,Islam,Belum Menikah,"Jl. Pucang Asri I no.11, Kertajaya, Gubeng, Surabaya","Jl. Pucang Asri I no.11, Kertajaya, Gubeng, Surabaya",WNI,1,0,Musik,https://www.linkedin.com/in/rr-nisrina-dea-rahma-3389ba204/,nisrina.dea@leapsurabaya.sch.id,nisrina.dea@leapsurabaya.sch.id,0821-7616-1260,61.902.080.3-606.000,23074206378,0001107009641,1420016746702,Transportasi Umum,www.instagram.com/ndearhm,0,https://drive.google.com/drive/folders/1GZ6DYfo-qGvBa9bONymUVqTjM20i6N5A?usp=sharing,0,2026-01-01,None,None,0,1688370707_4f82feba07d331ac440f.jpg,1708311115_cd2260deb2d58d4146b1.png
21,22,U00037,LEAP03704VII23,3523176705990001,Siti Uswatun Khasanah,Uswa,Tuban,1999-05-27,Perempuan,None,Islam,Belum Menikah,"Dusun Sisir, RT 04, RW 05, Desa Kedungsoko, Plumpang, Tuban","Margorejo, Wonocolo",WNI,2,None,"Mendengarkan Musik, Membaca",None,siti.uswatun@leapsurabaya.sch.id,siti.uswatun@leapsurabaya.sch.id,0857-4595-2525,61.719.186.1-648.000,None,None,1420021927123,Sepeda Motor,None,None,https://drive.google.com/drive/folders/1I775kRo3-5i1EfeslG6ub0zfIsNgf61I?usp=sharing,None,2026-01-01,None,None,0,1688372130_e01ff4f038b7bae7029d.jpeg,None
22,23,U00038,LEAP03807VI11,3522146808900002,"Rini Budi Rahayu, S.Pd.",Rini,Bojonegoro,1990-08-28,Perempuan,B,Islam,Menikah,Ds. Klampok No.5 Kec. Kapas Kab. Bojonegoro,Perumahan Sentra Point Blok AD No.21 Surabaya,WNI,4,1,"membaca buku fiksi, menonton film",https://www.linkedin.com/in/rini-rahayu-91b7b1259/,rini.rahayu@leapsurabaya.sch.id,rini.rahayu@leapsurabaya.sch.id,0851-6314-1616,42.366.046.8-615.000,17008685640,0003003442593,1420015505729,Sepeda Motor,https://www.instagram.com/rini.cy/,None,https://drive.google.com/drive/folders/1HIhzTwz_akP85pFjnw4wHNnS-VK8jLI6?usp=sharing,None,2026-01-01,None,None,1,1688370886_98f7bfba3590ca021bd4.jpg,1707990713_4e97cffbee1938a3c5c0.png
23,24,U00040,LEAP04004VII23,3525011107855000,"Agung Wijayanto, S.T.",Agung,Gresik,1985-07-11,Laki laki,None,None,Belum Menikah,"Gresik, Kec. Dukun, Des. Petiyintunggal 001/001",Asem Payung I/25,WNI,None,None,Reading,None,agung.wijayanto@leapsurabaya.sch.id,agungwijayanto1107@gmail.com,0831-1527-0222,None,None,None,1780000459418,Sepeda Motor,https://instagram.com/agungwijayanto_ec?igshid=MzNlNGNkZWQ4Mg==,https://www.facebook.com/profile.php?id=100009927274040&mibextid=ZbWKwL,https://drive.google.com/folderview?id=1JScNiC-Vt51o1nfW-cB-9ivY3EEzjoPO,None,2026-01-01,None,None,1,1690477143_9c6782184cac165c2b0f.jpeg,1712272386_b9becdba820e59218d87.png
24,25,U00041,LEAP04125III23,3578246111990003,Vivi Pramitha Wulandari,Vivi,Surabaya,1999-11-21,Perempuan,B,Islam,Belum Menikah,Jl. Kutisari Utara II D/17 d,Jl. Kutisari Indah Barat IX No. 11,WNI,1,None,"Menggambar, mewarnai, bersepda, mendengarkan musik",viviwulandari,vivi.wulandari@leapsurabaya.sch.id,None,0812-1722-2294,40.206.847.2-615.000,None,None,014001234634830,Sepeda Motor,@_viviwulandari,None,https://drive.google.com/drive/folders/1jC7Xp9bZ3TS6WvO4FYrOogVhHEzwVBPF?usp=sharing,Tidak memiliki riwayat penyakit,2026-01-01,None,None,1,1688711260_556a4a91325635c55a1a.jpg,None
25,26,U00042,LEAP04225III23,3516154706990003,Cantika Swasti Sumarsono Putri,Ica,Mojokerto,1999-06-07,Perempuan,O,Islam,Belum Menikah,"Jompong, Mojokerto","Jalan Kutisari Utara 1 No. 54, Tenggilis Mejoyo, Surabaya",WNI,2,None,"menonton series/ film, karaoke, jalan-jalan",www.linkedin.com/in/cantika-swasti,cantikaswasti76@gmail.com,None,0858-0626-8098,62.655.312.7-615.000,None,0002611267672,014,Sepeda Motor,www.instagram.com/cantikaswasti/,None,None,"Cacar, flu",2026-01-01,None,None,0,1688701716_c0099248b9cea8e57e8b.png,None
26,27,U00043,LEAP04301VIII23,3504160901970002,Trio Fajar Cahyanto,Trio,Tulungagung,1997-01-09,Laki laki,O+,Islam,Belum Menikah,"Dsn, Sawo RT/RW 007/002, Ds. Sawo, Kec. Campurdarat, Kab. Tulungagung","Jl. Keputih Makam Blok D No.5, Keputih, Sukolilo, Surabaya",WNI,3,None,Menonton Anime dan Olahraga,Tidak Ada,generalaffair@gmail.com,staffga@leapsurabaya.sch.id,0878-8306-175_,62.703.897.9-629.000,21012951303,0000666642172,0140481790254,Sepeda Motor,https://instagram.com/_triofajar?utm_source=qr&igshid=OGU0MmVlOWVjOQ==,https://www.facebook.com/waluyondoko?mibextid=ZbWKwL,https://drive.google.com/drive/folders/1hUPWYSsUT7vP8In6h_2x-_mPYuAdADVO?usp=sharing,Tidak Ada (100% Sehat),2026-01-01,None,None,1,1694501101_eb7a9452f5d7069e2d05.jpeg,None
27,28,U00044,LEAP04402X23,3526014802900001,Muifatul Febriani,Ifa,Bangkalan,1990-02-08,Perempuan,B,Islam,Menikah,Jl. KH. Kholil V No.49B Demangan Bangkalan,Jl. KH. Kholil V No.49B Demangan Bangkalan,WNI,1,2,Travelling,linkedin.com/in/muifatul-febriani-5840451ab,muifatul@leapsurabaya.sch.id,None,0819-3932-0162,None,None,None,1400018055013,Sepeda Motor,@muifatul,None,None,Tidak Ada,2026-01-01,None,None,0,1697605800_1c209604feebb43aea57.jpeg,1708938634_e0891560dfe70ac20cdd.png
28,29,U00046,LEAP04601X23,None,sosialmedia1,sosmed,None,None,None,None,None,Belum Menikah,None,None,None,None,None,None,None,sosialmedia1@gmail.com,None,None,None,None,None,None,None,None,None,None,None,2026-01-01,None,None,1,None,None
29,30,U00047,LEAP04701XII23,3575021903990005,Muhamad Haykal Roziqi,Haykal,Kota Pasuruan,1999-03-19,Laki laki,None,None,Belum Menikah,JL.KH.ACHMAD DAHLAN XIII/7,JL.KH.ACHMAD DAHLAN XIII/3,WNI,1,None,Traveling,Haykal Roziqi,Muhammad.haykal@leapsurabaya.sch.id,Muhammad.haykal@leapsurabaya.sch.id,0878-8799-2703,None,None,0001197706397,5360700017684,Motor Pribadi,haykalroziqi,Haikal Roziki,https://drive.google.com/drive/folders/1BKtcXkLyr7kf4DOCehJRKqpO5AveOj-p?usp=drive_link,None,2026-01-01,None,None,0,1701413223_0ad0b6e85cf61cb96a29.jpeg,None
30,31,U00048,LEAP04821XII23,None,"Yerly A Datu, S.Pd, M.Pd, CT.ACT, C.PS",Yerly,None,None,None,None,None,Belum Menikah,None,None,None,None,None,None,None,pengajar1@leapsurabaya.sch.id,None,None,None,None,None,None,None,None,None,None,None,2026-01-01,None,None,1,None,1705635412_63253866271a8b6fe62c.png
31,32,U00049,LEAP04901II24,3519136702980002,Ana Puspita,Ana,Madiun,2024-02-27,Perempuan,B,Islam,Menikah,"Jl. Kav Mentari 02 no.45 , Tambak Rejo, Waru, Sidoarjo","Jl. Kav Mentari 02 no.45 , Tambak Rejo, Waru, Sidoarjo",WNI,1,0,Olahraga dan Menggambar,https://www.linkedin.com/in/ana-puspita-529419222?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app,ana.puspita@leapsurabaya.sch.id,Ana.puspita@leapsurabaya.sch.id,0812-3128-4882,None,None,None,0142160829578,Sepeda Motor,https://www.instagram.com/anasta.id?igsh=MXdlZXV3d2RqMnJ0dQ==,None,None,Gerd,2026-01-01,None,None,0,1707216719_23e8d54bc0ee23db70f7.jpeg,None
32,33,U00050,LEAP05019II24,3578034505870001,"Peni Puspa Indarwati, S.S.",Peni,Surabaya,1987-05-05,Perempuan,O,Islam,Belum Menikah,Penjaringansari Baru I-A/Kav.5 Rungkut Surabaya,Penjaringansari Baru I-A/Kav.5 Rungkut Surabaya,WNI,1,None,"membaca, menonton film",https://www.linkedin.com/in/peni-puspa-2793151a8/,peni.indarwati@leapsurabaya.sch.id,peni.indarwati@leapsurabaya.sch.id,0812-1635-3322,35.780.345.0-587.000,None,0001849925428,0146750644161,Sepeda Motor,https://www.instagram.com/puepuen55/?hl=en,None,https://drive.google.com/file/d/1CXkd0zUfmQsZidPinfLE7Lh1q1iTxUfJ/view?usp=drive_link,None,2026-01-01,None,None,1,1707113938_3f8f1d86bc8fa7c21626.jpg,1707119676_d6c58fb6bb36ffc05cbc.png
33,34,U00052,LEAP05202V24,3578244602850001,Ratna Febrianti,Ratna,Surabaya,1985-02-06,Perempuan,O,None,Belum Menikah,Kutisari Indah Utara 7/20 Surabaya,Kutisari Indah Utara 7/20 Surabaya,WNI,3,None,Jalan-jalan,https://www.linkedin.com/in/ratna-febrianti-b71382301,febrianti.ratna@leapsurabaya.sch.id,febrianti.ratna@leapsurabaya.sch.id,0812-3222-789_,34.003.500.5-615.000,None,2271484124,0148221109341,Sepeda Motor,https://www.instagram.com/ratnabrail/?hl=en,None,https://drive.google.com/drive/folders/1KQugWew6s7u3K_Fho2WhPaZRa_f3QX7H?usp=sharing,flu,2026-01-01,None,None,1,1716221191_e94b670798bb2696d03d.jpg,None
34,35,U00053,LEAP05301VII24,None,Ann Clariss Agbalog Amora,Ann,None,None,None,None,None,Belum Menikah,None,None,None,None,None,None,None,edgetutor1@leapsurabaya.sch.id,None,None,None,None,None,None,None,None,None,None,None,2026-01-01,None,None,0,1716522842_b8a66f29051db6e6a30f.png,None

Processed Data for keluarga_karyawan table:

,id_keluarga,id_karyawan,hubungan_keluarga,nama_lengkap,pekerjaan,nomor_hp
0,None,2,Ibu,Nur Fatmawati,Wiraswasta,081234477137
1,None,9,Suami,Fathul Kirom,Suami,0852-3101-7799
2,None,12,Ayah,"Suwandi, S.Pd.",Guru Matematika SMAN 17 Surabaya,087853591616
3,None,12,Ibu,"Ir. Hj. Erhasyati Islamiyah, M.M.",(Pensiun) Guru Biologi SMA Muhammadiyah 2 Surabaya,08179365966
4,None,3,Suami,JONATHAN O'DRISCOLL,TIDAK BEKERJA,089696320278
5,None,12,Adik,Fahada Akbariyah,Pekerja Laboratoriumm RS Soewandhi,088801762951
6,None,12,Adik,Rafi Arif Billah,Mahasiswa S1 Manajemen Undika,08563002290
7,None,18,Ayah,Herrie Susanto,Wiraswasta,08123429138
8,None,18,Ibu,Juliani,tidak bekerja,081911541719
9,None,17,Saudara,AGUS DJOKO PRANOWO,KARYAWAN SWASTA,087852999236
10,None,19,Suami,Yerly A. Datu,Dosen,082146921559
11,None,19,Anak,Yonathan Yerly Datu,mahasiswa,083832072043
12,None,23,Suami,Chusnul Yakin,Wiraswasta,085158789353
13,None,20,Suami,Juni Arlianto,Pegawai Swasta,0881026400010
14,None,21,Ayah,"R. Ponco Suryono, SH. MM.",TNI-AD,085232001833
15,None,21,Ibu,"Sri Wahyuni Andajani, SH",None,085230218640
16,None,21,Adik,R. Sulthan Rafi Athallah,None,None
17,None,10,Istri,Miftakhul Jannah,Pengajar/ Guru,0881026400020
18,None,25,Ayah,Sali,Wiraswasta,081217222286
19,None,25,Ibu,Suhartini,Tidak bekerja,081331914377
20,None,5,Adik,Titi Hapsari Retnaningtias,Swasta,082245166547
21,None,7,Ayah,Sariman,Petani,082132967221
22,None,22,Ayah,Sukawan,Petani,None
23,None,22,Ibu,Sumarini,Ibu rumah tangga,None
24,None,10,Anak,Arshaka Keanu Arlianto,None,None
25,None,24,Ayah,Nasripan,Swasta,None
26,None,24,Adik,Nur Asyiah,Admin,085812449976
27,None,6,Suami,Fransiscus Arifin,Dokter PNS,0811375636
28,None,6,Anak,Clarissa Franka Arifin,Pelajar,+62 822-4596-0614
29,None,6,Anak,Agnesia Friska Arifin,Pelajar,+62 851-7169-5123
30,None,27,Saudara,Lifan Gusjianto,Freelance,082334958166
31,None,30,Saudara,M.Fauzi A.S,Staff PMI,082147782070
32,None,30,Saudara,Henny P.A,Reseller lipstik,085732512347
33,None,30,Adik,Naflah zahiyah maharani,SMA,0882009260421
34,None,30,Adik,M.abrizam reynan,TK A,None
35,None,33,Saudara,Suwadji,Wiraswasta,081331089339
36,None,32,Suami,Dhodik Bima Arjiansyah,Streaming,089510510030
37,None,34,Kakak,Sandra Restu Ariyani,Wiraswasta,0817599707
38,None,37,Kakak,Suci Nur Hasanah,Ibu Rumah Tangga,085797184443
39,None,37,Kakak,Siti Fatimah,Ibu Rumah Tangga,087724926657
40,None,37,Adik,Kanza Azzahra,Pelajar,083134684428
41,None,18,Saudara,Stefanus Erico Susanto,Karyawan Swasta,085161776657
42,None,18,Saudara,Giovano Laurentius Evan Susanto,Pelajar,085156506694
43,None,11,Suami,Dimas Sakti Mahardika Putra,Wiraswasta,087853172361
44,None,38,Istri,Nunuk,Ibu Rumah Tanga,085336874050
45,None,41,Suami,M Afghani Wardhana Setiyasa,PNS Pemkot Surabaya,+62 822-3185-5518
46,None,42,Ayah,Nur Hasim,Petani,085343916217
47,None,42,Adik,Arif al-Aziz,Mahasiswa,085655282437
48,None,43,Ibu,Helen Rosdiana Gultom,Guru TK,082233333219
49,None,46,Ayah,Suprayitno,Petani,082234399512
50,None,46,Ibu,Suwati,Petani,082234399512
51,None,46,Adik,Sifa Dwi Meisyahrani,Pelajar,085656504253
52,None,47,Ayah,Sukijan,Wiraswasta,082141452234
53,None,47,Ibu,Sri Ekorini,Ibu Rumah tangga,081249769300
54,None,48,Ayah,Marwito,Petani,081779437967
55,None,48,Ibu,Ayu Aryawati,Ibu Rumah Tangga,0881081081819
56,None,48,Kakak,Erik Aryanto Hidayat,Backend Developer,08551151105
57,None,49,Ayah,Amir,Pengusaha,---
58,None,49,Ibu,Sri Wahyuni,Ibu rumah tangga,087840782568
59,None,36,Ibu,Sylvia Widyastuti,Pekerja swasta,082142995636
60,None,50,Ibu,Siti Rokhani,Kerja di toko kelontong,085775734255
61,None,51,Ibu,Ratri Widorini,School Accounting,+62 822-6433-4296
62,None,51,Ayah,Agung Yuniarti Akhirin,Accounting,+62 813-3022-2722
63,None,51,Saudara,Zakeia Ayra Sinatrya,Mahasiswa,+62 895-3670-88279
64,None,52,Saudara,Nursahid,Tukang,085232118082
65,None,52,Ibu,Isro'ati,karyawan toko,085231063005
66,None,52,Saudara,Ach. Muchndori Lucmana,Staf sarana prasarana,081216216848

Processed Data for bidang_kategori table:

    id_bidang_kategori nama_kategori_bidang  id_bidang
0                    7       Brand Identity          7
1                   13             Training          9
2                   14            Referensi          9
3                   16             Training          8
4                   17             Training         11
5                   18            Referensi         11
6                   19            Referensi          8
7                   20            Referensi          7
8                   21             Training          7
9                   22             Proposal         11
10                  23                  MoU         11
11                  24          Dokumentasi          9

   idbidang         namabidang
0         7  Sales & Marketing
1         8              R & D
2         9       Sosial Media
3        11          Komunitas

Processed Data for bidang_link table:

,id_bidang_link,nama_form,link_drive,id_bidang_kategori,status_share
0,16,Daftar Training,https://drive.google.com/drive/folders/1BCPhp6eG5mNeWyTZS8i4xHEor-zgeyJu?usp=drive_link,13,0
1,17,Referensi,https://drive.google.com/drive/folders/1Lo6hzugBnuacIyHPF6nef-9BV1O9mnCQ?usp=drive_link,14,0
2,18,Dokumentasi,https://drive.google.com/drive/folders/14ieegP1eR_Vdj-QCOhevVeKR2DOaQ5_w?usp=drive_link,24,0
3,19,List Training,https://drive.google.com/drive/folders/1yivPYk3nJ3XmRZ5Np3S7d30AK3yw14GJ?usp=drive_link,16,0
4,20,Referensi,https://drive.google.com/drive/folders/1ah2G3XtafGmA3B1V01Np8rmv8lZrUmKl?usp=drive_link,19,0
5,21,Logo Leap,https://drive.google.com/drive/folders/1S1Og9cSimI2zuwCjD6PpBgSHqubhfcjI?usp=sharing,7,0
6,22,Referensi,https://drive.google.com/drive/folders/1JuWEPTbtE58G_1FzbLwZyjJhARpO7Pq-?usp=sharing,20,0

In [39]:
import json
import pickle
with open('fase_2_cimut.pkl', 'wb') as f:
    pickle.dump(df_new, f)

print("✓ Data df_new sudah disimpan ke df_new.pkl")
print("Siap untuk digunakan di insert_handler.ipynb")

✓ Data df_new sudah disimpan ke df_new.pkl
Siap untuk digunakan di insert_handler.ipynb