# fase_2 - script_cimut Migration

This notebook handles migration of database from old DB to new DB for fase 2.

**Purpose**: Benerin database lama ke database baru untuk bagian [NAMA TABEL]

In [1]:
import sys
import os
import mysql.connector
import pandas as pd
sys.path.append(os.path.abspath('..'))
from config import get_db_config
import warnings
warnings.filterwarnings('ignore')

## 1. Connect ke Database

In [2]:
# Connect ke database config
config = get_db_config()
# Ambil host dari salah satu config (misal db_old)
print(f'Database config loaded: {config["db_old"]["host"]}')

# Connect ke DB Lama
db_old = mysql.connector.connect(**config['db_old'])
cursor_old = db_old.cursor(dictionary=True)
print(f'Connected to old database: {config["db_old"]["database"]}')

# Connect ke DB Baru
db_new = mysql.connector.connect(**config['db_new'])
cursor_new = db_new.cursor(dictionary=True)
print(f'Connected to new database: {config["db_new"]["database"]}')

Database config loaded: localhost
Connected to old database: dataleap_v5_example
Connected to new database: dataleap_v5_migration

## 2. Ambil Data dari DB Lama

In [3]:
# ---------------------------------------------------------
# UPDATE: AMBIL DAFTAR TABEL SECARA DINAMIS
# ---------------------------------------------------------
cursor_old.execute("SHOW TABLES")
tables_data = cursor_old.fetchall()

# Mengambil nama tabel dari hasil query
# Note: Format output 'SHOW TABLES' biasanya {'Tables_in_dbname': 'tablename'}
target_tables = [list(t.values())[0] for t in tables_data]

print(f"\n--- Ditemukan {len(target_tables)} tabel di Database Lama ---")
print(target_tables)

# Dictionary untuk menyimpan data yang sudah di-load
df_old = {}

print("\n--- Memulai proses load semua data tabel ---")

for table in target_tables:
    try:
        # Load data menggunakan pandas langsung dari koneksi SQL
        query = f"SELECT * FROM `{table}`"
        df_old[table] = pd.read_sql(query, db_old)
        
        print(f"Berhasil load tabel: {table} | Jumlah baris: {len(df_old[table])}")
        
    except Exception as e:
        print(f"Gagal load tabel {table}: {e}")

print("\n--- Proses load selesai. Semua data tersimpan di 'df_old' ---")
print("Kamu sekarang bisa akses datanya dengan: df_old['nama_tabel']")

# Contoh akses data:
# print(df_old['users'].head())

# Tutup koneksi jika sudah tidak digunakan
# db_old.close()
# db_new.close()

--- Ditemukan 108 tabel di Database Lama ---
['absensi', 'absensi_note', 'bidang', 'bidangkategori', 'bidanglink', 'calon', 'calon_detil', 'calon_pertanyaan', 'calon_pertanyaan_detil', 'catatan_kelas', 'catatan_kelas_tag', 'catatan_mingguan', 'catatan_siswa', 'catatan_siswa_follow_up', 'catatanawal_admin', 'catatanawal_datautama', 'catatanawal_infolain', 'catatanawal_tglpenting', 'divisi', 'docs', 'file_rapor_siswa', 'form', 'form_calon', 'form_calon_detil1', 'form_calon_detil2', 'form_calon_detil3', 'form_calon_detil4', 'format_rapor', 'format_rapor_detil', 'format_rapor_detil_rumus', 'format_rapor_rumus', 'format_raport_level', 'hakakses', 'histori_pengajuan', 'history_rapor', 'identitas', 'infrastruktur', 'jabatan', 'jadwal', 'jadwal_detil', 'jadwal_pengajar', 'jadwal_siswa', 'jamkerja', 'kabupaten', 'karyawan', 'kecamatan', 'keluar', 'keluarga', 'kelurahan', 'kurikulum', 'kurikulum_detil', 'kurikulum_detil_sub', 'kurikulum_kelas', 'kursus', 'leapprofil', 'leapverse', 'level', 'libur', 'libur_pendkursus', 'linkdrive', 'linkform', 'log', 'mitra', 'mitra_note', 'mitra_users', 'mou', 'mou_histori', 'nowag', 'parameter_nilai', 'pekerjaan', 'pelamar', 'pelamar_note', 'pelamar_submit', 'pelamar_users', 'pendidikan', 'pendidikankursus', 'pengajuan', 'pengumuman', 'perijinan', 'perijinan_note', 'periode', 'pinjam', 'presensi_siswa', 'problem', 'provinsi', 'purchase', 'purchase_link', 'rapor', 'role', 'role_users', 'sesi', 'siswa', 'siswa_keluar', 'siswa_keluar_mitra', 'siswa_keluar_tag', 'siswamitra', 'sop', 'sopkategori', 'suratkeluar', 'suratkeluar_histori', 'surattugas', 'surattugas_users', 'syarat', 'tag_keluar', 'tag_materi_diskusi', 'ttd', 'users', 'zoom']

--- Memulai proses load semua data tabel ---
Berhasil load tabel: absensi | Jumlah baris: 13444
Berhasil load tabel: absensi_note | Jumlah baris: 11
Berhasil load tabel: bidang | Jumlah baris: 4
Berhasil load tabel: bidangkategori | Jumlah baris: 12
Berhasil load tabel: bidanglink | Jumlah baris: 7
Berhasil load tabel: calon | Jumlah baris: 4
Berhasil load tabel: calon_detil | Jumlah baris: 61
Berhasil load tabel: calon_pertanyaan | Jumlah baris: 229
Berhasil load tabel: calon_pertanyaan_detil | Jumlah baris: 4305
Berhasil load tabel: catatan_kelas | Jumlah baris: 12797
Berhasil load tabel: catatan_kelas_tag | Jumlah baris: 999
Berhasil load tabel: catatan_mingguan | Jumlah baris: 0
Berhasil load tabel: catatan_siswa | Jumlah baris: 1502
Berhasil load tabel: catatan_siswa_follow_up | Jumlah baris: 22
Berhasil load tabel: catatanawal_admin | Jumlah baris: 64
Berhasil load tabel: catatanawal_datautama | Jumlah baris: 9
Berhasil load tabel: catatanawal_infolain | Jumlah baris: 64
Berhasil load tabel: catatanawal_tglpenting | Jumlah baris: 10
Berhasil load tabel: divisi | Jumlah baris: 6
Berhasil load tabel: docs | Jumlah baris: 0
Berhasil load tabel: file_rapor_siswa | Jumlah baris: 1506
Berhasil load tabel: form | Jumlah baris: 1
Berhasil load tabel: form_calon | Jumlah baris: 184
Berhasil load tabel: form_calon_detil1 | Jumlah baris: 77
Berhasil load tabel: form_calon_detil2 | Jumlah baris: 77
Berhasil load tabel: form_calon_detil3 | Jumlah baris: 77
Berhasil load tabel: form_calon_detil4 | Jumlah baris: 77
Berhasil load tabel: format_rapor | Jumlah baris: 45
Berhasil load tabel: format_rapor_detil | Jumlah baris: 129
Berhasil load tabel: format_rapor_detil_rumus | Jumlah baris: 1650
Berhasil load tabel: format_rapor_rumus | Jumlah baris: 3
Berhasil load tabel: format_raport_level | Jumlah baris: 348
Berhasil load tabel: hakakses | Jumlah baris: 6
Berhasil load tabel: histori_pengajuan | Jumlah baris: 79
Berhasil load tabel: history_rapor | Jumlah baris: 1366
Berhasil load tabel: identitas | Jumlah baris: 0
Berhasil load tabel: infrastruktur | Jumlah baris: 1
Berhasil load tabel: jabatan | Jumlah baris: 11
Berhasil load tabel: jadwal | Jumlah baris: 551
Berhasil load tabel: jadwal_detil | Jumlah baris: 17267
Berhasil load tabel: jadwal_pengajar | Jumlah baris: 641
Berhasil load tabel: jadwal_siswa | Jumlah baris: 3905
Berhasil load tabel: jamkerja | Jumlah baris: 3
Berhasil load tabel: kabupaten | Jumlah baris: 521
Berhasil load tabel: karyawan | Jumlah baris: 51
Berhasil load tabel: kecamatan | Jumlah baris: 7269
Berhasil load tabel: keluar | Jumlah baris: 51
Berhasil load tabel: keluarga | Jumlah baris: 64
Berhasil load tabel: kelurahan | Jumlah baris: 83473
Berhasil load tabel: kurikulum | Jumlah baris: 0
Berhasil load tabel: kurikulum_detil | Jumlah baris: 0
Berhasil load tabel: kurikulum_detil_sub | Jumlah baris: 0
Berhasil load tabel: kurikulum_kelas | Jumlah baris: 0
Berhasil load tabel: kursus | Jumlah baris: 50
Berhasil load tabel: leapprofil | Jumlah baris: 0
Berhasil load tabel: leapverse | Jumlah baris: 365
Berhasil load tabel: level | Jumlah baris: 181
Berhasil load tabel: libur | Jumlah baris: 79
Berhasil load tabel: libur_pendkursus | Jumlah baris: 2
Berhasil load tabel: linkdrive | Jumlah baris: 0
Berhasil load tabel: linkform | Jumlah baris: 3
Berhasil load tabel: log | Jumlah baris: 21887
Berhasil load tabel: mitra | Jumlah baris: 22
Berhasil load tabel: mitra_note | Jumlah baris: 296
Berhasil load tabel: mitra_users | Jumlah baris: 228
Berhasil load tabel: mou | Jumlah baris: 2
Berhasil load tabel: mou_histori | Jumlah baris: 10
Berhasil load tabel: nowag | Jumlah baris: 1
Berhasil load tabel: parameter_nilai | Jumlah baris: 1187
Berhasil load tabel: pekerjaan | Jumlah baris: 67
Berhasil load tabel: pelamar | Jumlah baris: 178
Berhasil load tabel: pelamar_note | Jumlah baris: 403
Berhasil load tabel: pelamar_submit | Jumlah baris: 0
Berhasil load tabel: pelamar_users | Jumlah baris: 281
Berhasil load tabel: pendidikan | Jumlah baris: 53
Berhasil load tabel: pendidikankursus | Jumlah baris: 21
Berhasil load tabel: pengajuan | Jumlah baris: 33
Berhasil load tabel: pengumuman | Jumlah baris: 1
Berhasil load tabel: perijinan | Jumlah baris: 957
Berhasil load tabel: perijinan_note | Jumlah baris: 2107
Berhasil load tabel: periode | Jumlah baris: 93
Berhasil load tabel: pinjam | Jumlah baris: 194
Berhasil load tabel: presensi_siswa | Jumlah baris: 97762
Berhasil load tabel: problem | Jumlah baris: 160
Berhasil load tabel: provinsi | Jumlah baris: 36
Berhasil load tabel: purchase | Jumlah baris: 110
Berhasil load tabel: purchase_link | Jumlah baris: 1
Berhasil load tabel: rapor | Jumlah baris: 22837
Berhasil load tabel: role | Jumlah baris: 9
Berhasil load tabel: role_users | Jumlah baris: 0
Berhasil load tabel: sesi | Jumlah baris: 43
Berhasil load tabel: siswa | Jumlah baris: 1469
Berhasil load tabel: siswa_keluar | Jumlah baris: 556
Berhasil load tabel: siswa_keluar_mitra | Jumlah baris: 0
Berhasil load tabel: siswa_keluar_tag | Jumlah baris: 404
Berhasil load tabel: siswamitra | Jumlah baris: 0
Berhasil load tabel: sop | Jumlah baris: 4
Berhasil load tabel: sopkategori | Jumlah baris: 3
Berhasil load tabel: suratkeluar | Jumlah baris: 213
Berhasil load tabel: suratkeluar_histori | Jumlah baris: 477
Berhasil load tabel: surattugas | Jumlah baris: 135
Berhasil load tabel: surattugas_users | Jumlah baris: 304
Berhasil load tabel: syarat | Jumlah baris: 1
Berhasil load tabel: tag_keluar | Jumlah baris: 11
Berhasil load tabel: tag_materi_diskusi | Jumlah baris: 11
Berhasil load tabel: ttd | Jumlah baris: 1
Berhasil load tabel: users | Jumlah baris: 51
Berhasil load tabel: zoom | Jumlah baris: 14

--- Proses load selesai. Semua data tersimpan di 'df_old' ---
Kamu sekarang bisa akses datanya dengan: df_old['nama_tabel']

In [4]:
# ---------------------------------------------------------
# UPDATE: AMBIL DAFTAR TABEL SECARA DINAMIS (DATABASE BARU)
# ---------------------------------------------------------
# Menggunakan cursor dari database baru
cursor_new.execute("SHOW TABLES")
tables_data_new = cursor_new.fetchall()

# Mengambil nama tabel dari hasil query
target_tables_new = [list(t.values())[0] for t in tables_data_new]

print(f"\n--- Ditemukan {len(target_tables_new)} tabel di Database Baru ---")
print(target_tables_new)

# Dictionary untuk menyimpan data dari database baru (jika diperlukan untuk verifikasi)
df_new = {}

print("\n--- Memulai proses load semua data dari Database Baru ---")

for table in target_tables_new:
    try:
        # Load data menggunakan pandas dengan koneksi database baru
        query = f"SELECT * FROM `{table}`"
        df_new[table] = pd.read_sql(query, db_new)
        
        print(f"Berhasil load tabel: {table} | Jumlah baris: {len(df_new[table])}")
        
    except Exception as e:
        print(f"Gagal load tabel {table} dari DB Baru: {e}")

print("\n--- Proses load selesai. Data DB Baru tersimpan di 'df_new' ---")

--- Ditemukan 104 tabel di Database Baru ---
['absensi', 'activity_log', 'admin_sarpras', 'bidang_kategori', 'bidang_link', 'busdev_bidang', 'cache', 'cache_locks', 'calon_siswa', 'calon_siswa_akademik', 'calon_siswa_bayar', 'calon_siswa_jadwal', 'calon_siswa_kursus', 'calon_siswa_ortu', 'calon_siswa_proses', 'calon_siswa_status_logs', 'catatan_kelas', 'catatan_kelas_tag', 'catatan_mingguan', 'catatan_siswa', 'division_user', 'divisions', 'failed_jobs', 'followup_cs', 'histori_pengajuan', 'izin_karyawan', 'jadwal', 'jadwal_detail', 'jadwal_detail_logs', 'jadwal_hari', 'jadwal_pengajar', 'jadwal_siswa', 'job_batches', 'jobs', 'kabupaten', 'karyawan', 'karyawan_resign', 'kecamatan', 'keluarga_karyawan', 'kelurahan', 'kemitraan_verifikator', 'kontak_prospek', 'kursus', 'kursus_level', 'kursus_libur', 'kursus_siswa', 'level', 'libur', 'log_aktivitas', 'migrations', 'mitra', 'mitra_progres', 'model_has_permissions', 'model_has_roles', 'mou', 'parameter_nilai', 'password_reset_tokens', 'pelamar', 'pelamar_kerja', 'pelamar_kursus', 'pelamar_sekolah', 'peminjaman', 'pengadaan', 'pengajuan_karyawan', 'periode', 'permissions', 'presensi_siswa', 'problem', 'progres_pelamar', 'provinsi', 'rapor_format', 'rapor_format_formula', 'rapor_format_formula_sub', 'rapor_format_sub', 'rapor_lacak', 'rapor_level_config', 'rapor_siswa', 'rapor_siswa_file', 'rapor_sub_level', 'rekrutmen_pelamar', 'role_has_permissions', 'roles', 'sesi', 'sessions', 'shift_kerja', 'siswa', 'siswa_keluar', 'siswa_mitra', 'siswa_mitra_keluar', 'sop', 'sop_kategori', 'surat_keluar', 'surat_tugas', 'surat_tugas_anggota', 'syarat_resign', 'tag_siswa_keluar', 'topik_diskusi', 'ttd', 'users', 'verifikasi_absensi', 'verifikasi_izin', 'verifikasi_surat_keluar', 'web_berita', 'web_statistik']

--- Memulai proses load semua data dari Database Baru ---
Berhasil load tabel: absensi | Jumlah baris: 0
Berhasil load tabel: activity_log | Jumlah baris: 0
Berhasil load tabel: admin_sarpras | Jumlah baris: 1
Berhasil load tabel: bidang_kategori | Jumlah baris: 0
Berhasil load tabel: bidang_link | Jumlah baris: 0
Berhasil load tabel: busdev_bidang | Jumlah baris: 0
Berhasil load tabel: cache | Jumlah baris: 0
Berhasil load tabel: cache_locks | Jumlah baris: 0
Berhasil load tabel: calon_siswa | Jumlah baris: 0
Berhasil load tabel: calon_siswa_akademik | Jumlah baris: 0
Berhasil load tabel: calon_siswa_bayar | Jumlah baris: 0
Berhasil load tabel: calon_siswa_jadwal | Jumlah baris: 0
Berhasil load tabel: calon_siswa_kursus | Jumlah baris: 0
Berhasil load tabel: calon_siswa_ortu | Jumlah baris: 0
Berhasil load tabel: calon_siswa_proses | Jumlah baris: 0
Berhasil load tabel: calon_siswa_status_logs | Jumlah baris: 0
Berhasil load tabel: catatan_kelas | Jumlah baris: 0
Berhasil load tabel: catatan_kelas_tag | Jumlah baris: 0
Berhasil load tabel: catatan_mingguan | Jumlah baris: 0
Berhasil load tabel: catatan_siswa | Jumlah baris: 0
Berhasil load tabel: division_user | Jumlah baris: 0
Berhasil load tabel: divisions | Jumlah baris: 6
Berhasil load tabel: failed_jobs | Jumlah baris: 0
Berhasil load tabel: followup_cs | Jumlah baris: 0
Berhasil load tabel: histori_pengajuan | Jumlah baris: 0
Berhasil load tabel: izin_karyawan | Jumlah baris: 0
Berhasil load tabel: jadwal | Jumlah baris: 0
Berhasil load tabel: jadwal_detail | Jumlah baris: 0
Berhasil load tabel: jadwal_detail_logs | Jumlah baris: 0
Berhasil load tabel: jadwal_hari | Jumlah baris: 0
Berhasil load tabel: jadwal_pengajar | Jumlah baris: 0
Berhasil load tabel: jadwal_siswa | Jumlah baris: 0
Berhasil load tabel: job_batches | Jumlah baris: 0
Berhasil load tabel: jobs | Jumlah baris: 0
Berhasil load tabel: kabupaten | Jumlah baris: 514
Berhasil load tabel: karyawan | Jumlah baris: 0
Berhasil load tabel: karyawan_resign | Jumlah baris: 0
Berhasil load tabel: kecamatan | Jumlah baris: 7266
Berhasil load tabel: keluarga_karyawan | Jumlah baris: 0
Berhasil load tabel: kelurahan | Jumlah baris: 83449
Berhasil load tabel: kemitraan_verifikator | Jumlah baris: 0
Berhasil load tabel: kontak_prospek | Jumlah baris: 0
Berhasil load tabel: kursus | Jumlah baris: 0
Berhasil load tabel: kursus_level | Jumlah baris: 0
Berhasil load tabel: kursus_libur | Jumlah baris: 0
Berhasil load tabel: kursus_siswa | Jumlah baris: 0
Berhasil load tabel: level | Jumlah baris: 0
Berhasil load tabel: libur | Jumlah baris: 0
Berhasil load tabel: log_aktivitas | Jumlah baris: 0
Berhasil load tabel: migrations | Jumlah baris: 0
Berhasil load tabel: mitra | Jumlah baris: 0
Berhasil load tabel: mitra_progres | Jumlah baris: 0
Berhasil load tabel: model_has_permissions | Jumlah baris: 0
Berhasil load tabel: model_has_roles | Jumlah baris: 0
Berhasil load tabel: mou | Jumlah baris: 0
Berhasil load tabel: parameter_nilai | Jumlah baris: 0
Berhasil load tabel: password_reset_tokens | Jumlah baris: 0
Berhasil load tabel: pelamar | Jumlah baris: 0
Berhasil load tabel: pelamar_kerja | Jumlah baris: 0
Berhasil load tabel: pelamar_kursus | Jumlah baris: 0
Berhasil load tabel: pelamar_sekolah | Jumlah baris: 0
Berhasil load tabel: peminjaman | Jumlah baris: 0
Berhasil load tabel: pengadaan | Jumlah baris: 0
Berhasil load tabel: pengajuan_karyawan | Jumlah baris: 0
Berhasil load tabel: periode | Jumlah baris: 0
Berhasil load tabel: permissions | Jumlah baris: 0
Berhasil load tabel: presensi_siswa | Jumlah baris: 0
Berhasil load tabel: problem | Jumlah baris: 0
Berhasil load tabel: progres_pelamar | Jumlah baris: 0
Berhasil load tabel: provinsi | Jumlah baris: 38
Berhasil load tabel: rapor_format | Jumlah baris: 0
Berhasil load tabel: rapor_format_formula | Jumlah baris: 0
Berhasil load tabel: rapor_format_formula_sub | Jumlah baris: 0
Berhasil load tabel: rapor_format_sub | Jumlah baris: 0
Berhasil load tabel: rapor_lacak | Jumlah baris: 0
Berhasil load tabel: rapor_level_config | Jumlah baris: 0
Berhasil load tabel: rapor_siswa | Jumlah baris: 0
Berhasil load tabel: rapor_siswa_file | Jumlah baris: 0
Berhasil load tabel: rapor_sub_level | Jumlah baris: 0
Berhasil load tabel: rekrutmen_pelamar | Jumlah baris: 0
Berhasil load tabel: role_has_permissions | Jumlah baris: 0
Berhasil load tabel: roles | Jumlah baris: 0
Berhasil load tabel: sesi | Jumlah baris: 0
Berhasil load tabel: sessions | Jumlah baris: 0
Berhasil load tabel: shift_kerja | Jumlah baris: 3
Berhasil load tabel: siswa | Jumlah baris: 0
Berhasil load tabel: siswa_keluar | Jumlah baris: 0
Berhasil load tabel: siswa_mitra | Jumlah baris: 0
Berhasil load tabel: siswa_mitra_keluar | Jumlah baris: 0
Berhasil load tabel: sop | Jumlah baris: 0
Berhasil load tabel: sop_kategori | Jumlah baris: 3
Berhasil load tabel: surat_keluar | Jumlah baris: 0
Berhasil load tabel: surat_tugas | Jumlah baris: 0
Berhasil load tabel: surat_tugas_anggota | Jumlah baris: 0
Berhasil load tabel: syarat_resign | Jumlah baris: 0
Berhasil load tabel: tag_siswa_keluar | Jumlah baris: 0
Berhasil load tabel: topik_diskusi | Jumlah baris: 0
Berhasil load tabel: ttd | Jumlah baris: 0
Berhasil load tabel: users | Jumlah baris: 51
Berhasil load tabel: verifikasi_absensi | Jumlah baris: 0
Berhasil load tabel: verifikasi_izin | Jumlah baris: 0
Berhasil load tabel: verifikasi_surat_keluar | Jumlah baris: 0
Berhasil load tabel: web_berita | Jumlah baris: 0
Berhasil load tabel: web_statistik | Jumlah baris: 0

--- Proses load selesai. Data DB Baru tersimpan di 'df_new' ---

## 3. Transform Data (jika diperlukan)

karyawan, keluarga_karyawan, bidang_kategori, bidang_link.

In [5]:
cols_to_keep_from_old = [col for col in df_old['users'].columns 
                        if col not in ['nama', 'pass'] 
                        and col not in df_new['users'].columns]

# Merge berdasarkan email
df_merged_users = df_new['users'].merge(
    df_old['users'][['email'] + cols_to_keep_from_old],
    on='email',
    how='left'
)

display(df_merged_users.info())

<class 'pandas.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 28 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_user            51 non-null     str
 1   name               51 non-null     str
 2   email              51 non-null     str
 3   email_verified_at  0 non-null      object
 4   password           51 non-null     str
 5   remember_token     0 non-null      object
 6   created_at         0 non-null      object
 7   updated_at         0 non-null      object
 8   idusers            51 non-null     str
 9   foto               44 non-null     str
 10  idrole             51 non-null     str
 11  wa                 50 non-null     str
 12  thnbekerja         51 non-null     str
 13  idjabatan          51 non-null     str
 14  idjamkerja         14 non-null     float64
 15  minat              50 non-null     str
 16  status             51 non-null     str
 17  idbidang           10 non-null     float64
 18  ispurchase         50 non-null     float64
 19  isteaching         50 non-null     float64
 20  ishr               51 non-null     int64
 21  isga               51 non-null     int64
 22  isit               51 non-null     int64
 23  ispdd              51 non-null     int64
 24  isbusdev           51 non-null     int64
 25  ispimpinan         51 non-null     int64
 26  ttd                15 non-null     str
 27  expertise          39 non-null     str
dtypes: float64(4), int64(6), object(4), str(14)
memory usage: 11.3+ KB

None

In [6]:
# Create a new dictionary with the updated 'idusers' values
df_new_users_dict = df_merged_users.set_index('idusers')['id_user'].to_dict()

# Replace the 'idusers' values in df_old['karyawan'] with the corresponding values from df_new_users_dict
df_old['karyawan']['idusers'] = df_old['karyawan']['idusers'].map(df_new_users_dict)

# Display semua baris dan kolom
# print("\n5. TAMPILAN SEMUA DATA:")
# pd.set_option('display.max_rows', None)
# pd.set_option('display.max_columns', None)
# pd.set_option('display.width', None)
# pd.set_option('display.max_colwidth', None)
# display(df_old['karyawan'])

In [7]:
# Create a new dictionary with the updated 'idusers' values
df_new_users_dict = df_merged_users.set_index('id_user')['thnbekerja'].to_dict()

# Replace the 'idusers' values in df_old['karyawan'] with the corresponding values from df_new_users_dict
df_old['karyawan']['thnbekerja'] = df_old['karyawan']['idusers'].map(df_new_users_dict)

# # Display semua baris dan kolom
# print("\n5. TAMPILAN SEMUA DATA:")
# pd.set_option('display.max_rows', None)
# pd.set_option('display.max_columns', None)
# pd.set_option('display.width', None)
# pd.set_option('display.max_colwidth', None)
# display(df_old['karyawan'])

In [8]:
# Display only the 'id_karyawan' and 'nama_karyawan' columns
print("\n5. TAMPILAN SEMUA DATA:")
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)
display(df_old['karyawan'][['idkaryawan', 'nama', 'thnbekerja']])

5. TAMPILAN SEMUA DATA:

         idkaryawan                            nama  thnbekerja
0       LEAP001VI02                             NaN  2023-06-02
1    LEAP003III2023          Graciela Evanda Ronadi  2023-03-13
2      LEAP011XII01              DANIAR AULIA RIZKI  2020-12-01
3      LEAP012III02          Habibah Melyna Elfiani  2020-03-02
4      LEAP014VII31          Laksmi Puspitowardhani  2018-07-31
5     LEAP015II2011                             NaN   14-2-2011
6     LEAP016VI2017              Luluk Fatikah Sari  2017-06-19
7       LEAP018IV20         Ditari Kurnia Damayanti  2021-04-20
8     LEAP019VI2019                        Hartatik  2019-06-01
9       LEAP020IV30                   Juni Arlianto  2009-04-30
10    LEAP023XI2019      Titi Hapsari Retnaningtias  2019-10-01
11  LEAP026VIII2021                Qorin Rahmaniyah  2021-08-02
12    LEAP027VI2023                             fgz  2023-06-15
13    LEAP028VI2023                             NaN  2023-06-01
14      LEAP030VI27                Admin Pendidikan  2023-06-27
15    LEAP031VI2018                 Eka Nur Wahyuni  2018-06-08
16       LEAP032I02               GETARI ADYAGARINI  2023-01-02
17    LEAP033VIII05   Maria Florencia Erica Susanto  2022-08-05
18      LEAP034II16                   Mieke Puspita  2022-02-16
19  LEAP035VIII2012                MIFTAKHUL JANNAH  2012-08-07
20       LEAP036I02           Rr. Nisrina Dea Rahma  2023-01-02
21     LEAP037VII04           Siti Uswatun Khasanah  2023-07-04
22      LEAP038VI07                Rini Budi Rahayu  2011-06-07
23     LEAP040VII04                 Agung Wijayanto  2023-07-04
24     LEAP041III25         Vivi Pramitha Wulandari  2023-03-25
25     LEAP042III25  Cantika Swasti Sumarsono Putri  2023-03-25
26    LEAP043VIII01             Trio Fajar Cahyanto  2023-08-01
27     LEAP044X2023               Muifatul Febriani  2023-10-02
28     LEAP046X2023                             NaN  2023-10-01
29     LEAP047XII01           Muhamad Haykal Roziqi  2023-12-01
30   LEAP048XII2023                             NaN  2023-12-21
31      LEAP049II01                     Ana Puspita  2024-02-01
32    LEAP050II2024      Peni Puspa Indarwati, S.S.  2024-02-19
33       LEAP052V02                 Ratna Febrianti  2024-05-02
34     LEAP053VII01                             NaN  2024-07-01
35   LEAP054VII2024        Bryant Frederico Sutanto  2024-07-31
36  LEAP055VIII2024         MUHAMMAD JEFRY MULYANTO  2024-08-26
37  LEAP056VIII2022                    Amat Kasiyan  2022-08-01
38   LEAP057VII2025                       Ulfasiyah  2025-07-14
39      LEAP058VI09                Piotr Pawel Sopa  2025-06-09
40     LEAP059VII14         Amilia Khasanah Marzuki  2025-07-14
41  LEAP060VIII2025       Muhammad Yusril Romadhoni  2025-08-01
42  LEAP061VIII2025        Veronica Febriyanti Adam  2025-08-19
43     LEAP062X2025                     La Erpiadin  2025-10-23
44      LEAP063XI03            Aulia Ratna Meilinda  2025-11-03
45    LEAP064XI2025  PINANGGIH DIMAS PERMANA, S.Kom  2025-11-03
46    LEAP065XI2025                 Retno Wulandari  2025-11-03
47    LEAP066XI2025               Risma Dwi Aryanti  2025-11-03
48    LEAP067XI2025               Moh Rafli Wahyudi  2025-11-26
49     LEAP068I2026       Mochammad Rahmat Muttaqin  2026-01-26
50    LEAP069IV2026            Zaskya Ayra Sinatrya  2026-04-15

In [11]:
import pandas as pd

# Membuat kolom baru untuk konversi bulan menjadi angka romawi
df_old['karyawan']['bulan_romawi'] = df_old['karyawan']['thnbekerja'].apply(lambda x: pd.Period(x).strftime('%B').upper())

# Merubah setiap bulan menjadi angka romawi
bulan_romawi_mapping = {
    'JANUARY': 'I',
    'FEBRUARY': 'II',
    'MARCH': 'III',
    'APRIL': 'IV',
    'MAY': 'V',
    'JUNE': 'VI',
    'JULY': 'VII',
    'AUGUST': 'VIII',
    'SEPTEMBER': 'IX',
    'OCTOBER': 'X',
    'NOVEMBER': 'XI',
    'DECEMBER': 'XII'
}

df_old['karyawan']['bulan_romawi'] = df_old['karyawan']['bulan_romawi'].replace(bulan_romawi_mapping)

# Membuat kolom baru untuk tanggal dan tahun
df_old['karyawan']['tanggal'] = df_old['karyawan']['thnbekerja'].apply(lambda x: pd.Period(x).strftime('%d'))
df_old['karyawan']['tahun'] = df_old['karyawan']['thnbekerja'].apply(lambda x: pd.Period(x).year)

# Update df_old['karyawan']['idkaryawan'] dengan struktur penamaan yang diinginkan

df_old['karyawan']['idkaryawan'] = df_old['karyawan']['idkaryawan'].str[:7] + df_old['karyawan']['tanggal'] + df_old['karyawan']['bulan_romawi'] + df_old['karyawan']['tahun'].astype(str).str[-2:]

# Display only the 'id_karyawan' and 'nama_karyawan' columns
print("\n5. TAMPILAN SEMUA DATA:")
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)
display(df_old['karyawan'][['idkaryawan', 'nama', 'thnbekerja']])

5. TAMPILAN SEMUA DATA:

         idkaryawan                            nama  thnbekerja
0     LEAP00102VI23                             NaN  2023-06-02
1    LEAP00313III23          Graciela Evanda Ronadi  2023-03-13
2    LEAP01101XII20              DANIAR AULIA RIZKI  2020-12-01
3    LEAP01202III20          Habibah Melyna Elfiani  2020-03-02
4    LEAP01431VII18          Laksmi Puspitowardhani  2018-07-31
5     LEAP01514II11                             NaN   14-2-2011
6     LEAP01619VI17              Luluk Fatikah Sari  2017-06-19
7     LEAP01820IV21         Ditari Kurnia Damayanti  2021-04-20
8     LEAP01901VI19                        Hartatik  2019-06-01
9     LEAP02030IV09                   Juni Arlianto  2009-04-30
10     LEAP02301X19      Titi Hapsari Retnaningtias  2019-10-01
11  LEAP02602VIII21                Qorin Rahmaniyah  2021-08-02
12    LEAP02715VI23                             fgz  2023-06-15
13    LEAP02801VI23                             NaN  2023-06-01
14    LEAP03027VI23                Admin Pendidikan  2023-06-27
15    LEAP03108VI18                 Eka Nur Wahyuni  2018-06-08
16     LEAP03202I23               GETARI ADYAGARINI  2023-01-02
17  LEAP03305VIII22   Maria Florencia Erica Susanto  2022-08-05
18    LEAP03416II22                   Mieke Puspita  2022-02-16
19  LEAP03507VIII12                MIFTAKHUL JANNAH  2012-08-07
20     LEAP03602I23           Rr. Nisrina Dea Rahma  2023-01-02
21   LEAP03704VII23           Siti Uswatun Khasanah  2023-07-04
22    LEAP03807VI11                Rini Budi Rahayu  2011-06-07
23   LEAP04004VII23                 Agung Wijayanto  2023-07-04
24   LEAP04125III23         Vivi Pramitha Wulandari  2023-03-25
25   LEAP04225III23  Cantika Swasti Sumarsono Putri  2023-03-25
26  LEAP04301VIII23             Trio Fajar Cahyanto  2023-08-01
27     LEAP04402X23               Muifatul Febriani  2023-10-02
28     LEAP04601X23                             NaN  2023-10-01
29   LEAP04701XII23           Muhamad Haykal Roziqi  2023-12-01
30   LEAP04821XII23                             NaN  2023-12-21
31    LEAP04901II24                     Ana Puspita  2024-02-01
32    LEAP05019II24      Peni Puspa Indarwati, S.S.  2024-02-19
33     LEAP05202V24                 Ratna Febrianti  2024-05-02
34   LEAP05301VII24                             NaN  2024-07-01
35   LEAP05431VII24        Bryant Frederico Sutanto  2024-07-31
36  LEAP05526VIII24         MUHAMMAD JEFRY MULYANTO  2024-08-26
37  LEAP05601VIII22                    Amat Kasiyan  2022-08-01
38   LEAP05714VII25                       Ulfasiyah  2025-07-14
39    LEAP05809VI25                Piotr Pawel Sopa  2025-06-09
40   LEAP05914VII25         Amilia Khasanah Marzuki  2025-07-14
41  LEAP06001VIII25       Muhammad Yusril Romadhoni  2025-08-01
42  LEAP06119VIII25        Veronica Febriyanti Adam  2025-08-19
43     LEAP06223X25                     La Erpiadin  2025-10-23
44    LEAP06303XI25            Aulia Ratna Meilinda  2025-11-03
45    LEAP06403XI25  PINANGGIH DIMAS PERMANA, S.Kom  2025-11-03
46    LEAP06503XI25                 Retno Wulandari  2025-11-03
47    LEAP06603XI25               Risma Dwi Aryanti  2025-11-03
48    LEAP06726XI25               Moh Rafli Wahyudi  2025-11-26
49     LEAP06826I26       Mochammad Rahmat Muttaqin  2026-01-26
50    LEAP06915IV26            Zaskya Ayra Sinatrya  2026-04-15

5. TAMPILAN SEMUA DATA:

         idkaryawan                            nama  thnbekerja
0     LEAP00102VI23                             NaN  2023-06-02
1    LEAP00313III23          Graciela Evanda Ronadi  2023-03-13
2    LEAP01101XII20              DANIAR AULIA RIZKI  2020-12-01
3    LEAP01202III20          Habibah Melyna Elfiani  2020-03-02
4    LEAP01431VII18          Laksmi Puspitowardhani  2018-07-31
5     LEAP01514II11                             NaN   14-2-2011
6     LEAP01619VI17              Luluk Fatikah Sari  2017-06-19
7     LEAP01820IV21         Ditari Kurnia Damayanti  2021-04-20
8     LEAP01901VI19                        Hartatik  2019-06-01
9     LEAP02030IV09                   Juni Arlianto  2009-04-30
10     LEAP02301X19      Titi Hapsari Retnaningtias  2019-10-01
11  LEAP02602VIII21                Qorin Rahmaniyah  2021-08-02
12    LEAP02715VI23                             fgz  2023-06-15
13    LEAP02801VI23                             NaN  2023-06-01
14    LEAP03027VI23                Admin Pendidikan  2023-06-27
15    LEAP03108VI18                 Eka Nur Wahyuni  2018-06-08
16     LEAP03202I23               GETARI ADYAGARINI  2023-01-02
17  LEAP03305VIII22   Maria Florencia Erica Susanto  2022-08-05
18    LEAP03416II22                   Mieke Puspita  2022-02-16
19  LEAP03507VIII12                MIFTAKHUL JANNAH  2012-08-07
20     LEAP03602I23           Rr. Nisrina Dea Rahma  2023-01-02
21   LEAP03704VII23           Siti Uswatun Khasanah  2023-07-04
22    LEAP03807VI11                Rini Budi Rahayu  2011-06-07
23   LEAP04004VII23                 Agung Wijayanto  2023-07-04
24   LEAP04125III23         Vivi Pramitha Wulandari  2023-03-25
25   LEAP04225III23  Cantika Swasti Sumarsono Putri  2023-03-25
26  LEAP04301VIII23             Trio Fajar Cahyanto  2023-08-01
27     LEAP04402X23               Muifatul Febriani  2023-10-02
28     LEAP04601X23                             NaN  2023-10-01
29   LEAP04701XII23           Muhamad Haykal Roziqi  2023-12-01
30   LEAP04821XII23                             NaN  2023-12-21
31    LEAP04901II24                     Ana Puspita  2024-02-01
32    LEAP05019II24      Peni Puspa Indarwati, S.S.  2024-02-19
33     LEAP05202V24                 Ratna Febrianti  2024-05-02
34   LEAP05301VII24                             NaN  2024-07-01
35   LEAP05431VII24        Bryant Frederico Sutanto  2024-07-31
36  LEAP05526VIII24         MUHAMMAD JEFRY MULYANTO  2024-08-26
37  LEAP05601VIII22                    Amat Kasiyan  2022-08-01
38   LEAP05714VII25                       Ulfasiyah  2025-07-14
39    LEAP05809VI25                Piotr Pawel Sopa  2025-06-09
40   LEAP05914VII25         Amilia Khasanah Marzuki  2025-07-14
41  LEAP06001VIII25       Muhammad Yusril Romadhoni  2025-08-01
42  LEAP06119VIII25        Veronica Febriyanti Adam  2025-08-19
43     LEAP06223X25                     La Erpiadin  2025-10-23
44    LEAP06303XI25            Aulia Ratna Meilinda  2025-11-03
45    LEAP06403XI25  PINANGGIH DIMAS PERMANA, S.Kom  2025-11-03
46    LEAP06503XI25                 Retno Wulandari  2025-11-03
47    LEAP06603XI25               Risma Dwi Aryanti  2025-11-03
48    LEAP06726XI25               Moh Rafli Wahyudi  2025-11-26
49     LEAP06826I26       Mochammad Rahmat Muttaqin  2026-01-26
50    LEAP06915IV26            Zaskya Ayra Sinatrya  2026-04-15

In [ ]:
# Analisis df_merged_users untuk duplicate columns, null values, dan informasi lainnya

print("="*80)
print("ANALISIS df_merged_users")
print("="*80)

# 1. Info umum dataframe
print("\n1. INFORMASI UMUM:")
print(f"   Shape: {df_merged_users.shape}")
print(f"   Total Rows: {len(df_merged_users)}")
print(f"   Total Columns: {len(df_merged_users.columns)}")

# 2. Cek duplicate columns
print("\n2. DUPLICATE COLUMNS:")
duplicate_cols = df_merged_users.columns[df_merged_users.columns.duplicated()]
if len(duplicate_cols) > 0:
    print(f"   ⚠️  Ditemukan {len(duplicate_cols)} duplicate column(s):")
    for col in duplicate_cols.unique():
        print(f"      - {col}")
else:
    print("   ✓ Tidak ada duplicate columns")

# 3. Cek null values per column
print("\n3. NULL VALUES PER COLUMN:")
null_counts = df_merged_users.isnull().sum()
null_percentage = (null_counts / len(df_merged_users)) * 100
null_info = pd.DataFrame({
    'Column': null_counts.index,
    'Null_Count': null_counts.values,
    'Null_Percentage': null_percentage.values
}).sort_values('Null_Count', ascending=False)

null_info_display = null_info[null_info['Null_Count'] > 0]
if len(null_info_display) > 0:
    print(null_info_display.to_string(index=False))
else:
    print("   ✓ Tidak ada null values")

# 4. Data types
print("\n4. DATA TYPES:")
# Display data types with a more detailed summary
dtype_summary = pd.DataFrame({
    'Column': df_merged_users.dtypes.index,
    'Data_Type': df_merged_users.dtypes.values
})
print(dtype_summary.to_string(index=False))


print("\n5. VALUE COUNTS PER COLUMN:")
print("=" * 80)

for col in df_merged_users.columns:
    print(f"\n{col}:")
    print(f"  Unique values: {df_merged_users[col].nunique()}")
    if df_merged_users[col].dtype in ['object', 'str', 'int64', 'float64']:
        # Untuk kolom string/object, tampilkan value counts
        value_counts = df_merged_users[col].value_counts(dropna=False)
        if len(value_counts) <= 10:
            print(value_counts)
        else:
            print(value_counts.head(10))
            print(f"  ... dan {len(value_counts) - 10} nilai lainnya")
    else:
        # Untuk kolom numerik, tampilkan statistik
        print(f"  Min: {df_merged_users[col].min()}")
        print(f"  Max: {df_merged_users[col].max()}")
        print(f"  Mean: {df_merged_users[col].mean():.2f}")

In [ ]:
# Analisis df_old['karyawan'] untuk duplicate columns, null values, dan informasi lainnya

print("="*80)
print("ANALISIS df_old['karyawan']")
print("="*80)

# 1. Info umum dataframe
print("\n1. INFORMASI UMUM:")
print(f"   Shape: {df_old['karyawan'].shape}")
print(f"   Total Rows: {len(df_old['karyawan'])}")
print(f"   Total Columns: {len(df_old['karyawan'].columns)}")

# 2. Cek duplicate columns
print("\n2. DUPLICATE COLUMNS:")
duplicate_cols = df_old['karyawan'].columns[df_old['karyawan'].columns.duplicated()]
if len(duplicate_cols) > 0:
    print(f"   ⚠️  Ditemukan {len(duplicate_cols)} duplicate column(s):")
    for col in duplicate_cols.unique():
        print(f"      - {col}")
else:
    print("   ✓ Tidak ada duplicate columns")

# 3. Cek null values per column
print("\n3. NULL VALUES PER COLUMN:")
null_counts = df_old['karyawan'].isnull().sum()
null_percentage = (null_counts / len(df_old['karyawan'])) * 100
null_info = pd.DataFrame({
    'Column': null_counts.index,
    'Null_Count': null_counts.values,
    'Null_Percentage': null_percentage.values
}).sort_values('Null_Count', ascending=False)

null_info_display = null_info[null_info['Null_Count'] > 0]
if len(null_info_display) > 0:
    print(null_info_display.to_string(index=False))
else:
    print("   ✓ Tidak ada null values")

# 4. Data types
print("\n4. DATA TYPES:")
# Display data types with a more detailed summary
dtype_summary = pd.DataFrame({
    'Column': df_old['karyawan'].dtypes.index,
    'Data_Type': df_old['karyawan'].dtypes.values
})
print(dtype_summary.to_string(index=False))


print("\n5. VALUE COUNTS PER COLUMN:")
print("=" * 80)

for col in df_old['karyawan'].columns:
    print(f"\n{col}:")
    print(f"  Unique values: {df_old['karyawan'][col].nunique()}")
    if df_old['karyawan'][col].dtype in ['object', 'str', 'int64', 'float64']:
        # Untuk kolom string/object, tampilkan value counts
        value_counts = df_old['karyawan'][col].value_counts(dropna=False)
        if len(value_counts) <= 10:
            print(value_counts)
        else:
            print(value_counts.head(10))
            print(f"  ... dan {len(value_counts) - 10} nilai lainnya")
    else:
        # Untuk kolom numerik, tampilkan statistik
        print(f"  Min: {df_old['karyawan'][col].min()}")
        print(f"  Max: {df_old['karyawan'][col].max()}")
        print(f"  Mean: {df_old['karyawan'][col].mean():.2f}")

In [ ]:
# Define a dictionary mapping the provided options to their corresponding values
bpjskerja_mapping = {
    '21034278636': '21034278636',
    '21034278651': '21034278651',
    '18088838356': '18088838356',
    '21034278685': '21034278685',
    '17008686762': '17008686762',
    '21034278669': '21034278669',
    '21056548478': '21056548478',
    '23182511560': '23182511560',
    '35782566048': '35782566048',
    '17008687224': '17008687224',
    '23074206378': '23074206378',
    '17008685640': '17008685640',
    '21012951303': '21012951303',
    '23153213873': '23153213873'
}

# Create a new column 'bpjskerja_mapped' with the mapped values
df_old['karyawan']['bpjskerja'] = df_old['karyawan']['bpjskerja'].map(bpjskerja_mapping)

# Replace missing values with None
df_old['karyawan']['bpjskerja'].fillna(value=None, inplace=True)

# Verifikasi hasil
print(df_old['karyawan']['bpjskerja'].value_counts())

In [ ]:
# Define a dictionary mapping the provided options to their corresponding values
anakke_mapping = {
    '1': 1,
    '2': 2,
    'NaN': None,
    '3': 3,
    '-': None,
    'satu': 1,
    '4': 4,
    'Pertama': 1
}

# Create a new column 'anakke' in df_old['karyawan'] with the provided options
df_old['karyawan']['anakke'] = df_old['karyawan']['anakke'].replace(anakke_mapping)

# Verifikasi hasil
print(df_old['karyawan']['anakke'].value_counts())

In [ ]:
# Define a dictionary mapping the provided options to their corresponding values
warga_mapping = {
    'Indonesia': 'WNI',
    'NaN': None,
    'WNI': 'WNI',
    'INDONESIA': 'WNI',
    '-': None,
    'fghn': None,
    'Surabaya': 'WNI'
}

# Create a new column 'warga' in df_old['karyawan'] with the provided options
df_old['karyawan']['warga'] = df_old['karyawan']['warga'].replace(warga_mapping)

# Verifikasi hasil
print(df_old['karyawan']['warga'].value_counts())

In [ ]:
# Define a dictionary mapping the provided options to their corresponding values
goldar_mapping = {
    'O': 'O',
    'B': 'B',
    '-': None,
    'AB': 'AB',
    'Ti': None,
    'O+': 'O+',
    '0': None,
    'A': 'A',
    'fg': None
}

# Create a new column 'goldar' in df_old['karyawan'] with the provided options
df_old['karyawan']['goldar'] = df_old['karyawan']['goldar'].replace(goldar_mapping)

# Verifikasi hasil
print(df_old['karyawan']['goldar'].value_counts())

In [ ]:
# Define a dictionary mapping old values to new values
moda_mapping = {
    'Motor Pribadi':  'Sepeda Motor',
    'Motor pribadi':  'Sepeda Motor',
    'Motor':  'Sepeda Motor',
    '-': None,
    'SEPEDA MOTOR': 'Sepeda Motor',
    'Sepeda Motor Pribadi': 'Sepeda Motor',
    'ghj': None,
    'Sepeda motor': 'Sepeda Motor',
    'Mobil': 'Mobil',
    'sepeda motor': 'Sepeda Motor',
    'Transportasi umum': 'Transportasi Umum',
    'Personal Motor':  'Sepeda Motor',
    'Motor Pribadi':  'Sepeda Motor',
    'Jalan Kaki': 'Jalan Kaki',
    'grab / mobil pribadi': 'Grab / Mobil Pribadi',
    'Sepeda kayuh': 'Sepeda Kayuh',
    'Grab Bike / Car': 'Grab',
    'Tidak ada': None
}

# Use replace() to fix the values in 'moda' column
df_old['karyawan']['moda'] = df_old['karyawan']['moda'].replace(moda_mapping)

# Verifikasi hasil
print(df_old['karyawan']['moda'].value_counts())

In [ ]:
# Menggunakan replace()
df_old['karyawan']['jk'] = df_old['karyawan']['jk'].replace({
    'Wanita': 'Perempuan',
    'Pria': 'Laki-laki',
    'Laki - Laki': 'Laki-laki'
})

# Verifikasi hasil
print(df_old['karyawan']['jk'].value_counts())

In [ ]:
# Standardize agama (religion) values
agama_mapping = {
    'Islam': 'Islam',
    'ISLAM': 'Islam',
    'Kristen': 'Kristen Protestan',
    'Katholik': 'Katolik',
    'Katolik': 'Katolik',
    'Hindu': 'Hindu',
    'djhxt': None,
    'Buddha': 'Buddha',
    'Konghucu': 'Konghucu',
    '-': None,  # Convert '-' to NaN
}

df_old['karyawan']['agama'] = df_old['karyawan']['agama'].replace(agama_mapping)

# Map any remaining values to None (NaN)
df_old['karyawan']['agama'] = df_old['karyawan']['agama'].apply(
    lambda x: x if x in agama_mapping.values() else None
)

df_old['karyawan']['agama'].value_counts()

In [ ]:
# Standardize status pernikahan (marital status) values
status_mapping = {
    'Menikah': 'Menikah',
    'KAWIN': 'Menikah',
    'Kawin': 'Menikah',
    'Belum Menikah': 'Belum Menikah',
    'Belum menikah': 'Belum Menikah',
    'BELUM KAWIN': 'Belum Menikah',
    'Belum Kawin': 'Belum Menikah',
    'Belum kawin': 'Belum Menikah',
    'Single ': 'Belum Menikah',
    'Lajang': 'Belum Menikah',
    'Belum': 'Belum Menikah',
    'Belum nikah ': 'Belum Menikah',
    '-': None,
    'dxhj': None,
}

df_old['karyawan']['status'] = df_old['karyawan']['status'].replace(status_mapping)

# Verify results
df_old['karyawan']['status'].value_counts()

In [ ]:
# Standardize status values (Aktif -> 1, Non Aktif -> 0)
df_merged_users['status'] = df_merged_users['status'].replace({
    'Aktif': 1,
    'Non Aktif': 0
})

# Verify results
df_merged_users['status'].value_counts()

In [ ]:
# # 5. Display semua baris dan kolom
# print("\n5. TAMPILAN SEMUA DATA:")
# pd.set_option('display.max_rows', None)
# pd.set_option('display.max_columns', None)
# pd.set_option('display.width', None)
# pd.set_option('display.max_colwidth', None)
# display(df_merged_users)

In [ ]:
df_new['karyawan'].info()

In [ ]:
df_new['karyawan'].info()

In [ ]:
# df_new['karyawan']['id_karyawan'] = df_old['karyawan']['idkaryawan']
# df_new['karyawan']['id_user'] = df_old['karyawan']['idusers']
# df_new['karyawan']['nik_ktp'] = df_old['karyawan']['ktp']
# df_new['karyawan']['nama_lengkap'] = df_old['karyawan']['nama']
# df_new['karyawan']['nama_panggilan'] = df_old['karyawan']['nickname']
# df_new['karyawan']['tempat_lahir'] = df_old['karyawan']['kota']
# df_new['karyawan']['tanggal_lahir'] = df_old['karyawan']['tgl']
# df_new['karyawan']['jenis_kelamin'] = df_old['karyawan']['jk']
# df_new['karyawan']['golongan_darah'] = df_old['karyawan']['goldar']
# df_new['karyawan']['agama'] = df_old['karyawan']['agama']
# df_new['karyawan']['status_pernikahan'] = df_old['karyawan']['status']
# df_new['karyawan']['alamat_ktp'] = df_old['karyawan']['alamatktp']
# df_new['karyawan']['alamat_domisili'] = df_old['karyawan']['domisili']
# df_new['karyawan']['kewarganegaraan'] = df_old['karyawan']['warga']
# df_new['karyawan']['anak_ke'] = df_old['karyawan']['anakke']
# df_new['karyawan']['jumlah_anak'] = df_old['karyawan']['anak']
# df_new['karyawan']['hobi'] = df_old['karyawan']['hobi']
# df_new['karyawan']['akun_linkedin'] = df_old['karyawan']['linkedin']
# df_new['karyawan']['email_pribadi'] = df_old['karyawan']['email']
# df_new['karyawan']['email_kantor'] = df_old['karyawan']['emailkantor']
# df_new['karyawan']['nomor_telepon'] = df_old['karyawan']['telp']
# df_new['karyawan']['nomor_npwp'] = df_old['karyawan']['npwp']
# df_new['karyawan']['bpjs_ketenagakerjaan'] = df_old['karyawan']['bpjskerja']
# df_new['karyawan']['bpjs_kesehatan'] = df_old['karyawan']['bpjssehat']
# df_new['karyawan']['nomor_rekening'] = df_old['karyawan']['rekening']
# df_new['karyawan']['moda_transportasi'] = df_old['karyawan']['moda']
# df_new['karyawan']['akun_instagram'] = df_old['karyawan']['ig']
# df_new['karyawan']['akun_facebook'] = df_old['karyawan']['fb']
# df_new['karyawan']['link_dokumen_pribadi'] = df_old['karyawan']['link']
# df_new['karyawan']['riwayat_kesehatan'] = df_old['karyawan']['riwayat']
# df_new['karyawan']['tahun_mulai_kerja'] = df_old['users']['thnbekerja']
# df_new['karyawan']['keahlian'] = df_old['users']['expertise']
# df_new['karyawan']['id_shift'] = df_old['users']['idjamkerja']
# df_new['karyawan']['status_aktif'] = df_old['users']['status']
# df_new['karyawan']['foto_profile'] = df_old['users']['foto']
# df_new['karyawan']['ttd_digital'] = df_old['users']['ttd']

## 4. Insert ke DB Baru

## 5. Verifikasi Data

## 6. Return Hasil Migrasi untuk migrate_db.py

## 7. Close Connection