In [1]:
import sys
import os
import mysql.connector
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Ambil konfigurasi database dari folder utama project kalian
sys.path.append(os.path.abspath('..'))
from config import get_db_config

config = get_db_config()

# 1. Koneksi ke Database Baru (Fase Migrasi Sekarang)
db_new = mysql.connector.connect(**config['db_new'])
cursor_new = db_new.cursor(dictionary=True)

# 2. Koneksi ke Database Masa Depan (DB_FUTURE)
# Catatan: Pastikan di file config.py kalian sudah ada key 'db_future' ya!
db_future = mysql.connector.connect(**config['db_future'])
cursor_future = db_future.cursor(dictionary=True)

print(f"✅ Sukses Terhubung ke Database Baru : {config['db_new']['database']}")
print(f"🚀 Sukses Terhubung ke DB_FUTURE     : {config['db_future']['database']}")

✅ Sukses Terhubung ke Database Baru : 5
🚀 Sukses Terhubung ke DB_FUTURE     : 5

In [2]:
# # ==============================================================================
# # 1. VARIABEL UNTUK CIMUT
# # ==============================================================================
# tables_to_check = [
#     # Fase 1: Persiapan Master Data
#     "users",
#     "divisions",
#     "shift_kerja",
#     "admin_sarpras",
    
#     # Fase 2: Pendataan SDM & Wilayah Detail
#     "karyawan",
#     "keluarga_karyawan",
#     "bidang_kategori",
#     "bidang_link",
    
#     # Fase 3: Operasional, CRM & Pendaftaran (Fokus Utama)
#     "kontak_prospek",
#     "calon_siswa",
#     "calon_siswa_akademik",
#     "calon_siswa_ortu",
#     "calon_siswa_bayar",
#     "calon_siswa_jadwal",
#     "calon_siswa_kursus",
#     "calon_siswa_proses",
#     "peminjaman",
#     "pengadaan",
#     "problem",
    
#     # Fase 4: Penjadwalan & Siswa Aktif
#     "izin_karyawan",
#     "verifikasi_izin",
#     "absensi",
#     "verifikasi_absensi",
#     "karyawan_resign",

# ]

In [3]:


# ==============================================================================
# 2. VARIABEL UNTUK AFRIDA
# ==============================================================================
tables_to_check = [
    # Fase 1: Persiapan Master Data
    "kursus",
    "level",
    "sesi",
    "libur",
    "topik_diskusi",
    "kursus_level",
    "kursus_libur",
    
    # Fase 2: Pendataan SDM & Wilayah Detail
    "periode",
    "parameter_nilai",
    "kabupaten",
    "kecamatan",
    
    # Fase 3: Operasional, CRM & Pendaftaran
    "sop",
    "surat_keluar",
    "verifikasi_surat_keluar",
    "surat_tugas",
    "surat_tugas_anggota",
    "sop_kategori",
    
    # Fase 4: Penjadwalan & Siswa Aktif (Fokus Utama)
    "jadwal",
    "jadwal_hari",
    "jadwal_detail",
    "jadwal_pengajar",
    "jadwal_siswa",
    "catatan_kelas",
    "catatan_kelas_tag",
    "catatan_mingguan",
    
    # Fase 5: Penilaian & Finalisasi
    "presensi_siswa",
    "catatan_siswa",
    "followup_cs"
]

In [4]:
# # ==============================================================================
# # 3. VARIABEL UNTUK HANIF
# # ==============================================================================
# tables_to_check = [
#     # Fase 1: Persiapan Master Data
#     "roles",
#     "permissions",
#     "role_has_permissions",
#     "busdev_bidang",
#     "syarat_resign",
#     "ttd",
#     "tag_siswa_keluar",
    
#     # Fase 2: Pendataan SDM & Wilayah Detail
#     "division_user",
#     "model_has_roles",
#     "model_has_permissions",
#     "kelurahan",
    
#     # Fase 3: Operasional, CRM & Pendaftaran
#     "pengajuan_karyawan",
#     "histori_pengajuan",
#     "pelamar",
#     "pelamar_kerja",
#     "pelamar_sekolah",
#     "pelamar_kursus",
#     "progres_pelamar",
#     "rekrutmen_pelamar",
    
#     # Fase 4: Penjadwalan & Siswa Aktif (Fokus Utama)
#     "siswa",
#     "kursus_siswa",
#     "siswa_keluar",
#     "mitra",
#     "mitra_progres",
#     "kemitraan_verifikator",
#     "siswa_mitra",
#     "siswa_mitra_keluar",
    
#     # Fase 5: Penilaian & Finalisasi (Fokus Utama)
#     "rapor_format",
#     "rapor_format_sub",
#     "rapor_format_formula",
#     "rapor_format_formula_sub",
#     "rapor_level_config",
#     "rapor_sub_level",
#     "rapor_siswa",
#     "rapor_siswa_file",
#     "rapor_lacak"
# ]

In [5]:
import pandas as pd
import numpy as np

print("================================================================================")
print(" 🚀 BLUEPRINT INSPECTOR: SCAN SPESIFIK TABEL DI DB_FUTURE 🚀 ")
print("================================================================================")

print(f"Memulai inspeksi untuk {len(tables_to_check)} tabel spesifik di {config['db_future']['database']}...\n")

# --- TAHAP INSPEKSI & RENDER VISUAL ---
for table in tables_to_check:
    try:
        # 2. Ambil sampel data dari tabel di DB_FUTURE
        query_data = f"SELECT * FROM `{table}`"
        df_real_data = pd.read_sql(query_data, db_future)
        
        # 3. Tarik Struktur Fisik Kolom murni dari DB_FUTURE
        query_struct = f"""
        SELECT 
            c.COLUMN_NAME AS 'Nama Kolom',
            c.COLUMN_TYPE AS 'Tipe Data MySQL',
            CONCAT(
                CASE WHEN c.IS_NULLABLE = 'YES' THEN '✅ NULL (Boleh Kosong)' ELSE '🛑 NOT NULL (Wajib Isi)' END,
                CASE WHEN c.EXTRA = 'auto_increment' THEN '\\n🚀 AUTO_INCREMENT' ELSE '' END
            ) AS 'Aturan Nullability & Increment',
            CASE 
                WHEN c.COLUMN_KEY = 'PRI' THEN '🔑 PRIMARY KEY (PK)'
                WHEN c.COLUMN_KEY = 'MUL' AND k.REFERENCED_TABLE_NAME IS NOT NULL THEN '🔗 FOREIGN KEY (FK)'
                WHEN c.COLUMN_KEY = 'MUL' THEN 'INDEX'
                ELSE '-'
            END AS 'Status Kunci',
            CASE 
                WHEN k.REFERENCED_TABLE_NAME IS NOT NULL THEN CONCAT(k.REFERENCED_TABLE_NAME, ' (', k.REFERENCED_COLUMN_NAME, ')')
                ELSE '-'
            END AS 'Rujukan Induk (FK Origin)',
            CASE WHEN c.DATA_TYPE = 'enum' THEN REPLACE(REPLACE(REPLACE(c.COLUMN_TYPE, 'enum(', ''), ')', ''), "'", "") ELSE '-' END AS 'Daftar Pilihan ENUM'
        FROM INFORMATION_SCHEMA.COLUMNS c
        LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE k 
            ON c.TABLE_SCHEMA = k.TABLE_SCHEMA AND c.TABLE_NAME = k.TABLE_NAME AND c.COLUMN_NAME = k.COLUMN_NAME
        WHERE c.TABLE_SCHEMA = '{config['db_future']['database']}' AND c.TABLE_NAME = '{table}'
        ORDER BY c.ORDINAL_POSITION;
        """
        df_struct = pd.read_sql(query_struct, db_future).drop_duplicates(subset=['Nama Kolom'], keep='first').reset_index(drop=True)
        
        # Cek jika tabel ternyata tidak ada (typo atau belum dibuat)
        if df_struct.empty:
            print(f"\n================================================================================")
            print(f"❌ TABEL: {table.upper()} (TIDAK DITEMUKAN DI DB_FUTURE)")
            print(f"================================================================================")
            continue

        # 4. Lacak tabel anak yang menjadikan PK tabel ini sebagai FK mereka
        pk_referenced_list = []
        for idx, row_skri in df_struct.iterrows():
            if row_skri['Status Kunci'] == '🔑 PRIMARY KEY (PK)':
                lookup_fk_query = f"""
                SELECT CONCAT(TABLE_NAME, ' (', COLUMN_NAME, ')') as relasi
                FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
                WHERE REFERENCED_TABLE_SCHEMA = '{config['db_future']['database']}'
                  AND REFERENCED_TABLE_NAME = '{table}'
                  AND REFERENCED_COLUMN_NAME = '{row_skri['Nama Kolom']}';
                """
                df_relasi_luar = pd.read_sql(lookup_fk_query, db_future)
                if not df_relasi_luar.empty:
                    pk_referenced_list.append("\n".join(df_relasi_luar['relasi'].tolist()))
                else:
                    pk_referenced_list.append("-")
            else:
                pk_referenced_list.append("-")
        df_struct['Tabel Yang nge-FK ke Sini'] = pk_referenced_list

        # ---------------------------------------------------------
        # TAMPILAN RENDER PAPAN INFO
        # ---------------------------------------------------------
        print(f"\n================================================================================")
        print(f"📦 TABEL: {table.upper()}")
        print(f"================================================================================")
        
        print(f"📋 1. Karakteristik Wadah Pandas Dataframe (.info()):")
        df_real_data.info()
        print("\n" + "-"*60)
        
        print(f"🔍 2. Arsitektur Fisik Kolom pada DB_FUTURE:")
        display(df_struct.style.set_properties(**{'white-space': 'pre-wrap', 'text-align': 'left'}))
        print("\n" + "-"*60)
        
        print(f"📸 3. Sampel Isi Data Real di DB_FUTURE (Menampilkan Max 5 Baris Teratas):")
        # Menggunakan .head(5) agar visualisasi layar tidak terlalu panjang
        display(df_real_data if not df_real_data.empty else df_real_data)
        print("\n" + "="*80)
            
    except Exception as e:
        print(f"❌ Gagal menganalisis tabel `{table}`: {e}")

print("\n🎉 SCANNING SELESAI! 🎉")

================================================================================
 🚀 BLUEPRINT INSPECTOR: SCAN SPESIFIK TABEL DI DB_FUTURE 🚀
================================================================================
Memulai inspeksi untuk 28 tabel spesifik di 5...

================================================================================
📦 TABEL: KURSUS
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_kursus     20 non-null     object
 1   nama_kursus   20 non-null     object
 2   deskripsi     20 non-null     object
 3   tipe_kursus   20 non-null     object
 4   status_arsip  20 non-null     int64
dtypes: int64(1), object(4)
memory usage: 932.0+ bytes

------------------------------------------------------------
🔍 2. Arsitektur Fisik Kolom pada DB_FUTURE:

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_FUTURE (Menampilkan Max 5 Baris Teratas):

,id_kursus,nama_kursus,deskripsi,tipe_kursus,status_arsip
0,K00001,LEAP - General English,"GE, Balloons, Gogo, SO, Winner",B2C,0
1,K00002,LEAP - Coding Class,Coding Class Regular,B2C,0
2,K00003,LEAP - Leap Literacy Club,LLC,B2C,0
3,K00004,LEAP - Conversation Class,Conversation Class for Adults,B2C,0
4,K00005,LEAP - Aplikasi Perkantoran,"All In, Private,",B2C,0
5,K00006,Kemitraan - B2B Supervisi Guru,Nurul Faizah,B2B,0
6,K00007,Kemitraan - B2B Business English,"Delta Jaya, Hartono, PT HCA",B2B,0
7,K00009,Kemitraan - B2C Talentvis,Talentvis,B2B,0
8,K00010,LEAP - General English 2024,NEW CURRICULUM 2024,B2C,0
9,K00011,Kemitraan - B2B Language Upskilling Program,Nurul Faizah Agt 24 - Mei 25,B2B,0
10,K00012,Kemitraan - B2B Ekskul Coding 1,SD AL Muslim,B2B,0
11,K00013,LEAP - LX,Leapxperience,B2C,0
12,K00014,LEAP - Coding Class 2024,NEW CURRICULUM DOYOBI 2024,B2C,0
13,K00015,LEAP - Coding Class 2025,NEW CURR BSD EDU,B2C,0
14,K00016,LEAP - Leap Literacy Club 2025,LLC NEW LEVEL NAME,B2C,0
15,K00018,Kemitraan - B2B Ekskul Coding 2025,"Artistic Coders, Bot Chatters, Curious Creator...",B2B,0
16,K00019,Kemitraan - B2B Rupin General English,Gogo,B2B,0
17,K00020,Kemitraan - B2B Rupin Komputer,"Ms. Word, Excel, PPT",B2B,0
18,K00021,Kemitraan - B2B TK Mitra,"TK Mitra MJ (Seperti Balloons): Agripina, Al W...",B2B,0
19,K00022,Kemitraan - B2B CC Mitra,Convo for kids MJ,B2B,0

================================================================================

================================================================================
📦 TABEL: LEVEL
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181 entries, 0 to 180
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_level      181 non-null    object
 1   nama_level    181 non-null    object
 2   urutan_level  181 non-null    int64
dtypes: int64(1), object(2)
memory usage: 4.4+ KB

------------------------------------------------------------
🔍 2. Arsitektur Fisik Kolom pada DB_FUTURE:

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_FUTURE (Menampilkan Max 5 Baris Teratas):

    id_level   nama_level  urutan_level
0     L00001  Balloons 1A             1
1     L00002  Balloons 1B             2
2     L00003  Balloons 1C             3
3     L00004  Balloons 2A             4
4     L00005  Balloons 2B             5
..       ...          ...           ...
176   L00185            4             4
177   L00186            1             1
178   L00187            2             2
179   L00188            3             3
180   L00189            4             4

[181 rows x 3 columns]

================================================================================

================================================================================
📦 TABEL: SESI
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_sesi        43 non-null     object
 1   nama_sesi      43 non-null     object
 2   waktu_mulai    43 non-null     timedelta64[ns]
 3   waktu_selesai  43 non-null     timedelta64[ns]
dtypes: object(2), timedelta64[ns](2)
memory usage: 1.5+ KB

------------------------------------------------------------
🔍 2. Arsitektur Fisik Kolom pada DB_FUTURE:

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_FUTURE (Menampilkan Max 5 Baris Teratas):

   id_sesi                      nama_sesi     waktu_mulai   waktu_selesai
0   S00001                  GE/LLC Sesi 1 0 days 15:45:00 0 days 16:45:00
1   S00002                  GE/LLC Sesi 2 0 days 17:00:00 0 days 18:00:00
2   S00003                  GE/LLC Sesi 3 0 days 18:15:00 0 days 19:15:00
3   S00004                 CC Kids Sesi 1 0 days 10:10:00 0 days 11:10:00
4   S00005                CC Adult Sesi 1 0 days 16:00:00 0 days 17:00:00
5   S00006                CC Adult Sesi 3 0 days 20:00:00 0 days 21:00:00
6   S00007                  CODING Sesi 1 0 days 15:00:00 0 days 16:00:00
7   S00008                  CODING Sesi 2 0 days 16:00:00 0 days 17:00:00
8   S00009                  CODING Sesi 3 0 days 17:00:00 0 days 18:00:00
9   S00010                  CODING Sesi 4 0 days 17:45:00 0 days 18:45:00
10  S00011                   Nurul Faizah 0 days 07:35:00 0 days 09:55:00
11  S00012           BE Delta Jaya Sesi 1 0 days 13:00:00 0 days 14:30:00
12  S00013           BE Delta Jaya Sesi 2 0 days 14:45:00 0 days 16:15:00
13  S00014               Talentvis Sesi 1 0 days 10:00:00 0 days 12:30:00
14  S00015               Talentvis Sesi 2 0 days 13:00:00 0 days 16:00:00
15  S00016              BE HARTONO Sesi 1 0 days 09:00:00 0 days 10:00:00
16  S00017              BE HARTONO Sesi 2 0 days 10:30:00 0 days 12:00:00
17  S00018                CC Adult Sesi 2 0 days 18:15:00 0 days 19:15:00
18  S00019  Language Upskilling Program 1 0 days 14:55:00 0 days 15:55:00
19  S00020           Ekskul Coding SESI 1 0 days 14:00:00 0 days 15:30:00
20  S00021          BE HARTONO NEW SESI 1 0 days 08:00:00 0 days 09:00:00
21  S00022          BE HARTONO NEW SESI 2 0 days 08:00:00 0 days 09:30:00
22  S00023          BE HARTONO NEW SESI 3 0 days 09:15:00 0 days 10:15:00
23  S00024          BE HARTONO NEW SESI 4 0 days 09:45:00 0 days 11:15:00
24  S00025          BE HARTONO NEW SESI 5 0 days 10:45:00 0 days 11:45:00
25  S00026          BE HARTONO NEW SESI 6 0 days 11:30:00 0 days 13:00:00
26  S00027          BE HARTONO NEW SESI 7 0 days 12:00:00 0 days 13:00:00
27  S00028       SESI COBA JANGAN DIHAPUS 0 days 11:26:00 0 days 13:26:00
28  S00029                  CODING Sesi 5 0 days 18:00:00 0 days 19:00:00
29  S00030           Ekskul Coding SESI 2 0 days 14:10:00 0 days 15:10:00
30  S00031               RUPIN BSI SESI 4 0 days 13:00:00 0 days 14:00:00
31  S00032               RUPIN BSI SESI 5 0 days 14:30:00 0 days 15:30:00
32  S00033             TK MITRA MJ Sesi 1 0 days 07:45:00 0 days 09:15:00
33  S00034             TK MITRA MJ Sesi 2 0 days 09:00:00 0 days 10:00:00
34  S00035             TK MITRA MJ Sesi 3 0 days 09:00:00 0 days 10:30:00
35  S00036             TK MITRA MJ Sesi 4 0 days 10:45:00 0 days 11:45:00
36  S00037             TK MITRA MJ Sesi 5 0 days 10:50:00 0 days 11:50:00
37  S00038             TK MITRA MJ Sesi 6 0 days 11:00:00 0 days 12:00:00
38  S00039             TK MITRA MJ Sesi 7 0 days 11:30:00 0 days 12:30:00
39  S00040             TK MITRA MJ Sesi 8 0 days 12:00:00 0 days 13:00:00
40  S00041             TK MITRA MJ Sesi 9 0 days 12:30:00 0 days 13:30:00
41  S00042                CC Adult Sesi 3 0 days 19:00:00 0 days 20:00:00
42  S00043               BE PT HCA SESI 1 0 days 15:00:00 0 days 17:00:00

================================================================================

================================================================================
📦 TABEL: LIBUR
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id_libur              78 non-null     object
 1   nama_event            78 non-null     object
 2   deskripsi_libur       78 non-null     object
 3   tanggal_mulai         78 non-null     object
 4   tanggal_berakhir      78 non-null     object
 5   label_warna           78 non-null     object
 6   status_libur_program  78 non-null     int64
dtypes: int64(1), object(6)
memory usage: 4.4+ KB

------------------------------------------------------------
🔍 2. Arsitektur Fisik Kolom pada DB_FUTURE:

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_FUTURE (Menampilkan Max 5 Baris Teratas):

,id_libur,nama_event,deskripsi_libur,tanggal_mulai,tanggal_berakhir,label_warna,status_libur_program
0,L00005,Libur Nasional,Libur Tahun Baru Islam,2023-07-19,2023-07-20,fc-event-default,1
1,L00006,Libur Nasional,Libur Idul Adha,2023-06-29,2023-06-30,fc-event-default,1
2,L00007,Tahun Baru Islam 2023,Libur Tahun Baru Islam 2023,2023-07-19,2023-07-20,fc-event-default,1
3,L00008,Natal,Libur Natal,2023-12-22,2023-12-30,fc-event-default,1
4,L00009,Tahun Baru,Libur Tahun Baru,2024-01-01,2024-01-02,fc-event-default,1
...,...,...,...,...,...,...,...
73,L00083,Perkiraan 2027 Maulid Nabi,Perkiraan 2027,2027-08-15,2027-08-16,fc-event-default,1
74,L00084,Perkiraan 2027 Hari Kemerdekaan,Perkiraan 2027,2027-08-17,2027-08-18,fc-event-default,1
75,L00085,Perkiraan 2027 Nataru,Perkiraan 2027,2027-12-25,2028-01-01,fc-event-default,1
76,L00086,Perkiraan 2027,Perkiraan 2027,2027-12-26,2027-12-27,fc-event-default,1
77,L00087,Idul Adha,2026,2026-05-27,2026-05-28,fc-event-default,1

================================================================================

================================================================================
📦 TABEL: TOPIK_DISKUSI
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 3 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id_topik_diskusi         11 non-null     int64
 1   topik_diskusi            11 non-null     object
 2   deskripsi_topik_diskusi  11 non-null     object
dtypes: int64(1), object(2)
memory usage: 396.0+ bytes

------------------------------------------------------------
🔍 2. Arsitektur Fisik Kolom pada DB_FUTURE:

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_FUTURE (Menampilkan Max 5 Baris Teratas):

,id_topik_diskusi,topik_diskusi,deskripsi_topik_diskusi
0,1,Kendala Siswa,"Siswa yang sering membuat onar dikelas, siswa ..."
1,2,Kendala Kelas,Situasi dan kondisi kelas yang mengganggu atau...
2,3,Kendala Jadwal,Jika terinfo bahwa siswa memiliki jadwal yang ...
3,4,Ujian Susulan & Remidi,Tidak ada deskripsi
4,5,"Kendala Zoom, Class In, Koneksi & Device",Tidak ada deskripsi
5,6,Update Diskusi,Tidak ada deskripsi
6,7,Siswa Off/Postponed/Pindah Program,Tidak ada deskripsi
7,8,Progress Siswa,Tidak ada deskripsi
8,9,Update Siswa Sit-in/Trial/Baru,Tidak ada deskripsi
9,10,Siswa Tidak Naik,Tidak ada deskripsi
10,11,Tambahan Sesi,Tambahan Sesi

================================================================================

================================================================================
📦 TABEL: KURSUS_LEVEL
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 177 entries, 0 to 176
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_kursus_level  177 non-null    int64
 1   id_kursus        177 non-null    object
 2   id_level         177 non-null    object
dtypes: int64(1), object(2)
memory usage: 4.3+ KB

------------------------------------------------------------
🔍 2. Arsitektur Fisik Kolom pada DB_FUTURE:

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_FUTURE (Menampilkan Max 5 Baris Teratas):

     id_kursus_level id_kursus id_level
0                  1    K00001   L00001
1                  2    K00001   L00002
2                  3    K00001   L00003
3                  4    K00001   L00004
4                  5    K00001   L00005
..               ...       ...      ...
172              173    K00021   L00183
173              174    K00022   L00186
174              175    K00022   L00187
175              176    K00022   L00188
176              177    K00022   L00189

[177 rows x 3 columns]

================================================================================

================================================================================
📦 TABEL: KURSUS_LIBUR
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_kursus_libur  1 non-null      int64
 1   id_kursus        1 non-null      object
 2   id_libur         1 non-null      object
dtypes: int64(1), object(2)
memory usage: 156.0+ bytes

------------------------------------------------------------
🔍 2. Arsitektur Fisik Kolom pada DB_FUTURE:

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_FUTURE (Menampilkan Max 5 Baris Teratas):

   id_kursus_libur id_kursus id_libur
0                1    K00001   L00068

================================================================================

================================================================================
📦 TABEL: PERIODE
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91 entries, 0 to 90
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_periode     91 non-null     object
 1   nama_periode   91 non-null     object
 2   tanggal_mulai  91 non-null     object
 3   id_kursus      91 non-null     object
 4   jumlah_sesi    91 non-null     int64
 5   tahun_ajar     91 non-null     object
 6   status         91 non-null     int64
 7   is_active      91 non-null     int64
dtypes: int64(3), object(5)
memory usage: 5.8+ KB

------------------------------------------------------------
🔍 2. Arsitektur Fisik Kolom pada DB_FUTURE:

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_FUTURE (Menampilkan Max 5 Baris Teratas):

,id_periode,nama_periode,tanggal_mulai,id_kursus,jumlah_sesi,tahun_ajar,status,is_active
0,P00006,General English Term I July-October 2023,2023-07-04,K00001,30,2023/2024,1,1
1,P00008,General English Term II Oct '23 - Feb '24,2023-10-25,K00001,30,2023/2024,1,1
2,P00009,General English Term III Feb-Jun 2024,2024-02-21,K00001,30,2023/2024,1,1
3,P00010,Coding Semester I-2023/2024,2023-08-01,K00002,18,2023/2024,1,1
4,P00011,Coding Semester II-2023/2024,2024-01-23,K00002,18,2023/2024,1,1
...,...,...,...,...,...,...,...,...
86,P00102,RUPIN BSI Program Komputer JUL-DES 2026,2026-07-02,K00020,43,2025/2026,1,1
87,P00103,Kemitraan - TK MITRA MJ JAN-MEI 2026,2026-01-05,K00021,34,2025/2026,1,1
88,P00105,Kemitraan - CC MITRA MJ JAN-MEI 2026,2026-01-05,K00022,34,2025/2026,1,1
89,P00106,Kemitraan - Ekskul Coding (Al Muslim),2026-08-01,K00012,30,2026,1,1
90,P00107,Kemitraan BE - PT HCA,2026-05-04,K00007,24,2025/2026,1,1

================================================================================

================================================================================
📦 TABEL: PARAMETER_NILAI
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7122 entries, 0 to 7121
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_parameter_nilai  7122 non-null   int64
 1   id_level            7122 non-null   object
 2   nama_parameter      7122 non-null   object
 3   status_parameter    7122 non-null   int64
dtypes: int64(2), object(2)
memory usage: 222.7+ KB

------------------------------------------------------------
🔍 2. Arsitektur Fisik Kolom pada DB_FUTURE:

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_FUTURE (Menampilkan Max 5 Baris Teratas):

      id_parameter_nilai id_level       nama_parameter  status_parameter
0                      1   L00022  Class participation                 0
1                      2   L00022                 Oral                 0
2                      3   L00022            Listening                 0
3                      4   L00022              Writing                 0
4                      5   L00022            Writing-1                 1
...                  ...      ...                  ...               ...
7117                7118   L00184                Grade                 0
7118                7119   L00184             Comments                 0
7119                7120   L00185            listening                 1
7120                7121   L00185             speaking                 1
7121                7122   L00185              writing                 1

[7122 rows x 4 columns]

================================================================================

================================================================================
📦 TABEL: KABUPATEN
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_kabupaten    0 non-null      object
 1   id_provinsi     0 non-null      object
 2   nama_kabupaten  0 non-null      object
 3   code            0 non-null      object
dtypes: object(4)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. Arsitektur Fisik Kolom pada DB_FUTURE:

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_FUTURE (Menampilkan Max 5 Baris Teratas):

Empty DataFrame
Columns: [id_kabupaten, id_provinsi, nama_kabupaten, code]
Index: []

================================================================================

================================================================================
📦 TABEL: KECAMATAN
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_kecamatan    0 non-null      object
 1   id_kabupaten    0 non-null      object
 2   nama_kecamatan  0 non-null      object
 3   code            0 non-null      object
dtypes: object(4)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. Arsitektur Fisik Kolom pada DB_FUTURE:

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_FUTURE (Menampilkan Max 5 Baris Teratas):

Empty DataFrame
Columns: [id_kecamatan, id_kabupaten, nama_kecamatan, code]
Index: []

================================================================================

================================================================================
📦 TABEL: SOP
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_sop            8 non-null      int64
 1   id_sop_kategori   8 non-null      int64
 2   judul_sop         8 non-null      object
 3   link_dokumen_sop  8 non-null      object
 4   created_at        8 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(2), object(2)
memory usage: 452.0+ bytes

------------------------------------------------------------
🔍 2. Arsitektur Fisik Kolom pada DB_FUTURE:

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_FUTURE (Menampilkan Max 5 Baris Teratas):

,id_sop,id_sop_kategori,judul_sop,link_dokumen_sop,created_at
0,5,1,Akhir Penggunaan Kelas English (19.15 WIB),https://drive.google.com/file/d/1V0MpB7ctzPHe6...,2023-07-07 08:52:48
1,6,2,Penerimaan Surat Masuk,https://drive.google.com/file/d/1G8lO33yU7MufC...,2023-11-22 15:27:06
2,7,2,Pengajuan Surat Keluar,https://drive.google.com/file/d/14I7wYSk62WJAv...,2023-11-22 15:27:55
3,8,2,Pengajuan Surat Tugas,https://drive.google.com/file/d/1R-wKFqQeVSz62...,2023-11-22 15:28:27
4,9,1,Akhir Penggunaan Kelas English (19.15 WIB),https://drive.google.com/file/d/1V0MpB7ctzPHe6...,2023-07-07 08:52:48
5,10,2,Penerimaan Surat Masuk,https://drive.google.com/file/d/1G8lO33yU7MufC...,2023-11-22 15:27:06
6,11,2,Pengajuan Surat Keluar,https://drive.google.com/file/d/14I7wYSk62WJAv...,2023-11-22 15:27:55
7,12,2,Pengajuan Surat Tugas,https://drive.google.com/file/d/1R-wKFqQeVSz62...,2023-11-22 15:28:27

================================================================================

================================================================================
📦 TABEL: SURAT_KELUAR
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 213 entries, 0 to 212
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_sk            213 non-null    int64
 1   id_user          213 non-null    object
 2   keterangan_sk    213 non-null    object
 3   link_dokumen_sk  213 non-null    object
 4   status_sk        213 non-null    object
 5   nomor_sk         213 non-null    object
 6   catatan_sk       213 non-null    object
 7   created_at       213 non-null    datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(6)
memory usage: 13.4+ KB

------------------------------------------------------------
🔍 2. Arsitektur Fisik Kolom pada DB_FUTURE:

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_FUTURE (Menampilkan Max 5 Baris Teratas):

,id_sk,id_user,keterangan_sk,link_dokumen_sk,status_sk,nomor_sk,catatan_sk,created_at
0,24,U00011,Surat Permohonan Uji Kompetensi dan Penggunaan...,https://docs.google.com/document/d/1xyhc4T-FlR...,Sudah Revisi,090A/LEAP/IX/2023- 090B/LEAP/IX/2023,Lengkapi Tanggal Pelaksanaan dengan tanggal ya...,2023-09-11 17:57:49
1,26,U00011,Beasiswa Siswa GE,https://docs.google.com/document/d/1jMTK_3b57e...,Disetujui,101/LEAP/BD/X/2023,Tidak ada catatan,2023-10-25 16:57:38
2,27,U00011,PERJANJIAN KERJASAMA / MEMORANDUM OF UNDERSTAN...,https://docs.google.com/document/d/1Edeb7hWaBq...,Disetujui,102/LEAP/BD/X/2023,Tidak ada catatan,2023-10-26 17:37:59
3,28,U00026,Sertifikat / Sertifikat Kelas APK Private / 1 ...,https://drive.google.com/drive/folders/1JMrPJF...,Disetujui,Sertif 002a/APEX/XI/2324/02 (Page 1) dan 002b/...,Tidak ada catatan,2023-11-10 16:10:04
4,29,U00011,Penawaran Pelatihan Business English ke PT. La...,https://docs.google.com/document/d/1wBK62noEJw...,Disetujui,105/LEAP/BD/XI/2023,Tidak ada catatan,2023-11-13 15:41:58
...,...,...,...,...,...,...,...,...
208,248,U00016,Jurnal Siswa & Laporan Akhir Community Service...,https://docs.google.com/document/d/1QJOQCHDN3j...,Disetujui,Nomor surat belum diisi,Tidak ada catatan,2026-04-07 14:44:54
209,250,U00033,Pelaporan Hasil Ujian Susulan Semester Genap K...,https://drive.google.com/file/d/14MFeTQ6SsupYk...,Disetujui,042/PDDK/SKET/LEAP/IV/2026,Tidak ada catatan,2026-04-14 13:51:55
210,251,U00023,MoM Rupin (Mid Semester Evaluation & Next Batc...,https://docs.google.com/document/d/1s3G_jzBIlH...,Disetujui,043/PDDK/MoM/LEAP/IV/2026,Tidak ada catatan,2026-04-16 08:51:31
211,252,U00034,Surat Izin Uji Coba Proyek SMPN 13,https://docs.google.com/document/d/14r8_bXEJjl...,Disetujui,046/PDDK/PM/LEAP/IV/2026,Tidak ada catatan,2026-04-17 15:38:24
212,253,U00034,Surat Izin Uji Coba Proyek SMPN 35,https://docs.google.com/document/d/1tleVpLUO0j...,Disetujui,045/PDDK/PM/LEAP/IV/2026,Tidak ada catatan,2026-04-17 16:01:39

================================================================================

================================================================================
📦 TABEL: VERIFIKASI_SURAT_KELUAR
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1431 entries, 0 to 1430
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id_verifikasi_surat    1431 non-null   int64
 1   id_sk                  1326 non-null   float64
 2   status_verifikasi_sk   1431 non-null   object
 3   catatan_verifikasi_sk  1431 non-null   object
 4   created_at             1431 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(1), object(2)
memory usage: 56.0+ KB

------------------------------------------------------------
🔍 2. Arsitektur Fisik Kolom pada DB_FUTURE:

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_FUTURE (Menampilkan Max 5 Baris Teratas):

,id_verifikasi_surat,id_sk,status_verifikasi_sk,catatan_verifikasi_sk,created_at
0,1,NaN,,Tidak ada catatan,2023-06-12 13:32:50
1,2,NaN,,Tidak ada catatan,2023-06-12 13:33:07
2,3,NaN,,Tidak ada catatan,2023-06-12 14:28:56
3,4,NaN,,Tidak ada catatan,2023-06-30 15:30:35
4,5,NaN,,Tidak ada catatan,2023-07-01 20:35:43
...,...,...,...,...,...
1426,1427,251.0,Disetujui,Tidak ada catatan,2026-04-16 15:23:32
1427,1428,252.0,Diajukan,Tidak ada catatan,2026-04-17 15:38:24
1428,1429,253.0,Diajukan,Tidak ada catatan,2026-04-17 16:01:39
1429,1430,252.0,Disetujui,Tidak ada catatan,2026-04-17 16:13:16
1430,1431,253.0,Disetujui,Tidak ada catatan,2026-04-17 16:13:32

================================================================================

================================================================================
📦 TABEL: SURAT_TUGAS
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135 entries, 0 to 134
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_st               135 non-null    int64
 1   id_user             135 non-null    object
 2   acara               135 non-null    object
 3   undangan            135 non-null    object
 4   waktu_acara         135 non-null    datetime64[ns]
 5   lokasi_acara        135 non-null    object
 6   jenis_kegiatan      135 non-null    object
 7   status_st           135 non-null    object
 8   periode             0 non-null      object
 9   nomor_st            135 non-null    object
 10  catatan_st          135 non-null    object
 11  link_st             135 non-null    object
 12  link_laporan        135 non-null    object
 13  catatan_laporan     135 non-null    object
 14  keterangan_st       135 non-null    object
 15  catatan_pembatalan  135 non-null    object
 16  created_at          135 non-null    datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(14)
memory usage: 18.1+ KB

------------------------------------------------------------
🔍 2. Arsitektur Fisik Kolom pada DB_FUTURE:

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_FUTURE (Menampilkan Max 5 Baris Teratas):

,id_st,id_user,acara,undangan,waktu_acara,lokasi_acara,jenis_kegiatan,status_st,periode,nomor_st,catatan_st,link_st,link_laporan,catatan_laporan,keterangan_st,catatan_pembatalan,created_at
0,20,U00015,Pertemuan rutin di bulan Juli 2023 forum Laras...,Larasdikdudi,2023-07-27,SMK Teknik PAL Surabaya Jalan Ujung Surabaya,Offline,Disetujui,None,023/LEAP/ST/VII/2023,Tidak ada catatan,https://docs.google.com/document/d/1rILu6FE8Bd...,https://docs.google.com/document/d/1IAhWT4XjbX...,done/laporan sudah diisi,,Tidak ada catatan,2023-07-25 09:56:19
1,21,U00015,Temu Warga RT 01 RW 08,Pengurus RT 01/ RW08,2023-08-23,Balai RW,Offline,Disetujui,None,024/LEAP/ST/VIII/2023,Tidak ada catatan,https://docs.google.com/document/d/1OQxpdKYfDF...,https://docs.google.com/document/d/1XrvRmYckBw...,Tidak ada catatan,,Tidak ada catatan,2023-08-22 17:43:48
2,22,U00016,TEDxSurabaya Translators:\r\n\r\n1. Simulasi C...,TEDxSurabaya,2023-09-15,Topic: Connect to TEDxSurabaya Join Zoom Meeti...,Online,Disetujui,None,025/LEAP/ST/VIII/2023,Tidak ada catatan,https://docs.google.com/document/d/10Zi6g0R9RR...,https://docs.google.com/document/d/1pa9G3E3eUa...,laporan kegiatan done,,Tidak ada catatan,2023-09-13 13:01:52
3,23,U00015,Pertemuan Rutin Larasdikdudi bulan September 2023,https://drive.google.com/drive/u/3/folders/1OI...,2023-09-27,AULA SMK Negeri 2 Surabaya Jalan Tentara Genie...,Offline,Disetujui,None,028/LEAP/ST/IX/2023,Tidak ada catatan,https://docs.google.com/document/d/1wMOD-N6oMQ...,https://docs.google.com/document/d/1xMv7AK2L9S...,done,,Tidak ada catatan,2023-09-19 13:54:26
4,24,U00015,Sosialisasi Kerjasama LKP dan PKBM dengan Seme...,Dinas Pendidikan Kota Surabaya (bu Hilda),2023-09-20,"Tempat : Ruang Bung Tomo, Dinas Pendidikan Kot...",Offline,Disetujui,None,027/LEAP/ST/IX/2023,Tidak ada catatan,https://docs.google.com/document/d/1LBx4WpqXcY...,https://docs.google.com/document/d/1jJdGMkonp_...,Tidak ada catatan,,Tidak ada catatan,2023-09-19 13:55:50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,163,U00016,TEDx,TEDx,2026-04-19,Surabaya Intercultural School. Jalan HR Muhammad,Offline,Disetujui,None,030/HR/ST/LEAP/III/2026,Tidak ada catatan,https://docs.google.com/document/d/1yLNtt2uchj...,https://docs.google.com/document/d/1yoA9gDLRwT...,Tidak ada catatan,,Tidak ada catatan,2026-03-03 11:52:40
131,164,U00016,Supervisi Tengah Semester,Yayasan BSI - Banyuwangi,2026-04-10,Pesanggaran - Banyuwangi,Offline,Disetujui,None,039/HR/ST/LEAP/IV/2026,Tidak ada catatan,https://docs.google.com/document/d/1ymoUqyKfLG...,https://docs.google.com/document/d/1ONn9G_Detj...,done,,Tidak ada catatan,2026-04-06 10:49:15
132,165,U00016,Indonesia Youth Debate Summit,Sekolah Ciputra Surabaya,2026-04-23,"Ciputra Hall, Sekolah Ciputra Surabaya",Offline,Disetujui,None,040/HR/ST/LEAP/IV/2026,Tidak ada catatan,https://docs.google.com/document/d/1CRncv0KVgX...,https://docs.google.com/document/d/1Z7RSXw0696...,Tidak ada catatan,,Tidak ada catatan,2026-04-08 12:56:00
133,166,U00016,Student Appreciation (Shining Beyond Limits) S...,SD Al Muslim,2026-04-18,Politeknik Pelayaran Surabaya,Offline,Disetujui,None,032/HR/ST/MIM/IV/2026,Tidak ada catatan,https://docs.google.com/document/d/1Jfx39xH2pj...,https://docs.google.com/document/d/1lFTezKhCkA...,Tidak ada catatan,,Tidak ada catatan,2026-04-17 15:39:08
134,167,U00016,Student Appreciation (Shining Beyond Limits) S...,SD Al Muslim,2026-04-18,Politeknik Pelayaran Surabaya,Offline,Disetujui,None,044/HR/ST/LEAP/IV/2026,Tidak ada catatan,https://docs.google.com/document/d/1PzlRtvydlt...,https://docs.google.com/document/d/1VCs1Bp7XeP...,Tidak ada catatan,,Tidak ada catatan,2026-04-17 16:01:07

================================================================================

================================================================================
📦 TABEL: SURAT_TUGAS_ANGGOTA
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 780 entries, 0 to 779
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_st_anggota  780 non-null    int64
 1   id_st          780 non-null    int64
 2   id_user        780 non-null    object
dtypes: int64(2), object(1)
memory usage: 18.4+ KB

------------------------------------------------------------
🔍 2. Arsitektur Fisik Kolom pada DB_FUTURE:

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_FUTURE (Menampilkan Max 5 Baris Teratas):

     id_st_anggota  id_st id_user
0                1     20  U00023
1                2     21  U00043
2                3     22  U00016
3                4     23  U00023
4                5     24  U00014
..             ...    ...     ...
775            864    165  U00034
776            865    164  U00016
777            866    164  U00023
778            867    166  U00060
779            868    167  U00052

[780 rows x 3 columns]

================================================================================

================================================================================
📦 TABEL: SOP_KATEGORI
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_sop_kategori    2 non-null      int64
 1   nama_kategori_sop  2 non-null      object
dtypes: int64(1), object(1)
memory usage: 164.0+ bytes

------------------------------------------------------------
🔍 2. Arsitektur Fisik Kolom pada DB_FUTURE:

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_FUTURE (Menampilkan Max 5 Baris Teratas):

   id_sop_kategori nama_kategori_sop
0                1             Kelas
1                2           HR / GA

================================================================================

================================================================================
📦 TABEL: JADWAL
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3843 entries, 0 to 3842
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id_jadwal              3843 non-null   int64
 1   id_kursus              3843 non-null   object
 2   id_periode             3843 non-null   object
 3   id_level               3843 non-null   object
 4   id_sesi                3843 non-null   object
 5   metode_belajar_jadwal  3843 non-null   object
 6   nama_rombel            3843 non-null   object
 7   status_arsip           3843 non-null   int64
 8   tempat                 3843 non-null   object
dtypes: int64(2), object(7)
memory usage: 270.3+ KB

------------------------------------------------------------
🔍 2. Arsitektur Fisik Kolom pada DB_FUTURE:

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_FUTURE (Menampilkan Max 5 Baris Teratas):

,id_jadwal,id_kursus,id_periode,id_level,id_sesi,metode_belajar_jadwal,nama_rombel,status_arsip,tempat
0,1,K00001,P00006,L00017,S00002,Online,01 GOGO 3B SR2 (ERICA),1,Ruang Kelas 4
1,2,K00001,P00006,L00024,S00002,Offline,02 SO 1C SR2 (QORIN),1,Ruang Kelas 5
2,3,K00001,P00006,L00023,S00001,Offline,03 SO 1B SR1 (TATIK),1,Ruang Kelas 1
3,4,K00001,P00006,L00025,S00003,Offline,04 SO 2A SR3 (TATIK),1,Ruang Kelas 1
4,5,K00001,P00006,L00014,S00003,Offline,05 GOGO 1B SelK3 (ERICA),1,Ruang Kelas 4
...,...,...,...,...,...,...,...,...,...
3838,3839,K00004,P00081,L00136,S00005,Online,CC 6 Mon 4.30-5.30 (Agung) APR 26,0,zoom
3839,3840,K00004,P00081,L00136,S00006,Online,CC 3 Wed 7-8 (Agung) APR 26,0,ZOOM
3840,3841,K00004,P00081,L00136,S00042,Online,CC 1 Fri 7-8 (Agung) APR 26,0,Ruang Kelas
3841,3842,K00007,P00107,L00125,S00043,Offline,01 BEHCA PRE-BASIC MON 15-17 (Yerly),0,Offline (P.T. Holland Colours Asia)
3842,3843,K00007,P00107,L00126,S00043,Offline,02 BEHCA BASIC TUE 15-17 (Yerly),0,Offline (P.T. Holland Colours Asia)

================================================================================

================================================================================
📦 TABEL: JADWAL_HARI
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1950 entries, 0 to 1949
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_jadwal_hari  1950 non-null   int64
 1   id_jadwal       1950 non-null   int64
 2   nama_hari       1950 non-null   object
dtypes: int64(2), object(1)
memory usage: 45.8+ KB

------------------------------------------------------------
🔍 2. Arsitektur Fisik Kolom pada DB_FUTURE:

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_FUTURE (Menampilkan Max 5 Baris Teratas):

      id_jadwal_hari  id_jadwal nama_hari
0                  1          1     Senin
1                  2          1      Rabu
2                  3          2     Senin
3                  4          2      Rabu
4                  5          3     Senin
...              ...        ...       ...
1945            1946       3290     Senin
1946            1947       3291      Rabu
1947            1948       3292     Jumat
1948            1949       3293     Senin
1949            1950       3294    Selasa

[1950 rows x 3 columns]

================================================================================

================================================================================
📦 TABEL: JADWAL_DETAIL
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120799 entries, 0 to 120798
Data columns (total 18 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   id_jadwal_detail           120799 non-null  int64
 1   id_jadwal                  120799 non-null  int64
 2   judul                      120799 non-null  object
 3   deskripsi                  120799 non-null  object
 4   url_jadwal_detail          120799 non-null  object
 5   penanda_mulai              120799 non-null  object
 6   penanda_selesai            120799 non-null  object
 7   label_warna                120799 non-null  object
 8   id_mitra                   0 non-null       object
 9   id_sesi_override           0 non-null       object
 10  status_detail              120799 non-null  object
 11  source_type                120799 non-null  object
 12  original_jadwal_detail_id  0 non-null       object
 13  has_operational_data       120799 non-null  int64
 14  presensi_disimpan_at       0 non-null       object
 15  last_generated_at          0 non-null       object
 16  created_at                 120799 non-null  datetime64[ns]
 17  updated_at                 120799 non-null  datetime64[ns]
dtypes: datetime64[ns](2), int64(3), object(13)
memory usage: 16.6+ MB

------------------------------------------------------------
🔍 2. Arsitektur Fisik Kolom pada DB_FUTURE:

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_FUTURE (Menampilkan Max 5 Baris Teratas):

,id_jadwal_detail,id_jadwal,judul,deskripsi,url_jadwal_detail,penanda_mulai,penanda_selesai,label_warna,id_mitra,id_sesi_override,status_detail,source_type,original_jadwal_detail_id,has_operational_data,presensi_disimpan_at,last_generated_at,created_at,updated_at
0,1,8,08 SO 2A SelK3 (GETA),Tidak ada deskripsi,https://us02web.zoom.us/j/5403514055?pwd=ZnZ2d...,2023-07-04,2023-07-05,fc-event-info,None,None,active,migrasi,None,0,None,None,2026-06-12 17:22:15,2026-06-12 17:22:15
1,2,8,08 SO 2A SelK3 (GETA),Tidak ada deskripsi,https://us02web.zoom.us/j/5403514055?pwd=ZnZ2d...,2023-07-06,2023-07-07,fc-event-info,None,None,active,migrasi,None,0,None,None,2026-06-12 17:22:15,2026-06-12 17:22:15
2,3,8,08 SO 2A SelK3 (GETA),Tidak ada deskripsi,https://us02web.zoom.us/j/5403514055?pwd=ZnZ2d...,2023-07-11,2023-07-12,fc-event-info,None,None,active,migrasi,None,0,None,None,2026-06-12 17:22:15,2026-06-12 17:22:15
3,4,8,08 SO 2A SelK3 (GETA),Tidak ada deskripsi,https://us02web.zoom.us/j/5403514055?pwd=ZnZ2d...,2023-07-13,2023-07-14,fc-event-info,None,None,active,migrasi,None,0,None,None,2026-06-12 17:22:15,2026-06-12 17:22:15
4,5,8,08 SO 2A SelK3 (GETA),Tidak ada deskripsi,https://us02web.zoom.us/j/5403514055?pwd=ZnZ2d...,2023-07-18,2023-07-19,fc-event-info,None,None,active,migrasi,None,0,None,None,2026-06-12 17:22:15,2026-06-12 17:22:15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120794,120795,3842,01 BEHCA PRE-BASIC MON 15-17 (Yerly),Tidak ada deskripsi,Link belum tersedia,2026-10-05,2026-10-06,fc-event-info,None,None,active,migrasi,None,0,None,None,2026-06-12 17:22:15,2026-06-12 17:22:15
120795,120796,3842,01 BEHCA PRE-BASIC MON 15-17 (Yerly),Tidak ada deskripsi,Link belum tersedia,2026-10-12,2026-10-13,fc-event-info,None,None,active,migrasi,None,0,None,None,2026-06-12 17:22:15,2026-06-12 17:22:15
120796,120797,3842,01 BEHCA PRE-BASIC MON 15-17 (Yerly),Tidak ada deskripsi,Link belum tersedia,2026-10-19,2026-10-20,fc-event-info,None,None,active,migrasi,None,0,None,None,2026-06-12 17:22:15,2026-06-12 17:22:15
120797,120798,3842,01 BEHCA PRE-BASIC MON 15-17 (Yerly),Tidak ada deskripsi,Link belum tersedia,2026-10-26,2026-10-27,fc-event-info,None,None,active,migrasi,None,0,None,None,2026-06-12 17:22:15,2026-06-12 17:22:15
120798,120799,3842,01 BEHCA PRE-BASIC MON 15-17 (Yerly),Tidak ada deskripsi,Link belum tersedia,2026-11-02,2026-11-03,fc-event-info,None,None,active,migrasi,None,0,None,None,2026-06-12 17:22:15,2026-06-12 17:22:15

================================================================================

================================================================================
📦 TABEL: JADWAL_PENGAJAR
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1280 entries, 0 to 1279
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_jadwal_pengajar  1280 non-null   int64
 1   id_jadwal           1280 non-null   int64
 2   id_user             1280 non-null   object
dtypes: int64(2), object(1)
memory usage: 30.1+ KB

------------------------------------------------------------
🔍 2. Arsitektur Fisik Kolom pada DB_FUTURE:

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_FUTURE (Menampilkan Max 5 Baris Teratas):

      id_jadwal_pengajar  id_jadwal id_user
0                      1          3  U00019
1                      2          7  U00026
2                      3          9  U00035
3                      4         17  U00038
4                      5         21  U00019
...                  ...        ...     ...
1275                1276       3292  U00040
1276                1277       3293  U00048
1277                1278       3294  U00048
1278                1279       3293  U00026
1279                1280       3294  U00026

[1280 rows x 3 columns]

================================================================================

================================================================================
📦 TABEL: JADWAL_SISWA
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 15 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id_jadwal_siswa             0 non-null      object
 1   id_siswa                    0 non-null      object
 2   id_jadwal                   0 non-null      object
 3   tanggal_mulai               0 non-null      object
 4   tambahan_sesi               0 non-null      object
 5   tambahan_keterangan         0 non-null      object
 6   status_keluar               0 non-null      object
 7   is_acc_rapor                0 non-null      object
 8   status_ketuntasan           0 non-null      object
 9   catatan_ketuntasan_guru     0 non-null      object
 10  catatan_ketuntasan_admin    0 non-null      object
 11  ketuntasan_diperbarui_oleh  0 non-null      object
 12  ketuntasan_diperbarui_pada  0 non-null      object
 13  tanggal_keluar              0 non-null      object
 14  tanggal_aktif               0 non-null      object
dtypes: object(15)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. Arsitektur Fisik Kolom pada DB_FUTURE:

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_FUTURE (Menampilkan Max 5 Baris Teratas):

Empty DataFrame
Columns: [id_jadwal_siswa, id_siswa, id_jadwal, tanggal_mulai, tambahan_sesi, tambahan_keterangan, status_keluar, is_acc_rapor, status_ketuntasan, catatan_ketuntasan_guru, catatan_ketuntasan_admin, ketuntasan_diperbarui_oleh, ketuntasan_diperbarui_pada, tanggal_keluar, tanggal_aktif]
Index: []

================================================================================

================================================================================
📦 TABEL: CATATAN_KELAS
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89579 entries, 0 to 89578
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_ck               89579 non-null  int64
 1   id_jadwal           89579 non-null  int64
 2   id_jadwal_detail    89579 non-null  int64
 3   id_karyawan         0 non-null      object
 4   catatan_kelas       89579 non-null  object
 5   topik_diskusi       89579 non-null  object
 6   tanggal_konfirmasi  89579 non-null  datetime64[ns]
 7   hasil_konfirmasi    89579 non-null  object
dtypes: datetime64[ns](1), int64(3), object(4)
memory usage: 5.5+ MB

------------------------------------------------------------
🔍 2. Arsitektur Fisik Kolom pada DB_FUTURE:

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_FUTURE (Menampilkan Max 5 Baris Teratas):

,id_ck,id_jadwal,id_jadwal_detail,id_karyawan,catatan_kelas,topik_diskusi,tanggal_konfirmasi,hasil_konfirmasi
0,1,7,1231,None,1. Bya ijin tidak hadir karena masih perjalana...,,2026-06-12 17:22:16,
1,2,3,721,None,Kelas berjalan lancar. Valencia bisa mengikuti...,,2026-06-12 17:22:16,
2,3,9,1171,None,Elycia didn't come. Harits and Kinan came 15 m...,,2026-06-12 17:22:16,
3,4,22,331,None,Semua siswa hadir ada murid trial Kim suaranya...,,2026-06-12 17:22:16,
4,5,1,451,None,kelas berjalan dengan lancar elma & ghaus mema...,,2026-06-12 17:22:16,
...,...,...,...,...,...,...,...,...
89574,89575,3771,117890,None,<p>27) <strong>Sesi 27</strong> - Topik hari i...,,2026-06-12 17:22:16,
89575,89576,3742,117223,None,<p>1. Sesi ke 25 pembelajaran dimulai tepat wa...,,2026-06-12 17:22:16,
89576,89577,3841,120749,None,<p>Sesi 2: Peserta datang tepat waktu. Interne...,,2026-06-12 17:22:16,
89577,89578,3766,117804,None,"<p style=""text-align: justify;""><strong>Pertem...",,2026-06-12 17:22:16,
89578,89579,3767,117847,None,"<p style=""text-align: justify;""><strong>Pertem...",,2026-06-12 17:22:16,

================================================================================

================================================================================
📦 TABEL: CATATAN_KELAS_TAG
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_ck_tag         0 non-null      object
 1   id_ck             0 non-null      object
 2   id_topik_diskusi  0 non-null      object
dtypes: object(3)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. Arsitektur Fisik Kolom pada DB_FUTURE:

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_FUTURE (Menampilkan Max 5 Baris Teratas):

Empty DataFrame
Columns: [id_ck_tag, id_ck, id_topik_diskusi]
Index: []

================================================================================

================================================================================
📦 TABEL: CATATAN_MINGGUAN
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id_cm                  0 non-null      object
 1   id_user                0 non-null      object
 2   tanggal_mulai_cm       0 non-null      object
 3   tanggal_selesai_cm     0 non-null      object
 4   keterangan_cm          0 non-null      object
 5   keputusan_cm           0 non-null      object
 6   tanggal_verifikasi_cm  0 non-null      object
dtypes: object(7)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. Arsitektur Fisik Kolom pada DB_FUTURE:

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_FUTURE (Menampilkan Max 5 Baris Teratas):

Empty DataFrame
Columns: [id_cm, id_user, tanggal_mulai_cm, tanggal_selesai_cm, keterangan_cm, keputusan_cm, tanggal_verifikasi_cm]
Index: []

================================================================================

================================================================================
📦 TABEL: PRESENSI_SISWA
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_presensi_siswa  0 non-null      object
 1   id_jadwal_detail   0 non-null      object
 2   id_siswa           0 non-null      object
 3   waktu_presensi     0 non-null      object
 4   status_presensi    0 non-null      object
dtypes: object(5)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. Arsitektur Fisik Kolom pada DB_FUTURE:

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_FUTURE (Menampilkan Max 5 Baris Teratas):

Empty DataFrame
Columns: [id_presensi_siswa, id_jadwal_detail, id_siswa, waktu_presensi, status_presensi]
Index: []

================================================================================

================================================================================
📦 TABEL: CATATAN_SISWA
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_cs             0 non-null      object
 1   id_jadwal         0 non-null      object
 2   id_jadwal_detail  0 non-null      object
 3   id_siswa          0 non-null      object
 4   id_karyawan       0 non-null      object
 5   tanggal           0 non-null      object
 6   catatan_cs        0 non-null      object
dtypes: object(7)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. Arsitektur Fisik Kolom pada DB_FUTURE:

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_FUTURE (Menampilkan Max 5 Baris Teratas):

Empty DataFrame
Columns: [id_cs, id_jadwal, id_jadwal_detail, id_siswa, id_karyawan, tanggal, catatan_cs]
Index: []

================================================================================

================================================================================
📦 TABEL: FOLLOWUP_CS
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id_followup_cs          0 non-null      object
 1   id_cs                   0 non-null      object
 2   tanggal_followup        0 non-null      object
 3   id_user                 0 non-null      object
 4   kesimpulan_followup_cs  0 non-null      object
 5   status_followup         0 non-null      object
dtypes: object(6)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. Arsitektur Fisik Kolom pada DB_FUTURE:

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_FUTURE (Menampilkan Max 5 Baris Teratas):

Empty DataFrame
Columns: [id_followup_cs, id_cs, tanggal_followup, id_user, kesimpulan_followup_cs, status_followup]
Index: []

================================================================================

🎉 SCANNING SELESAI! 🎉