In [1]:
import sys
import os
import mysql.connector
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Ambil konfigurasi database dari folder utama project kalian
sys.path.append(os.path.abspath('..'))
from config import get_db_config

config = get_db_config()

# 1. Koneksi ke Database Baru (Fase Migrasi Sekarang)
db_new = mysql.connector.connect(**config['db_new'])
cursor_new = db_new.cursor(dictionary=True)

# 2. Koneksi ke Database Masa Depan (DB_FUTURE)
# Catatan: Pastikan di file config.py kalian sudah ada key 'db_future' ya!
db_future = mysql.connector.connect(**config['db_future'])
cursor_future = db_future.cursor(dictionary=True)

print(f"✅ Sukses Terhubung ke Database Baru : {config['db_new']['database']}")
print(f"🚀 Sukses Terhubung ke DB_FUTURE     : {config['db_future']['database']}")

✅ Sukses Terhubung ke Database Baru : dataleap_v5_migration
🚀 Sukses Terhubung ke DB_FUTURE     : 2

In [2]:
tables_to_check = [
    # --- Bagian Cimut ---
    "users", 
    "divisions", 
    "shift_kerja", 
    "admin_sarpras", 
    "sop_kategori", 
    "provinsi", 
    "web_berita", 
    "web_statistik",
    
    # --- Bagian Afrida ---
    "kursus", 
    "level", 
    "sesi", 
    "libur", 
    "topik_diskusi", 
    "kursus_level", 
    "kursus_libur",
    
    # --- Bagian Hanif ---
    "roles", 
    "permissions", 
    "role_has_permissions", 
    "busdev_bidang", 
    "syarat_resign", 
    "ttd", 
    "tag_siswa_keluar"
]

In [3]:
# === Cell 2: Inspeksi Detektor Pintar dengan Prioritas Target Revisi di Atas ===
import pandas as pd
import numpy as np

print("================================================================================")
print(" 🕵️‍♂️ FORENSIK ARSITEKTUR KONTROL: DETEKTOR AUTO-SMART COMPILER (REVISI PRIORITY) 🕵️‍♂️ ")
print("================================================================================")

# List penampung data di memori untuk keperluan sorting visualisasi
revisi_tables_queue = []
identical_tables_queue = []

# --- TAHAP A: PROSES PEN ARIKAN DATA & EVALUASI STRUKTUR DI BELAKANG LAYAR ---
for table in tables_to_check:
    try:
        # 1. Ambil data asli dari DB_NEW untuk kebutuhan .info() dan sampel isi data
        query = f"SELECT * FROM `{table}`"
        df_real_data = pd.read_sql(query, db_new)
        
        # 2. Tarik Struktur Fisik Kolom dari DB_NEW
        query_new_struct = f"""
        SELECT 
            c.COLUMN_NAME AS 'Nama Kolom',
            c.COLUMN_TYPE AS 'Tipe Data MySQL',
            CONCAT(
                CASE WHEN c.IS_NULLABLE = 'YES' THEN '✅ NULL (Boleh Kosong)' ELSE '🛑 NOT NULL (Wajib Isi)' END,
                CASE WHEN c.EXTRA = 'auto_increment' THEN '\\n🚀 AUTO_INCREMENT' ELSE '' END
            ) AS 'Aturan Nullability & Increment',
            CASE 
                WHEN c.COLUMN_KEY = 'PRI' THEN '🔑 PRIMARY KEY (PK)'
                WHEN c.COLUMN_KEY = 'MUL' AND k.REFERENCED_TABLE_NAME IS NOT NULL THEN '🔗 FOREIGN KEY (FK)'
                WHEN c.COLUMN_KEY = 'MUL' THEN 'INDEX'
                ELSE '-'
            END AS 'Status Kunci',
            CASE 
                WHEN k.REFERENCED_TABLE_NAME IS NOT NULL THEN CONCAT(k.REFERENCED_TABLE_NAME, ' (', k.REFERENCED_COLUMN_NAME, ')')
                ELSE '-'
            END AS 'Rujukan Induk (FK Origin)',
            CASE WHEN c.DATA_TYPE = 'enum' THEN REPLACE(REPLACE(REPLACE(c.COLUMN_TYPE, 'enum(', ''), ')', ''), "'", "") ELSE '-' END AS 'Daftar Pilihan ENUM'
        FROM INFORMATION_SCHEMA.COLUMNS c
        LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE k 
            ON c.TABLE_SCHEMA = k.TABLE_SCHEMA AND c.TABLE_NAME = k.TABLE_NAME AND c.COLUMN_NAME = k.COLUMN_NAME
        WHERE c.TABLE_SCHEMA = '{config['db_new']['database']}' AND c.TABLE_NAME = '{table}'
        ORDER BY c.ORDINAL_POSITION;
        """
        df_struct_new = pd.read_sql(query_new_struct, db_new).drop_duplicates(subset=['Nama Kolom'], keep='first').reset_index(drop=True)
        
        # Lacak tabel anak yang nge-FK ke PK tabel ini di DB_NEW
        pk_referenced_list = []
        for idx, row_skri in df_struct_new.iterrows():
            if row_skri['Status Kunci'] == '🔑 PRIMARY KEY (PK)':
                lookup_fk_query = f"""
                SELECT CONCAT(TABLE_NAME, ' (', COLUMN_NAME, ')') as relasi
                FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
                WHERE REFERENCED_TABLE_SCHEMA = '{config['db_new']['database']}'
                  AND REFERENCED_TABLE_NAME = '{table}'
                  AND REFERENCED_COLUMN_NAME = '{row_skri['Nama Kolom']}';
                """
                df_relasi_luar = pd.read_sql(lookup_fk_query, db_new)
                if not df_relasi_luar.empty:
                    pk_referenced_list.append("\n".join(df_relasi_luar['relasi'].tolist()))
                else:
                    pk_referenced_list.append("-")
            else:
                pk_referenced_list.append("-")
        df_struct_new['Tabel Yang nge-FK (DB_NEW)'] = pk_referenced_list

        # 3. Tarik Struktur Fisik Kolom dari DB_FUTURE
        query_future_struct = f"""
        SELECT 
            c.COLUMN_NAME AS 'Nama Kolom',
            c.COLUMN_TYPE AS 'Tipe Data MySQL',
            CONCAT(
                CASE WHEN c.IS_NULLABLE = 'YES' THEN '✅ NULL (Boleh Kosong)' ELSE '🛑 NOT NULL (Wajib Isi)' END,
                CASE WHEN c.EXTRA = 'auto_increment' THEN '\\n🚀 AUTO_INCREMENT' ELSE '' END
            ) AS 'Aturan Nullability & Increment',
            CASE 
                WHEN c.COLUMN_KEY = 'PRI' THEN '🔑 PRIMARY KEY (PK)'
                WHEN c.COLUMN_KEY = 'MUL' AND k.REFERENCED_TABLE_NAME IS NOT NULL THEN '🔗 FOREIGN KEY (FK)'
                WHEN c.COLUMN_KEY = 'MUL' THEN 'INDEX'
                ELSE '-'
            END AS 'Status Kunci',
            CASE 
                WHEN k.REFERENCED_TABLE_NAME IS NOT NULL THEN CONCAT(k.REFERENCED_TABLE_NAME, ' (', k.REFERENCED_COLUMN_NAME, ')')
                ELSE '-'
            END AS 'Rujukan Induk (FK Origin)',
            CASE WHEN c.DATA_TYPE = 'enum' THEN REPLACE(REPLACE(REPLACE(c.COLUMN_TYPE, 'enum(', ''), ')', ''), "'", "") ELSE '-' END AS 'Daftar Pilihan ENUM'
        FROM INFORMATION_SCHEMA.COLUMNS c
        LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE k 
            ON c.TABLE_SCHEMA = k.TABLE_SCHEMA AND c.TABLE_NAME = k.TABLE_NAME AND c.COLUMN_NAME = k.COLUMN_NAME
        WHERE c.TABLE_SCHEMA = '{config['db_future']['database']}' AND c.TABLE_NAME = '{table}'
        ORDER BY c.ORDINAL_POSITION;
        """
        df_struct_future = pd.read_sql(query_future_struct, db_future).drop_duplicates(subset=['Nama Kolom'], keep='first').reset_index(drop=True)
        
        # Lacak tabel anak yang nge-FK ke PK tabel ini di DB_FUTURE
        pk_referenced_list_future = []
        for idx, row_skri in df_struct_future.iterrows():
            if row_skri['Status Kunci'] == '🔑 PRIMARY KEY (PK)':
                lookup_fk_query_future = f"""
                SELECT CONCAT(TABLE_NAME, ' (', COLUMN_NAME, ')') as relasi
                FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
                WHERE REFERENCED_TABLE_SCHEMA = '{config['db_future']['database']}'
                  AND REFERENCED_TABLE_NAME = '{table}'
                  AND REFERENCED_COLUMN_NAME = '{row_skri['Nama Kolom']}';
                """
                df_relasi_luar_future = pd.read_sql(lookup_fk_query_future, db_future)
                if not df_relasi_luar_future.empty:
                    pk_referenced_list_future.append("\n".join(df_relasi_luar_future['relasi'].tolist()))
                else:
                    pk_referenced_list_future.append("-")
            else:
                pk_referenced_list_future.append("-")
        df_struct_future['Tabel Yang nge-FK (DB_FUTURE)'] = pk_referenced_list_future

        # 4. Deep Comparison Kesamaan Jeroan Kolom dasar
        cols_to_compare = ['Nama Kolom', 'Tipe Data MySQL', 'Aturan Nullability & Increment', 'Status Kunci', 'Rujukan Induk (FK Origin)', 'Daftar Pilihan ENUM']
        
        is_structure_identical = False
        if not df_struct_new.empty and not df_struct_future.empty:
            is_structure_identical = df_struct_new[cols_to_compare].equals(df_struct_future[cols_to_compare])

        # Wadah paket data tabel untuk di-render nanti
        table_package = {
            'name': table,
            'df_real_data': df_real_data,
            'df_struct_new': df_struct_new,
            'df_struct_future': df_struct_future,
            'is_identical': is_structure_identical
        }

        # 🔥 FILTER SAKTI CIMUT: Pisahkan antrean, utamakan yang bermasalah (revisi) ke atas!
        if is_structure_identical:
            identical_tables_queue.append(table_package)
        else:
            revisi_tables_queue.append(table_package)
            
    except Exception as e:
        print(f"❌ Gagal menganalisis awal tabel `{table}`: {e}")

# --- TAHAP B: MULAI PEN TAMPILAN VISUALISASI BERDASARKAN ANT REAN PRIORITAS ---

# 🚨 1. KELOMPOK UTAMA (PALING ATAS): DAFTAR TABEL YANG WAJIB DIREVISI 🚨
if revisi_tables_queue:
    print("\n" + "!"*80)
    print(f"🚨 [🔥 REVISI PRIORITY BOARD] TERDETEKSI {len(revisi_tables_queue)} TABEL BERBEDA - HARUS SEGERA DIPERBAIKI!")
    print("!"*80)
    
    for pkg in revisi_tables_queue:
        print(f"\n================================================================================")
        print(f"⚠️  [STATUS: TARGET REVISI] TABEL: {pkg['name'].upper()}")
        print(f"================================================================================")
        
        print(f"📋 1. Karakteristik Wadah Pandas Dataframe (.info()):")
        pkg['df_real_data'].info()
        print("\n" + "-"*60)
        
        print(f"🔍 2. [TABEL REAL SAAT INI] Arsitektur Fisik Kolom pada DB_NEW:")
        display(pkg['df_struct_new'].style.set_properties(**{'white-space': 'pre-wrap', 'text-align': 'left'}))
        print("\n" + "-"*60)
        
        print(f"🔮 3. [⚠️ TARGET BLUEPRINT RUJUKAN] Tinjau Struktur yang Benar pada DB_FUTURE di bawah:")
        if pkg['df_struct_future'].empty:
            print("❌ ERROR: Tabel ini tidak ditemukan / belum dibuat sama sekali di DB_FUTURE!")
        else:
            display(pkg['df_struct_future'].style.set_properties(**{'white-space': 'pre-wrap', 'text-align': 'left'}))
        print("\n" + "-"*60)
        
        print(f"📸 4. Sampel Isi Data Real di DB_NEW:")
        display(pkg['df_real_data'] if pkg['df_real_data'].empty else pkg['df_real_data'])
        print("\n" + "="*80)

# ✨ 2. KELOMPOK KEDUA (BAW AH): DAFTAR TABEL YANG SUDAH AMAN IDENTIK ✨
if identical_tables_queue:
    print("\n" + "="*80)
    print(f"✨ [🟢 PERFECTLY MATCHED BOARD] SEBANYAK {len(identical_tables_queue)} TABEL STRUKTURNYA SUDAH IDENTIK SAMA PERSIS!")
    print("="*80)
    
    for pkg in identical_tables_queue:
        print(f"\n================================================================================")
        print(f"✅ [STATUS: AMAN IDENTIK] TABEL: {pkg['name'].upper()}")
        print(f"================================================================================")
        
        print(f"📋 1. Karakteristik Wadah Pandas Dataframe (.info()):")
        pkg['df_real_data'].info()
        print("\n" + "-"*60)
        
        print(f"🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:")
        display(pkg['df_struct_new'].style.set_properties(**{'white-space': 'pre-wrap', 'text-align': 'left'}))
        print("\n" + "-"*60)
        
        print("✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨")
        print("ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.")
        print("\n" + "-"*60)
        
        print(f"📸 3. Sampel Isi Data Real di DB_NEW:")
        display(pkg['df_real_data'] if pkg['df_real_data'].empty else pkg['df_real_data'])
        print("\n" + "="*80)

================================================================================
 🕵️‍♂️ FORENSIK ARSITEKTUR KONTROL: DETEKTOR AUTO-SMART COMPILER (REVISI PRIORITY) 🕵️‍♂️
================================================================================

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
🚨 [🔥 REVISI PRIORITY BOARD] TERDETEKSI 2 TABEL BERBEDA - HARUS SEGERA DIPERBAIKI!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

================================================================================
⚠️  [STATUS: TARGET REVISI] TABEL: LIBUR
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79 entries, 0 to 78
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id_libur              79 non-null     object
 1   nama_event            79 non-null     object
 2   deskripsi_libur       79 non-null     object
 3   sumber                79 non-null     object
 4   tanggal_mulai         79 non-null     object
 5   tanggal_berakhir      79 non-null     object
 6   label_warna           79 non-null     object
 7   status_libur_program  79 non-null     int64
dtypes: int64(1), object(7)
memory usage: 5.1+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL SAAT INI] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
🔮 3. [⚠️ TARGET BLUEPRINT RUJUKAN] Tinjau Struktur yang Benar pada DB_FUTURE di bawah:

------------------------------------------------------------
📸 4. Sampel Isi Data Real di DB_NEW:

,id_libur,nama_event,deskripsi_libur,sumber,tanggal_mulai,tanggal_berakhir,label_warna,status_libur_program
0,L00005,Libur Nasional,,,2023-07-19,2023-07-20,,1
1,L00006,Libur Nasional,,,2023-06-29,2023-06-30,,1
2,L00007,Tahun Baru Islam 2023,,,2023-07-19,2023-07-20,,1
3,L00008,Natal,,,2023-12-22,2023-12-30,,1
4,L00009,Tahun Baru,,,2024-01-01,2024-01-02,,1
...,...,...,...,...,...,...,...,...
74,L00083,Perkiraan 2027 Maulid Nabi,,,2027-08-15,2027-08-16,,1
75,L00084,Perkiraan 2027 Hari Kemerdekaan,,,2027-08-17,2027-08-18,,1
76,L00085,Perkiraan 2027 Nataru,,,2027-12-25,2028-01-01,,1
77,L00086,Perkiraan 2027,,,2027-12-26,2027-12-27,,1
78,L00087,Idul Adha,,,2026-05-27,2026-05-28,,1

================================================================================

================================================================================
⚠️  [STATUS: TARGET REVISI] TABEL: ROLES
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          9 non-null      int64
 1   name        9 non-null      object
 2   guard_name  9 non-null      object
 3   created_at  9 non-null      datetime64[ns]
 4   updated_at  9 non-null      datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(2)
memory usage: 492.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL SAAT INI] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
🔮 3. [⚠️ TARGET BLUEPRINT RUJUKAN] Tinjau Struktur yang Benar pada DB_FUTURE di bawah:

------------------------------------------------------------
📸 4. Sampel Isi Data Real di DB_NEW:

   id             name guard_name          created_at          updated_at
0   1               HR        web 2026-05-30 20:01:10 2026-05-30 20:01:10
1   2         KARYAWAN        web 2026-05-30 20:01:10 2026-05-30 20:01:10
2   3               IT        web 2026-05-30 20:01:10 2026-05-30 20:01:10
3   4         PIMPINAN        web 2026-05-30 20:01:10 2026-05-30 20:01:10
4   5         PENGAJAR        web 2026-05-30 20:01:10 2026-05-30 20:01:10
5   6       PENDIDIKAN        web 2026-05-30 20:01:10 2026-05-30 20:01:10
6   7  General Affairs        web 2026-05-30 20:01:10 2026-05-30 20:01:10
7   8           Busdev        web 2026-05-30 20:01:10 2026-05-30 20:01:10
8   9            Siswa        web 2026-05-30 20:01:10 2026-05-30 20:01:10

================================================================================

================================================================================
✨ [🟢 PERFECTLY MATCHED BOARD] SEBANYAK 20 TABEL STRUKTURNYA SUDAH IDENTIK SAMA PERSIS!
================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: USERS
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_user            51 non-null     object
 1   name               51 non-null     object
 2   email              51 non-null     object
 3   email_verified_at  0 non-null      object
 4   password           51 non-null     object
 5   remember_token     0 non-null      object
 6   created_at         0 non-null      object
 7   updated_at         0 non-null      object
dtypes: object(8)
memory usage: 3.3+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

,id_user,name,email,email_verified_at,password,remember_token,created_at,updated_at
0,U00001,ADMINISTRATOR,ditari@leapsurabaya.sch.id,None,aGtq,None,None,None
1,U00003,"Graciela Evanda Ronadi, S.Kom.",graciela@leapsurabaya.sch.id,None,qWmlbcVjYmo%3D,None,None,None
2,U00011,DANIAR AULIA RIZKI,daniar.rizki@leapsurabaya.sch.id,None,aGtq,None,None,None
3,U00012,Habibah Melyna,habibah.elfiani@leapsurabaya.sch.id,None,o56YqZJkZA%3D%3D,None,None,None
4,U00014,Laksmi Puspitowardhani,laksmi.p@leapsurabaya.sch.id,None,aWlpbw%3D%3D,None,None,None
5,U00015,Ika Asriani Yadin,ikayadin@leapsurabaya.sch.id,None,aGtq,None,None,None
6,U00016,"Luluk Fatikah Sari, S.Pd.",luluk.sari@leapsurabaya.sch.id,None,o66jrsxjY2s%3D,None,None,None
7,U00018,Ditari Kurnia,admin@gmail.com,None,aGtq,None,None,None
8,U00019,"Hartatik, S.S.",hartatik@leapsurabaya.sch.id,None,p5qenpJkZA%3D%3D,None,None,None
9,U00020,Juni Arlianto,juni.arlianto@leapsurabaya.sch.id,None,aGtq,None,None,None
10,U00023,Titi Hapsari,titi.hapsari@leapsurabaya.sch.id,None,aGtq,None,None,None
11,U00026,"Qorin Rahmaniyah, S.Pd.",qorin.rahmaniah@leapsurabaya.sch.id,None,bnFw,None,None,None
12,U00027,Test,test@gmail.com,None,aGtq,None,None,None
13,U00028,pengajar,pengajar@gmail.com,None,aGtq,None,None,None
14,U00030,Akun Data PPDK,data@gmail.com,None,o56YqZJkZGw%3D,None,None,None
15,U00031,"Eka Nur Wahyuni, S. Pd.",eka.wahyuni@leapsurabaya.sch.id,None,fKSYp9akqJnNqauhm5WZ,None,None,None
16,U00032,"Getari Adyagarini, M.Pd",getari@leapsurabaya.sch.id,None,aGtq,None,None,None
17,U00033,"Maria Florencia Erica Susanto, A.Md.",ericasusanto@leapsurabaya.sch.id,None,sKimp9STn6DGYGY%3D,None,None,None
18,U00034,"Mieke Puspita, S.Pd",miekepuspita@leapsurabaya.sch.id,None,o56YqZJkZGw%3D,None,None,None
19,U00035,"Miftakhul Jannah, S.Pd",miftakhul.jannah@leapsurabaya.sch.id,None,aGtq,None,None,None
20,U00036,"Rr. Nisrina Dea Rahma, S.Hum",nisrina.dea@leapsurabaya.sch.id,None,pZ2cmtOaYmmT,None,None,None
21,U00037,Siti Uswatun Khasanah,siti.uswatun@leapsurabaya.sch.id,None,aGtq,None,None,None
22,U00038,"Rini Budi Rahayu, S.Pd.",rini.rahayu@leapsurabaya.sch.id,None,o56YqZNiY2s%3D,None,None,None
23,U00040,"Agung Wijayanto, S.T.",agung.wijayanto@leapsurabaya.sch.id,None,aGtq,None,None,None
24,U00041,Vivi Pramitha Wulandari,vivi.wulandari@leapsurabaya.sch.id,None,aGtq,None,None,None
25,U00042,Cantika Swasti Sumarsono Putri,cantikaswasti76@gmail.com,None,aGtq,None,None,None
26,U00043,Trio Fajar Cahyanto,generalaffair@gmail.com,None,aGtq,None,None,None
27,U00044,Muifatul Febriani,muifatul@leapsurabaya.sch.id,None,aGtq,None,None,None
28,U00046,sosialmedia1,sosialmedia1@gmail.com,None,aGtq,None,None,None
29,U00047,Muhamad Haykal Roziqi,Muhammad.haykal@leapsurabaya.sch.id,None,i6Kkp8KlYmqYZGs%3D,None,None,None
30,U00048,"Yerly A Datu, S.Pd, M.Pd, CT.ACT, C.PS",pengajar1@leapsurabaya.sch.id,None,aGtq,None,None,None
31,U00049,Ana Puspita,ana.puspita@leapsurabaya.sch.id,None,aGtq,None,None,None
32,U00050,"Peni Puspa Indarwati, S.S.",peni.indarwati@leapsurabaya.sch.id,None,pJqkptCmZm0%3D,None,None,None
33,U00052,Ratna Febrianti,febrianti.ratna@leapsurabaya.sch.id,None,aGtq,None,None,None
34,U00053,Ann Clariss Agbalog Amora,edgetutor1@leapsurabaya.sch.id,None,o56YqdWnpafXYWhm,None,None,None
35,U00054,Bryant Frederico Sutanto,Bryant.f@leapsurabaya.sch.id,None,aGtq,None,None,None
36,U00055,Muhammad Jefry Mulyanto,muhammad.jefry@leapsurabaya.sch.id,None,oZ%2BpsqGelpnVYWtjaJSb,None,None,None
37,U00056,Amat Kasiyan,Amat@leap.surabaya.sch.id,None,aGtq,None,None,None
38,U00057,"Ulfasiyah, S.S.",ulfasiyah@leapsurabaya.sch.id,None,aGtq,None,None,None
39,U00058,Piotr Pawel Sopa,piotr.pawel@leapsurabaya.sch.id,None,aGtq,None,None,None
40,U00059,Amilia Khasanah Marzuki,Amilia.Khasanah@leapsurabaya.sch.id,None,aGtq,None,None,None
41,U00060,Muhammad Yusril Romadhoni,Muhammad.Yusril@leapsurabaya.sch.id,None,aGtq,None,None,None
42,U00061,"Veronica Febriyanti Adam, S.S.",veronica.febriyanti@leapsurabaya.sch.id,None,iqGgp8Z0o6HMmKpkaZSe,None,None,None
43,U00062,La Erpiadin,la.erpiadin@leapsurabaya.sch.id,None,aGtq,None,None,None
44,U00063,"Aulia Ratna Meilinda, S.Pd.",Aulia.Ratna@leapsurabaya.sch.id,None,aGtq,None,None,None
45,U00064,"PINANGGIH DIMAS PERMANA, S.Kom",Pinanggih.Dimas@leapsurabaya.sch.id,None,aGtq,None,None,None
46,U00065,"Retno Wulandari, S.Pd.",Retno.Wulandari@leapsurabaya.sch.id,None,aGtq,None,None,None
47,U00066,"Risma Dwi Aryanti, S.Pd.",Risma.Dwi@leapsurabaya.sch.id,None,n26ua5WLaZ0%3D,None,None,None
48,U00067,"Moh Rafli Wahyudi, S.Pd.",Moh.Rafli@leapsurabaya.sch.id,None,g56YqaihnKHRYWg%3D,None,None,None
49,U00068,Mochammad Rahmat Muttaqin,rahmat.muttaqin@leapsurabaya.sch.id,None,aGtq,None,None,None
50,U00069,Zaskya Ayra Sinatrya,zaskya.Ayra@leapsurabaya.sch.id,None,sZqqocJiYmmWYGo%3D,None,None,None

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: DIVISIONS
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_division    6 non-null      int64
 1   name_division  6 non-null      object
 2   description    0 non-null      object
 3   is_active      6 non-null      int64
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

   id_division name_division description  is_active
0            1            IT        None          1
1            2        Busdev        None          1
2            3       HR / GA        None          1
3            4    Pendidikan        None          1
4            5       Finance        None          1
5            6       Direksi        None          1

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: SHIFT_KERJA
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_shift    3 non-null      int64
 1   nama_shift  3 non-null      object
 2   jam_masuk   3 non-null      timedelta64[ns]
 3   jam_pulang  3 non-null      timedelta64[ns]
dtypes: int64(1), object(1), timedelta64[ns](2)
memory usage: 228.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

   id_shift          nama_shift       jam_masuk      jam_pulang
0         1  Freelance Fulltime 0 days 10:15:00 0 days 19:15:00
1         2   DIGITAL ENGLISH 1 0 days 08:00:00 0 days 17:00:00
2         3   DIGITAL ENGLISH 2 0 days 10:15:00 0 days 19:15:00

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: ADMIN_SARPRAS
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_admin_sarpras  1 non-null      int64
 1   wa_admin_sarpras  1 non-null      object
dtypes: int64(1), object(1)
memory usage: 148.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

   id_admin_sarpras wa_admin_sarpras
0                 1     085174387539

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: SOP_KATEGORI
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_sop_kategori    3 non-null      int64
 1   nama_kategori_sop  3 non-null      object
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

   id_sop_kategori nama_kategori_sop
0                1             Kelas
1                2           HR / GA
2                3              test

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: PROVINSI
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_provinsi    38 non-null     int64
 1   nama_provinsi  38 non-null     object
 2   code           38 non-null     object
dtypes: int64(1), object(2)
memory usage: 1.0+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

    id_provinsi               nama_provinsi code
0             1         Nusa Tenggara Barat    3
1             2                        Bali    2
2             3                 Jawa Tengah    4
3             5                  Jawa Barat    1
4             6  Daerah Istimewa Yogyakarta    5
5             7              Sumatera Barat    8
6             8                     Lampung   10
7             9                       Jambi    9
8            10            Sulawesi Selatan    7
9            11                  Jawa Timur    6
10           12                      Banten   13
11           13                    Bengkulu   12
12           14   Kepulauan Bangka Belitung   14
13           15            Sumatera Selatan   11
14           16                 Dki Jakarta   15
15           17         Nusa Tenggara Timur   19
16           18            Kalimantan Barat   17
17           19                      Maluku   20
18           20          Kalimantan Selatan   16
19           21           Kalimantan Tengah   18
20           22                Papua Tengah   23
21           23              Sulawesi Barat   22
22           24                 Papua Barat   25
23           25               Papua Selatan   21
24           26            Papua Pegunungan   24
25           27              Kepulauan Riau   29
26           28           Sulawesi Tenggara   28
27           29                       Papua   26
28           30                        Riau   30
29           31             Sulawesi Tengah   27
30           32            Kalimantan Timur   32
31           33            Kalimantan Utara   33
32           34              Sulawesi Utara   34
33           35                        Aceh   35
34           36              Sumatera Utara   31
35           37                Maluku Utara   36
36           38                   Gorontalo   38
37           39            Papua Barat Daya   37

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: WEB_BERITA
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id_berita               0 non-null      object
 1   judul_berita            0 non-null      object
 2   konten_berita           0 non-null      object
 3   path_gambar_berita      0 non-null      object
 4   urutan_tampilan_berita  0 non-null      object
dtypes: object(5)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

Empty DataFrame
Columns: [id_berita, judul_berita, konten_berita, path_gambar_berita, urutan_tampilan_berita]
Index: []

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: WEB_STATISTIK
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_stat         0 non-null      object
 1   tanggal_stat    0 non-null      object
 2   jumlah_unduhan  0 non-null      object
 3   pengguna_aktif  0 non-null      object
dtypes: object(4)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

Empty DataFrame
Columns: [id_stat, tanggal_stat, jumlah_unduhan, pengguna_aktif]
Index: []

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: KURSUS
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_kursus     21 non-null     object
 1   nama_kursus   21 non-null     object
 2   deskripsi     21 non-null     object
 3   tipe_kursus   21 non-null     object
 4   status_arsip  21 non-null     int64
dtypes: int64(1), object(4)
memory usage: 972.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

,id_kursus,nama_kursus,deskripsi,tipe_kursus,status_arsip
0,K00001,LEAP - General English,"GE, Balloons, Gogo, SO, Winner",B2C,0
1,K00002,LEAP - Coding Class,Coding Class Regular,B2C,0
2,K00003,LEAP - Leap Literacy Club,LLC,B2C,0
3,K00004,LEAP - Conversation Class,Conversation Class for Adults,B2C,0
4,K00005,LEAP - Aplikasi Perkantoran,"All In, Private,",B2C,0
5,K00006,Kemitraan - B2B Supervisi Guru,Nurul Faizah,B2C,0
6,K00007,Kemitraan - B2B Business English,"Delta Jaya, Hartono, PT HCA",B2C,0
7,K00009,Kemitraan - B2C Talentvis,Talentvis,B2C,0
8,K00010,LEAP - General English 2024,NEW CURRICULUM 2024,B2C,0
9,K00011,Kemitraan - B2B Language Upskilling Program,Nurul Faizah Agt 24 - Mei 25,B2C,0
10,K00012,Kemitraan - B2B Ekskul Coding 1,SD AL Muslim,B2C,0
11,K00013,LEAP - LX,Leapxperience,B2C,0
12,K00014,LEAP - Coding Class 2024,NEW CURRICULUM DOYOBI 2024,B2C,0
13,K00015,LEAP - Coding Class 2025,NEW CURR BSD EDU,B2C,0
14,K00016,LEAP - Leap Literacy Club 2025,LLC NEW LEVEL NAME,B2C,0
15,K00017,Coba Raport,untuk coba coba saja,B2C,0
16,K00018,Kemitraan - B2B Ekskul Coding 2025,"Artistic Coders, Bot Chatters, Curious Creator...",B2C,0
17,K00019,Kemitraan - B2B Rupin General English,Gogo,B2C,0
18,K00020,Kemitraan - B2B Rupin Komputer,"Ms. Word, Excel, PPT",B2C,0
19,K00021,Kemitraan - B2B TK Mitra,"TK Mitra MJ (Seperti Balloons): Agripina, Al W...",B2C,0
20,K00022,Kemitraan - B2B CC Mitra,Convo for kids MJ,B2C,0

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: LEVEL
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181 entries, 0 to 180
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_level      181 non-null    object
 1   nama_level    181 non-null    object
 2   urutan_level  181 non-null    int64
dtypes: int64(1), object(2)
memory usage: 4.4+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

    id_level   nama_level  urutan_level
0     L00001  Balloons 1A             1
1     L00002  Balloons 1B             2
2     L00003  Balloons 1C             3
3     L00004  Balloons 2A             4
4     L00005  Balloons 2B             5
..       ...          ...           ...
176   L00185            4             4
177   L00186            1             1
178   L00187            2             2
179   L00188            3             3
180   L00189            4             4

[181 rows x 3 columns]

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: SESI
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_sesi        43 non-null     object
 1   nama_sesi      43 non-null     object
 2   waktu_mulai    43 non-null     timedelta64[ns]
 3   waktu_selesai  43 non-null     timedelta64[ns]
dtypes: object(2), timedelta64[ns](2)
memory usage: 1.5+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

   id_sesi                      nama_sesi     waktu_mulai   waktu_selesai
0   S00001                  GE/LLC Sesi 1 0 days 15:45:00 0 days 16:45:00
1   S00002                  GE/LLC Sesi 2 0 days 17:00:00 0 days 18:00:00
2   S00003                  GE/LLC Sesi 3 0 days 18:15:00 0 days 19:15:00
3   S00004                 CC Kids Sesi 1 0 days 10:10:00 0 days 11:10:00
4   S00005                CC Adult Sesi 1 0 days 16:00:00 0 days 17:00:00
5   S00006                CC Adult Sesi 3 0 days 20:00:00 0 days 21:00:00
6   S00007                  CODING Sesi 1 0 days 15:00:00 0 days 16:00:00
7   S00008                  CODING Sesi 2 0 days 16:00:00 0 days 17:00:00
8   S00009                  CODING Sesi 3 0 days 17:00:00 0 days 18:00:00
9   S00010                  CODING Sesi 4 0 days 17:45:00 0 days 18:45:00
10  S00011                   Nurul Faizah 0 days 07:35:00 0 days 09:55:00
11  S00012           BE Delta Jaya Sesi 1 0 days 13:00:00 0 days 14:30:00
12  S00013           BE Delta Jaya Sesi 2 0 days 14:45:00 0 days 16:15:00
13  S00014               Talentvis Sesi 1 0 days 10:00:00 0 days 12:30:00
14  S00015               Talentvis Sesi 2 0 days 13:00:00 0 days 16:00:00
15  S00016              BE HARTONO Sesi 1 0 days 09:00:00 0 days 10:00:00
16  S00017              BE HARTONO Sesi 2 0 days 10:30:00 0 days 12:00:00
17  S00018                CC Adult Sesi 2 0 days 18:15:00 0 days 19:15:00
18  S00019  Language Upskilling Program 1 0 days 14:55:00 0 days 15:55:00
19  S00020           Ekskul Coding SESI 1 0 days 14:00:00 0 days 15:30:00
20  S00021          BE HARTONO NEW SESI 1 0 days 08:00:00 0 days 09:00:00
21  S00022          BE HARTONO NEW SESI 2 0 days 08:00:00 0 days 09:30:00
22  S00023          BE HARTONO NEW SESI 3 0 days 09:15:00 0 days 10:15:00
23  S00024          BE HARTONO NEW SESI 4 0 days 09:45:00 0 days 11:15:00
24  S00025          BE HARTONO NEW SESI 5 0 days 10:45:00 0 days 11:45:00
25  S00026          BE HARTONO NEW SESI 6 0 days 11:30:00 0 days 13:00:00
26  S00027          BE HARTONO NEW SESI 7 0 days 12:00:00 0 days 13:00:00
27  S00028       SESI COBA JANGAN DIHAPUS 0 days 11:26:00 0 days 13:26:00
28  S00029                  CODING Sesi 5 0 days 18:00:00 0 days 19:00:00
29  S00030           Ekskul Coding SESI 2 0 days 14:10:00 0 days 15:10:00
30  S00031               RUPIN BSI SESI 4 0 days 13:00:00 0 days 14:00:00
31  S00032               RUPIN BSI SESI 5 0 days 14:30:00 0 days 15:30:00
32  S00033             TK MITRA MJ Sesi 1 0 days 07:45:00 0 days 09:15:00
33  S00034             TK MITRA MJ Sesi 2 0 days 09:00:00 0 days 10:00:00
34  S00035             TK MITRA MJ Sesi 3 0 days 09:00:00 0 days 10:30:00
35  S00036             TK MITRA MJ Sesi 4 0 days 10:45:00 0 days 11:45:00
36  S00037             TK MITRA MJ Sesi 5 0 days 10:50:00 0 days 11:50:00
37  S00038             TK MITRA MJ Sesi 6 0 days 11:00:00 0 days 12:00:00
38  S00039             TK MITRA MJ Sesi 7 0 days 11:30:00 0 days 12:30:00
39  S00040             TK MITRA MJ Sesi 8 0 days 12:00:00 0 days 13:00:00
40  S00041             TK MITRA MJ Sesi 9 0 days 12:30:00 0 days 13:30:00
41  S00042                CC Adult Sesi 3 0 days 19:00:00 0 days 20:00:00
42  S00043               BE PT HCA SESI 1 0 days 15:00:00 0 days 17:00:00

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: TOPIK_DISKUSI
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 3 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id_topik_diskusi         11 non-null     int64
 1   topik_diskusi            11 non-null     object
 2   deskripsi_topik_diskusi  11 non-null     object
dtypes: int64(1), object(2)
memory usage: 396.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

,id_topik_diskusi,topik_diskusi,deskripsi_topik_diskusi
0,1,Kendala Siswa,
1,2,Kendala Kelas,
2,3,Kendala Jadwal,
3,4,Ujian Susulan & Remidi,
4,5,"Kendala Zoom, Class In, Koneksi & Device",
5,6,Update Diskusi,
6,7,Siswa Off/Postponed/Pindah Program,
7,8,Progress Siswa,
8,9,Update Siswa Sit-in/Trial/Baru,
9,10,Siswa Tidak Naik,
10,11,Tambahan Sesi,

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: KURSUS_LEVEL
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181 entries, 0 to 180
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_kursus_level  181 non-null    int64
 1   id_kursus        181 non-null    object
 2   id_level         181 non-null    object
dtypes: int64(1), object(2)
memory usage: 4.4+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

     id_kursus_level id_kursus id_level
0                  1    K00001   L00001
1                  2    K00001   L00002
2                  3    K00001   L00003
3                  4    K00001   L00004
4                  5    K00001   L00005
..               ...       ...      ...
176              177    K00021   L00183
177              178    K00022   L00186
178              179    K00022   L00187
179              180    K00022   L00188
180              181    K00022   L00189

[181 rows x 3 columns]

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: KURSUS_LIBUR
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_kursus_libur  2 non-null      int64
 1   id_kursus        2 non-null      object
 2   id_libur         2 non-null      object
dtypes: int64(1), object(2)
memory usage: 180.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

   id_kursus_libur id_kursus id_libur
0                1    K00001   L00070
1                2    K00001   L00068

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: PERMISSIONS
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          0 non-null      object
 1   name        0 non-null      object
 2   guard_name  0 non-null      object
 3   created_at  0 non-null      object
 4   updated_at  0 non-null      object
dtypes: object(5)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

Empty DataFrame
Columns: [id, name, guard_name, created_at, updated_at]
Index: []

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: ROLE_HAS_PERMISSIONS
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   permission_id  0 non-null      object
 1   role_id        0 non-null      object
dtypes: object(2)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

Empty DataFrame
Columns: [permission_id, role_id]
Index: []

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: BUSDEV_BIDANG
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_bidang    4 non-null      int64
 1   nama_bidang  4 non-null      object
dtypes: int64(1), object(1)
memory usage: 196.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

   id_bidang        nama_bidang
0          7  Sales & Marketing
1          8              R & D
2          9       Sosial Media
3         11          Komunitas

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: SYARAT_RESIGN
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_syarat   1 non-null      int64
 1   isi_syarat  1 non-null      object
dtypes: int64(1), object(1)
memory usage: 148.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

   id_syarat                                         isi_syarat
0          1  <p>SOP pemutusan kerja dan pengunduran diri Ka...

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: TTD
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id_ttd  1 non-null      int64
 1   ttd     1 non-null      object
 2   status  1 non-null      object
dtypes: int64(1), object(2)
memory usage: 156.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

   id_ttd                                  ttd status
0       1  1775719060_815664e38e280d4e971a.png     Ya

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: TAG_SISWA_KELUAR
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_tag_keluar      11 non-null     int64
 1   nama_tag           11 non-null     object
 2   keterangan_keluar  11 non-null     object
dtypes: int64(1), object(2)
memory usage: 396.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

,id_tag_keluar,nama_tag,keterangan_keluar
0,1,AKADEMIK,"Jika siswa tidak naik/lulus level, merasa tida..."
1,2,APLIKASI,Jika siswa merasa kesulitan mengoperasikan Lea...
2,3,DOMISILI,"Jika siswa pindah luar kota, ingin les PTM nam..."
3,4,INSTRUKTUR,Jika siswa merasa lebih menyukai cara mengajar...
4,5,JADWAL,Jika siswa memiliki jadwal kegiatan yang lebih...
5,6,KELUARGA,"Jika siswa memiliki masalah keluarga, saudara ..."
6,7,KEUANGAN,Jika siswa memiliki kendala ekonomi di keluarg...
7,8,LAINNYA,
8,9,LULUS,Jika siswa sudah lulus kesluruhan level di pro...
9,10,PROGRAM,Jika siswa merasa bosan dengan materi dan akti...
10,11,TIDAK ADA ALASAN,Jika siswa tidak memberikan alasan ijin cuti a...

================================================================================