# fase_1 - script_cimut Migration

This notebook handles migration of database from old DB to new DB for fase 1.

**Purpose**: Benerin database lama ke database baru untuk bagian [NAMA TABEL]

In [16]:
import sys
import os
import mysql.connector
import pandas as pd
sys.path.append(os.path.abspath('..'))
from config import get_db_config
import warnings
warnings.filterwarnings('ignore')

## 1. Connect ke Database

In [17]:
# Connect ke database config
config = get_db_config()
# Ambil host dari salah satu config (misal db_old)
print(f'Database config loaded: {config["db_old"]["host"]}')

# Connect ke DB Lama
db_old = mysql.connector.connect(**config['db_old'])
cursor_old = db_old.cursor(dictionary=True)
print(f'Connected to old database: {config["db_old"]["database"]}')

# Connect ke DB Baru
db_new = mysql.connector.connect(**config['db_new'])
cursor_new = db_new.cursor(dictionary=True)
print(f'Connected to new database: {config["db_new"]["database"]}')

# Connect ke DB Future
db_future = mysql.connector.connect(**config['db_future'])
cursor_future = db_future.cursor(dictionary=True)
print(f'Connected to future database: {config["db_future"]["database"]}')

Database config loaded: localhost
Connected to old database: dataleap_v5_example
Connected to new database: dataleap_v5_migration
Connected to future database: 2

## 2. Ambil Data dari DB Lama

In [18]:
# ---------------------------------------------------------
# UPDATE: AMBIL DAFTAR TABEL SECARA DINAMIS
# ---------------------------------------------------------
cursor_old.execute("SHOW TABLES")
tables_data = cursor_old.fetchall()

# Mengambil nama tabel dari hasil query
# Note: Format output 'SHOW TABLES' biasanya {'Tables_in_dbname': 'tablename'}
target_tables = [list(t.values())[0] for t in tables_data]

print(f"\n--- Ditemukan {len(target_tables)} tabel di Database Lama ---")
print(target_tables)

# Dictionary untuk menyimpan data yang sudah di-load
df_old = {}

print("\n--- Memulai proses load semua data tabel ---")

for table in target_tables:
    try:
        # Load data menggunakan pandas langsung dari koneksi SQL
        query = f"SELECT * FROM `{table}`"
        df_old[table] = pd.read_sql(query, db_old)
        
        print(f"Berhasil load tabel: {table} | Jumlah baris: {len(df_old[table])}")
        
    except Exception as e:
        print(f"Gagal load tabel {table}: {e}")

print("\n--- Proses load selesai. Semua data tersimpan di 'df_old' ---")
print("Kamu sekarang bisa akses datanya dengan: df_old['nama_tabel']")

# Contoh akses data:
# print(df_old['users'].head())

# Tutup koneksi jika sudah tidak digunakan
# db_old.close()
# db_new.close()

--- Ditemukan 108 tabel di Database Lama ---
['absensi', 'absensi_note', 'bidang', 'bidangkategori', 'bidanglink', 'calon', 'calon_detil', 'calon_pertanyaan', 'calon_pertanyaan_detil', 'catatan_kelas', 'catatan_kelas_tag', 'catatan_mingguan', 'catatan_siswa', 'catatan_siswa_follow_up', 'catatanawal_admin', 'catatanawal_datautama', 'catatanawal_infolain', 'catatanawal_tglpenting', 'divisi', 'docs', 'file_rapor_siswa', 'form', 'form_calon', 'form_calon_detil1', 'form_calon_detil2', 'form_calon_detil3', 'form_calon_detil4', 'format_rapor', 'format_rapor_detil', 'format_rapor_detil_rumus', 'format_rapor_rumus', 'format_raport_level', 'hakakses', 'histori_pengajuan', 'history_rapor', 'identitas', 'infrastruktur', 'jabatan', 'jadwal', 'jadwal_detil', 'jadwal_pengajar', 'jadwal_siswa', 'jamkerja', 'kabupaten', 'karyawan', 'kecamatan', 'keluar', 'keluarga', 'kelurahan', 'kurikulum', 'kurikulum_detil', 'kurikulum_detil_sub', 'kurikulum_kelas', 'kursus', 'leapprofil', 'leapverse', 'level', 'libur', 'libur_pendkursus', 'linkdrive', 'linkform', 'log', 'mitra', 'mitra_note', 'mitra_users', 'mou', 'mou_histori', 'nowag', 'parameter_nilai', 'pekerjaan', 'pelamar', 'pelamar_note', 'pelamar_submit', 'pelamar_users', 'pendidikan', 'pendidikankursus', 'pengajuan', 'pengumuman', 'perijinan', 'perijinan_note', 'periode', 'pinjam', 'presensi_siswa', 'problem', 'provinsi', 'purchase', 'purchase_link', 'rapor', 'role', 'role_users', 'sesi', 'siswa', 'siswa_keluar', 'siswa_keluar_mitra', 'siswa_keluar_tag', 'siswamitra', 'sop', 'sopkategori', 'suratkeluar', 'suratkeluar_histori', 'surattugas', 'surattugas_users', 'syarat', 'tag_keluar', 'tag_materi_diskusi', 'ttd', 'users', 'zoom']

--- Memulai proses load semua data tabel ---
Berhasil load tabel: absensi | Jumlah baris: 13444
Berhasil load tabel: absensi_note | Jumlah baris: 11
Berhasil load tabel: bidang | Jumlah baris: 4
Berhasil load tabel: bidangkategori | Jumlah baris: 12
Berhasil load tabel: bidanglink | Jumlah baris: 7
Berhasil load tabel: calon | Jumlah baris: 4
Berhasil load tabel: calon_detil | Jumlah baris: 61
Berhasil load tabel: calon_pertanyaan | Jumlah baris: 229
Berhasil load tabel: calon_pertanyaan_detil | Jumlah baris: 4305
Berhasil load tabel: catatan_kelas | Jumlah baris: 12797
Berhasil load tabel: catatan_kelas_tag | Jumlah baris: 999
Berhasil load tabel: catatan_mingguan | Jumlah baris: 0
Berhasil load tabel: catatan_siswa | Jumlah baris: 1502
Berhasil load tabel: catatan_siswa_follow_up | Jumlah baris: 22
Berhasil load tabel: catatanawal_admin | Jumlah baris: 64
Berhasil load tabel: catatanawal_datautama | Jumlah baris: 9
Berhasil load tabel: catatanawal_infolain | Jumlah baris: 64
Berhasil load tabel: catatanawal_tglpenting | Jumlah baris: 10
Berhasil load tabel: divisi | Jumlah baris: 6
Berhasil load tabel: docs | Jumlah baris: 0
Berhasil load tabel: file_rapor_siswa | Jumlah baris: 1506
Berhasil load tabel: form | Jumlah baris: 1
Berhasil load tabel: form_calon | Jumlah baris: 184
Berhasil load tabel: form_calon_detil1 | Jumlah baris: 77
Berhasil load tabel: form_calon_detil2 | Jumlah baris: 77
Berhasil load tabel: form_calon_detil3 | Jumlah baris: 77
Berhasil load tabel: form_calon_detil4 | Jumlah baris: 77
Berhasil load tabel: format_rapor | Jumlah baris: 45
Berhasil load tabel: format_rapor_detil | Jumlah baris: 129
Berhasil load tabel: format_rapor_detil_rumus | Jumlah baris: 1650
Berhasil load tabel: format_rapor_rumus | Jumlah baris: 3
Berhasil load tabel: format_raport_level | Jumlah baris: 348
Berhasil load tabel: hakakses | Jumlah baris: 6
Berhasil load tabel: histori_pengajuan | Jumlah baris: 79
Berhasil load tabel: history_rapor | Jumlah baris: 1366
Berhasil load tabel: identitas | Jumlah baris: 0
Berhasil load tabel: infrastruktur | Jumlah baris: 1
Berhasil load tabel: jabatan | Jumlah baris: 11
Berhasil load tabel: jadwal | Jumlah baris: 551
Berhasil load tabel: jadwal_detil | Jumlah baris: 17267
Berhasil load tabel: jadwal_pengajar | Jumlah baris: 641
Berhasil load tabel: jadwal_siswa | Jumlah baris: 3905
Berhasil load tabel: jamkerja | Jumlah baris: 3
Berhasil load tabel: kabupaten | Jumlah baris: 521
Berhasil load tabel: karyawan | Jumlah baris: 51
Berhasil load tabel: kecamatan | Jumlah baris: 7269
Berhasil load tabel: keluar | Jumlah baris: 51
Berhasil load tabel: keluarga | Jumlah baris: 64
Berhasil load tabel: kelurahan | Jumlah baris: 83473
Berhasil load tabel: kurikulum | Jumlah baris: 0
Berhasil load tabel: kurikulum_detil | Jumlah baris: 0
Berhasil load tabel: kurikulum_detil_sub | Jumlah baris: 0
Berhasil load tabel: kurikulum_kelas | Jumlah baris: 0
Berhasil load tabel: kursus | Jumlah baris: 50
Berhasil load tabel: leapprofil | Jumlah baris: 0
Berhasil load tabel: leapverse | Jumlah baris: 365
Berhasil load tabel: level | Jumlah baris: 181
Berhasil load tabel: libur | Jumlah baris: 79
Berhasil load tabel: libur_pendkursus | Jumlah baris: 2
Berhasil load tabel: linkdrive | Jumlah baris: 0
Berhasil load tabel: linkform | Jumlah baris: 3
Berhasil load tabel: log | Jumlah baris: 21887
Berhasil load tabel: mitra | Jumlah baris: 22
Berhasil load tabel: mitra_note | Jumlah baris: 296
Berhasil load tabel: mitra_users | Jumlah baris: 228
Berhasil load tabel: mou | Jumlah baris: 2
Berhasil load tabel: mou_histori | Jumlah baris: 10
Berhasil load tabel: nowag | Jumlah baris: 1
Berhasil load tabel: parameter_nilai | Jumlah baris: 1187
Berhasil load tabel: pekerjaan | Jumlah baris: 67
Berhasil load tabel: pelamar | Jumlah baris: 178
Berhasil load tabel: pelamar_note | Jumlah baris: 403
Berhasil load tabel: pelamar_submit | Jumlah baris: 0
Berhasil load tabel: pelamar_users | Jumlah baris: 281
Berhasil load tabel: pendidikan | Jumlah baris: 53
Berhasil load tabel: pendidikankursus | Jumlah baris: 21
Berhasil load tabel: pengajuan | Jumlah baris: 33
Berhasil load tabel: pengumuman | Jumlah baris: 1
Berhasil load tabel: perijinan | Jumlah baris: 957
Berhasil load tabel: perijinan_note | Jumlah baris: 2107
Berhasil load tabel: periode | Jumlah baris: 93
Berhasil load tabel: pinjam | Jumlah baris: 194
Berhasil load tabel: presensi_siswa | Jumlah baris: 97762
Berhasil load tabel: problem | Jumlah baris: 160
Berhasil load tabel: provinsi | Jumlah baris: 36
Berhasil load tabel: purchase | Jumlah baris: 110
Berhasil load tabel: purchase_link | Jumlah baris: 1
Berhasil load tabel: rapor | Jumlah baris: 22837
Berhasil load tabel: role | Jumlah baris: 9
Berhasil load tabel: role_users | Jumlah baris: 0
Berhasil load tabel: sesi | Jumlah baris: 43
Berhasil load tabel: siswa | Jumlah baris: 1469
Berhasil load tabel: siswa_keluar | Jumlah baris: 556
Berhasil load tabel: siswa_keluar_mitra | Jumlah baris: 0
Berhasil load tabel: siswa_keluar_tag | Jumlah baris: 404
Berhasil load tabel: siswamitra | Jumlah baris: 0
Berhasil load tabel: sop | Jumlah baris: 4
Berhasil load tabel: sopkategori | Jumlah baris: 3
Berhasil load tabel: suratkeluar | Jumlah baris: 213
Berhasil load tabel: suratkeluar_histori | Jumlah baris: 477
Berhasil load tabel: surattugas | Jumlah baris: 135
Berhasil load tabel: surattugas_users | Jumlah baris: 304
Berhasil load tabel: syarat | Jumlah baris: 1
Berhasil load tabel: tag_keluar | Jumlah baris: 11
Berhasil load tabel: tag_materi_diskusi | Jumlah baris: 11
Berhasil load tabel: ttd | Jumlah baris: 1
Berhasil load tabel: users | Jumlah baris: 51
Berhasil load tabel: zoom | Jumlah baris: 14

--- Proses load selesai. Semua data tersimpan di 'df_old' ---
Kamu sekarang bisa akses datanya dengan: df_old['nama_tabel']

In [19]:
# ---------------------------------------------------------
# UPDATE: AMBIL DAFTAR TABEL SECARA DINAMIS (DATABASE BARU)
# ---------------------------------------------------------
# Menggunakan cursor dari database baru
cursor_new.execute("SHOW TABLES")
tables_data_new = cursor_new.fetchall()

# Mengambil nama tabel dari hasil query
target_tables_new = [list(t.values())[0] for t in tables_data_new]

print(f"\n--- Ditemukan {len(target_tables_new)} tabel di Database Baru ---")
print(target_tables_new)

# Dictionary untuk menyimpan data dari database baru (jika diperlukan untuk verifikasi)
df_new = {}

print("\n--- Memulai proses load semua data dari Database Baru ---")

for table in target_tables_new:
    try:
        # Load data menggunakan pandas dengan koneksi database baru
        query = f"SELECT * FROM `{table}`"
        df_new[table] = pd.read_sql(query, db_new)
        
        print(f"Berhasil load tabel: {table} | Jumlah baris: {len(df_new[table])}")
        
    except Exception as e:
        print(f"Gagal load tabel {table} dari DB Baru: {e}")

print("\n--- Proses load selesai. Data DB Baru tersimpan di 'df_new' ---")

--- Ditemukan 104 tabel di Database Baru ---
['absensi', 'activity_log', 'admin_sarpras', 'bidang_kategori', 'bidang_link', 'busdev_bidang', 'cache', 'cache_locks', 'calon_siswa', 'calon_siswa_akademik', 'calon_siswa_bayar', 'calon_siswa_jadwal', 'calon_siswa_kursus', 'calon_siswa_ortu', 'calon_siswa_proses', 'calon_siswa_status_logs', 'catatan_kelas', 'catatan_kelas_tag', 'catatan_mingguan', 'catatan_siswa', 'division_user', 'divisions', 'failed_jobs', 'followup_cs', 'histori_pengajuan', 'izin_karyawan', 'jadwal', 'jadwal_detail', 'jadwal_detail_logs', 'jadwal_hari', 'jadwal_pengajar', 'jadwal_siswa', 'job_batches', 'jobs', 'kabupaten', 'karyawan', 'karyawan_resign', 'kecamatan', 'keluarga_karyawan', 'kelurahan', 'kemitraan_verifikator', 'kontak_prospek', 'kursus', 'kursus_level', 'kursus_libur', 'kursus_siswa', 'level', 'libur', 'log_aktivitas', 'migrations', 'mitra', 'mitra_progres', 'model_has_permissions', 'model_has_roles', 'mou', 'parameter_nilai', 'password_reset_tokens', 'pelamar', 'pelamar_kerja', 'pelamar_kursus', 'pelamar_sekolah', 'peminjaman', 'pengadaan', 'pengajuan_karyawan', 'periode', 'permissions', 'presensi_siswa', 'problem', 'progres_pelamar', 'provinsi', 'rapor_format', 'rapor_format_formula', 'rapor_format_formula_sub', 'rapor_format_sub', 'rapor_lacak', 'rapor_level_config', 'rapor_siswa', 'rapor_siswa_file', 'rapor_sub_level', 'rekrutmen_pelamar', 'role_has_permissions', 'roles', 'sesi', 'sessions', 'shift_kerja', 'siswa', 'siswa_keluar', 'siswa_mitra', 'siswa_mitra_keluar', 'sop', 'sop_kategori', 'surat_keluar', 'surat_tugas', 'surat_tugas_anggota', 'syarat_resign', 'tag_siswa_keluar', 'topik_diskusi', 'ttd', 'users', 'verifikasi_absensi', 'verifikasi_izin', 'verifikasi_surat_keluar', 'web_berita', 'web_statistik']

--- Memulai proses load semua data dari Database Baru ---
Berhasil load tabel: absensi | Jumlah baris: 0
Berhasil load tabel: activity_log | Jumlah baris: 0
Berhasil load tabel: admin_sarpras | Jumlah baris: 1
Berhasil load tabel: bidang_kategori | Jumlah baris: 12
Berhasil load tabel: bidang_link | Jumlah baris: 7
Berhasil load tabel: busdev_bidang | Jumlah baris: 4
Berhasil load tabel: cache | Jumlah baris: 0
Berhasil load tabel: cache_locks | Jumlah baris: 0
Berhasil load tabel: calon_siswa | Jumlah baris: 165
Berhasil load tabel: calon_siswa_akademik | Jumlah baris: 338
Berhasil load tabel: calon_siswa_bayar | Jumlah baris: 338
Berhasil load tabel: calon_siswa_jadwal | Jumlah baris: 338
Berhasil load tabel: calon_siswa_kursus | Jumlah baris: 338
Berhasil load tabel: calon_siswa_ortu | Jumlah baris: 338
Berhasil load tabel: calon_siswa_proses | Jumlah baris: 338
Berhasil load tabel: calon_siswa_status_logs | Jumlah baris: 0
Berhasil load tabel: catatan_kelas | Jumlah baris: 25594
Berhasil load tabel: catatan_kelas_tag | Jumlah baris: 0
Berhasil load tabel: catatan_mingguan | Jumlah baris: 0
Berhasil load tabel: catatan_siswa | Jumlah baris: 0
Berhasil load tabel: division_user | Jumlah baris: 0
Berhasil load tabel: divisions | Jumlah baris: 12
Berhasil load tabel: failed_jobs | Jumlah baris: 0
Berhasil load tabel: followup_cs | Jumlah baris: 0
Berhasil load tabel: histori_pengajuan | Jumlah baris: 79
Berhasil load tabel: izin_karyawan | Jumlah baris: 0
Berhasil load tabel: jadwal | Jumlah baris: 1098
Berhasil load tabel: jadwal_detail | Jumlah baris: 34514
Berhasil load tabel: jadwal_detail_logs | Jumlah baris: 0
Berhasil load tabel: jadwal_hari | Jumlah baris: 1950
Berhasil load tabel: jadwal_pengajar | Jumlah baris: 1280
Berhasil load tabel: jadwal_siswa | Jumlah baris: 0
Berhasil load tabel: job_batches | Jumlah baris: 0
Berhasil load tabel: jobs | Jumlah baris: 0
Berhasil load tabel: kabupaten | Jumlah baris: 514
Berhasil load tabel: karyawan | Jumlah baris: 51
Berhasil load tabel: karyawan_resign | Jumlah baris: 0
Berhasil load tabel: kecamatan | Jumlah baris: 7266
Berhasil load tabel: keluarga_karyawan | Jumlah baris: 64
Berhasil load tabel: kelurahan | Jumlah baris: 83449
Berhasil load tabel: kemitraan_verifikator | Jumlah baris: 0
Berhasil load tabel: kontak_prospek | Jumlah baris: 210
Berhasil load tabel: kursus | Jumlah baris: 21
Berhasil load tabel: kursus_level | Jumlah baris: 543
Berhasil load tabel: kursus_libur | Jumlah baris: 6
Berhasil load tabel: kursus_siswa | Jumlah baris: 0
Berhasil load tabel: level | Jumlah baris: 181
Berhasil load tabel: libur | Jumlah baris: 79
Berhasil load tabel: log_aktivitas | Jumlah baris: 0
Berhasil load tabel: migrations | Jumlah baris: 0
Berhasil load tabel: mitra | Jumlah baris: 1
Berhasil load tabel: mitra_progres | Jumlah baris: 0
Berhasil load tabel: model_has_permissions | Jumlah baris: 0
Berhasil load tabel: model_has_roles | Jumlah baris: 0
Berhasil load tabel: mou | Jumlah baris: 0
Berhasil load tabel: parameter_nilai | Jumlah baris: 2374
Berhasil load tabel: password_reset_tokens | Jumlah baris: 0
Berhasil load tabel: pelamar | Jumlah baris: 0
Berhasil load tabel: pelamar_kerja | Jumlah baris: 0
Berhasil load tabel: pelamar_kursus | Jumlah baris: 0
Berhasil load tabel: pelamar_sekolah | Jumlah baris: 0
Berhasil load tabel: peminjaman | Jumlah baris: 194
Berhasil load tabel: pengadaan | Jumlah baris: 110
Berhasil load tabel: pengajuan_karyawan | Jumlah baris: 33
Berhasil load tabel: periode | Jumlah baris: 91
Berhasil load tabel: permissions | Jumlah baris: 0
Berhasil load tabel: presensi_siswa | Jumlah baris: 0
Berhasil load tabel: problem | Jumlah baris: 160
Berhasil load tabel: progres_pelamar | Jumlah baris: 0
Berhasil load tabel: provinsi | Jumlah baris: 38
Berhasil load tabel: rapor_format | Jumlah baris: 45
Berhasil load tabel: rapor_format_formula | Jumlah baris: 9
Berhasil load tabel: rapor_format_formula_sub | Jumlah baris: 4950
Berhasil load tabel: rapor_format_sub | Jumlah baris: 129
Berhasil load tabel: rapor_lacak | Jumlah baris: 0
Berhasil load tabel: rapor_level_config | Jumlah baris: 1044
Berhasil load tabel: rapor_siswa | Jumlah baris: 0
Berhasil load tabel: rapor_siswa_file | Jumlah baris: 21
Berhasil load tabel: rapor_sub_level | Jumlah baris: 0
Berhasil load tabel: rekrutmen_pelamar | Jumlah baris: 0
Berhasil load tabel: role_has_permissions | Jumlah baris: 0
Berhasil load tabel: roles | Jumlah baris: 9
Berhasil load tabel: sesi | Jumlah baris: 43
Berhasil load tabel: sessions | Jumlah baris: 0
Berhasil load tabel: shift_kerja | Jumlah baris: 3
Berhasil load tabel: siswa | Jumlah baris: 795
Berhasil load tabel: siswa_keluar | Jumlah baris: 0
Berhasil load tabel: siswa_mitra | Jumlah baris: 0
Berhasil load tabel: siswa_mitra_keluar | Jumlah baris: 0
Berhasil load tabel: sop | Jumlah baris: 4
Berhasil load tabel: sop_kategori | Jumlah baris: 3
Berhasil load tabel: surat_keluar | Jumlah baris: 213
Berhasil load tabel: surat_tugas | Jumlah baris: 135
Berhasil load tabel: surat_tugas_anggota | Jumlah baris: 260
Berhasil load tabel: syarat_resign | Jumlah baris: 1
Berhasil load tabel: tag_siswa_keluar | Jumlah baris: 11
Berhasil load tabel: topik_diskusi | Jumlah baris: 33
Berhasil load tabel: ttd | Jumlah baris: 1
Berhasil load tabel: users | Jumlah baris: 51
Berhasil load tabel: verifikasi_absensi | Jumlah baris: 11
Berhasil load tabel: verifikasi_izin | Jumlah baris: 0
Berhasil load tabel: verifikasi_surat_keluar | Jumlah baris: 477
Berhasil load tabel: web_berita | Jumlah baris: 0
Berhasil load tabel: web_statistik | Jumlah baris: 0

--- Proses load selesai. Data DB Baru tersimpan di 'df_new' ---

In [20]:
# ---------------------------------------------------------
# UPDATE: AMBIL DAFTAR TABEL SECARA DINAMIS (DATABASE BARU)
# ---------------------------------------------------------
# Menggunakan cursor dari database baru
cursor_future.execute("SHOW TABLES")
tables_data_future = cursor_future.fetchall()

# Mengambil nama tabel dari hasil query
target_tables_future = [list(t.values())[0] for t in tables_data_future]

print(f"\n--- Ditemukan {len(target_tables_future)} tabel di Database Future ---")
print(target_tables_future)

# Dictionary untuk menyimpan data dari database future (jika diperlukan untuk verifikasi)
df_future = {}

print("\n--- Memulai proses load semua data dari Database Future ---")

for table in target_tables_future:
    try:
        # Load data menggunakan pandas dengan koneksi database future
        query = f"SELECT * FROM `{table}`"
        df_future[table] = pd.read_sql(query, db_future)
        
        print(f"Berhasil load tabel: {table} | Jumlah baris: {len(df_future[table])}")
        
    except Exception as e:
        print(f"Gagal load tabel {table} dari DB Future: {e}")

print("\n--- Proses load selesai. Data DB Future tersimpan di 'df_future' ---")

--- Ditemukan 113 tabel di Database Future ---
['absensi', 'activity_log', 'admin_sarpras', 'bidang_kategori', 'bidang_link', 'busdev_bidang', 'cache', 'cache_locks', 'calon_siswa', 'calon_siswa_akademik', 'calon_siswa_bayar', 'calon_siswa_fo_detail', 'calon_siswa_form_program_requirements', 'calon_siswa_form_programs', 'calon_siswa_jadwal', 'calon_siswa_kursus', 'calon_siswa_ortu', 'calon_siswa_proses', 'calon_siswa_proses_logs', 'calon_siswa_status_logs', 'catatan_kelas', 'catatan_kelas_tag', 'catatan_mingguan', 'catatan_remidi_siswa', 'catatan_siswa', 'division_user', 'divisions', 'failed_jobs', 'followup_cs', 'histori_pengajuan', 'izin_karyawan', 'jadwal', 'jadwal_detail', 'jadwal_detail_logs', 'jadwal_hari', 'jadwal_pengajar', 'jadwal_siswa', 'job_batches', 'jobs', 'kabupaten', 'karyawan', 'karyawan_resign', 'kecamatan', 'keluarga_karyawan', 'kelurahan', 'kemitraan_verifikator', 'kontak_prospek', 'kursus', 'kursus_level', 'kursus_libur', 'kursus_siswa', 'level', 'libur', 'log_aktivitas', 'migrations', 'mitra', 'mitra_progres', 'model_has_permissions', 'model_has_roles', 'mou', 'parameter_nilai', 'password_reset_tokens', 'pelamar', 'pelamar_kerja', 'pelamar_kursus', 'pelamar_sekolah', 'peminjaman', 'pengadaan', 'pengajuan_karyawan', 'penilaian_kinerja', 'periode', 'permissions', 'presensi_siswa', 'problem', 'progres_pelamar', 'provinsi', 'rapor_format', 'rapor_format_formula', 'rapor_format_formula_sub', 'rapor_format_sub', 'rapor_lacak', 'rapor_level_config', 'rapor_setting_kursus', 'rapor_siswa', 'rapor_siswa_file', 'rapor_sub_level', 'rekrutmen_pelamar', 'role_has_permissions', 'roles', 'sesi', 'sessions', 'shift_kerja', 'siswa', 'siswa_bulk_edit_logs', 'siswa_keluar', 'siswa_keluar_feedbacks', 'siswa_mitra', 'siswa_mitra_keluar', 'sop', 'sop_kategori', 'surat_keluar', 'surat_tugas', 'surat_tugas_anggota', 'syarat_resign', 'tag_siswa_keluar', 'topik_diskusi', 'ttd', 'users', 'verifikasi_absensi', 'verifikasi_izin', 'verifikasi_surat_keluar', 'web_berita', 'web_statistik']

--- Memulai proses load semua data dari Database Future ---
Berhasil load tabel: absensi | Jumlah baris: 0
Berhasil load tabel: activity_log | Jumlah baris: 0
Berhasil load tabel: admin_sarpras | Jumlah baris: 1
Berhasil load tabel: bidang_kategori | Jumlah baris: 0
Berhasil load tabel: bidang_link | Jumlah baris: 0
Berhasil load tabel: busdev_bidang | Jumlah baris: 0
Berhasil load tabel: cache | Jumlah baris: 0
Berhasil load tabel: cache_locks | Jumlah baris: 0
Berhasil load tabel: calon_siswa | Jumlah baris: 0
Berhasil load tabel: calon_siswa_akademik | Jumlah baris: 0
Berhasil load tabel: calon_siswa_bayar | Jumlah baris: 0
Berhasil load tabel: calon_siswa_fo_detail | Jumlah baris: 0
Berhasil load tabel: calon_siswa_form_program_requirements | Jumlah baris: 0
Berhasil load tabel: calon_siswa_form_programs | Jumlah baris: 0
Berhasil load tabel: calon_siswa_jadwal | Jumlah baris: 0
Berhasil load tabel: calon_siswa_kursus | Jumlah baris: 0
Berhasil load tabel: calon_siswa_ortu | Jumlah baris: 0
Berhasil load tabel: calon_siswa_proses | Jumlah baris: 0
Berhasil load tabel: calon_siswa_proses_logs | Jumlah baris: 0
Berhasil load tabel: calon_siswa_status_logs | Jumlah baris: 0
Berhasil load tabel: catatan_kelas | Jumlah baris: 0
Berhasil load tabel: catatan_kelas_tag | Jumlah baris: 0
Berhasil load tabel: catatan_mingguan | Jumlah baris: 0
Berhasil load tabel: catatan_remidi_siswa | Jumlah baris: 0
Berhasil load tabel: catatan_siswa | Jumlah baris: 0
Berhasil load tabel: division_user | Jumlah baris: 0
Berhasil load tabel: divisions | Jumlah baris: 6
Berhasil load tabel: failed_jobs | Jumlah baris: 0
Berhasil load tabel: followup_cs | Jumlah baris: 0
Berhasil load tabel: histori_pengajuan | Jumlah baris: 0
Berhasil load tabel: izin_karyawan | Jumlah baris: 0
Berhasil load tabel: jadwal | Jumlah baris: 0
Berhasil load tabel: jadwal_detail | Jumlah baris: 0
Berhasil load tabel: jadwal_detail_logs | Jumlah baris: 0
Berhasil load tabel: jadwal_hari | Jumlah baris: 0
Berhasil load tabel: jadwal_pengajar | Jumlah baris: 0
Berhasil load tabel: jadwal_siswa | Jumlah baris: 0
Berhasil load tabel: job_batches | Jumlah baris: 0
Berhasil load tabel: jobs | Jumlah baris: 0
Berhasil load tabel: kabupaten | Jumlah baris: 0
Berhasil load tabel: karyawan | Jumlah baris: 0
Berhasil load tabel: karyawan_resign | Jumlah baris: 0
Berhasil load tabel: kecamatan | Jumlah baris: 0
Berhasil load tabel: keluarga_karyawan | Jumlah baris: 0
Berhasil load tabel: kelurahan | Jumlah baris: 0
Berhasil load tabel: kemitraan_verifikator | Jumlah baris: 0
Berhasil load tabel: kontak_prospek | Jumlah baris: 0
Berhasil load tabel: kursus | Jumlah baris: 21
Berhasil load tabel: kursus_level | Jumlah baris: 181
Berhasil load tabel: kursus_libur | Jumlah baris: 0
Berhasil load tabel: kursus_siswa | Jumlah baris: 0
Berhasil load tabel: level | Jumlah baris: 181
Berhasil load tabel: libur | Jumlah baris: 0
Berhasil load tabel: log_aktivitas | Jumlah baris: 0
Berhasil load tabel: migrations | Jumlah baris: 0
Berhasil load tabel: mitra | Jumlah baris: 0
Berhasil load tabel: mitra_progres | Jumlah baris: 0
Berhasil load tabel: model_has_permissions | Jumlah baris: 0
Berhasil load tabel: model_has_roles | Jumlah baris: 0
Berhasil load tabel: mou | Jumlah baris: 0
Berhasil load tabel: parameter_nilai | Jumlah baris: 0
Berhasil load tabel: password_reset_tokens | Jumlah baris: 0
Berhasil load tabel: pelamar | Jumlah baris: 0
Berhasil load tabel: pelamar_kerja | Jumlah baris: 0
Berhasil load tabel: pelamar_kursus | Jumlah baris: 0
Berhasil load tabel: pelamar_sekolah | Jumlah baris: 0
Berhasil load tabel: peminjaman | Jumlah baris: 0
Berhasil load tabel: pengadaan | Jumlah baris: 0
Berhasil load tabel: pengajuan_karyawan | Jumlah baris: 0
Berhasil load tabel: penilaian_kinerja | Jumlah baris: 0
Berhasil load tabel: periode | Jumlah baris: 0
Berhasil load tabel: permissions | Jumlah baris: 0
Berhasil load tabel: presensi_siswa | Jumlah baris: 0
Berhasil load tabel: problem | Jumlah baris: 0
Berhasil load tabel: progres_pelamar | Jumlah baris: 0
Berhasil load tabel: provinsi | Jumlah baris: 0
Berhasil load tabel: rapor_format | Jumlah baris: 0
Berhasil load tabel: rapor_format_formula | Jumlah baris: 0
Berhasil load tabel: rapor_format_formula_sub | Jumlah baris: 0
Berhasil load tabel: rapor_format_sub | Jumlah baris: 0
Berhasil load tabel: rapor_lacak | Jumlah baris: 0
Berhasil load tabel: rapor_level_config | Jumlah baris: 0
Berhasil load tabel: rapor_setting_kursus | Jumlah baris: 0
Berhasil load tabel: rapor_siswa | Jumlah baris: 0
Berhasil load tabel: rapor_siswa_file | Jumlah baris: 0
Berhasil load tabel: rapor_sub_level | Jumlah baris: 0
Berhasil load tabel: rekrutmen_pelamar | Jumlah baris: 0
Berhasil load tabel: role_has_permissions | Jumlah baris: 0
Berhasil load tabel: roles | Jumlah baris: 0
Berhasil load tabel: sesi | Jumlah baris: 43
Berhasil load tabel: sessions | Jumlah baris: 0
Berhasil load tabel: shift_kerja | Jumlah baris: 3
Berhasil load tabel: siswa | Jumlah baris: 0
Berhasil load tabel: siswa_bulk_edit_logs | Jumlah baris: 0
Berhasil load tabel: siswa_keluar | Jumlah baris: 0
Berhasil load tabel: siswa_keluar_feedbacks | Jumlah baris: 0
Berhasil load tabel: siswa_mitra | Jumlah baris: 0
Berhasil load tabel: siswa_mitra_keluar | Jumlah baris: 0
Berhasil load tabel: sop | Jumlah baris: 0
Berhasil load tabel: sop_kategori | Jumlah baris: 3
Berhasil load tabel: surat_keluar | Jumlah baris: 0
Berhasil load tabel: surat_tugas | Jumlah baris: 0
Berhasil load tabel: surat_tugas_anggota | Jumlah baris: 0
Berhasil load tabel: syarat_resign | Jumlah baris: 0
Berhasil load tabel: tag_siswa_keluar | Jumlah baris: 0
Berhasil load tabel: topik_diskusi | Jumlah baris: 11
Berhasil load tabel: ttd | Jumlah baris: 0
Berhasil load tabel: users | Jumlah baris: 51
Berhasil load tabel: verifikasi_absensi | Jumlah baris: 0
Berhasil load tabel: verifikasi_izin | Jumlah baris: 0
Berhasil load tabel: verifikasi_surat_keluar | Jumlah baris: 0
Berhasil load tabel: web_berita | Jumlah baris: 0
Berhasil load tabel: web_statistik | Jumlah baris: 0

--- Proses load selesai. Data DB Future tersimpan di 'df_future' ---

## 3. Transform Data (jika diperlukan)

users, divisions, shift_kerja, admin_sarpras, sop_kategori, provinsi, web_berita, web_statistik.

In [21]:
df_new['shift_kerja']['nama_shift'] = df_old['jamkerja']['namajamkerja']
df_new['shift_kerja']['jam_masuk']  = df_old['jamkerja']['jammasuk']
df_new['shift_kerja']['jam_pulang'] = df_old['jamkerja']['jampulang']

df_new['admin_sarpras']['wa_admin_sarpras'] = df_old['nowag']['wa']

df_new['sop_kategori']['nama_kategori_sop'] = df_old['sopkategori']['nama']

print("--- Info Tabel Baru (shift_kerja) ---")
df_new['shift_kerja'].info()
print("--- Info Tabel Baru (admin_sarpras) ---")
df_new['admin_sarpras'].info()
print("--- Info Tabel Baru (sop_kategori) ---")
df_new['sop_kategori'].info()

--- Info Tabel Baru (shift_kerja) ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_shift    3 non-null      int64
 1   nama_shift  3 non-null      object
 2   jam_masuk   3 non-null      timedelta64[ns]
 3   jam_pulang  3 non-null      timedelta64[ns]
dtypes: int64(1), object(1), timedelta64[ns](2)
memory usage: 228.0+ bytes
--- Info Tabel Baru (admin_sarpras) ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_admin_sarpras  1 non-null      int64
 1   wa_admin_sarpras  1 non-null      object
dtypes: int64(1), object(1)
memory usage: 148.0+ bytes
--- Info Tabel Baru (sop_kategori) ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_sop_kategori    3 non-null      int64
 1   nama_kategori_sop  3 non-null      object
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes

In [22]:
# Pastikan DataFrame sudah terisi
df_users = df_old['users']

print("--- 1. Pengecekan Nilai Kosong (NULL) ---")
# Cek berapa banyak data kosong di tiap kolom
print(df_users.isnull().sum())

print("\n--- 2. Pengecekan Data Duplikat ---")
# Cek jumlah baris duplikat
duplicate_count = df_users.duplicated().sum()
print(f"Jumlah baris duplikat: {duplicate_count}")

if duplicate_count > 0:
    print("\n--- 3. Contoh Data Duplikat ---")
    # Menampilkan data yang duplikat agar kamu bisa evaluasi
    print(df_users[df_users.duplicated(keep=False)].head())

print("\n--- 4. Pengecekan Format Email (Opsional) ---")
# Contoh: Cek apakah ada email yang tidak mengandung '@' (sederhana)
invalid_emails = df_users[~df_users['email'].str.contains('@', na=False)]
if not invalid_emails.empty:
    print(f"Ada {len(invalid_emails)} email yang formatnya aneh:")
    print(invalid_emails[['email']])
else:
    print("Semua format email terlihat aman.")

--- 1. Pengecekan Nilai Kosong (NULL) ---
idusers        0
email          0
pass           0
nama           1
foto           7
idrole         0
wa             1
thnbekerja     0
idjabatan      0
idjamkerja    37
minat          1
status         0
idbidang      41
ispurchase     1
isteaching     1
ishr           0
isga           0
isit           0
ispdd          0
isbusdev       0
ispimpinan     0
ttd           36
expertise     12
dtype: int64

--- 2. Pengecekan Data Duplikat ---
Jumlah baris duplikat: 0

--- 4. Pengecekan Format Email (Opsional) ---
Semua format email terlihat aman.

In [23]:
df_old['users'].loc[df_old['users']['idusers'] == 'U00046', 'nama'] = 'sosialmedia1'

In [24]:
df_old['users'].isnull().sum()

idusers        0
email          0
pass           0
nama           0
foto           7
idrole         0
wa             1
thnbekerja     0
idjabatan      0
idjamkerja    37
minat          1
status         0
idbidang      41
ispurchase     1
isteaching     1
ishr           0
isga           0
isit           0
ispdd          0
isbusdev       0
ispimpinan     0
ttd           36
expertise     12
dtype: int64

In [25]:
import pandas as pd
import datetime

print("================================================================================")
print(" 🚀 FASE 1 - STEP 1: TRANSFORMASI TABEL USERS (WITH TIMESTAMP FIXED) 🚀 ")
print("================================================================================")

# Ambil waktu saat ini sebagai penanda waktu migrasi resmi
current_time = datetime.datetime.now()

# 🎯 Sesuai arahan Cimut, pasangkan kolom dasar db_old ke wadah df_new
df_new['users']['id_user'] = df_old['users']['idusers']
df_new['users']['name'] = df_old['users']['nama']
df_new['users']['email'] = df_old['users']['email']
df_new['users']['password'] = df_old['users']['pass']

# 🆕 PENAMBAHAN BAGIAN UPDATE BARU: Suntik otomatis kolom timestamp sistem Laravel
df_new['users']['email_verified_at'] = current_time
df_new['users']['created_at'] = current_time
df_new['users']['updated_at'] = current_time

# Tampilkan hasil verifikasi struktur akhir
print("\n✓ Sukses menyinkronkan data users dengan timestamp masa depan!")
print("--- Preview data yang akan diinsert ke tabel users ---")
df_new['users'].info()
display(df_new['users'])

================================================================================
 🚀 FASE 1 - STEP 1: TRANSFORMASI TABEL USERS (WITH TIMESTAMP FIXED) 🚀
================================================================================

✓ Sukses menyinkronkan data users dengan timestamp masa depan!
--- Preview data yang akan diinsert ke tabel users ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_user            51 non-null     object
 1   name               51 non-null     object
 2   email              51 non-null     object
 3   email_verified_at  51 non-null     datetime64[us]
 4   password           51 non-null     object
 5   remember_token     0 non-null      object
 6   created_at         51 non-null     datetime64[us]
 7   updated_at         51 non-null     datetime64[us]
dtypes: datetime64[us](3), object(5)
memory usage: 3.3+ KB

,id_user,name,email,email_verified_at,password,remember_token,created_at,updated_at
0,U00001,ADMINISTRATOR,ditari@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,aGtq,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
1,U00003,"Graciela Evanda Ronadi, S.Kom.",graciela@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,qWmlbcVjYmo%3D,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
2,U00011,DANIAR AULIA RIZKI,daniar.rizki@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,aGtq,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
3,U00012,Habibah Melyna,habibah.elfiani@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,o56YqZJkZA%3D%3D,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
4,U00014,Laksmi Puspitowardhani,laksmi.p@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,aWlpbw%3D%3D,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
5,U00015,Ika Asriani Yadin,ikayadin@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,aGtq,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
6,U00016,"Luluk Fatikah Sari, S.Pd.",luluk.sari@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,o66jrsxjY2s%3D,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
7,U00018,Ditari Kurnia,admin@gmail.com,2026-06-06 22:57:58.616115,aGtq,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
8,U00019,"Hartatik, S.S.",hartatik@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,p5qenpJkZA%3D%3D,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
9,U00020,Juni Arlianto,juni.arlianto@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,aGtq,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
10,U00023,Titi Hapsari,titi.hapsari@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,aGtq,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
11,U00026,"Qorin Rahmaniyah, S.Pd.",qorin.rahmaniah@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,bnFw,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
12,U00027,Test,test@gmail.com,2026-06-06 22:57:58.616115,aGtq,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
13,U00028,pengajar,pengajar@gmail.com,2026-06-06 22:57:58.616115,aGtq,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
14,U00030,Akun Data PPDK,data@gmail.com,2026-06-06 22:57:58.616115,o56YqZJkZGw%3D,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
15,U00031,"Eka Nur Wahyuni, S. Pd.",eka.wahyuni@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,fKSYp9akqJnNqauhm5WZ,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
16,U00032,"Getari Adyagarini, M.Pd",getari@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,aGtq,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
17,U00033,"Maria Florencia Erica Susanto, A.Md.",ericasusanto@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,sKimp9STn6DGYGY%3D,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
18,U00034,"Mieke Puspita, S.Pd",miekepuspita@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,o56YqZJkZGw%3D,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
19,U00035,"Miftakhul Jannah, S.Pd",miftakhul.jannah@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,aGtq,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
20,U00036,"Rr. Nisrina Dea Rahma, S.Hum",nisrina.dea@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,pZ2cmtOaYmmT,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
21,U00037,Siti Uswatun Khasanah,siti.uswatun@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,aGtq,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
22,U00038,"Rini Budi Rahayu, S.Pd.",rini.rahayu@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,o56YqZNiY2s%3D,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
23,U00040,"Agung Wijayanto, S.T.",agung.wijayanto@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,aGtq,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
24,U00041,Vivi Pramitha Wulandari,vivi.wulandari@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,aGtq,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
25,U00042,Cantika Swasti Sumarsono Putri,cantikaswasti76@gmail.com,2026-06-06 22:57:58.616115,aGtq,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
26,U00043,Trio Fajar Cahyanto,generalaffair@gmail.com,2026-06-06 22:57:58.616115,aGtq,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
27,U00044,Muifatul Febriani,muifatul@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,aGtq,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
28,U00046,sosialmedia1,sosialmedia1@gmail.com,2026-06-06 22:57:58.616115,aGtq,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
29,U00047,Muhamad Haykal Roziqi,Muhammad.haykal@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,i6Kkp8KlYmqYZGs%3D,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
30,U00048,"Yerly A Datu, S.Pd, M.Pd, CT.ACT, C.PS",pengajar1@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,aGtq,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
31,U00049,Ana Puspita,ana.puspita@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,aGtq,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
32,U00050,"Peni Puspa Indarwati, S.S.",peni.indarwati@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,pJqkptCmZm0%3D,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
33,U00052,Ratna Febrianti,febrianti.ratna@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,aGtq,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
34,U00053,Ann Clariss Agbalog Amora,edgetutor1@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,o56YqdWnpafXYWhm,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
35,U00054,Bryant Frederico Sutanto,Bryant.f@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,aGtq,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
36,U00055,Muhammad Jefry Mulyanto,muhammad.jefry@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,oZ%2BpsqGelpnVYWtjaJSb,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
37,U00056,Amat Kasiyan,Amat@leap.surabaya.sch.id,2026-06-06 22:57:58.616115,aGtq,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
38,U00057,"Ulfasiyah, S.S.",ulfasiyah@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,aGtq,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
39,U00058,Piotr Pawel Sopa,piotr.pawel@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,aGtq,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
40,U00059,Amilia Khasanah Marzuki,Amilia.Khasanah@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,aGtq,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
41,U00060,Muhammad Yusril Romadhoni,Muhammad.Yusril@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,aGtq,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
42,U00061,"Veronica Febriyanti Adam, S.S.",veronica.febriyanti@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,iqGgp8Z0o6HMmKpkaZSe,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
43,U00062,La Erpiadin,la.erpiadin@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,aGtq,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
44,U00063,"Aulia Ratna Meilinda, S.Pd.",Aulia.Ratna@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,aGtq,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
45,U00064,"PINANGGIH DIMAS PERMANA, S.Kom",Pinanggih.Dimas@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,aGtq,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
46,U00065,"Retno Wulandari, S.Pd.",Retno.Wulandari@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,aGtq,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
47,U00066,"Risma Dwi Aryanti, S.Pd.",Risma.Dwi@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,n26ua5WLaZ0%3D,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
48,U00067,"Moh Rafli Wahyudi, S.Pd.",Moh.Rafli@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,g56YqaihnKHRYWg%3D,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
49,U00068,Mochammad Rahmat Muttaqin,rahmat.muttaqin@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,aGtq,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115
50,U00069,Zaskya Ayra Sinatrya,zaskya.Ayra@leapsurabaya.sch.id,2026-06-06 22:57:58.616115,sZqqocJiYmmWYGo%3D,None,2026-06-06 22:57:58.616115,2026-06-06 22:57:58.616115

In [26]:
# Analisis tabel df_old['divisi']

print("=" * 60)
print("ANALISIS TABEL: df_old['divisi']")
print("=" * 60)

# 1. Lihat struktur dan isi data
print("\n--- 1. STRUKTUR DATA ---")
print(f"Shape: {df_old['divisi'].shape}")
print(f"Jumlah baris: {len(df_old['divisi'])}")
print(f"Jumlah kolom: {len(df_old['divisi'].columns)}")

print("\n--- 2. NAMA KOLOM ---")
print(df_old['divisi'].columns.tolist())

print("\n--- 3. PREVIEW DATA ---")
print(df_old['divisi'])

print("\n--- 4. INFO TABEL ---")
df_old['divisi'].info()

print("\n--- 5. DATA TYPES ---")
print(df_old['divisi'].dtypes)

print("\n--- 6. PENGECEKAN NULL/KOSONG ---")
null_counts_divisi = df_old['divisi'].isnull().sum()
print(null_counts_divisi)
if null_counts_divisi.sum() > 0:
    print(f"\n⚠️ Ada {null_counts_divisi.sum()} nilai kosong ditemukan")
else:
    print("\n✓ Tidak ada nilai kosong")

print("\n--- 7. PENGECEKAN DUPLIKAT ---")
duplicate_rows_divisi = df_old['divisi'].duplicated().sum()
print(f"Jumlah baris duplikat: {duplicate_rows_divisi}")
if duplicate_rows_divisi > 0:
    print("\nData duplikat:")
    print(df_old['divisi'][df_old['divisi'].duplicated(keep=False)])

print("\n--- 8. STATISTIK DESKRIPTIF ---")
print(df_old['divisi'].describe(include='all'))

print("\n--- 9. UNIQUE VALUES PER KOLOM ---")
for col_divisi in df_old['divisi'].columns:
    print(f"{col_divisi}: {df_old['divisi'][col_divisi].nunique()} unique values")

print("\n--- 10. VALUE COUNTS (untuk kolom kategori) ---")
for col_divisi in df_old['divisi'].columns:
    print(f"\n{col_divisi}:")
    print(df_old['divisi'][col_divisi].value_counts(dropna=False))

============================================================
ANALISIS TABEL: df_old['divisi']
============================================================

--- 1. STRUKTUR DATA ---
Shape: (6, 2)
Jumlah baris: 6
Jumlah kolom: 2

--- 2. NAMA KOLOM ---
['iddivisi', 'nama']

--- 3. PREVIEW DATA ---
  iddivisi        nama
0   D00001          IT
1   D00002      Busdev
2   D00003     HR / GA
3   D00005  Pendidikan
4   D00006     Finance
5   D00007     Direksi

--- 4. INFO TABEL ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   iddivisi  6 non-null      object
 1   nama      6 non-null      object
dtypes: object(2)
memory usage: 228.0+ bytes

--- 5. DATA TYPES ---
iddivisi    object
nama        object
dtype: object

--- 6. PENGECEKAN NULL/KOSONG ---
iddivisi    0
nama        0
dtype: int64

✓ Tidak ada nilai kosong

--- 7. PENGECEKAN DUPLIKAT ---
Jumlah baris duplikat: 0

--- 8. STATISTIK DESKRIPTIF ---
       iddivisi nama
count         6    6
unique        6    6
top      D00001   IT
freq          1    1

--- 9. UNIQUE VALUES PER KOLOM ---
iddivisi: 6 unique values
nama: 6 unique values

--- 10. VALUE COUNTS (untuk kolom kategori) ---

iddivisi:
iddivisi
D00001    1
D00002    1
D00003    1
D00005    1
D00006    1
D00007    1
Name: count, dtype: int64

nama:
nama
IT            1
Busdev        1
HR / GA       1
Pendidikan    1
Finance       1
Direksi       1
Name: count, dtype: int64

In [27]:
df_future['roles'].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           0 non-null      object
 1   id_division  0 non-null      object
 2   name         0 non-null      object
 3   guard_name   0 non-null      object
 4   created_at   0 non-null      object
 5   updated_at   0 non-null      object
dtypes: object(6)
memory usage: 132.0+ bytes

In [28]:
# Mapping data dari df_old['divisi'] ke df_new['divisions']
df_new['divisions']['id_division'] = df_old['divisi']['iddivisi']
df_new['divisions']['name_division'] = df_old['divisi']['nama']
df_new['divisions']['description'] = None
df_new['divisions']['is_active'] = 1

print("--- Preview data divisions yang sudah dimapping ---")
display(df_new['divisions'])
print("\n--- Info tabel divisions ---")
display(df_new['divisions'].info())

--- Preview data divisions yang sudah dimapping ---

   id_division name_division description  is_active
0       D00001            IT        None          1
1       D00002        Busdev        None          1
2       D00003       HR / GA        None          1
3       D00005    Pendidikan        None          1
4       D00006       Finance        None          1
5       D00007       Direksi        None          1
6          NaN           NaN        None          1
7          NaN           NaN        None          1
8          NaN           NaN        None          1
9          NaN           NaN        None          1
10         NaN           NaN        None          1
11         NaN           NaN        None          1

--- Info tabel divisions ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_division    6 non-null      object
 1   name_division  6 non-null      object
 2   description    0 non-null      object
 3   is_active      12 non-null     int64
dtypes: int64(1), object(3)
memory usage: 516.0+ bytes

None

In [29]:
df_old['role_users'].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   idru     0 non-null      object
 1   idusers  0 non-null      object
 2   idmitra  0 non-null      object
dtypes: object(3)
memory usage: 132.0+ bytes

In [31]:
print("="*80)
print("RINGKASAN DATA YANG SUDAH DIPROSES")
print("="*80)

tables_to_show = ['users', 'divisions', 'shift_kerja', 'admin_sarpras', 'sop_kategori']

for table_name in tables_to_show:
    print(f"\n{'='*80}")
    print(f"TABEL: {table_name}")
    print(f"{'='*80}")
    
    if table_name == 'users':
        source_df = df_new['users']
        print(f"\nJumlah baris: {len(source_df)}")
        print(f"Jumlah kolom: {len(source_df.columns)}\n")
        print(source_df.to_string())
        
    elif table_name == 'divisions':
        source_df = df_new['divisions']
        print(f"\nJumlah baris: {len(source_df)}")
        print(f"Jumlah kolom: {len(source_df.columns)}\n")
        print(source_df.to_string())
        
    elif table_name == 'shift_kerja':
        source_df = df_new['shift_kerja']
        print(f"\nJumlah baris: {len(source_df)}")
        print(f"Jumlah kolom: {len(source_df.columns)}\n")
        print(source_df.to_string())
        
    elif table_name == 'admin_sarpras':
        source_df = df_new['admin_sarpras']
        print(f"\nJumlah baris: {len(source_df)}")
        print(f"Jumlah kolom: {len(source_df.columns)}\n")
        print(source_df.to_string())
        
    elif table_name == 'sop_kategori':
        source_df = df_new['sop_kategori']
        print(f"\nJumlah baris: {len(source_df)}")
        print(f"Jumlah kolom: {len(source_df.columns)}\n")
        print(source_df.to_string())

print(f"\n{'='*80}")
print("SELESAI")
print(f"{'='*80}")

================================================================================
RINGKASAN DATA YANG SUDAH DIPROSES
================================================================================

================================================================================
TABEL: users
================================================================================

Jumlah baris: 51
Jumlah kolom: 8

   id_user                                    name                                    email          email_verified_at                password remember_token                 created_at                 updated_at
0   U00001                           ADMINISTRATOR               ditari@leapsurabaya.sch.id 2026-06-06 22:57:58.616115                    aGtq           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
1   U00003          Graciela Evanda Ronadi, S.Kom.             graciela@leapsurabaya.sch.id 2026-06-06 22:57:58.616115          qWmlbcVjYmo%3D           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
2   U00011                      DANIAR AULIA RIZKI         daniar.rizki@leapsurabaya.sch.id 2026-06-06 22:57:58.616115                    aGtq           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
3   U00012                          Habibah Melyna      habibah.elfiani@leapsurabaya.sch.id 2026-06-06 22:57:58.616115        o56YqZJkZA%3D%3D           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
4   U00014                  Laksmi Puspitowardhani             laksmi.p@leapsurabaya.sch.id 2026-06-06 22:57:58.616115            aWlpbw%3D%3D           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
5   U00015                       Ika Asriani Yadin             ikayadin@leapsurabaya.sch.id 2026-06-06 22:57:58.616115                    aGtq           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
6   U00016               Luluk Fatikah Sari, S.Pd.           luluk.sari@leapsurabaya.sch.id 2026-06-06 22:57:58.616115          o66jrsxjY2s%3D           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
7   U00018                           Ditari Kurnia                          admin@gmail.com 2026-06-06 22:57:58.616115                    aGtq           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
8   U00019                          Hartatik, S.S.             hartatik@leapsurabaya.sch.id 2026-06-06 22:57:58.616115        p5qenpJkZA%3D%3D           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
9   U00020                           Juni Arlianto        juni.arlianto@leapsurabaya.sch.id 2026-06-06 22:57:58.616115                    aGtq           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
10  U00023                            Titi Hapsari         titi.hapsari@leapsurabaya.sch.id 2026-06-06 22:57:58.616115                    aGtq           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
11  U00026                 Qorin Rahmaniyah, S.Pd.      qorin.rahmaniah@leapsurabaya.sch.id 2026-06-06 22:57:58.616115                    bnFw           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
12  U00027                                    Test                           test@gmail.com 2026-06-06 22:57:58.616115                    aGtq           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
13  U00028                                pengajar                       pengajar@gmail.com 2026-06-06 22:57:58.616115                    aGtq           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
14  U00030                          Akun Data PPDK                           data@gmail.com 2026-06-06 22:57:58.616115          o56YqZJkZGw%3D           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
15  U00031                 Eka Nur Wahyuni, S. Pd.          eka.wahyuni@leapsurabaya.sch.id 2026-06-06 22:57:58.616115    fKSYp9akqJnNqauhm5WZ           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
16  U00032                 Getari Adyagarini, M.Pd               getari@leapsurabaya.sch.id 2026-06-06 22:57:58.616115                    aGtq           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
17  U00033    Maria Florencia Erica Susanto, A.Md.         ericasusanto@leapsurabaya.sch.id 2026-06-06 22:57:58.616115      sKimp9STn6DGYGY%3D           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
18  U00034                     Mieke Puspita, S.Pd         miekepuspita@leapsurabaya.sch.id 2026-06-06 22:57:58.616115          o56YqZJkZGw%3D           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
19  U00035                  Miftakhul Jannah, S.Pd     miftakhul.jannah@leapsurabaya.sch.id 2026-06-06 22:57:58.616115                    aGtq           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
20  U00036            Rr. Nisrina Dea Rahma, S.Hum          nisrina.dea@leapsurabaya.sch.id 2026-06-06 22:57:58.616115            pZ2cmtOaYmmT           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
21  U00037                   Siti Uswatun Khasanah         siti.uswatun@leapsurabaya.sch.id 2026-06-06 22:57:58.616115                    aGtq           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
22  U00038                 Rini Budi Rahayu, S.Pd.          rini.rahayu@leapsurabaya.sch.id 2026-06-06 22:57:58.616115          o56YqZNiY2s%3D           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
23  U00040                   Agung Wijayanto, S.T.      agung.wijayanto@leapsurabaya.sch.id 2026-06-06 22:57:58.616115                    aGtq           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
24  U00041                 Vivi Pramitha Wulandari       vivi.wulandari@leapsurabaya.sch.id 2026-06-06 22:57:58.616115                    aGtq           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
25  U00042          Cantika Swasti Sumarsono Putri                cantikaswasti76@gmail.com 2026-06-06 22:57:58.616115                    aGtq           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
26  U00043                     Trio Fajar Cahyanto                  generalaffair@gmail.com 2026-06-06 22:57:58.616115                    aGtq           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
27  U00044                       Muifatul Febriani             muifatul@leapsurabaya.sch.id 2026-06-06 22:57:58.616115                    aGtq           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
28  U00046                            sosialmedia1                   sosialmedia1@gmail.com 2026-06-06 22:57:58.616115                    aGtq           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
29  U00047                   Muhamad Haykal Roziqi      Muhammad.haykal@leapsurabaya.sch.id 2026-06-06 22:57:58.616115      i6Kkp8KlYmqYZGs%3D           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
30  U00048  Yerly A Datu, S.Pd, M.Pd, CT.ACT, C.PS            pengajar1@leapsurabaya.sch.id 2026-06-06 22:57:58.616115                    aGtq           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
31  U00049                             Ana Puspita          ana.puspita@leapsurabaya.sch.id 2026-06-06 22:57:58.616115                    aGtq           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
32  U00050              Peni Puspa Indarwati, S.S.       peni.indarwati@leapsurabaya.sch.id 2026-06-06 22:57:58.616115          pJqkptCmZm0%3D           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
33  U00052                         Ratna Febrianti      febrianti.ratna@leapsurabaya.sch.id 2026-06-06 22:57:58.616115                    aGtq           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
34  U00053               Ann Clariss Agbalog Amora           edgetutor1@leapsurabaya.sch.id 2026-06-06 22:57:58.616115        o56YqdWnpafXYWhm           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
35  U00054                Bryant Frederico Sutanto             Bryant.f@leapsurabaya.sch.id 2026-06-06 22:57:58.616115                    aGtq           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
36  U00055                 Muhammad Jefry Mulyanto       muhammad.jefry@leapsurabaya.sch.id 2026-06-06 22:57:58.616115  oZ%2BpsqGelpnVYWtjaJSb           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
37  U00056                            Amat Kasiyan                Amat@leap.surabaya.sch.id 2026-06-06 22:57:58.616115                    aGtq           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
38  U00057                         Ulfasiyah, S.S.            ulfasiyah@leapsurabaya.sch.id 2026-06-06 22:57:58.616115                    aGtq           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
39  U00058                        Piotr Pawel Sopa          piotr.pawel@leapsurabaya.sch.id 2026-06-06 22:57:58.616115                    aGtq           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
40  U00059                 Amilia Khasanah Marzuki      Amilia.Khasanah@leapsurabaya.sch.id 2026-06-06 22:57:58.616115                    aGtq           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
41  U00060               Muhammad Yusril Romadhoni      Muhammad.Yusril@leapsurabaya.sch.id 2026-06-06 22:57:58.616115                    aGtq           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
42  U00061          Veronica Febriyanti Adam, S.S.  veronica.febriyanti@leapsurabaya.sch.id 2026-06-06 22:57:58.616115    iqGgp8Z0o6HMmKpkaZSe           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
43  U00062                             La Erpiadin          la.erpiadin@leapsurabaya.sch.id 2026-06-06 22:57:58.616115                    aGtq           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
44  U00063             Aulia Ratna Meilinda, S.Pd.          Aulia.Ratna@leapsurabaya.sch.id 2026-06-06 22:57:58.616115                    aGtq           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
45  U00064          PINANGGIH DIMAS PERMANA, S.Kom      Pinanggih.Dimas@leapsurabaya.sch.id 2026-06-06 22:57:58.616115                    aGtq           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
46  U00065                  Retno Wulandari, S.Pd.      Retno.Wulandari@leapsurabaya.sch.id 2026-06-06 22:57:58.616115                    aGtq           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
47  U00066                Risma Dwi Aryanti, S.Pd.            Risma.Dwi@leapsurabaya.sch.id 2026-06-06 22:57:58.616115          n26ua5WLaZ0%3D           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
48  U00067                Moh Rafli Wahyudi, S.Pd.            Moh.Rafli@leapsurabaya.sch.id 2026-06-06 22:57:58.616115      g56YqaihnKHRYWg%3D           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
49  U00068               Mochammad Rahmat Muttaqin      rahmat.muttaqin@leapsurabaya.sch.id 2026-06-06 22:57:58.616115                    aGtq           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115
50  U00069                    Zaskya Ayra Sinatrya          zaskya.Ayra@leapsurabaya.sch.id 2026-06-06 22:57:58.616115      sZqqocJiYmmWYGo%3D           None 2026-06-06 22:57:58.616115 2026-06-06 22:57:58.616115

================================================================================
TABEL: divisions
================================================================================

Jumlah baris: 12
Jumlah kolom: 4

   id_division name_division description  is_active
0       D00001            IT        None          1
1       D00002        Busdev        None          1
2       D00003       HR / GA        None          1
3       D00005    Pendidikan        None          1
4       D00006       Finance        None          1
5       D00007       Direksi        None          1
6          NaN           NaN        None          1
7          NaN           NaN        None          1
8          NaN           NaN        None          1
9          NaN           NaN        None          1
10         NaN           NaN        None          1
11         NaN           NaN        None          1

================================================================================
TABEL: shift_kerja
================================================================================

Jumlah baris: 3
Jumlah kolom: 4

   id_shift          nama_shift       jam_masuk      jam_pulang
0         1  Freelance Fulltime 0 days 10:15:00 0 days 19:15:00
1         2   DIGITAL ENGLISH 1 0 days 08:00:00 0 days 17:00:00
2         3   DIGITAL ENGLISH 2 0 days 10:15:00 0 days 19:15:00

================================================================================
TABEL: admin_sarpras
================================================================================

Jumlah baris: 1
Jumlah kolom: 2

   id_admin_sarpras wa_admin_sarpras
0                 1     085174387539

================================================================================
TABEL: sop_kategori
================================================================================

Jumlah baris: 3
Jumlah kolom: 2

   id_sop_kategori nama_kategori_sop
0                1             Kelas
1                2           HR / GA
2                3              test

================================================================================
SELESAI
================================================================================

In [32]:
import json
import pickle
with open('fase_1_cimut.pkl', 'wb') as f:
    pickle.dump(df_new, f)

print("✓ Data df_new sudah disimpan ke df_new.pkl")
print("Siap untuk digunakan di insert_handler.ipynb")

✓ Data df_new sudah disimpan ke df_new.pkl
Siap untuk digunakan di insert_handler.ipynb