In [1]:
import sys
import os
import mysql.connector
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Ambil konfigurasi database dari folder utama project kalian
sys.path.append(os.path.abspath('..'))
from config import get_db_config

config = get_db_config()

# 1. Koneksi ke Database Baru (Fase Migrasi Sekarang)
db_new = mysql.connector.connect(**config['db_new'])
cursor_new = db_new.cursor(dictionary=True)

# 2. Koneksi ke Database Masa Depan (DB_FUTURE)
# Catatan: Pastikan di file config.py kalian sudah ada key 'db_future' ya!
db_future = mysql.connector.connect(**config['db_future'])
cursor_future = db_future.cursor(dictionary=True)

print(f"✅ Sukses Terhubung ke Database Baru : {config['db_new']['database']}")
print(f"🚀 Sukses Terhubung ke DB_FUTURE     : {config['db_future']['database']}")

✅ Sukses Terhubung ke Database Baru : 7
🚀 Sukses Terhubung ke DB_FUTURE     : 7

In [2]:
tables_to_check = [
    'rapor_format',             # Master template format rapor utama
    'rapor_format_sub',         # Sub-bab / kategori penilaian dalam format rapor
    'rapor_format_formula',     # Rumus / formula dasar kalkulasi nilai rapor
    'rapor_format_formula_sub', # Detail parameter sub-formula penilaian
    'rapor_level_config',       # Konfigurasi standar rapor berdasarkan tingkatan kelas
    'rapor_sub_level',          # Sub-tingkatan atau pengelompokan level rapor

    # --- BLOK B: DATA TRANSAKSIONAL RAPOR SISWA REAL (Karya Hanif) ---
    'rapor_siswa',              # Input data nilai rapor milik masing-masing siswa
    'rapor_siswa_file',         # Berkas / file PDF rapor siswa yang sudah di-generate
    'rapor_lacak',              # Log tracking / riwayat pembagian & perubahan rapor

    # --- BLOK C: AKADEMIK & OPERASIONAL SISWA (Karya Afrida) ---
    'presensi_siswa',           # Log kehadiran harian siswa di kelas
    'catatan_siswa',            # Catatan khusus / lembar BK untuk perkembangan siswa
    'followup_cs',              # Catatan tindak lanjut tim Customer Service ke wali siswa
]

In [3]:
# === Cell 2: Inspeksi Detektor Pintar dengan Prioritas Target Revisi di Atas ===
import pandas as pd
import numpy as np

print("================================================================================")
print(" 🕵️‍♂️ FORENSIK ARSITEKTUR KONTROL: DETEKTOR AUTO-SMART COMPILER (REVISI PRIORITY) 🕵️‍♂️ ")
print("================================================================================")

# List penampung data di memori untuk keperluan sorting visualisasi
revisi_tables_queue = []
identical_tables_queue = []

# --- TAHAP A: PROSES PEN ARIKAN DATA & EVALUASI STRUKTUR DI BELAKANG LAYAR ---
for table in tables_to_check:
    try:
        # 1. Ambil data asli dari DB_NEW untuk kebutuhan .info() dan sampel isi data
        query = f"SELECT * FROM `{table}`"
        df_real_data = pd.read_sql(query, db_new)
        
        # 2. Tarik Struktur Fisik Kolom dari DB_NEW
        query_new_struct = f"""
        SELECT 
            c.COLUMN_NAME AS 'Nama Kolom',
            c.COLUMN_TYPE AS 'Tipe Data MySQL',
            CONCAT(
                CASE WHEN c.IS_NULLABLE = 'YES' THEN '✅ NULL (Boleh Kosong)' ELSE '🛑 NOT NULL (Wajib Isi)' END,
                CASE WHEN c.EXTRA = 'auto_increment' THEN '\\n🚀 AUTO_INCREMENT' ELSE '' END
            ) AS 'Aturan Nullability & Increment',
            CASE 
                WHEN c.COLUMN_KEY = 'PRI' THEN '🔑 PRIMARY KEY (PK)'
                WHEN c.COLUMN_KEY = 'MUL' AND k.REFERENCED_TABLE_NAME IS NOT NULL THEN '🔗 FOREIGN KEY (FK)'
                WHEN c.COLUMN_KEY = 'MUL' THEN 'INDEX'
                ELSE '-'
            END AS 'Status Kunci',
            CASE 
                WHEN k.REFERENCED_TABLE_NAME IS NOT NULL THEN CONCAT(k.REFERENCED_TABLE_NAME, ' (', k.REFERENCED_COLUMN_NAME, ')')
                ELSE '-'
            END AS 'Rujukan Induk (FK Origin)',
            CASE WHEN c.DATA_TYPE = 'enum' THEN REPLACE(REPLACE(REPLACE(c.COLUMN_TYPE, 'enum(', ''), ')', ''), "'", "") ELSE '-' END AS 'Daftar Pilihan ENUM'
        FROM INFORMATION_SCHEMA.COLUMNS c
        LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE k 
            ON c.TABLE_SCHEMA = k.TABLE_SCHEMA AND c.TABLE_NAME = k.TABLE_NAME AND c.COLUMN_NAME = k.COLUMN_NAME
        WHERE c.TABLE_SCHEMA = '{config['db_new']['database']}' AND c.TABLE_NAME = '{table}'
        ORDER BY c.ORDINAL_POSITION;
        """
        df_struct_new = pd.read_sql(query_new_struct, db_new).drop_duplicates(subset=['Nama Kolom'], keep='first').reset_index(drop=True)
        
        # Lacak tabel anak yang nge-FK ke PK tabel ini di DB_NEW
        pk_referenced_list = []
        for idx, row_skri in df_struct_new.iterrows():
            if row_skri['Status Kunci'] == '🔑 PRIMARY KEY (PK)':
                lookup_fk_query = f"""
                SELECT CONCAT(TABLE_NAME, ' (', COLUMN_NAME, ')') as relasi
                FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
                WHERE REFERENCED_TABLE_SCHEMA = '{config['db_new']['database']}'
                  AND REFERENCED_TABLE_NAME = '{table}'
                  AND REFERENCED_COLUMN_NAME = '{row_skri['Nama Kolom']}';
                """
                df_relasi_luar = pd.read_sql(lookup_fk_query, db_new)
                if not df_relasi_luar.empty:
                    pk_referenced_list.append("\n".join(df_relasi_luar['relasi'].tolist()))
                else:
                    pk_referenced_list.append("-")
            else:
                pk_referenced_list.append("-")
        df_struct_new['Tabel Yang nge-FK (DB_NEW)'] = pk_referenced_list

        # 3. Tarik Struktur Fisik Kolom dari DB_FUTURE
        query_future_struct = f"""
        SELECT 
            c.COLUMN_NAME AS 'Nama Kolom',
            c.COLUMN_TYPE AS 'Tipe Data MySQL',
            CONCAT(
                CASE WHEN c.IS_NULLABLE = 'YES' THEN '✅ NULL (Boleh Kosong)' ELSE '🛑 NOT NULL (Wajib Isi)' END,
                CASE WHEN c.EXTRA = 'auto_increment' THEN '\\n🚀 AUTO_INCREMENT' ELSE '' END
            ) AS 'Aturan Nullability & Increment',
            CASE 
                WHEN c.COLUMN_KEY = 'PRI' THEN '🔑 PRIMARY KEY (PK)'
                WHEN c.COLUMN_KEY = 'MUL' AND k.REFERENCED_TABLE_NAME IS NOT NULL THEN '🔗 FOREIGN KEY (FK)'
                WHEN c.COLUMN_KEY = 'MUL' THEN 'INDEX'
                ELSE '-'
            END AS 'Status Kunci',
            CASE 
                WHEN k.REFERENCED_TABLE_NAME IS NOT NULL THEN CONCAT(k.REFERENCED_TABLE_NAME, ' (', k.REFERENCED_COLUMN_NAME, ')')
                ELSE '-'
            END AS 'Rujukan Induk (FK Origin)',
            CASE WHEN c.DATA_TYPE = 'enum' THEN REPLACE(REPLACE(REPLACE(c.COLUMN_TYPE, 'enum(', ''), ')', ''), "'", "") ELSE '-' END AS 'Daftar Pilihan ENUM'
        FROM INFORMATION_SCHEMA.COLUMNS c
        LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE k 
            ON c.TABLE_SCHEMA = k.TABLE_SCHEMA AND c.TABLE_NAME = k.TABLE_NAME AND c.COLUMN_NAME = k.COLUMN_NAME
        WHERE c.TABLE_SCHEMA = '{config['db_future']['database']}' AND c.TABLE_NAME = '{table}'
        ORDER BY c.ORDINAL_POSITION;
        """
        df_struct_future = pd.read_sql(query_future_struct, db_future).drop_duplicates(subset=['Nama Kolom'], keep='first').reset_index(drop=True)
        
        # Lacak tabel anak yang nge-FK ke PK tabel ini di DB_FUTURE
        pk_referenced_list_future = []
        for idx, row_skri in df_struct_future.iterrows():
            if row_skri['Status Kunci'] == '🔑 PRIMARY KEY (PK)':
                lookup_fk_query_future = f"""
                SELECT CONCAT(TABLE_NAME, ' (', COLUMN_NAME, ')') as relasi
                FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
                WHERE REFERENCED_TABLE_SCHEMA = '{config['db_future']['database']}'
                  AND REFERENCED_TABLE_NAME = '{table}'
                  AND REFERENCED_COLUMN_NAME = '{row_skri['Nama Kolom']}';
                """
                df_relasi_luar_future = pd.read_sql(lookup_fk_query_future, db_future)
                if not df_relasi_luar_future.empty:
                    pk_referenced_list_future.append("\n".join(df_relasi_luar_future['relasi'].tolist()))
                else:
                    pk_referenced_list_future.append("-")
            else:
                pk_referenced_list_future.append("-")
        df_struct_future['Tabel Yang nge-FK (DB_FUTURE)'] = pk_referenced_list_future

        # 4. Deep Comparison Kesamaan Jeroan Kolom dasar
        cols_to_compare = ['Nama Kolom', 'Tipe Data MySQL', 'Aturan Nullability & Increment', 'Status Kunci', 'Rujukan Induk (FK Origin)', 'Daftar Pilihan ENUM']
        
        is_structure_identical = False
        if not df_struct_new.empty and not df_struct_future.empty:
            is_structure_identical = df_struct_new[cols_to_compare].equals(df_struct_future[cols_to_compare])

        # Wadah paket data tabel untuk di-render nanti
        table_package = {
            'name': table,
            'df_real_data': df_real_data,
            'df_struct_new': df_struct_new,
            'df_struct_future': df_struct_future,
            'is_identical': is_structure_identical
        }

        # 🔥 FILTER SAKTI CIMUT: Pisahkan antrean, utamakan yang bermasalah (revisi) ke atas!
        if is_structure_identical:
            identical_tables_queue.append(table_package)
        else:
            revisi_tables_queue.append(table_package)
            
    except Exception as e:
        print(f"❌ Gagal menganalisis awal tabel `{table}`: {e}")

# --- TAHAP B: MULAI PEN TAMPILAN VISUALISASI BERDASARKAN ANT REAN PRIORITAS ---

# 🚨 1. KELOMPOK UTAMA (PALING ATAS): DAFTAR TABEL YANG WAJIB DIREVISI 🚨
if revisi_tables_queue:
    print("\n" + "!"*80)
    print(f"🚨 [🔥 REVISI PRIORITY BOARD] TERDETEKSI {len(revisi_tables_queue)} TABEL BERBEDA - HARUS SEGERA DIPERBAIKI!")
    print("!"*80)
    
    for pkg in revisi_tables_queue:
        print(f"\n================================================================================")
        print(f"⚠️  [STATUS: TARGET REVISI] TABEL: {pkg['name'].upper()}")
        print(f"================================================================================")
        
        print(f"📋 1. Karakteristik Wadah Pandas Dataframe (.info()):")
        pkg['df_real_data'].info()
        print("\n" + "-"*60)
        
        print(f"🔍 2. [TABEL REAL SAAT INI] Arsitektur Fisik Kolom pada DB_NEW:")
        display(pkg['df_struct_new'].style.set_properties(**{'white-space': 'pre-wrap', 'text-align': 'left'}))
        print("\n" + "-"*60)
        
        print(f"🔮 3. [⚠️ TARGET BLUEPRINT RUJUKAN] Tinjau Struktur yang Benar pada DB_FUTURE di bawah:")
        if pkg['df_struct_future'].empty:
            print("❌ ERROR: Tabel ini tidak ditemukan / belum dibuat sama sekali di DB_FUTURE!")
        else:
            display(pkg['df_struct_future'].style.set_properties(**{'white-space': 'pre-wrap', 'text-align': 'left'}))
        print("\n" + "-"*60)
        
        print(f"📸 4. Sampel Isi Data Real di DB_NEW:")
        display(pkg['df_real_data'] if pkg['df_real_data'].empty else pkg['df_real_data'])
        print("\n" + "="*80)

# ✨ 2. KELOMPOK KEDUA (BAW AH): DAFTAR TABEL YANG SUDAH AMAN IDENTIK ✨
if identical_tables_queue:
    print("\n" + "="*80)
    print(f"✨ [🟢 PERFECTLY MATCHED BOARD] SEBANYAK {len(identical_tables_queue)} TABEL STRUKTURNYA SUDAH IDENTIK SAMA PERSIS!")
    print("="*80)
    
    for pkg in identical_tables_queue:
        print(f"\n================================================================================")
        print(f"✅ [STATUS: AMAN IDENTIK] TABEL: {pkg['name'].upper()}")
        print(f"================================================================================")
        
        print(f"📋 1. Karakteristik Wadah Pandas Dataframe (.info()):")
        pkg['df_real_data'].info()
        print("\n" + "-"*60)
        
        print(f"🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:")
        display(pkg['df_struct_new'].style.set_properties(**{'white-space': 'pre-wrap', 'text-align': 'left'}))
        print("\n" + "-"*60)
        
        print("✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨")
        print("ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.")
        print("\n" + "-"*60)
        
        print(f"📸 3. Sampel Isi Data Real di DB_NEW:")
        display(pkg['df_real_data'] if pkg['df_real_data'].empty else pkg['df_real_data'])
        print("\n" + "="*80)

================================================================================
 🕵️‍♂️ FORENSIK ARSITEKTUR KONTROL: DETEKTOR AUTO-SMART COMPILER (REVISI PRIORITY) 🕵️‍♂️
================================================================================

================================================================================
✨ [🟢 PERFECTLY MATCHED BOARD] SEBANYAK 12 TABEL STRUKTURNYA SUDAH IDENTIK SAMA PERSIS!
================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: RAPOR_FORMAT
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_rapor_format  41 non-null     object
 1   id_kursus        41 non-null     object
 2   judul_rapor      41 non-null     object
 3   urutan           41 non-null     int64
dtypes: int64(1), object(3)
memory usage: 1.4+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

   id_rapor_format id_kursus             judul_rapor  urutan
0           F00001    K00001    CLASSROOM ASSESSMENT       1
1           F00002    K00001        END OF TERM TEST       2
2           F00003    K00001           CLASS REMARKS       3
3           F00004    K00001    CLASSROOM ASSESSMENT       1
4           F00005    K00001        END OF TERM TEST       2
5           F00006    K00001           CLASS REMARKS       3
6           F00007    K00001    CLASSROOM ASSESSMENT       1
7           F00008    K00001        END OF TERM TEST       2
8           F00009    K00001           CLASS REMARKS       3
9           F00010    K00003    CLASSROOM ASSESSMENT       1
10          F00012    K00003           CLASS REMARKS       3
11          F00013    K00004    CLASSROOM ASSESSMENT       1
12          F00015    K00004           CLASS REMARKS       3
13          F00016    K00002    Classroom Assessment       1
14          F00017    K00002  Final Project Activity       2
15          F00018    K00002           Class Remarks       3
16          F00019    K00009     Learning Assessment       1
17          F00020    K00010    CLASSROOM ASSESSMENT       1
18          F00021    K00010    END OF SEMESTER TEST       2
19          F00022    K00010           CLASS REMARKS       3
20          F00023    K00010    CLASSROOM ASSESSMENT       1
21          F00024    K00010    END OF SEMESTER TEST       2
22          F00025    K00010           CLASS REMARKS       3
23          F00026    K00010    CLASSROOM ASSESSMENT       1
24          F00027    K00010    END OF SEMESTER TEST       2
25          F00028    K00010           CLASS REMARKS       3
26          F00029    K00010    CLASSROOM ASSESSMENT       1
27          F00030    K00010    END OF SEMESTER TEST       2
28          F00031    K00010           CLASS REMARKS       3
29          F00032    K00014    Classroom Assessment       1
30          F00033    K00014  Final Project Activity       2
31          F00034    K00014           Class Remarks       3
32          F00035    K00012   Classroom Assessments       1
33          F00036    K00012  Final Project Activity       2
34          F00037    K00012           Class Remarks       3
35          F00038    K00015    CLASSWORK ASSESSMENT       1
36          F00039    K00015             END OF TERM       2
37          F00040    K00015           CLASS REMARKS       3
38          F00042    K00019    CLASSROOM ASSESSMENT       1
39          F00043    K00019    END OF SEMESTER TEST       2
40          F00044    K00019           CLASS REMARKS       3

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: RAPOR_FORMAT_SUB
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121 entries, 0 to 120
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_rapor_format_sub  121 non-null    object
 1   id_rapor_format      121 non-null    object
 2   sub_judul_rapor      121 non-null    object
 3   urutan               121 non-null    int64
dtypes: int64(1), object(3)
memory usage: 3.9+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

    id_rapor_format_sub id_rapor_format          sub_judul_rapor  urutan
0                D00001          F00001      Class Participation       1
1                D00002          F00001                     Oral       2
2                D00003          F00001                Listening       3
3                D00005          F00002       Oral and Listening       1
4                D00006          F00004      Class Participation       1
..                  ...             ...                      ...     ...
116              D00132          F00043                  Written       2
117              D00133          F00042  Class Participation\t\t       0
118              D00134          F00042                     Oral       2
119              D00135          F00042                Listening       3
120              D00136          F00042                  Writing       4

[121 rows x 4 columns]

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: RAPOR_FORMAT_FORMULA
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id_rapor_format_formula  9 non-null      int64
 1   id_rapor_format          9 non-null      object
 2   logika_operator          9 non-null      object
dtypes: int64(1), object(2)
memory usage: 348.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

   id_rapor_format_formula id_rapor_format logika_operator
0                        1          F00003          P00911
1                        2          F00006          P00831
2                        3          F00009          P00759
3                        4          F00003          P00911
4                        5          F00006          P00831
5                        6          F00009          P00759
6                        7          F00003          P00911
7                        8          F00006          P00831
8                        9          F00009          P00759

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: RAPOR_FORMAT_FORMULA_SUB
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4875 entries, 0 to 4874
Data columns (total 5 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id_rapor_format_formula_sub  4875 non-null   int64
 1   id_rapor_format_sub          4875 non-null   object
 2   logika_operator              4875 non-null   object
 3   id_level                     4875 non-null   object
 4   urutan                       4875 non-null   int64
dtypes: int64(2), object(3)
memory usage: 190.6+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

,id_rapor_format_formula_sub,id_rapor_format_sub,logika_operator,id_level,urutan
0,1,D00001,P00902,L00001,0
1,2,D00002,P00903,L00001,0
2,3,D00003,P00904,L00001,0
3,4,D00005,(,L00001,0
4,5,D00005,P00906,L00001,0
...,...,...,...,...,...
4870,4921,D00024,P02414,L00140,0
4871,4922,D00023,P02413,L00140,0
4872,4923,D00025,P02409,L00139,0
4873,4924,D00024,P02408,L00139,0
4874,4925,D00023,P02407,L00139,0

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: RAPOR_LEVEL_CONFIG
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id_rapor_level_config  340 non-null    int64
 1   id_level               340 non-null    object
 2   id_kursus              340 non-null    object
 3   id_rapor_format        340 non-null    object
dtypes: int64(1), object(3)
memory usage: 10.8+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

     id_rapor_level_config id_level id_kursus id_rapor_format
0                        1   L00011    K00001          F00004
1                        2   L00014    K00001          F00004
2                        3   L00015    K00001          F00004
3                        4   L00016    K00001          F00004
4                        5   L00017    K00001          F00004
..                     ...      ...       ...             ...
335                    336   L00145    K00015          F00040
336                    337   L00146    K00015          F00040
337                    338   L00147    K00015          F00040
338                    339   L00148    K00015          F00040
339                    340   L00149    K00015          F00040

[340 rows x 4 columns]

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: RAPOR_SUB_LEVEL
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_rapor_sub_level   0 non-null      object
 1   id_rapor_format_sub  0 non-null      object
 2   id_level             0 non-null      object
dtypes: object(3)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

Empty DataFrame
Columns: [id_rapor_sub_level, id_rapor_format_sub, id_level]
Index: []

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: RAPOR_SISWA
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20718 entries, 0 to 20717
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_rapor_siswa      20718 non-null  int64
 1   id_jadwal           20718 non-null  int64
 2   id_siswa            20718 non-null  int64
 3   tanggal_input       20718 non-null  datetime64[ns]
 4   id_parameter_nilai  20718 non-null  int64
 5   final_result        20718 non-null  object
dtypes: datetime64[ns](1), int64(4), object(1)
memory usage: 971.3+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

,id_rapor_siswa,id_jadwal,id_siswa,tanggal_input,id_parameter_nilai,final_result
0,1,29,85,2023-09-29 15:01:39,14,B+
1,2,29,85,2023-09-29 15:01:39,15,A
2,3,29,85,2023-09-29 15:01:39,16,A
3,4,29,85,2023-09-29 15:01:39,17,A
4,5,29,85,2023-09-29 15:01:39,18,70
...,...,...,...,...,...,...
20713,22677,274,2168,2026-01-30 13:16:52,992,
20714,22678,274,2168,2026-01-30 13:16:52,993,
20715,22679,274,2168,2026-01-30 13:16:52,994,
20716,22680,274,2168,2026-01-30 13:16:52,995,
20717,22681,274,2168,2026-01-30 13:16:52,996,

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: RAPOR_SISWA_FILE
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1316 entries, 0 to 1315
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_rapor_siswa_file  1316 non-null   int64
 1   id_rapor_siswa       1309 non-null   float64
 2   file_rapor_path      1316 non-null   object
dtypes: float64(1), int64(1), object(1)
memory usage: 31.0+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

      id_rapor_siswa_file  id_rapor_siswa                     file_rapor_path
0                       1          5166.0         uploads/rapor/S0000329.jpeg
1                       2          5172.0         uploads/rapor/S0000474.jpeg
2                       3          5183.0         uploads/rapor/S0000481.jpeg
3                       4          5178.0         uploads/rapor/S0000475.jpeg
4                       5          5189.0         uploads/rapor/S0000482.jpeg
...                   ...             ...                                 ...
1311                 1482             NaN  uploads/rapor/INDAH_SEVIANITA.jpeg
1312                 1484         15818.0          uploads/rapor/TRIAL01.jpeg
1313                 1486         22652.0             uploads/rapor/coba.jpeg
1314                 1487         22672.0    uploads/rapor/coba_raport_3.jpeg
1315                 1488         22662.0    uploads/rapor/coba_raport_2.jpeg

[1316 rows x 3 columns]

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: RAPOR_LACAK
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1197 entries, 0 to 1196
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_rapor_lacak       1197 non-null   int64
 1   id_siswa             1197 non-null   int64
 2   id_jadwal            1197 non-null   int64
 3   tanggal_terkirim     1197 non-null   datetime64[ns]
 4   status_pengiriman    1197 non-null   object
 5   id_rapor_siswa_file  1197 non-null   int64
dtypes: datetime64[ns](1), int64(4), object(1)
memory usage: 56.2+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

,id_rapor_lacak,id_siswa,id_jadwal,tanggal_terkirim,status_pengiriman,id_rapor_siswa_file
0,1,609,173,2024-11-18 10:57:59,Terkirim,396
1,6,714,352,2024-12-02 11:37:12,Terkirim,400
2,10,609,274,2024-12-02 11:50:37,Terkirim,1484
3,12,609,274,2024-12-02 11:51:25,Terkirim,1484
4,13,609,274,2024-12-04 15:32:22,Terkirim,1484
...,...,...,...,...,...,...
1192,1371,304,452,2025-12-15 13:50:31,Terkirim,1474
1193,1372,2032,452,2025-12-15 13:50:32,Terkirim,1475
1194,1373,254,452,2025-12-15 13:50:32,Terkirim,1473
1195,1374,211,452,2025-12-15 13:50:39,Terkirim,1472
1196,1375,218,452,2025-12-16 09:49:23,Terkirim,1476

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: PRESENSI_SISWA
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_presensi_siswa  0 non-null      object
 1   id_jadwal_detail   0 non-null      object
 2   id_siswa           0 non-null      object
 3   waktu_presensi     0 non-null      object
 4   status_presensi    0 non-null      object
dtypes: object(5)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

Empty DataFrame
Columns: [id_presensi_siswa, id_jadwal_detail, id_siswa, waktu_presensi, status_presensi]
Index: []

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: CATATAN_SISWA
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_cs             0 non-null      object
 1   id_jadwal         0 non-null      object
 2   id_jadwal_detail  0 non-null      object
 3   id_siswa          0 non-null      object
 4   id_karyawan       0 non-null      object
 5   tanggal           0 non-null      object
 6   catatan_cs        0 non-null      object
dtypes: object(7)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

Empty DataFrame
Columns: [id_cs, id_jadwal, id_jadwal_detail, id_siswa, id_karyawan, tanggal, catatan_cs]
Index: []

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: FOLLOWUP_CS
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id_followup_cs          0 non-null      object
 1   id_cs                   0 non-null      object
 2   tanggal_followup        0 non-null      object
 3   id_user                 0 non-null      object
 4   kesimpulan_followup_cs  0 non-null      object
 5   status_followup         0 non-null      object
dtypes: object(6)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

Empty DataFrame
Columns: [id_followup_cs, id_cs, tanggal_followup, id_user, kesimpulan_followup_cs, status_followup]
Index: []

================================================================================