In [1]:
import sys
import os
import mysql.connector
import pandas as pd
sys.path.append(os.path.abspath('..'))
from config import get_db_config
import warnings
warnings.filterwarnings('ignore')
import json
import pickle
import numpy as np
import datetime
from IPython.display import display, HTML

In [2]:
# Connect ke database config
config = get_db_config()
# Ambil host dari salah satu config (misal db_old)
print(f'Database config loaded: {config["db_old"]["host"]}')

# Connect ke DB Lama
db_old = mysql.connector.connect(**config['db_old'])
cursor_old = db_old.cursor(dictionary=True)
print(f'Connected to old database: {config["db_old"]["database"]}')

# Connect ke DB Baru
db_new = mysql.connector.connect(**config['db_new'])
cursor_new = db_new.cursor(dictionary=True)
print(f'Connected to new database: {config["db_new"]["database"]}')

db_future = mysql.connector.connect(**config['db_future'])
cursor_future = db_future.cursor(dictionary=True)
print(f'Connected to future database: {config["db_future"]["database"]}')

Database config loaded: localhost
Connected to old database: dataleap_v5_example_new
Connected to new database: dataleap_v5_migration
Connected to future database: dataleap_v5_migration

In [3]:
print("================================================================================")
print(" 🚀 SETUP INSERT HANDLER GLOBAL - FASE 3 (SALING SILANG & AUTO-SKIP) 🚀 ")
print("================================================================================")

# ================================================================================
# TAHAP 1: MEMUAT SE LURUH BERKAS PICKLE DAN MERGE JADI SATU PINTU
# ================================================================================
all_fase_3_data = {}

# 1. Load File Cimut
try:
    with open('fase_3_cimut.pkl', 'rb') as f:
        all_fase_3_data.update(pickle.load(f))
    print("✓ Berhasil memuat data hasil konversi Cimut.")
except Exception as e:
    print(f"⚠️ Gagal memuat file pkl Cimut: {e}")

# 2. Load File Afrida
try:
    with open('fase_3_afrida.pkl', 'rb') as f:
        all_fase_3_data.update(pickle.load(f))
    print("✓ Berhasil memuat data hasil konversi Afrida.")
except Exception as e:
    print(f"⚠️ Gagal memuat file pkl Afrida: {e}")

# 3. Load File Hanif (Jika ada file terpisah, opsional)
try:
    if os.path.exists('fase_3_hanif.pkl'):
        with open('fase_3_hanif.pkl', 'rb') as f:
            all_fase_3_data.update(pickle.load(f))
        print("✓ Berhasil memuat data hasil konversi Hanif.")
except:
    print(f"⚠️ Gagal memuat file pkl Hanif: {f}")
    pass

================================================================================
 🚀 SETUP INSERT HANDLER GLOBAL - FASE 3 (SALING SILANG & AUTO-SKIP) 🚀
================================================================================

✓ Berhasil memuat data hasil konversi Cimut.
✓ Berhasil memuat data hasil konversi Afrida.
✓ Berhasil memuat data hasil konversi Hanif.

In [4]:
# ================================================================================
# TAHAP 2: ATUR URUTAN STRATEGIS SALING SILANG (CIMUT, AFRIDA, & HANIF)
# ================================================================================
# Susunan di bawah ini diatur ketat lintas personel agar Foreign Key aman masuk ke MySQL!
tables_to_insert_ordered_1= [
    # --- BLOK A: PENDAFTARAN & SDM (Karya Hanif) ---
    'pelamar',                  # Induk data pelamar kerja/kursus
    'pelamar_kerja',            # Detail pelamar posisi kerja
    'pelamar_sekolah',          # Riwayat sekolah pelamar
    'pelamar_kursus',           # Riwayat kursus pelamar
    'progres_pelamar',          # Log catatan tahapan seleksi
    'rekrutmen_pelamar',        # Keputusan akhir rekrutmen pelamar
    'pengajuan_karyawan',       # Form pengajuan penambahan staff baru
    'histori_pengajuan',        # Log alur persetujuan pengajuan staff
]

In [5]:
# ================================================================================
# TAHAP 2: ATUR URUTAN STRATEGIS SALING SILANG (CIMUT, AFRIDA, & HANIF)
# ================================================================================
# Susunan di bawah ini diatur ketat lintas personel agar Foreign Key aman masuk ke MySQL!
tables_to_insert_ordered_2 = [
    # --- BLOK B: SURAT-MENYURAT & SOP (Karya Afrida) ---
    'sop',                      # Standar operasional prosedur instansi
    'surat_keluar',             # Log keluar dokumen/surat resmi
    'verifikasi_surat_keluar',  # Log persetujuan surat keluar oleh atasan
    'surat_tugas',              # Surat perintah penugasan formal
    'surat_tugas_anggota',      # Anggota staff yang terikat di dalam surat tugas
    'sop_kategori', 
]

In [6]:
# ================================================================================
# TAHAP 2: ATUR URUTAN STRATEGIS SALING SILANG (CIMUT, AFRIDA, & HANIF)
# ================================================================================
# Susunan di bawah ini diatur ketat lintas personel agar Foreign Key aman masuk ke MySQL!
tables_to_insert_ordered_3 = [
    # --- BLOK C: MARKETING & ADMISI CALON SISWA (Karya Cimut) ---
    'kontak_prospek',           # Database mentah leads / prospek marketing
    'calon_siswa',              # Formulir profil utama calon siswa baru
    'calon_siswa_ortu',         # Data wali / orang tua calon siswa
    'calon_siswa_akademik',     # Riwayat background akademik calon siswa
    'calon_siswa_bayar',        # Log transaksi pembayaran formulir/DP awal
    'calon_siswa_jadwal',       # Plotting jadwal tes/interview calon siswa
    'calon_siswa_kursus',       # Pilihan program kursus yang diminati calon siswa
    'calon_siswa_proses',       # Jalur perkembangan dokumen admisinya
    'calon_siswa_status_logs',  # Log perubahan status akhir (Diterima/Ditolak/Pending)

    # --- BLOK D: LOGISTIK & OPERASIONAL INTERNAL (Karya Cimut) ---
    'pengadaan',                # Form pengajuan belanja/pengadaan aset barang
    'peminjaman',               # Log pinjam pakai sarana prasarana oleh staff
    'problem'                   # Log laporan kerusakan/kendala teknis fasilitas
]

In [7]:
import pandas as pd
import datetime
import numpy as np
import mysql.connector

# ================================================================================
# TAHAP 3: FUNGSI UTAMA INSERT DENGAN RINGKASAN DI ATAS & DIAGNOSTIK ERROR DI BAWAH
# ================================================================================
def insert_data_with_preview_and_skip_v2(db_connection, cursor, tables_data, ordered_list):
    results = {}
    
    print("="*80)
    print("🎬 MEMULAI EKSEKUSI PENYUNTIKAN DATA KE MYSQL BARU (SISTEM RINGKASAN ATAS)")
    print("="*80)
    
    # ----------------------------------------------------------------------------
    # SUB-LANGKAH A: PROSES INSERT KE MYSQL DI BELAKANG LAYAR
    # ----------------------------------------------------------------------------
    for table_name in ordered_list:
        if table_name not in tables_data:
            results[table_name] = {
                'status': 'not_found', 
                'rows': 0, 
                'msg': f'⚠️  {table_name}: Tidak ditemukan di file pkl'
            }
            continue
            
        df_target = tables_data[table_name]
        
        if df_target is None or df_target.empty:
            results[table_name] = {
                'status': 'empty', 
                'rows': 0, 
                'msg': f'ℹ️  {table_name}: DataFrame kosong (0 baris)'
            }
            continue
            
        try:
            # Bersihkan kolom kosong murni agar tidak merusak placeholder query
            df_to_push = df_target.dropna(axis=1, how='all')
            
            columns_str = ', '.join([f'`{col}`' for col in df_to_push.columns])
            placeholders_str = ', '.join(['%s'] * len(df_to_push.columns))
            
            # Gunakan INSERT IGNORE untuk auto-skip duplikat primary key
            insert_query = f"INSERT IGNORE INTO `{table_name}` ({columns_str}) VALUES ({placeholders_str})"
            
            # Konversi DataFrame ke Native List Python (Hancurkan tipe data NumPy)
            raw_numpy_list = df_to_push.to_numpy().tolist()
            clean_data_tuples = [
                tuple(None if pd.isna(x) or str(x).strip() in ["NaT", "NaN"] else x for x in row) 
                for row in raw_numpy_list
            ]
            
            # Eksekusi massal
            cursor.executemany(insert_query, clean_data_tuples)
            db_connection.commit()
            
            total_rows = len(clean_data_tuples)
            results[table_name] = {
                'status': 'success', 
                'rows': total_rows, 
                'msg': f'✓ {table_name}: Sukses diproses! Sebanyak {total_rows} baris sukses dimasukkan / di-skip aman.'
            }
            
        except Exception as e:
            db_connection.rollback()
            results[table_name] = {
                'status': 'failed', 
                'rows': 0, 
                'msg': f'✗ {table_name}: Gagal total saat insert - Alasan: {e}'
            }

    # ----------------------------------------------------------------------------
    # 📊 CETAK PAPAN RINGKASAN DI PALING ATAS (SUMMARY BOARD)
    # ----------------------------------------------------------------------------
    print("\n================================================================================")
    print(" 📊 PAPAN RINGKASAN STATUS MIGRATION DATA (SUMMARY BOARD) 📊")
    print("================================================================================")
    
    # 1. Cetak yang sukses dulu biar rapi
    print("🟢 TABEL YANG SUKSES MASUK:")
    success_exist = False
    for table_name in ordered_list:
        if table_name in results and results[table_name]['status'] == 'success':
            print(f"  {results[table_name]['msg']}")
            success_exist = True
    if not success_exist: print("  (Tidak ada tabel yang sukses)")

    print("\n🔴 TABEL YANG BERMASALAH / GAGAL MASUK (MOHON DIANALISA):")
    failed_exist = False
    for table_name in ordered_list:
        if table_name in results and results[table_name]['status'] in ['failed', 'not_found', 'empty']:
            print(f"  {results[table_name]['msg']}")
            failed_exist = True
    if not failed_exist: print("  🎉 LUAR BIASA! Semua tabel bersih tidak ada yang gagal.")
            
    print("================================================================================\n")


    # ----------------------------------------------------------------------------
    # 📸 CETAK PREVIEW HISTORI & DIAGNOSTIK ERROR DI BAGIAN BAWAH
    # ----------------------------------------------------------------------------
    print("="*80)
    print("📸 MEMULAI LOG VISUALISASI PREVIEW & DIAGNOSTIK TABEL")
    print("="*80)
    
    for table_name in ordered_list:
        if table_name in results:
            # Taktik A: Jika Sukses, tampilkan preview standard 5 baris teratas
            if results[table_name]['status'] == 'success':
                print(f"\n📂 [🟢 PREVIEW TABEL SUKSES: {table_name.upper()}]")
                print("-" * 50)
                display(tables_data[table_name]) 
                print("-" * 80)
                
            # Taktik B: Jika GAGAL, tembak dan kuliti struktur datanya secara transparan!
            elif results[table_name]['status'] == 'failed':
                print(f"\n🚨 [🔴 DIAGNOSTIK TABEL ERROR: {table_name.upper()}] 🚨")
                print(f"Alasan MySQL Menolak: {results[table_name]['msg']}")
                print("-" * 50)
                print("Berikut 5 baris sampel data yang gagal dikirim, cek tipe datanya (apakah ada .0 atau string aneh):")
                display(tables_data[table_name])
                print(f"\nTipe data kolom internal DataFrame untuk tabel '{table_name}':")
                # Menampilkan tipe data internal pandas agar ketahuan mana float ghaib / objek aneh
                print(tables_data[table_name].dtypes)
                print("-" * 80)
            
    print("\n" + "="*80)
    print("🏁 PROSES INSPEKSI SELESAI. SILAKAN CEK HASIL DIAGNOSTIK DI ATAS 🏁")
    print("="*80)
    return results

In [8]:
# ================================================================================
# TAHAP 4: MENJALANKAN EKSEKUSI DATA REAL (MENGGUNAKAN VERSI RINGKASAN ATAS)
# ================================================================================
results_fase_3 = insert_data_with_preview_and_skip_v2(
    db_connection=db_future, 
    cursor=cursor_future, 
    tables_data=all_fase_3_data, 
    ordered_list=tables_to_insert_ordered_1
)

================================================================================
🎬 MEMULAI EKSEKUSI PENYUNTIKAN DATA KE MYSQL BARU (SISTEM RINGKASAN ATAS)
================================================================================

================================================================================
 📊 PAPAN RINGKASAN STATUS MIGRATION DATA (SUMMARY BOARD) 📊
================================================================================
🟢 TABEL YANG SUKSES MASUK:
  ✓ pelamar: Sukses diproses! Sebanyak 192 baris sukses dimasukkan / di-skip aman.
  ✓ pelamar_kerja: Sukses diproses! Sebanyak 67 baris sukses dimasukkan / di-skip aman.
  ✓ pelamar_sekolah: Sukses diproses! Sebanyak 53 baris sukses dimasukkan / di-skip aman.
  ✓ pelamar_kursus: Sukses diproses! Sebanyak 50 baris sukses dimasukkan / di-skip aman.
  ✓ progres_pelamar: Sukses diproses! Sebanyak 403 baris sukses dimasukkan / di-skip aman.
  ✓ rekrutmen_pelamar: Sukses diproses! Sebanyak 281 baris sukses dimasukkan / di-skip aman.
  ✓ pengajuan_karyawan: Sukses diproses! Sebanyak 33 baris sukses dimasukkan / di-skip aman.
  ✓ histori_pengajuan: Sukses diproses! Sebanyak 79 baris sukses dimasukkan / di-skip aman.

🔴 TABEL YANG BERMASALAH / GAGAL MASUK (MOHON DIANALISA):
  🎉 LUAR BIASA! Semua tabel bersih tidak ada yang gagal.
================================================================================

================================================================================
📸 MEMULAI LOG VISUALISASI PREVIEW & DIAGNOSTIK TABEL
================================================================================

📂 [🟢 PREVIEW TABEL SUKSES: PELAMAR]
--------------------------------------------------

     id_pengajuan  ...           created_at
0            <NA>  ...  2020-01-01 00:00:00
1            <NA>  ...  2023-06-29 10:24:53
2            <NA>  ...  2020-01-01 00:00:00
3            <NA>  ...  2020-01-01 00:00:00
4               2  ...  2023-07-05 11:17:01
..            ...  ...                  ...
187          <NA>  ...  2020-01-01 00:00:00
188          <NA>  ...  2020-01-01 00:00:00
189          <NA>  ...  2020-01-01 00:00:00
190          <NA>  ...  2020-01-01 00:00:00
191          <NA>  ...  2020-01-01 00:00:00

[192 rows x 42 columns]

--------------------------------------------------------------------------------

📂 [🟢 PREVIEW TABEL SUKSES: PELAMAR_KERJA]
--------------------------------------------------

    id_pelamar  ...                                    deskripsi_kerja
0          101  ...  <p>- Membuat lesson plan</p>\r\n<p>- Membuat s...
1          181  ...  <p>Mengajar dua kelas pada semester 1 dan 2. D...
2          182  ...  <p><span style="color: rgba(0, 0, 0, 0.9); fon...
3          150  ...  <p>Melayani keluhan dan kebutuhan pelanggan BN...
4          183  ...                              <p>Mengajar Siswa</p>
..         ...  ...                                                ...
62         138  ...  <p style="text-align: justify;">Memberikan lay...
63         138  ...  <p style="text-align: justify;">Membantu guru ...
64         138  ...  <p style="text-align: justify;">Memasukkan dat...
65         160  ...  <p>Bertanggung jawab untuk mendukung proses be...
66         158  ...  <p>part time di resto chinese bantu bantu acar...

[67 rows x 5 columns]

--------------------------------------------------------------------------------

📂 [🟢 PREVIEW TABEL SUKSES: PELAMAR_SEKOLAH]
--------------------------------------------------

    id_pelamar  ...                                         organisasi
0          101  ...                                                  -
1          181  ...                                               PMII
2          182  ...  SKI (Sie Kerohanian Islam)\r\nKepanitiaan Faku...
3          150  ...                                         BEM, KAMMI
4          183  ...
5          183  ...
6          191  ...       HUMAS EXTRAKURIKULER TEATER DAN KARYA ILMIAH
7          191  ...                                                  -
8          191  ...                                                  -
9          186  ...                                                  -
10         186  ...                                                  -
11         189  ...                                                  -
12         184  ...                                        OSIS di SMK
13         179  ...
14         179  ...                Ketua Umum KOHATI Fakultas Tarbiyah
15         180  ...                 Paduan Suara Universitas Airlangga
16         180  ...
17         180  ...                      Paduan Suara SMA N 2 Bengkulu
18         145  ...                                           OSIS SMU
19         192  ...
20         190  ...  Unit Kegiatan Mahasiswa Aktifitas Fotografi Un...
21         176  ...                                               HIMA
22         176  ...
23         163  ...  1. Himpunan Mahasiswa Jurusan (HMJ)\r\n2. Alia...
24         188  ...                Himaprodi Pendidikan Bahasa Inggris
25         190  ...                        OSIS SMA Negeri 10 Surabaya
26         188  ...
27         188  ...                            OSIS SMP Negeri 1 Tuban
28         188  ...                                                  -
29         185  ...                                            HIMA TI
30         187  ...  1. Sekretaris Unit Kegiatas Mahasiswa Futsal d...
31         176  ...                                          tidak ada
32         176  ...                                             AIESEC
33          41  ...                                         Himatifta
34          56  ...
35          58  ...                           Pasukan Pengibar Bendera
36          71  ...                                               Hima
37          55  ...   KETUA ISMAIEN (Ikatan Santri Ma'hadul Mu'minien)
38         167  ...
39         124  ...                                               HIMA
40         124  ...                                               HIMA
41         101  ...  Peer Tutor for Qur’an Recitation (July 2016 – ...
42         101  ...  Chairman of the 31st Cohort. Student Represent...
43         101  ...
44         127  ...            Volunteer English Tutor -- HIMASAINTRA
45         136  ...
46         131  ...
47         157  ...  Bergabung dalam organisasi Himpunan Mahasiswa ...
48         138  ...
49         160  ...
50          85  ...                             OSIS SMA Vita Surabaya
51         158  ...
52         162  ...                Himpunan Mahasiswa, FIFA, PSSI, etc

[53 rows x 7 columns]

--------------------------------------------------------------------------------

📂 [🟢 PREVIEW TABEL SUKSES: PELAMAR_KURSUS]
--------------------------------------------------

    id_pelamar  ...                    nomor_sertifikat
0          101  ...                        184617619842
1          181  ...                    000 - 756 - 458.
2          150  ...                             TDK ADA
3          189  ...                                   -
4          186  ...             021.1/K21/11164/VI.2023
5          186  ...         004/DIKLAT/YPPI/PE/III/2023
6          182  ...  No. 021.1 / K21 / 11173 / V / 2023
7          176  ...                                   -
8          163  ...                  1892/PB/TR/10.2022
9          184  ...                                   -
10         179  ...                             0000651
11         191  ...                                   -
12         145  ...                                   -
13         180  ...                 70/UN3.1.11/DL/2021
14         182  ...                            12827527
15         182  ...       No. 62090 3511 3 0069147 2023
16         186  ...                      tdk ada nomer
17          55  ...                          2329080407
18          55  ...                         Belum Rilis
19          41  ...                                   -
20          41  ...                                   -
21         184  ...                        15.1.5.32333
22         184  ...                                   -
23         184  ...                    01291/35/065/LSK
24         101  ...                    21ID0015RONG405A
25         101  ...               620903511300685582023
26         101  ...                   2882/JS2/XII/2021
27         124  ...                    405/E.E5/KP/2018
28         124  ...                             3131093
29         124  ...                      0028/B/KP/2021
30         124  ...                              110574
31         124  ...                             1764635
32         124  ...                             1123274
33         124  ...           05/serasi/peserta/II/2021
34         124  ...                     854/WM02/T/2022
35         124  ...            APCEIU-CL002-2022-101-E7
36         124  ...                     tidak ada nomor
37         101  ...               LAZ-RGI/MMXIV31080405
38         101  ...                 35/KPM/FKM4/IV/2024
39         101  ...                             9116881
40         131  ...                   2684/PR/TR/V/2024
41         131  ...                 29449/PR/TR/VI/2024
42         157  ...             05511 4224 0001171 2021
43         157  ...        076/DK/D.7/FBS/UNIBA/IX/2022
44         157  ...  25/HS/BWI/FBS-CERTIFICATE/III/2023
45         157  ...               7308/E2/DT.01.00/2023
46         157  ...                                   -
47         182  ...                                   -
48         182  ...            No : 001/TLPB/II/2526/17
49         182  ...                                   -

[50 rows x 6 columns]

--------------------------------------------------------------------------------

📂 [🟢 PREVIEW TABEL SUKSES: PROGRES_PELAMAR]
--------------------------------------------------

     id_pelamar id_user  ... pertanyaan           created_at
0           177  U00001  ...          -  2023-05-29 16:56:05
1           177  U00012  ...          -  2023-05-29 16:57:22
2           177  U00001  ...          -  2023-05-29 16:59:34
3           178  U00001  ...          -  2023-05-29 17:45:09
4           178  U00001  ...          -  2023-05-30 06:21:30
..          ...     ...  ...        ...                  ...
398         174  U00018  ...          -  2026-04-08 08:22:57
399         175  U00018  ...          -  2026-04-08 08:24:43
400         176  U00018  ...          -  2026-04-13 09:24:34
401         176  U00018  ...          -  2026-04-17 10:44:29
402         175  U00018  ...          -  2026-04-17 10:44:38

[403 rows x 7 columns]

--------------------------------------------------------------------------------

📂 [🟢 PREVIEW TABEL SUKSES: REKRUTMEN_PELAMAR]
--------------------------------------------------

     id_pelamar id_user
0             5  U00014
1             2  U00014
2             2  U00023
3            12  U00014
4            12  U00016
..          ...     ...
276         173  U00015
277         173  U00018
278         176  U00014
279         176  U00015
280         176  U00018

[281 rows x 2 columns]

--------------------------------------------------------------------------------

📂 [🟢 PREVIEW TABEL SUKSES: PENGAJUAN_KARYAWAN]
--------------------------------------------------

   id_user  ...           created_at
0   U00016  ...  2023-06-16 17:02:47
1   U00014  ...  2023-07-04 13:52:25
2   U00014  ...  2023-07-18 10:11:14
3   U00012  ...  2023-07-18 11:24:24
4   U00016  ...  2023-07-18 16:36:22
5   U00012  ...  2023-07-20 13:59:46
6   U00012  ...  2023-08-08 16:55:25
7   U00020  ...  2023-08-28 14:40:03
8   U00014  ...  2023-09-21 15:40:36
9   U00014  ...  2023-10-13 17:00:40
10  U00012  ...  2023-11-29 12:25:37
11  U00014  ...  2023-12-21 13:33:03
12  U00012  ...  2023-12-21 16:58:02
13  U00018  ...  2024-03-01 11:57:07
14  U00018  ...  2024-04-19 16:49:32
15  U00016  ...  2024-05-14 13:24:41
16  U00012  ...  2024-05-15 10:08:51
17  U00012  ...  2024-05-15 11:40:51
18  U00014  ...  2024-05-15 16:57:00
19  U00014  ...  2024-05-27 17:12:48
20  U00014  ...  2024-06-04 14:26:30
21  U00012  ...  2024-08-02 11:22:12
22  U00012  ...  2024-08-05 11:02:07
23  U00023  ...  2024-08-13 10:08:59
24  U00012  ...  2024-11-22 11:48:47
25  U00016  ...  2025-03-05 14:16:55
26  U00014  ...  2025-05-21 09:52:06
27  U00016  ...  2025-05-21 12:45:01
28  U00016  ...  2025-07-21 15:43:54
29  U00014  ...  2025-09-30 16:07:40
30  U00016  ...  2025-10-01 16:24:08
31  U00014  ...  2025-11-06 15:24:10
32  U00023  ...  2026-02-11 11:13:41

[33 rows x 9 columns]

--------------------------------------------------------------------------------

📂 [🟢 PREVIEW TABEL SUKSES: HISTORI_PENGAJUAN]
--------------------------------------------------

    id_pengajuan  ...           created_at
0              1  ...  2023-06-16 17:02:47
1              2  ...  2023-07-04 13:52:25
2              2  ...  2023-07-04 14:13:49
3              3  ...  2023-07-18 10:11:14
4              3  ...  2023-07-18 10:21:19
..           ...  ...                  ...
74            32  ...  2025-11-06 15:24:10
75            32  ...  2025-11-06 15:41:54
76            32  ...  2025-11-06 15:42:26
77            32  ...  2025-11-06 15:42:41
78            33  ...  2026-02-11 11:13:41

[79 rows x 4 columns]

--------------------------------------------------------------------------------

================================================================================
🏁 PROSES INSPEKSI SELESAI. SILAKAN CEK HASIL DIAGNOSTIK DI ATAS 🏁
================================================================================

In [9]:
# ================================================================================
# TAHAP 4: MENJALANKAN EKSEKUSI DATA REAL (MENGGUNAKAN VERSI RINGKASAN ATAS)
# ================================================================================
results_fase_3 = insert_data_with_preview_and_skip_v2(
    db_connection=db_future, 
    cursor=cursor_future, 
    tables_data=all_fase_3_data, 
    ordered_list=tables_to_insert_ordered_2
)

================================================================================
🎬 MEMULAI EKSEKUSI PENYUNTIKAN DATA KE MYSQL BARU (SISTEM RINGKASAN ATAS)
================================================================================

================================================================================
 📊 PAPAN RINGKASAN STATUS MIGRATION DATA (SUMMARY BOARD) 📊
================================================================================
🟢 TABEL YANG SUKSES MASUK:
  ✓ sop: Sukses diproses! Sebanyak 4 baris sukses dimasukkan / di-skip aman.
  ✓ surat_keluar: Sukses diproses! Sebanyak 231 baris sukses dimasukkan / di-skip aman.
  ✓ verifikasi_surat_keluar: Sukses diproses! Sebanyak 513 baris sukses dimasukkan / di-skip aman.
  ✓ surat_tugas: Sukses diproses! Sebanyak 139 baris sukses dimasukkan / di-skip aman.
  ✓ surat_tugas_anggota: Sukses diproses! Sebanyak 319 baris sukses dimasukkan / di-skip aman.
  ✓ sop_kategori: Sukses diproses! Sebanyak 2 baris sukses dimasukkan / di-skip aman.

🔴 TABEL YANG BERMASALAH / GAGAL MASUK (MOHON DIANALISA):
  🎉 LUAR BIASA! Semua tabel bersih tidak ada yang gagal.
================================================================================

================================================================================
📸 MEMULAI LOG VISUALISASI PREVIEW & DIAGNOSTIK TABEL
================================================================================

📂 [🟢 PREVIEW TABEL SUKSES: SOP]
--------------------------------------------------

                                    judul_sop  ... id_sop_kategori
0  Akhir Penggunaan Kelas English (19.15 WIB)  ...               1
1                      Penerimaan Surat Masuk  ...               2
2                      Pengajuan Surat Keluar  ...               2
3                       Pengajuan Surat Tugas  ...               2

[4 rows x 4 columns]

--------------------------------------------------------------------------------

📂 [🟢 PREVIEW TABEL SUKSES: SURAT_KELUAR]
--------------------------------------------------

     id_sk  ...          created_at
0       29  ... 2023-11-13 15:41:58
1       27  ... 2023-10-26 17:37:59
2       28  ... 2023-11-10 16:10:04
3       26  ... 2023-10-25 16:57:38
4       24  ... 2023-09-11 17:57:49
..     ...  ...                 ...
226    268  ... 2026-06-02 10:15:56
227    269  ... 2026-06-04 15:39:50
228    270  ... 2026-06-08 10:56:13
229    271  ... 2026-06-10 13:55:27
230    272  ... 2026-06-10 14:59:06

[231 rows x 8 columns]

--------------------------------------------------------------------------------

📂 [🟢 PREVIEW TABEL SUKSES: VERIFIKASI_SURAT_KELUAR]
--------------------------------------------------

     id_sk status_verifikasi_sk catatan_verifikasi_sk          created_at
0     <NA>             Diajukan     Tidak ada catatan 2023-06-12 13:32:50
1     <NA>             Diajukan     Tidak ada catatan 2023-06-12 13:33:07
2     <NA>             Diajukan     Tidak ada catatan 2023-06-12 14:28:56
3     <NA>             Diajukan     Tidak ada catatan 2023-06-30 15:30:35
4     <NA>             Diajukan     Tidak ada catatan 2023-07-01 20:35:43
..     ...                  ...                   ...                 ...
508    269            Disetujui     Tidak ada catatan 2026-06-04 15:41:13
509    270             Diajukan     Tidak ada catatan 2026-06-08 10:56:13
510    271             Diajukan     Tidak ada catatan 2026-06-10 13:55:27
511    270            Disetujui     Tidak ada catatan 2026-06-10 14:12:11
512    272             Diajukan     Tidak ada catatan 2026-06-10 14:59:06

[513 rows x 4 columns]

--------------------------------------------------------------------------------

📂 [🟢 PREVIEW TABEL SUKSES: SURAT_TUGAS]
--------------------------------------------------

     id_st id_user  ... catatan_pembatalan          created_at
0       24  U00015  ...  Tidak ada catatan 2023-09-19 13:55:50
1       23  U00015  ...  Tidak ada catatan 2023-09-19 13:54:26
2       22  U00016  ...  Tidak ada catatan 2023-09-13 13:01:52
3       20  U00015  ...  Tidak ada catatan 2023-07-25 09:56:19
4       21  U00015  ...  Tidak ada catatan 2023-08-22 17:43:48
..     ...     ...  ...                ...                 ...
134    167  U00016  ...  Tidak ada catatan 2026-04-17 16:01:07
135    168  U00018  ...  Tidak ada catatan 2026-05-04 11:09:02
136    169  U00016  ...  Tidak ada catatan 2026-05-20 14:06:43
137    170  U00014  ...  Tidak ada catatan 2026-05-25 14:05:54
138    171  U00016  ...  Tidak ada catatan 2026-06-11 10:36:01

[139 rows x 17 columns]

--------------------------------------------------------------------------------

📂 [🟢 PREVIEW TABEL SUKSES: SURAT_TUGAS_ANGGOTA]
--------------------------------------------------

     id_st id_user
0        6  U00012
1        6  U00003
2        7  U00026
3        7  U00012
4        8  U00026
..     ...     ...
314    170  U00035
315    170  U00052
316    170  U00070
317    171  U00014
318    171  U00015

[319 rows x 2 columns]

--------------------------------------------------------------------------------

📂 [🟢 PREVIEW TABEL SUKSES: SOP_KATEGORI]
--------------------------------------------------

   id_sop_kategori nama_kategori_sop
0                1             Kelas
1                2           HR / GA

--------------------------------------------------------------------------------

================================================================================
🏁 PROSES INSPEKSI SELESAI. SILAKAN CEK HASIL DIAGNOSTIK DI ATAS 🏁
================================================================================

In [10]:
# ================================================================================
# TAHAP 4: MENJALANKAN EKSEKUSI DATA REAL (MENGGUNAKAN VERSI RINGKASAN ATAS)
# ================================================================================
results_fase_3 = insert_data_with_preview_and_skip_v2(
    db_connection=db_future, 
    cursor=cursor_future, 
    tables_data=all_fase_3_data, 
    ordered_list=tables_to_insert_ordered_3
)

================================================================================
🎬 MEMULAI EKSEKUSI PENYUNTIKAN DATA KE MYSQL BARU (SISTEM RINGKASAN ATAS)
================================================================================

================================================================================
 📊 PAPAN RINGKASAN STATUS MIGRATION DATA (SUMMARY BOARD) 📊
================================================================================
🟢 TABEL YANG SUKSES MASUK:
  ✓ kontak_prospek: Sukses diproses! Sebanyak 194 baris sukses dimasukkan / di-skip aman.
  ✓ calon_siswa_kursus: Sukses diproses! Sebanyak 166 baris sukses dimasukkan / di-skip aman.
  ✓ pengadaan: Sukses diproses! Sebanyak 110 baris sukses dimasukkan / di-skip aman.
  ✓ peminjaman: Sukses diproses! Sebanyak 194 baris sukses dimasukkan / di-skip aman.
  ✓ problem: Sukses diproses! Sebanyak 160 baris sukses dimasukkan / di-skip aman.

🔴 TABEL YANG BERMASALAH / GAGAL MASUK (MOHON DIANALISA):
  ✗ calon_siswa: Gagal total saat insert - Alasan: 1054 (42S22): Unknown column 'fo_status' in 'field list'
  ✗ calon_siswa_ortu: Gagal total saat insert - Alasan: 1054 (42S22): Unknown column 'tempat_lahir_ayah' in 'field list'
  ✗ calon_siswa_akademik: Gagal total saat insert - Alasan: 1054 (42S22): Unknown column 'submission_state' in 'field list'
  ✗ calon_siswa_bayar: Gagal total saat insert - Alasan: 1054 (42S22): Unknown column 'id_calon_akademik' in 'field list'
  ✗ calon_siswa_jadwal: Gagal total saat insert - Alasan: 1054 (42S22): Unknown column 'id_calon_akademik' in 'field list'
  ✗ calon_siswa_proses: Gagal total saat insert - Alasan: 1054 (42S22): Unknown column 'id_calon_akademik' in 'field list'
  ℹ️  calon_siswa_status_logs: DataFrame kosong (0 baris)
================================================================================

================================================================================
📸 MEMULAI LOG VISUALISASI PREVIEW & DIAGNOSTIK TABEL
================================================================================

📂 [🟢 PREVIEW TABEL SUKSES: KONTAK_PROSPEK]
--------------------------------------------------

     id_kontak_prospek  ... tanggal_kontak_terakhir
0                    1  ...     2025-09-18 17:39:40
1                    2  ...     2025-09-23 16:25:14
2                    3  ...     2025-10-03 09:48:34
3                    4  ...     2025-10-03 09:49:15
4                    5  ...     2025-10-03 09:48:50
..                 ...  ...                     ...
189                190  ...     2025-10-17 15:41:09
190                191  ...     2025-10-17 15:41:26
191                192  ...     2025-10-24 15:27:54
192                193  ...     2025-10-24 15:28:21
193                194  ...     2025-10-24 15:28:41

[194 rows x 11 columns]

--------------------------------------------------------------------------------

🚨 [🔴 DIAGNOSTIK TABEL ERROR: CALON_SISWA] 🚨
Alasan MySQL Menolak: ✗ calon_siswa: Gagal total saat insert - Alasan: 1054 (42S22): Unknown column 'fo_status' in 'field list'
--------------------------------------------------
Berikut 5 baris sampel data yang gagal dikirim, cek tipe datanya (apakah ada .0 atau string aneh):

     id_calon kode_unik  ... created_at           updated_at
0           1  PIJWREZC  ...       None  2025-09-18 17:39:40
1           2  LEHUEB6B  ...       None  2025-09-23 16:25:14
2           3  HBJ6O8TF  ...       None  2025-10-03 09:48:34
3           4  LI0QW5C1  ...       None  2025-10-03 09:49:15
4           5  CEFRJE2H  ...       None  2025-10-03 09:48:50
..        ...       ...  ...        ...                  ...
161       162  1H85H846  ...       None                 None
162       163  CWWQZ9HU  ...       None                 None
163       164  ROLCHKDI  ...       None                 None
164       165  WVUWAQMD  ...       None                 None
165       166  XBZALU18  ...       None                 None

[166 rows x 34 columns]

Tipe data kolom internal DataFrame untuk tabel 'calon_siswa':
id_calon                 int64
kode_unik               object
nama_lengkap            object
id_kontak_prospek        int64
nama_panggilan          object
jenis_kelamin           object
tempat_lahir            object
tanggal_lahir           object
kewarganegaraan         object
email                   object
agama                   object
nama_kontak_awal        object
wa_kontak_awal          object
id_provinsi             object
id_kabupaten            object
id_kecamatan            object
id_kelurahan            object
alamat_lengkap          object
wa_siswa                object
wa_ortu                 object
wa_administrasi         object
assigned_fo             object
assigned_akademik       object
catatan_awal_fo         object
fo_status               object
fo_status_updated_at    object
handover_at             object
link_form_sent_at       object
form_completed_at       object
first_submitted_at      object
latest_submitted_at     object
deleted_at              object
created_at              object
updated_at              object
dtype: object
--------------------------------------------------------------------------------

🚨 [🔴 DIAGNOSTIK TABEL ERROR: CALON_SISWA_ORTU] 🚨
Alasan MySQL Menolak: ✗ calon_siswa_ortu: Gagal total saat insert - Alasan: 1054 (42S22): Unknown column 'tempat_lahir_ayah' in 'field list'
--------------------------------------------------
Berikut 5 baris sampel data yang gagal dikirim, cek tipe datanya (apakah ada .0 atau string aneh):

     id_calon_ortu  id_calon  ... tempat_lahir_wali tanggal_lahir_wali
0                1         1  ...              None               None
1                2         2  ...              None               None
2                3         3  ...              None               None
3                4         4  ...              None               None
4                5         5  ...              None               None
..             ...       ...  ...               ...                ...
161            162       162  ...              None               None
162            163       163  ...              None               None
163            164       164  ...              None               None
164            165       165  ...              None               None
165            166       166  ...              None               None

[166 rows x 20 columns]

Tipe data kolom internal DataFrame untuk tabel 'calon_siswa_ortu':
id_calon_ortu          int64
id_calon               int64
nama_ayah             object
pekerjaan_ayah        object
pendidikan_ayah       object
penghasilan_ayah      object
tempat_lahir_ayah     object
tanggal_lahir_ayah    object
nama_ibu              object
pekerjaan_ibu         object
pendidikan_ibu        object
penghasilan_ibu       object
tempat_lahir_ibu      object
tanggal_lahir_ibu     object
nama_wali             object
pekerjaan_wali        object
pendidikan_wali       object
penghasilan_wali      object
tempat_lahir_wali     object
tanggal_lahir_wali    object
dtype: object
--------------------------------------------------------------------------------

🚨 [🔴 DIAGNOSTIK TABEL ERROR: CALON_SISWA_AKADEMIK] 🚨
Alasan MySQL Menolak: ✗ calon_siswa_akademik: Gagal total saat insert - Alasan: 1054 (42S22): Unknown column 'submission_state' in 'field list'
--------------------------------------------------
Berikut 5 baris sampel data yang gagal dikirim, cek tipe datanya (apakah ada .0 atau string aneh):

     id_calon_akademik  id_calon  ... lampiran_file               submitted_at
0                    1         1  ...          None 2026-06-23 19:57:48.304978
1                    2         2  ...          None 2026-06-23 19:57:48.304978
2                    3         3  ...          None 2026-06-23 19:57:48.304978
3                    4         4  ...          None 2026-06-23 19:57:48.304978
4                    5         5  ...          None 2026-06-23 19:57:48.304978
..                 ...       ...  ...           ...                        ...
161                162       162  ...          None 2026-06-23 19:57:48.304978
162                163       163  ...          None 2026-06-23 19:57:48.304978
163                164       164  ...          None 2026-06-23 19:57:48.304978
164                165       165  ...          None 2026-06-23 19:57:48.304978
165                166       166  ...          None 2026-06-23 19:57:48.304978

[166 rows x 28 columns]

Tipe data kolom internal DataFrame untuk tabel 'calon_siswa_akademik':
id_calon_akademik                     int64
id_calon                              int64
nama_sekolah                         object
jenjang_kelas_1                      object
jenjang_kelas_2                      object
kurikulum_sekolah                    object
id_kursus                            object
id_periode                           object
id_level                             object
submission_state                     object
preferensi_metode_belajar            object
riwayat_les                          object
kesulitan_belajar                    object
kegiatan_sekarang                    object
kegiatan_lainnya                     object
kemampuan_officeApp                  object
kemampuan_editing                    object
kemampuan_kustom                     object
kemampuan_komputer                   object
kemampuan_software                   object
penggunaan_gadget                    object
sumber_info                          object
referensi                            object
alasan_daftar                        object
alasan_program                       object
harapan_program                      object
lampiran_file                        object
submitted_at                 datetime64[us]
dtype: object
--------------------------------------------------------------------------------

🚨 [🔴 DIAGNOSTIK TABEL ERROR: CALON_SISWA_BAYAR] 🚨
Alasan MySQL Menolak: ✗ calon_siswa_bayar: Gagal total saat insert - Alasan: 1054 (42S22): Unknown column 'id_calon_akademik' in 'field list'
--------------------------------------------------
Berikut 5 baris sampel data yang gagal dikirim, cek tipe datanya (apakah ada .0 atau string aneh):

     id_calon_bayar  id_calon_akademik  ... bulan_mulai_belajar lokasi_belajar
0                 1                  1  ...           September            Sby
1                 2                  2  ...           September            Sby
2                 3                  3  ...                None           None
3                 4                  4  ...                None           None
4                 5                  5  ...           September            Sby
..              ...                ...  ...                 ...            ...
161             162                162  ...                None           None
162             163                163  ...                None           None
163             164                164  ...                None           None
164             165                165  ...                None           None
165             166                166  ...                None           None

[166 rows x 7 columns]

Tipe data kolom internal DataFrame untuk tabel 'calon_siswa_bayar':
id_calon_bayar               int64
id_calon_akademik            int64
nomor_invoice               object
bank_pembayaran             object
tanggal_konfirmasi_bayar    object
bulan_mulai_belajar         object
lokasi_belajar              object
dtype: object
--------------------------------------------------------------------------------

🚨 [🔴 DIAGNOSTIK TABEL ERROR: CALON_SISWA_JADWAL] 🚨
Alasan MySQL Menolak: ✗ calon_siswa_jadwal: Gagal total saat insert - Alasan: 1054 (42S22): Unknown column 'id_calon_akademik' in 'field list'
--------------------------------------------------
Berikut 5 baris sampel data yang gagal dikirim, cek tipe datanya (apakah ada .0 atau string aneh):

     id_calon_jadwal  id_calon_akademik  ... tanggal_masuk tanggal_keluar
0                  1                  1  ...    2025-09-24           None
1                  2                  2  ...    2025-09-25           None
2                  3                  3  ...          None           None
3                  4                  4  ...    2025-09-25           None
4                  5                  5  ...          None           None
..               ...                ...  ...           ...            ...
161              162                162  ...          None           None
162              163                163  ...          None           None
163              164                164  ...          None           None
164              165                165  ...          None           None
165              166                166  ...          None           None

[166 rows x 7 columns]

Tipe data kolom internal DataFrame untuk tabel 'calon_siswa_jadwal':
id_calon_jadwal         int64
id_calon_akademik       int64
tanggal_kontak_awal    object
tanggal_wawancara      object
tanggal_pembayaran     object
tanggal_masuk          object
tanggal_keluar         object
dtype: object
--------------------------------------------------------------------------------

📂 [🟢 PREVIEW TABEL SUKSES: CALON_SISWA_KURSUS]
--------------------------------------------------

     id_calon_kursus  id_calon  urutan nama_kursus jenis_program
0                  1         1       1          GE       English
1                  2         2       2          GE       English
2                  3         3       3         COD       Digital
3                  4         4       4          GE       English
4                  5         5       5          GE       English
..               ...       ...     ...         ...           ...
161              162       162     162        None          None
162              163       163     163        None          None
163              164       164     164        None          None
164              165       165     165        None          None
165              166       166     166        None          None

[166 rows x 5 columns]

--------------------------------------------------------------------------------

🚨 [🔴 DIAGNOSTIK TABEL ERROR: CALON_SISWA_PROSES] 🚨
Alasan MySQL Menolak: ✗ calon_siswa_proses: Gagal total saat insert - Alasan: 1054 (42S22): Unknown column 'id_calon_akademik' in 'field list'
--------------------------------------------------
Berikut 5 baris sampel data yang gagal dikirim, cek tipe datanya (apakah ada .0 atau string aneh):

     id_calon_siswa_proses  ...  detail_lainnya
0                        1  ...            None
1                        2  ...            None
2                        3  ...            None
3                        4  ...            None
4                        5  ...            None
..                     ...  ...             ...
161                    162  ...            None
162                    163  ...            None
163                    164  ...            None
164                    165  ...            None
165                    166  ...            None

[166 rows x 27 columns]

Tipe data kolom internal DataFrame untuk tabel 'calon_siswa_proses':
id_calon_siswa_proses               int64
id_calon_akademik                   int64
admin_pengontak                    object
penanggung_jawab                   object
jenis_trial                        object
hasil_trial                        object
waktu_trial_1                      object
waktu_trial_2                      object
tanggal_trial                      object
laporan_trial                      object
placement_trial                    object
lokasi_trial                       object
sumber_lead                        object
status_pipeline                    object
status_updated_at          datetime64[us]
status_diterima                     int64
status_form_pendaftaran           float64
hasil_penempatan                   object
followup_1                         object
followup_2                         object
followup_3                         object
akun_leapverse                     object
wa_grup_leapverse                  object
catatan_admin                      object
catatan_penting                    object
keterangan_tambahan                object
detail_lainnya                     object
dtype: object
--------------------------------------------------------------------------------

📂 [🟢 PREVIEW TABEL SUKSES: PENGADAAN]
--------------------------------------------------

     id_pengadaan  ...                                      url_pembelian
0              18  ...  https://docs.google.com/spreadsheets/d/15Xuh2Z...
1              20  ...  https://docs.google.com/spreadsheets/d/15Xuh2Z...
2              21  ...  https://docs.google.com/spreadsheets/d/15Xuh2Z...
3              22  ...  https://docs.google.com/spreadsheets/d/15Xuh2Z...
4              23  ...  https://docs.google.com/spreadsheets/d/15Xuh2Z...
..            ...  ...                                                ...
105           124  ...  https://docs.google.com/spreadsheets/d/15Xuh2Z...
106           125  ...  https://docs.google.com/spreadsheets/d/15Xuh2Z...
107           126  ...  https://docs.google.com/spreadsheets/d/15Xuh2Z...
108           127  ...  https://docs.google.com/spreadsheets/d/15Xuh2Z...
109           128  ...  https://docs.google.com/spreadsheets/d/15Xuh2Z...

[110 rows x 9 columns]

--------------------------------------------------------------------------------

📂 [🟢 PREVIEW TABEL SUKSES: PEMINJAMAN]
--------------------------------------------------

     id_pinjam tanggal_pinjam  ...            catatan_sarpras          created_at
0            2     2023-06-11  ...                            2023-06-12 13:20:39
1            3     2023-06-11  ...                            2023-06-12 13:21:35
2            5     2023-08-21  ...                            2023-08-16 15:01:55
3            6     2023-08-23  ...                            2023-08-23 10:19:12
4            7     2023-10-11  ...                            2023-10-10 15:30:53
..         ...            ...  ...                        ...                 ...
189        192     2026-04-10  ...  <p>Sudah dikembalikan</p> 2026-04-09 11:40:52
190        193     2026-04-10  ...                            2026-04-10 16:26:19
191        194     2026-04-17  ...                            2026-04-15 16:06:08
192        195     2026-04-17  ...                            2026-04-16 15:22:28
193        196     2026-04-17  ...                            2026-04-17 16:22:59

[194 rows x 7 columns]

--------------------------------------------------------------------------------

📂 [🟢 PREVIEW TABEL SUKSES: PROBLEM]
--------------------------------------------------

     id_problem  ...                                    gambar_problem
0            43  ...                                              None
1            58  ...                                              None
2            60  ...                                              None
3            61  ...                                              None
4            62  ...                                              None
..          ...  ...                                               ...
155         251  ...                                              None
156         252  ...  /storage/sarpas_images/sarpas_69d772008efe9.jpeg
157         253  ...   /storage/sarpas_images/sarpas_69dcdb6dd7663.jpg
158         254  ...                                              None
159         255  ...   /storage/sarpas_images/sarpas_69e1cfc5c079c.jpg

[160 rows x 8 columns]

--------------------------------------------------------------------------------

================================================================================
🏁 PROSES INSPEKSI SELESAI. SILAKAN CEK HASIL DIAGNOSTIK DI ATAS 🏁
================================================================================

In [11]:
# print("================================================================================")
# print(" 🧹 MEMULAI PROSES TRUNCATE DATA GLOBAL - FASE 3 (SISTEM RINGKASAN ATAS) 🧹 ")
# print("================================================================================")

# def truncate_tables_with_summary(db_connection, cursor, ordered_list):
#     truncate_results = {}
    
#     try:
#         # 🔥 SAKTI 1: Matikan benteng Foreign Key checks agar MySQL tidak memblokir penghapusan
#         cursor.execute("SET FOREIGN_KEY_CHECKS=0")
#         db_connection.commit()
#         print("🔓 Sensor Foreign Key Checks berhasil DIMATIKAN sementara.\n")
#     except Exception as e:
#         print(f"✗ Gagal mematikan Foreign Key Checks: {e}")
#         return
        
#     # ----------------------------------------------------------------------------
#     # SUB-LANGKAH A: PROSES EKSEKUSI TRUNCATE DI BELAKANG LAYAR
#     # ----------------------------------------------------------------------------
#     for table_name in ordered_list:
#         try:
#             truncate_query = f"TRUNCATE TABLE `{table_name}`"
#             cursor.execute(truncate_query)
#             db_connection.commit()
            
#             truncate_results[table_name] = {
#                 'status': 'success',
#                 'msg': f"✓ {table_name}: Sukses dibersihkan total! Seluruh baris data amblas."
#             }
#         except Exception as e:
#             db_connection.rollback()
#             truncate_results[table_name] = {
#                 'status': 'failed',
#                 'msg': f"✗ {table_name}: Gagal dikosongkan! Alasan: {e}"
#             }

#     try:
#         # 🔥 SAKTI 2: Wajib nyalakan kembali benteng Foreign Key checks setelah selesai
#         cursor.execute("SET FOREIGN_KEY_CHECKS=1")
#         db_connection.commit()
#         print("🔒 Sensor Foreign Key Checks berhasil DIHIDUPKAN kembali dengan aman.")
#     except Exception as e:
#         print(f"⚠️ Peringatan: Gagal menghidupkan kembali Foreign Key Checks: {e}")

#     # ----------------------------------------------------------------------------
#     # 🔥 CETAK PAPAN RINGKASAN TRUNCATE DI PALING ATAS (ANTI-SCROLL BOARD)
#     # ----------------------------------------------------------------------------
#     print("\n================================================================================")
#     print(" 📊 PAPAN RINGKASAN STATUS TRUNCATE DATABASE (CLEANUP SUMMARY BOARD) 📊")
#     print("================================================================================")
#     for table_name in ordered_list:
#         if table_name in truncate_results:
#             print(truncate_results[table_name]['msg'])
#         else:
#             print(f"⚠️  {table_name}: Lewat dari antrean pembersihan.")
#     print("================================================================================")
    
#     return truncate_results

# # === JALANKAN EKSEKUSI PEMBERSIHAN MENGGUNAKAN DAFTAR TABEL SALING SILANGMU ===
# results_truncate_fase_3 = truncate_tables_with_summary(
#     db_connection=db_new, 
#     cursor=cursor_new, 
#     ordered_list=tables_to_insert_ordered  # Otomatis memakai list urutan saling silang yang kita buat tadi
# )