In [1]:
import sys
import os
import mysql.connector
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Ambil konfigurasi database dari folder utama project kalian
sys.path.append(os.path.abspath('..'))
from config import get_db_config

config = get_db_config()

# 1. Koneksi ke Database Baru (Fase Migrasi Sekarang)
db_new = mysql.connector.connect(**config['db_new'])
cursor_new = db_new.cursor(dictionary=True)

# 2. Koneksi ke Database Masa Depan (DB_FUTURE)
# Catatan: Pastikan di file config.py kalian sudah ada key 'db_future' ya!
db_future = mysql.connector.connect(**config['db_future'])
cursor_future = db_future.cursor(dictionary=True)

print(f"✅ Sukses Terhubung ke Database Baru : {config['db_new']['database']}")
print(f"🚀 Sukses Terhubung ke DB_FUTURE     : {config['db_future']['database']}")

✅ Sukses Terhubung ke Database Baru : 3
🚀 Sukses Terhubung ke DB_FUTURE     : 3

In [2]:
tables_to_check = [
    # --- Bagian Cimut (Fokus Utama) ---
    "kontak_prospek", 
    "calon_siswa", 
    "calon_siswa_akademik", 
    "calon_siswa_ortu", 
    "calon_siswa_bayar", 
    "calon_siswa_jadwal", 
    "calon_siswa_kursus", 
    "calon_siswa_proses", 
    "calon_siswa_status_logs", 
    "peminjaman", 
    "pengadaan", 
    "problem",
    
    # --- Bagian Afrida ---
    "sop", 
    "surat_keluar", 
    "verifikasi_surat_keluar", 
    "surat_tugas", 
    "surat_tugas_anggota",
    
    # --- Bagian Hanif ---
    "pengajuan_karyawan", 
    "histori_pengajuan", 
    "pelamar", 
    "pelamar_kerja", 
    "pelamar_sekolah", 
    "pelamar_kursus", 
    "progres_pelamar", 
    "rekrutmen_pelamar"
]

In [3]:
# === Cell 2: Inspeksi Detektor Pintar dengan Prioritas Target Revisi di Atas ===
import pandas as pd
import numpy as np

print("================================================================================")
print(" 🕵️‍♂️ FORENSIK ARSITEKTUR KONTROL: DETEKTOR AUTO-SMART COMPILER (REVISI PRIORITY) 🕵️‍♂️ ")
print("================================================================================")

# List penampung data di memori untuk keperluan sorting visualisasi
revisi_tables_queue = []
identical_tables_queue = []

# --- TAHAP A: PROSES PEN ARIKAN DATA & EVALUASI STRUKTUR DI BELAKANG LAYAR ---
for table in tables_to_check:
    try:
        # 1. Ambil data asli dari DB_NEW untuk kebutuhan .info() dan sampel isi data
        query = f"SELECT * FROM `{table}`"
        df_real_data = pd.read_sql(query, db_new)
        
        # 2. Tarik Struktur Fisik Kolom dari DB_NEW
        query_new_struct = f"""
        SELECT 
            c.COLUMN_NAME AS 'Nama Kolom',
            c.COLUMN_TYPE AS 'Tipe Data MySQL',
            CONCAT(
                CASE WHEN c.IS_NULLABLE = 'YES' THEN '✅ NULL (Boleh Kosong)' ELSE '🛑 NOT NULL (Wajib Isi)' END,
                CASE WHEN c.EXTRA = 'auto_increment' THEN '\\n🚀 AUTO_INCREMENT' ELSE '' END
            ) AS 'Aturan Nullability & Increment',
            CASE 
                WHEN c.COLUMN_KEY = 'PRI' THEN '🔑 PRIMARY KEY (PK)'
                WHEN c.COLUMN_KEY = 'MUL' AND k.REFERENCED_TABLE_NAME IS NOT NULL THEN '🔗 FOREIGN KEY (FK)'
                WHEN c.COLUMN_KEY = 'MUL' THEN 'INDEX'
                ELSE '-'
            END AS 'Status Kunci',
            CASE 
                WHEN k.REFERENCED_TABLE_NAME IS NOT NULL THEN CONCAT(k.REFERENCED_TABLE_NAME, ' (', k.REFERENCED_COLUMN_NAME, ')')
                ELSE '-'
            END AS 'Rujukan Induk (FK Origin)',
            CASE WHEN c.DATA_TYPE = 'enum' THEN REPLACE(REPLACE(REPLACE(c.COLUMN_TYPE, 'enum(', ''), ')', ''), "'", "") ELSE '-' END AS 'Daftar Pilihan ENUM'
        FROM INFORMATION_SCHEMA.COLUMNS c
        LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE k 
            ON c.TABLE_SCHEMA = k.TABLE_SCHEMA AND c.TABLE_NAME = k.TABLE_NAME AND c.COLUMN_NAME = k.COLUMN_NAME
        WHERE c.TABLE_SCHEMA = '{config['db_new']['database']}' AND c.TABLE_NAME = '{table}'
        ORDER BY c.ORDINAL_POSITION;
        """
        df_struct_new = pd.read_sql(query_new_struct, db_new).drop_duplicates(subset=['Nama Kolom'], keep='first').reset_index(drop=True)
        
        # Lacak tabel anak yang nge-FK ke PK tabel ini di DB_NEW
        pk_referenced_list = []
        for idx, row_skri in df_struct_new.iterrows():
            if row_skri['Status Kunci'] == '🔑 PRIMARY KEY (PK)':
                lookup_fk_query = f"""
                SELECT CONCAT(TABLE_NAME, ' (', COLUMN_NAME, ')') as relasi
                FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
                WHERE REFERENCED_TABLE_SCHEMA = '{config['db_new']['database']}'
                  AND REFERENCED_TABLE_NAME = '{table}'
                  AND REFERENCED_COLUMN_NAME = '{row_skri['Nama Kolom']}';
                """
                df_relasi_luar = pd.read_sql(lookup_fk_query, db_new)
                if not df_relasi_luar.empty:
                    pk_referenced_list.append("\n".join(df_relasi_luar['relasi'].tolist()))
                else:
                    pk_referenced_list.append("-")
            else:
                pk_referenced_list.append("-")
        df_struct_new['Tabel Yang nge-FK (DB_NEW)'] = pk_referenced_list

        # 3. Tarik Struktur Fisik Kolom dari DB_FUTURE
        query_future_struct = f"""
        SELECT 
            c.COLUMN_NAME AS 'Nama Kolom',
            c.COLUMN_TYPE AS 'Tipe Data MySQL',
            CONCAT(
                CASE WHEN c.IS_NULLABLE = 'YES' THEN '✅ NULL (Boleh Kosong)' ELSE '🛑 NOT NULL (Wajib Isi)' END,
                CASE WHEN c.EXTRA = 'auto_increment' THEN '\\n🚀 AUTO_INCREMENT' ELSE '' END
            ) AS 'Aturan Nullability & Increment',
            CASE 
                WHEN c.COLUMN_KEY = 'PRI' THEN '🔑 PRIMARY KEY (PK)'
                WHEN c.COLUMN_KEY = 'MUL' AND k.REFERENCED_TABLE_NAME IS NOT NULL THEN '🔗 FOREIGN KEY (FK)'
                WHEN c.COLUMN_KEY = 'MUL' THEN 'INDEX'
                ELSE '-'
            END AS 'Status Kunci',
            CASE 
                WHEN k.REFERENCED_TABLE_NAME IS NOT NULL THEN CONCAT(k.REFERENCED_TABLE_NAME, ' (', k.REFERENCED_COLUMN_NAME, ')')
                ELSE '-'
            END AS 'Rujukan Induk (FK Origin)',
            CASE WHEN c.DATA_TYPE = 'enum' THEN REPLACE(REPLACE(REPLACE(c.COLUMN_TYPE, 'enum(', ''), ')', ''), "'", "") ELSE '-' END AS 'Daftar Pilihan ENUM'
        FROM INFORMATION_SCHEMA.COLUMNS c
        LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE k 
            ON c.TABLE_SCHEMA = k.TABLE_SCHEMA AND c.TABLE_NAME = k.TABLE_NAME AND c.COLUMN_NAME = k.COLUMN_NAME
        WHERE c.TABLE_SCHEMA = '{config['db_future']['database']}' AND c.TABLE_NAME = '{table}'
        ORDER BY c.ORDINAL_POSITION;
        """
        df_struct_future = pd.read_sql(query_future_struct, db_future).drop_duplicates(subset=['Nama Kolom'], keep='first').reset_index(drop=True)
        
        # Lacak tabel anak yang nge-FK ke PK tabel ini di DB_FUTURE
        pk_referenced_list_future = []
        for idx, row_skri in df_struct_future.iterrows():
            if row_skri['Status Kunci'] == '🔑 PRIMARY KEY (PK)':
                lookup_fk_query_future = f"""
                SELECT CONCAT(TABLE_NAME, ' (', COLUMN_NAME, ')') as relasi
                FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
                WHERE REFERENCED_TABLE_SCHEMA = '{config['db_future']['database']}'
                  AND REFERENCED_TABLE_NAME = '{table}'
                  AND REFERENCED_COLUMN_NAME = '{row_skri['Nama Kolom']}';
                """
                df_relasi_luar_future = pd.read_sql(lookup_fk_query_future, db_future)
                if not df_relasi_luar_future.empty:
                    pk_referenced_list_future.append("\n".join(df_relasi_luar_future['relasi'].tolist()))
                else:
                    pk_referenced_list_future.append("-")
            else:
                pk_referenced_list_future.append("-")
        df_struct_future['Tabel Yang nge-FK (DB_FUTURE)'] = pk_referenced_list_future

        # 4. Deep Comparison Kesamaan Jeroan Kolom dasar
        cols_to_compare = ['Nama Kolom', 'Tipe Data MySQL', 'Aturan Nullability & Increment', 'Status Kunci', 'Rujukan Induk (FK Origin)', 'Daftar Pilihan ENUM']
        
        is_structure_identical = False
        if not df_struct_new.empty and not df_struct_future.empty:
            is_structure_identical = df_struct_new[cols_to_compare].equals(df_struct_future[cols_to_compare])

        # Wadah paket data tabel untuk di-render nanti
        table_package = {
            'name': table,
            'df_real_data': df_real_data,
            'df_struct_new': df_struct_new,
            'df_struct_future': df_struct_future,
            'is_identical': is_structure_identical
        }

        # 🔥 FILTER SAKTI CIMUT: Pisahkan antrean, utamakan yang bermasalah (revisi) ke atas!
        if is_structure_identical:
            identical_tables_queue.append(table_package)
        else:
            revisi_tables_queue.append(table_package)
            
    except Exception as e:
        print(f"❌ Gagal menganalisis awal tabel `{table}`: {e}")

# --- TAHAP B: MULAI PEN TAMPILAN VISUALISASI BERDASARKAN ANT REAN PRIORITAS ---

# 🚨 1. KELOMPOK UTAMA (PALING ATAS): DAFTAR TABEL YANG WAJIB DIREVISI 🚨
if revisi_tables_queue:
    print("\n" + "!"*80)
    print(f"🚨 [🔥 REVISI PRIORITY BOARD] TERDETEKSI {len(revisi_tables_queue)} TABEL BERBEDA - HARUS SEGERA DIPERBAIKI!")
    print("!"*80)
    
    for pkg in revisi_tables_queue:
        print(f"\n================================================================================")
        print(f"⚠️  [STATUS: TARGET REVISI] TABEL: {pkg['name'].upper()}")
        print(f"================================================================================")
        
        print(f"📋 1. Karakteristik Wadah Pandas Dataframe (.info()):")
        pkg['df_real_data'].info()
        print("\n" + "-"*60)
        
        print(f"🔍 2. [TABEL REAL SAAT INI] Arsitektur Fisik Kolom pada DB_NEW:")
        display(pkg['df_struct_new'].style.set_properties(**{'white-space': 'pre-wrap', 'text-align': 'left'}))
        print("\n" + "-"*60)
        
        print(f"🔮 3. [⚠️ TARGET BLUEPRINT RUJUKAN] Tinjau Struktur yang Benar pada DB_FUTURE di bawah:")
        if pkg['df_struct_future'].empty:
            print("❌ ERROR: Tabel ini tidak ditemukan / belum dibuat sama sekali di DB_FUTURE!")
        else:
            display(pkg['df_struct_future'].style.set_properties(**{'white-space': 'pre-wrap', 'text-align': 'left'}))
        print("\n" + "-"*60)
        
        print(f"📸 4. Sampel Isi Data Real di DB_NEW:")
        display(pkg['df_real_data'] if pkg['df_real_data'].empty else pkg['df_real_data'])
        print("\n" + "="*80)

# ✨ 2. KELOMPOK KEDUA (BAW AH): DAFTAR TABEL YANG SUDAH AMAN IDENTIK ✨
if identical_tables_queue:
    print("\n" + "="*80)
    print(f"✨ [🟢 PERFECTLY MATCHED BOARD] SEBANYAK {len(identical_tables_queue)} TABEL STRUKTURNYA SUDAH IDENTIK SAMA PERSIS!")
    print("="*80)
    
    for pkg in identical_tables_queue:
        print(f"\n================================================================================")
        print(f"✅ [STATUS: AMAN IDENTIK] TABEL: {pkg['name'].upper()}")
        print(f"================================================================================")
        
        print(f"📋 1. Karakteristik Wadah Pandas Dataframe (.info()):")
        pkg['df_real_data'].info()
        print("\n" + "-"*60)
        
        print(f"🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:")
        display(pkg['df_struct_new'].style.set_properties(**{'white-space': 'pre-wrap', 'text-align': 'left'}))
        print("\n" + "-"*60)
        
        print("✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨")
        print("ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.")
        print("\n" + "-"*60)
        
        print(f"📸 3. Sampel Isi Data Real di DB_NEW:")
        display(pkg['df_real_data'] if pkg['df_real_data'].empty else pkg['df_real_data'])
        print("\n" + "="*80)

================================================================================
 🕵️‍♂️ FORENSIK ARSITEKTUR KONTROL: DETEKTOR AUTO-SMART COMPILER (REVISI PRIORITY) 🕵️‍♂️
================================================================================

================================================================================
✨ [🟢 PERFECTLY MATCHED BOARD] SEBANYAK 25 TABEL STRUKTURNYA SUDAH IDENTIK SAMA PERSIS!
================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: KONTAK_PROSPEK
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id_kontak_prospek        194 non-null    int64
 1   kode_kontak              194 non-null    object
 2   nama_penanya             194 non-null    object
 3   nomor_telepon            194 non-null    object
 4   email                    163 non-null    object
 5   sumber_informasi         165 non-null    object
 6   catatan_awal_fo          0 non-null      object
 7   id_admin_fo              0 non-null      object
 8   status_kontak            194 non-null    object
 9   tanggal_kontak_pertama   0 non-null      object
 10  tanggal_kontak_terakhir  65 non-null     datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(9)
memory usage: 16.8+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

,id_kontak_prospek,kode_kontak,nama_penanya,nomor_telepon,email,sumber_informasi,catatan_awal_fo,id_admin_fo,status_kontak,tanggal_kontak_pertama,tanggal_kontak_terakhir
0,1,PQ8WD1T7,Daria Azmiya Jasmine,082231346758,puterihapsari.f@gmail.com,Teman/kerabat/saudara,None,None,1,None,2025-09-18 17:39:40
1,2,FRX3MYBA,Annisa Zahro Ramadhania,081336647476,dwirohm4@gmail.com,Instagram,None,None,1,None,2025-09-23 16:25:14
2,3,8SZ2FCXU,Zulfa Bariatur Rahma,085707179656,chyzryth@gmail.com,Lainnya,None,None,1,None,2025-10-03 09:48:34
3,4,V4LATPWN,Achmad Naufal Albiruni,087765283592,melisnifuku@gmail.com,Instagram,None,None,1,None,2025-10-03 09:49:15
4,5,D81NEPDX,Khansa Amalia Putri Aji,081554932188,afadhilpa@gmail.com,Teman/kerabat/saudara,None,None,0,None,2025-10-03 09:48:50
...,...,...,...,...,...,...,...,...,...,...,...
189,190,ROLGGUVW,Atiya Sabita,,None,None,None,None,waiting for confirmation,None,2025-10-17 15:41:09
190,191,KIUULWZE,Dwi,,None,None,None,None,follow up another time,None,2025-10-17 15:41:26
191,192,5PBZSF6H,Aca,,None,None,None,None,follow up another time,None,2025-10-24 15:27:54
192,193,OHGUROZF,Bu Hartik,,None,None,None,None,waiting for confirmation,None,2025-10-24 15:28:21
193,194,RPMZWN17,Fenita,,None,None,None,None,follow up another time,None,2025-10-24 15:28:41

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: CALON_SISWA
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160 entries, 0 to 159
Data columns (total 34 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id_calon              160 non-null    int64
 1   kode_unik             160 non-null    object
 2   nama_lengkap          157 non-null    object
 3   id_kontak_prospek     160 non-null    int64
 4   nama_panggilan        159 non-null    object
 5   jenis_kelamin         107 non-null    object
 6   tempat_lahir          0 non-null      object
 7   tanggal_lahir         0 non-null      object
 8   kewarganegaraan       159 non-null    object
 9   email                 157 non-null    object
 10  agama                 0 non-null      object
 11  nama_kontak_awal      7 non-null      object
 12  wa_kontak_awal        35 non-null     object
 13  id_provinsi           157 non-null    float64
 14  id_kabupaten          109 non-null    float64
 15  id_kecamatan          0 non-null      object
 16  id_kelurahan          0 non-null      object
 17  alamat_lengkap        0 non-null      object
 18  wa_siswa              7 non-null      object
 19  wa_ortu               153 non-null    object
 20  wa_administrasi       0 non-null      object
 21  assigned_fo           0 non-null      object
 22  assigned_akademik     0 non-null      object
 23  catatan_awal_fo       0 non-null      object
 24  fo_status             160 non-null    object
 25  fo_status_updated_at  0 non-null      object
 26  handover_at           0 non-null      object
 27  link_form_sent_at     0 non-null      object
 28  form_completed_at     0 non-null      object
 29  first_submitted_at    0 non-null      object
 30  latest_submitted_at   0 non-null      object
 31  deleted_at            0 non-null      object
 32  created_at            0 non-null      object
 33  updated_at            35 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(2), object(29)
memory usage: 42.6+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

,id_calon,kode_unik,nama_lengkap,id_kontak_prospek,nama_panggilan,jenis_kelamin,tempat_lahir,tanggal_lahir,kewarganegaraan,email,...,fo_status,fo_status_updated_at,handover_at,link_form_sent_at,form_completed_at,first_submitted_at,latest_submitted_at,deleted_at,created_at,updated_at
0,1,PQ8WD1T7,Daria Azmiya Jasmine,1,Daria,Perempuan,None,None,Indonesia,puterihapsari.f@gmail.com,...,1,None,None,None,None,None,None,None,None,2025-09-18 17:39:40
1,2,FRX3MYBA,Annisa Zahro Ramadhania,2,Annisa,Perempuan,None,None,Indonesia,dwirohm4@gmail.com,...,1,None,None,None,None,None,None,None,None,2025-09-23 16:25:14
2,3,8SZ2FCXU,Zulfa Bariatur Rahma,3,Zulfa,Perempuan,None,None,Indonesia,chyzryth@gmail.com,...,1,None,None,None,None,None,None,None,None,2025-10-03 09:48:34
3,4,V4LATPWN,Achmad Naufal Albiruni,4,Albi,None,None,None,Indonesia,melisnifuku@gmail.com,...,1,None,None,None,None,None,None,None,None,2025-10-03 09:49:15
4,5,D81NEPDX,Khansa Amalia Putri Aji,5,Khansa,Perempuan,None,None,Indonesia,afadhilpa@gmail.com,...,0,None,None,None,None,None,None,None,None,2025-10-03 09:48:50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,162,G0A5JYMU,Antonius Miguel Kurniawan,162,Miguel,None,None,None,Indonesia,adeodatus.kurniawan@gmail.com,...,0,None,None,None,None,None,None,None,None,NaT
156,163,6MF0GWLP,Tisha kayla janitra,163,Tisha,Perempuan,None,None,Indonesia,nroskalindha18@gmail.com,...,1,None,None,None,None,None,None,None,None,NaT
157,164,389YW93Z,Clariza Arifianti,164,Clara,Perempuan,None,None,Indonesia,clarizarisa3@gmail.com,...,0,None,None,None,None,None,None,None,None,NaT
158,165,V6W8SC8A,Shaqila Anindra Dzakira,165,Shaqila,Perempuan,None,None,Indonesia,shaqilaanindra@gmail.com,...,1,None,None,None,None,None,None,None,None,NaT
159,166,W41FGJX5,Mega Dewi,166,Mega,Perempuan,None,None,Indonesia,megads286@gmail.com,...,0,None,None,None,None,None,None,None,None,NaT

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: CALON_SISWA_AKADEMIK
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id_calon_akademik          158 non-null    int64
 1   id_calon                   158 non-null    int64
 2   nama_sekolah               95 non-null     object
 3   jenjang_kelas_1            7 non-null      object
 4   jenjang_kelas_2            6 non-null      object
 5   kurikulum_sekolah          92 non-null     object
 6   id_kursus                  158 non-null    object
 7   id_periode                 0 non-null      object
 8   id_level                   0 non-null      object
 9   submission_state           158 non-null    object
 10  preferensi_metode_belajar  0 non-null      object
 11  riwayat_les                6 non-null      object
 12  kesulitan_belajar          4 non-null      object
 13  kegiatan_sekarang          60 non-null     object
 14  kegiatan_lainnya           9 non-null      object
 15  kemampuan_officeApp        7 non-null      object
 16  kemampuan_editing          0 non-null      object
 17  kemampuan_kustom           0 non-null      object
 18  kemampuan_komputer         6 non-null      object
 19  kemampuan_software         7 non-null      object
 20  penggunaan_gadget          6 non-null      object
 21  sumber_info                157 non-null    object
 22  referensi                  1 non-null      object
 23  alasan_daftar              112 non-null    object
 24  alasan_program             0 non-null      object
 25  harapan_program            6 non-null      object
 26  lampiran_file              1 non-null      object
 27  submitted_at               0 non-null      object
dtypes: int64(2), object(26)
memory usage: 34.7+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

,id_calon_akademik,id_calon,nama_sekolah,jenjang_kelas_1,jenjang_kelas_2,kurikulum_sekolah,id_kursus,id_periode,id_level,submission_state,...,kemampuan_komputer,kemampuan_software,penggunaan_gadget,sumber_info,referensi,alasan_daftar,alasan_program,harapan_program,lampiran_file,submitted_at
0,1,1,TK Al Maghfirah,TK,B,NASIONAL,K00010,None,None,draft,...,None,None,None,Teman/kerabat/saudara,None,None,None,None,None,None
1,2,2,SD Khadijah Wonorejo,SD,3,CAMBRIDGE,K00010,None,None,draft,...,None,None,None,Instagram,None,supaya lebih paham bhs Inggris,None,None,None,None
2,3,3,SMAN 17 Surabaya,SMA/SMK,10,NASIONAL,K00014,None,None,draft,...,sudah pernah,Acode,"Handphone,Laptop",Lainnya,None,UPSKILLING,None,None,None,None
3,4,4,SD Khadijah Wonorejo,SD,5,CAMBRIDGE,K00010,None,None,draft,...,None,None,None,Instagram,None,None,None,None,None,None
4,5,5,SMAN 17 Surabaya,SMA/SMK,11,NASIONAL,K00010,None,None,draft,...,None,None,None,Teman/kerabat/saudara,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,162,162,SD Kartika Nasional Plus,None,None,NASIONAL,K00010,None,None,draft,...,None,None,None,Teman/kerabat/saudara,None,None,None,None,None,None
154,163,163,Tk al fajar,None,None,NASIONAL,K00010,None,None,draft,...,None,None,None,Teman/kerabat/saudara,None,None,None,None,None,None
155,164,164,None,None,None,None,K00004,None,None,draft,...,None,None,None,Website,None,Untuk menambah skill dalam berbahasa inggris,None,None,None,None
156,165,165,SDIT Ghilmani Surabaya,None,None,NASIONAL,K00010,None,None,draft,...,None,None,None,Instagram,None,None,None,None,None,None
157,166,166,None,None,None,None,K00004,None,None,draft,...,None,None,None,Tiktok,None,coba gratis,None,None,None,None

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: CALON_SISWA_ORTU
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 166 entries, 0 to 165
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_calon_ortu       166 non-null    int64
 1   id_calon            166 non-null    int64
 2   nama_ayah           0 non-null      object
 3   pekerjaan_ayah      0 non-null      object
 4   pendidikan_ayah     0 non-null      object
 5   penghasilan_ayah    0 non-null      object
 6   tempat_lahir_ayah   166 non-null    object
 7   tanggal_lahir_ayah  0 non-null      object
 8   nama_ibu            0 non-null      object
 9   pekerjaan_ibu       0 non-null      object
 10  pendidikan_ibu      0 non-null      object
 11  penghasilan_ibu     0 non-null      object
 12  tempat_lahir_ibu    0 non-null      object
 13  tanggal_lahir_ibu   0 non-null      object
 14  nama_wali           0 non-null      object
 15  pekerjaan_wali      0 non-null      object
 16  pendidikan_wali     0 non-null      object
 17  penghasilan_wali    0 non-null      object
 18  tempat_lahir_wali   0 non-null      object
 19  tanggal_lahir_wali  0 non-null      object
dtypes: int64(2), object(18)
memory usage: 26.1+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

,id_calon_ortu,id_calon,nama_ayah,pekerjaan_ayah,pendidikan_ayah,penghasilan_ayah,tempat_lahir_ayah,tanggal_lahir_ayah,nama_ibu,pekerjaan_ibu,pendidikan_ibu,penghasilan_ibu,tempat_lahir_ibu,tanggal_lahir_ibu,nama_wali,pekerjaan_wali,pendidikan_wali,penghasilan_wali,tempat_lahir_wali,tanggal_lahir_wali
0,1,1,None,None,None,None,,None,None,None,None,None,None,None,None,None,None,None,None,None
1,2,2,None,None,None,None,,None,None,None,None,None,None,None,None,None,None,None,None,None
2,3,3,None,None,None,None,,None,None,None,None,None,None,None,None,None,None,None,None,None
3,4,4,None,None,None,None,,None,None,None,None,None,None,None,None,None,None,None,None,None
4,5,5,None,None,None,None,,None,None,None,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,162,162,None,None,None,None,,None,None,None,None,None,None,None,None,None,None,None,None,None
162,163,163,None,None,None,None,,None,None,None,None,None,None,None,None,None,None,None,None,None
163,164,164,None,None,None,None,,None,None,None,None,None,None,None,None,None,None,None,None,None
164,165,165,None,None,None,None,,None,None,None,None,None,None,None,None,None,None,None,None,None
165,166,166,None,None,None,None,,None,None,None,None,None,None,None,None,None,None,None,None,None

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: CALON_SISWA_BAYAR
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 166 entries, 0 to 165
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id_calon_bayar            166 non-null    int64
 1   id_calon_akademik         166 non-null    int64
 2   nomor_invoice             0 non-null      object
 3   bank_pembayaran           62 non-null     object
 4   tanggal_konfirmasi_bayar  0 non-null      object
 5   bulan_mulai_belajar       65 non-null     object
 6   lokasi_belajar            71 non-null     object
dtypes: int64(2), object(5)
memory usage: 9.2+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

,id_calon_bayar,id_calon_akademik,nomor_invoice,bank_pembayaran,tanggal_konfirmasi_bayar,bulan_mulai_belajar,lokasi_belajar
0,1,1,None,Mandiri,None,September,Sby
1,2,2,None,Mandiri,None,September,Sby
2,3,3,None,None,None,None,None
3,4,4,None,None,None,None,None
4,5,5,None,Mandiri,None,September,Sby
...,...,...,...,...,...,...,...
161,162,162,None,None,None,None,None
162,163,163,None,None,None,None,None
163,164,164,None,None,None,None,None
164,165,165,None,None,None,None,None
165,166,166,None,None,None,None,None

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: CALON_SISWA_JADWAL
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 166 entries, 0 to 165
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_calon_jadwal      166 non-null    int64
 1   id_calon_akademik    166 non-null    int64
 2   tanggal_kontak_awal  9 non-null      object
 3   tanggal_wawancara    4 non-null      object
 4   tanggal_pembayaran   0 non-null      object
 5   tanggal_masuk        5 non-null      object
 6   tanggal_keluar       0 non-null      object
dtypes: int64(2), object(5)
memory usage: 9.2+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

,id_calon_jadwal,id_calon_akademik,tanggal_kontak_awal,tanggal_wawancara,tanggal_pembayaran,tanggal_masuk,tanggal_keluar
0,1,1,2025-09-15,None,None,2025-09-24,None
1,2,2,2025-09-16,2025-09-16,None,2025-09-25,None
2,3,3,2025-09-16,None,None,None,None
3,4,4,2025-09-17,2025-09-17,None,2025-09-25,None
4,5,5,2025-09-15,2025-09-18,None,None,None
...,...,...,...,...,...,...,...
161,162,162,None,None,None,None,None
162,163,163,None,None,None,None,None
163,164,164,None,None,None,None,None
164,165,165,None,None,None,None,None
165,166,166,None,None,None,None,None

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: CALON_SISWA_KURSUS
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 166 entries, 0 to 165
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_calon_kursus  166 non-null    int64
 1   id_calon         166 non-null    int64
 2   urutan           166 non-null    int64
 3   nama_kursus      166 non-null    object
 4   jenis_program    166 non-null    object
dtypes: int64(3), object(2)
memory usage: 6.6+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

     id_calon_kursus  id_calon  urutan nama_kursus jenis_program
0                  1         1       1     English
1                  2         2       1     English
2                  3         3       1     Digital
3                  4         4       1     English
4                  5         5       1     English
..               ...       ...     ...         ...           ...
161              162       162       1
162              163       163       1
163              164       164       1
164              165       165       1
165              166       166       1

[166 rows x 5 columns]

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: CALON_SISWA_PROSES
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 27 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id_calon_siswa_proses    156 non-null    int64
 1   id_calon_akademik        156 non-null    int64
 2   admin_pengontak          7 non-null      object
 3   penanggung_jawab         0 non-null      object
 4   jenis_trial              0 non-null      object
 5   hasil_trial              0 non-null      object
 6   waktu_trial_1            71 non-null     timedelta64[ns]
 7   waktu_trial_2            71 non-null     timedelta64[ns]
 8   tanggal_trial            0 non-null      object
 9   laporan_trial            1 non-null      object
 10  placement_trial          0 non-null      object
 11  lokasi_trial             10 non-null     object
 12  sumber_lead              0 non-null      object
 13  status_pipeline          156 non-null    object
 14  status_updated_at        0 non-null      object
 15  status_diterima          156 non-null    int64
 16  status_form_pendaftaran  156 non-null    int64
 17  hasil_penempatan         1 non-null      object
 18  followup_1               1 non-null      datetime64[ns]
 19  followup_2               1 non-null      datetime64[ns]
 20  followup_3               0 non-null      object
 21  akun_leapverse           0 non-null      object
 22  wa_grup_leapverse        0 non-null      object
 23  catatan_admin            0 non-null      object
 24  catatan_penting          0 non-null      object
 25  keterangan_tambahan      0 non-null      object
 26  detail_lainnya           3 non-null      object
dtypes: datetime64[ns](2), int64(4), object(19), timedelta64[ns](2)
memory usage: 33.0+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

,id_calon_siswa_proses,id_calon_akademik,admin_pengontak,penanggung_jawab,jenis_trial,hasil_trial,waktu_trial_1,waktu_trial_2,tanggal_trial,laporan_trial,...,hasil_penempatan,followup_1,followup_2,followup_3,akun_leapverse,wa_grup_leapverse,catatan_admin,catatan_penting,keterangan_tambahan,detail_lainnya
0,1,1,Ibu Sari,None,None,None,0 days 00:00:00,0 days,None,None,...,21 BALLOONS SR1 (QORIN),NaT,NaT,None,None,None,None,None,None,None
1,2,2,Bu Dwi,None,None,None,0 days 15:45:00,0 days,None,None,...,None,NaT,NaT,None,None,None,None,None,None,None
2,3,3,Ibu Fitri,None,None,None,0 days 00:00:00,0 days,None,None,...,None,NaT,NaT,None,None,None,None,None,None,None
3,4,4,Bu Lita,None,None,None,NaT,NaT,None,None,...,None,NaT,NaT,None,None,None,None,None,None,None
4,5,5,Ibu Fadhil,None,None,None,0 days 00:00:00,0 days,None,None,...,None,NaT,NaT,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,162,162,None,None,None,None,NaT,NaT,None,None,...,None,NaT,NaT,None,None,None,None,None,None,None
152,163,163,None,None,None,None,NaT,NaT,None,None,...,None,NaT,NaT,None,None,None,None,None,None,None
153,164,164,None,None,None,None,NaT,NaT,None,None,...,None,NaT,NaT,None,None,None,None,None,None,None
154,165,165,None,None,None,None,NaT,NaT,None,None,...,None,NaT,NaT,None,None,None,None,None,None,None
155,166,166,None,None,None,None,NaT,NaT,None,None,...,None,NaT,NaT,None,None,None,None,None,None,None

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: CALON_SISWA_STATUS_LOGS
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 0 non-null      object
 1   id_calon           0 non-null      object
 2   status_sebelumnya  0 non-null      object
 3   status_baru        0 non-null      object
 4   diubah_oleh        0 non-null      object
 5   catatan            0 non-null      object
 6   waktu_perubahan    0 non-null      object
 7   created_at         0 non-null      object
 8   updated_at         0 non-null      object
dtypes: object(9)
memory usage: 132.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

Empty DataFrame
Columns: [id, id_calon, status_sebelumnya, status_baru, diubah_oleh, catatan, waktu_perubahan, created_at, updated_at]
Index: []

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: PEMINJAMAN
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_pinjam        194 non-null    int64
 1   tanggal_pinjam   194 non-null    datetime64[ns]
 2   keperluan        194 non-null    object
 3   id_user          194 non-null    object
 4   status_pinjam    194 non-null    object
 5   catatan_sarpras  194 non-null    object
 6   created_at       194 non-null    datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(4)
memory usage: 10.7+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

,id_pinjam,tanggal_pinjam,keperluan,id_user,status_pinjam,catatan_sarpras,created_at
0,2,2023-06-11,<p>pinjam kamera - fun class tk mitra - 1 - 11...,U00026,Diajukan,,2023-06-12 13:20:39
1,3,2023-06-11,<p>1. kamera - fun class TK mitra - 1 - 11 Jun...,U00026,Diajukan,,2023-06-12 13:21:35
2,5,2023-08-21,<p>1. Tablet Leap - 1 - Jaga-jaga untuk Mid Te...,U00026,Diajukan,,2023-08-16 15:01:55
3,6,2023-08-23,<p>Pinjam kamera untuk rekaman video checklist...,U00033,Diajukan,,2023-08-23 10:19:12
4,7,2023-10-11,<p>1. Tablet Leap - 1 - Jaga-jaga untuk Final ...,U00026,Diajukan,,2023-10-10 15:30:53
...,...,...,...,...,...,...,...
189,192,2026-04-10,"<p><span style=""color: #212529; font-family: R...",U00060,Diajukan,<p>Sudah dikembalikan</p>,2026-04-09 11:40:52
190,193,2026-04-10,"<p><span style=""color: #212529; font-family: R...",U00041,Diajukan,,2026-04-10 16:26:19
191,194,2026-04-17,<p>List Peminjaman barang kegiatan student app...,U00060,Diajukan,,2026-04-15 16:06:08
192,195,2026-04-17,"<p><span style=""color: #212529; font-family: R...",U00060,Diajukan,,2026-04-16 15:22:28
193,196,2026-04-17,"<p><span style=""color: #212529; font-family: R...",U00041,Diajukan,,2026-04-17 16:22:59

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: PENGADAAN
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_pengadaan       110 non-null    int64
 1   deskripsi          110 non-null    object
 2   url_produk         110 non-null    object
 3   id_user            110 non-null    object
 4   status_pengajuan   110 non-null    object
 5   catatan_admin      110 non-null    object
 6   tanggal_pengajuan  110 non-null    datetime64[ns]
 7   tanggal_selesai    110 non-null    datetime64[ns]
 8   url_pembelian      108 non-null    object
dtypes: datetime64[ns](2), int64(1), object(6)
memory usage: 7.9+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

,id_pengadaan,deskripsi,url_produk,id_user,status_pengajuan,catatan_admin,tanggal_pengajuan,tanggal_selesai,url_pembelian
0,18,"<p><span style=""font-family: Arial; font-size:...",https://docs.google.com/spreadsheets/d/1B0sVeV...,U00012,Diajukan,,2023-07-06 11:14:15,2026-05-30 22:42:04,https://docs.google.com/spreadsheets/d/15Xuh2Z...
1,20,"<p>""KABEL TELEPON</p>\r\n<p>kabel roset telepo...",https://docs.google.com/spreadsheets/d/1B0sVeV...,U00012,Diajukan,,2023-08-03 09:36:19,2026-05-30 22:42:04,https://docs.google.com/spreadsheets/d/15Xuh2Z...
2,21,<p>15 pcs Sarung kursi untuk Lab Komputer (10 ...,https://docs.google.com/spreadsheets/d/1Onr3rr...,U00001,Diajukan,,2023-08-22 09:58:34,2026-05-30 22:42:04,https://docs.google.com/spreadsheets/d/15Xuh2Z...
3,22,<p>Pembelian 48 pcs Landyard</p>,https://docs.google.com/spreadsheets/d/1Onr3rr...,U00001,Diajukan,,2023-08-22 10:42:37,2026-05-30 22:42:04,https://docs.google.com/spreadsheets/d/15Xuh2Z...
4,23,"<p>1 ""HEADPHONE JACK</p>\n<p>MBOISGET - PREMIU...",https://docs.google.com/spreadsheets/d/1B0sVeV...,U00012,Diajukan,,2023-08-28 16:03:09,2023-09-10 00:00:00,https://docs.google.com/spreadsheets/d/15Xuh2Z...
...,...,...,...,...,...,...,...,...,...
105,124,"<p><img src=""data:image/png;base64,iVBORw0KGgo...",https://docs.google.com/spreadsheets/d/1pYJ0oJ...,U00043,Diajukan,,2026-03-02 16:23:47,2026-05-30 22:42:04,https://docs.google.com/spreadsheets/d/15Xuh2Z...
106,125,"<p><img src=""data:image/png;base64,iVBORw0KGgo...",https://docs.google.com/spreadsheets/d/1pYJ0oJ...,U00043,Diajukan,,2026-03-09 11:43:19,2026-05-30 22:42:04,https://docs.google.com/spreadsheets/d/15Xuh2Z...
107,126,"<p><img src=""data:image/png;base64,iVBORw0KGgo...",https://docs.google.com/spreadsheets/d/1pYJ0oJ...,U00043,Diajukan,,2026-03-30 17:40:43,2026-05-30 22:42:04,https://docs.google.com/spreadsheets/d/15Xuh2Z...
108,127,"<p><img src=""data:image/png;base64,iVBORw0KGgo...",https://docs.google.com/spreadsheets/d/1pYJ0oJ...,U00043,Diajukan,,2026-03-31 10:45:15,2026-05-30 22:42:04,https://docs.google.com/spreadsheets/d/15Xuh2Z...
109,128,"<p><img src=""data:image/png;base64,iVBORw0KGgo...",https://docs.google.com/spreadsheets/d/1pYJ0oJ...,U00043,Diajukan,,2026-04-01 15:32:25,2026-05-30 22:42:04,https://docs.google.com/spreadsheets/d/15Xuh2Z...

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: PROBLEM
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160 entries, 0 to 159
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_problem        160 non-null    int64
 1   detail_masalah    160 non-null    object
 2   id_user           160 non-null    object
 3   status_perbaikan  160 non-null    object
 4   tanggal_lapor     160 non-null    datetime64[ns]
 5   tanggal_selesai   160 non-null    datetime64[ns]
 6   catatan_teknisi   160 non-null    object
 7   gambar_problem    160 non-null    object
dtypes: datetime64[ns](2), int64(1), object(5)
memory usage: 10.1+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

,id_problem,detail_masalah,id_user,status_perbaikan,tanggal_lapor,tanggal_selesai,catatan_teknisi,gambar_problem
0,43,AC Kelas Miss Erika kurang dingin ( belakang,U00012,Diajukan,2023-06-28 16:07:52,2026-05-30 22:42:04,"sudah info ke Pak Irawan,\r\nTukang AC masih l...",
1,58,Boya/mic untuk kelas hybrid tidak berfungsi (,U00026,Diajukan,2023-07-06 10:45:03,2023-07-17 00:00:00,,
2,60,tegangan listrik di ruang kelas belakang dapur...,U00033,Diajukan,2023-07-13 16:59:57,2023-08-10 00:00:00,pemberian stabilizer,
3,61,ac brisik,U00033,Diajukan,2023-07-14 09:24:29,2023-07-25 00:00:00,sudah tidak berisik,
4,62,Kabel power monitor PC room 2 longgar. Saat me...,U00036,Diajukan,2023-07-17 15:04:01,2023-07-17 00:00:00,,
...,...,...,...,...,...,...,...,...
155,251,"AC room 6 tidak dingin, dan ada air menetes da...",U00050,Diajukan,2026-04-08 16:55:36,2026-04-13 00:00:00,,
156,252,AC Ruang 6 (miss Peni) kondisi saat ini di OFF...,U00020,Diajukan,2026-04-09 16:31:44,2026-04-13 00:00:00,AC sudah diperbaiki,/storage/sarpas_images/sarpas_69d772008efe9.jpeg
157,253,Sesi 3. Hybrid. Guru menggunakan mic unt hybri...,U00026,Diajukan,2026-04-13 19:02:53,2026-04-15 00:00:00,,/storage/sarpas_images/sarpas_69dcdb6dd7663.jpg
158,254,"Bracket TV kurang kenceng, suka geser kedepan ...",U00019,Diajukan,2026-04-16 16:58:21,2026-04-17 00:00:00,,
159,255,Baut kursi luluk copot,U00016,Diajukan,2026-04-17 13:14:29,2026-04-17 00:00:00,,/storage/sarpas_images/sarpas_69e1cfc5c079c.jpg

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: SOP
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_sop            4 non-null      int64
 1   id_sop_kategori   4 non-null      int64
 2   judul_sop         4 non-null      object
 3   link_dokumen_sop  4 non-null      object
 4   created_at        4 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(2), object(2)
memory usage: 292.0+ bytes

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

,id_sop,id_sop_kategori,judul_sop,link_dokumen_sop,created_at
0,1,1,Akhir Penggunaan Kelas English (19.15 WIB),https://drive.google.com/file/d/1V0MpB7ctzPHe6...,2023-07-07 08:52:48
1,2,2,Penerimaan Surat Masuk,https://drive.google.com/file/d/1G8lO33yU7MufC...,2023-11-22 15:27:06
2,3,2,Pengajuan Surat Keluar,https://drive.google.com/file/d/14I7wYSk62WJAv...,2023-11-22 15:27:55
3,4,2,Pengajuan Surat Tugas,https://drive.google.com/file/d/1R-wKFqQeVSz62...,2023-11-22 15:28:27

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: SURAT_KELUAR
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 213 entries, 0 to 212
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_sk            213 non-null    int64
 1   id_user          213 non-null    object
 2   keterangan_sk    213 non-null    object
 3   link_dokumen_sk  213 non-null    object
 4   status_sk        213 non-null    object
 5   nomor_sk         213 non-null    object
 6   catatan_sk       213 non-null    object
 7   created_at       213 non-null    datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(6)
memory usage: 13.4+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

,id_sk,id_user,keterangan_sk,link_dokumen_sk,status_sk,nomor_sk,catatan_sk,created_at
0,24,U00011,Surat Permohonan Uji Kompetensi dan Penggunaan...,https://docs.google.com/document/d/1xyhc4T-FlR...,Sudah Revisi,090A/LEAP/IX/2023- 090B/LEAP/IX/2023,Lengkapi Tanggal Pelaksanaan dengan tanggal ya...,2023-09-11 17:57:49
1,26,U00011,Beasiswa Siswa GE,https://docs.google.com/document/d/1jMTK_3b57e...,Disetujui,101/LEAP/BD/X/2023,,2023-10-25 16:57:38
2,27,U00011,PERJANJIAN KERJASAMA / MEMORANDUM OF UNDERSTAN...,https://docs.google.com/document/d/1Edeb7hWaBq...,Disetujui,102/LEAP/BD/X/2023,,2023-10-26 17:37:59
3,28,U00026,Sertifikat / Sertifikat Kelas APK Private / 1 ...,https://drive.google.com/drive/folders/1JMrPJF...,Disetujui,Sertif 002a/APEX/XI/2324/02 (Page 1) dan 002b/...,,2023-11-10 16:10:04
4,29,U00011,Penawaran Pelatihan Business English ke PT. La...,https://docs.google.com/document/d/1wBK62noEJw...,Disetujui,105/LEAP/BD/XI/2023,,2023-11-13 15:41:58
...,...,...,...,...,...,...,...,...
208,248,U00016,Jurnal Siswa & Laporan Akhir Community Service...,https://docs.google.com/document/d/1QJOQCHDN3j...,Disetujui,,,2026-04-07 14:44:54
209,250,U00033,Pelaporan Hasil Ujian Susulan Semester Genap K...,https://drive.google.com/file/d/14MFeTQ6SsupYk...,Disetujui,042/PDDK/SKET/LEAP/IV/2026,,2026-04-14 13:51:55
210,251,U00023,MoM Rupin (Mid Semester Evaluation & Next Batc...,https://docs.google.com/document/d/1s3G_jzBIlH...,Disetujui,043/PDDK/MoM/LEAP/IV/2026,,2026-04-16 08:51:31
211,252,U00034,Surat Izin Uji Coba Proyek SMPN 13,https://docs.google.com/document/d/14r8_bXEJjl...,Disetujui,046/PDDK/PM/LEAP/IV/2026,,2026-04-17 15:38:24
212,253,U00034,Surat Izin Uji Coba Proyek SMPN 35,https://docs.google.com/document/d/1tleVpLUO0j...,Disetujui,045/PDDK/PM/LEAP/IV/2026,,2026-04-17 16:01:39

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: VERIFIKASI_SURAT_KELUAR
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 477 entries, 0 to 476
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id_verifikasi_surat    477 non-null    int64
 1   id_sk                  442 non-null    float64
 2   status_verifikasi_sk   477 non-null    object
 3   catatan_verifikasi_sk  477 non-null    object
 4   created_at             477 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(1), object(2)
memory usage: 18.8+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

,id_verifikasi_surat,id_sk,status_verifikasi_sk,catatan_verifikasi_sk,created_at
0,1,NaN,,,2023-06-12 13:32:50
1,2,NaN,,,2023-06-12 13:33:07
2,3,NaN,,,2023-06-12 14:28:56
3,4,NaN,,,2023-06-30 15:30:35
4,5,NaN,,,2023-07-01 20:35:43
...,...,...,...,...,...
472,473,251.0,Disetujui,,2026-04-16 15:23:32
473,474,252.0,,,2026-04-17 15:38:24
474,475,253.0,,,2026-04-17 16:01:39
475,476,252.0,Disetujui,,2026-04-17 16:13:16
476,477,253.0,Disetujui,,2026-04-17 16:13:32

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: SURAT_TUGAS
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135 entries, 0 to 134
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_st               135 non-null    int64
 1   id_user             135 non-null    object
 2   acara               135 non-null    object
 3   undangan            135 non-null    object
 4   waktu_acara         135 non-null    datetime64[ns]
 5   lokasi_acara        135 non-null    object
 6   jenis_kegiatan      135 non-null    object
 7   status_st           135 non-null    object
 8   periode             0 non-null      object
 9   nomor_st            135 non-null    object
 10  catatan_st          135 non-null    object
 11  link_st             135 non-null    object
 12  link_laporan        135 non-null    object
 13  catatan_laporan     135 non-null    object
 14  keterangan_st       135 non-null    object
 15  catatan_pembatalan  135 non-null    object
 16  created_at          135 non-null    datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(14)
memory usage: 18.1+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

,id_st,id_user,acara,undangan,waktu_acara,lokasi_acara,jenis_kegiatan,status_st,periode,nomor_st,catatan_st,link_st,link_laporan,catatan_laporan,keterangan_st,catatan_pembatalan,created_at
0,20,U00015,Pertemuan rutin di bulan Juli 2023 forum Laras...,Larasdikdudi,2023-07-27,SMK Teknik PAL Surabaya Jalan Ujung Surabaya,Offline,Disetujui,None,023/LEAP/ST/VII/2023,,https://docs.google.com/document/d/1rILu6FE8Bd...,https://docs.google.com/document/d/1IAhWT4XjbX...,done/laporan sudah diisi,,,2023-07-25 09:56:19
1,21,U00015,Temu Warga RT 01 RW 08,Pengurus RT 01/ RW08,2023-08-23,Balai RW,Offline,Disetujui,None,024/LEAP/ST/VIII/2023,,https://docs.google.com/document/d/1OQxpdKYfDF...,https://docs.google.com/document/d/1XrvRmYckBw...,,,,2023-08-22 17:43:48
2,22,U00016,TEDxSurabaya Translators:\r\n\r\n1. Simulasi C...,TEDxSurabaya,2023-09-15,Topic: Connect to TEDxSurabaya Join Zoom Meeti...,Online,Disetujui,None,025/LEAP/ST/VIII/2023,,https://docs.google.com/document/d/10Zi6g0R9RR...,https://docs.google.com/document/d/1pa9G3E3eUa...,laporan kegiatan done,,,2023-09-13 13:01:52
3,23,U00015,Pertemuan Rutin Larasdikdudi bulan September 2023,https://drive.google.com/drive/u/3/folders/1OI...,2023-09-27,AULA SMK Negeri 2 Surabaya Jalan Tentara Genie...,Offline,Disetujui,None,028/LEAP/ST/IX/2023,,https://docs.google.com/document/d/1wMOD-N6oMQ...,https://docs.google.com/document/d/1xMv7AK2L9S...,done,,,2023-09-19 13:54:26
4,24,U00015,Sosialisasi Kerjasama LKP dan PKBM dengan Seme...,Dinas Pendidikan Kota Surabaya (bu Hilda),2023-09-20,"Tempat : Ruang Bung Tomo, Dinas Pendidikan Kot...",Offline,Disetujui,None,027/LEAP/ST/IX/2023,,https://docs.google.com/document/d/1LBx4WpqXcY...,https://docs.google.com/document/d/1jJdGMkonp_...,,,,2023-09-19 13:55:50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,163,U00016,TEDx,TEDx,2026-04-19,Surabaya Intercultural School. Jalan HR Muhammad,Offline,Disetujui,None,030/HR/ST/LEAP/III/2026,,https://docs.google.com/document/d/1yLNtt2uchj...,https://docs.google.com/document/d/1yoA9gDLRwT...,,,,2026-03-03 11:52:40
131,164,U00016,Supervisi Tengah Semester,Yayasan BSI - Banyuwangi,2026-04-10,Pesanggaran - Banyuwangi,Offline,Disetujui,None,039/HR/ST/LEAP/IV/2026,,https://docs.google.com/document/d/1ymoUqyKfLG...,https://docs.google.com/document/d/1ONn9G_Detj...,done,,,2026-04-06 10:49:15
132,165,U00016,Indonesia Youth Debate Summit,Sekolah Ciputra Surabaya,2026-04-23,"Ciputra Hall, Sekolah Ciputra Surabaya",Offline,Disetujui,None,040/HR/ST/LEAP/IV/2026,,https://docs.google.com/document/d/1CRncv0KVgX...,https://docs.google.com/document/d/1Z7RSXw0696...,,,,2026-04-08 12:56:00
133,166,U00016,Student Appreciation (Shining Beyond Limits) S...,SD Al Muslim,2026-04-18,Politeknik Pelayaran Surabaya,Offline,Disetujui,None,032/HR/ST/MIM/IV/2026,,https://docs.google.com/document/d/1Jfx39xH2pj...,https://docs.google.com/document/d/1lFTezKhCkA...,,,,2026-04-17 15:39:08
134,167,U00016,Student Appreciation (Shining Beyond Limits) S...,SD Al Muslim,2026-04-18,Politeknik Pelayaran Surabaya,Offline,Disetujui,None,044/HR/ST/LEAP/IV/2026,,https://docs.google.com/document/d/1PzlRtvydlt...,https://docs.google.com/document/d/1VCs1Bp7XeP...,,,,2026-04-17 16:01:07

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: SURAT_TUGAS_ANGGOTA
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_st_anggota  260 non-null    int64
 1   id_st          260 non-null    int64
 2   id_user        260 non-null    object
dtypes: int64(2), object(1)
memory usage: 6.2+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

     id_st_anggota  id_st id_user
0                1     20  U00023
1                2     21  U00043
2                3     22  U00016
3                4     23  U00023
4                5     24  U00014
..             ...    ...     ...
255            256    165  U00034
256            257    164  U00016
257            258    164  U00023
258            259    166  U00060
259            260    167  U00052

[260 rows x 3 columns]

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: PENGAJUAN_KARYAWAN
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_pengajuan  33 non-null     int64
 1   id_user       33 non-null     object
 2   posisi        33 non-null     object
 3   jumlah        33 non-null     int64
 4   syarat        33 non-null     object
 5   pertanyaan    33 non-null     object
 6   alur_seleksi  33 non-null     object
 7   daftar_tes    33 non-null     object
 8   status        33 non-null     object
 9   created_at    33 non-null     datetime64[ns]
dtypes: datetime64[ns](1), int64(2), object(7)
memory usage: 2.7+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

,id_pengajuan,id_user,posisi,jumlah,syarat,pertanyaan,alur_seleksi,daftar_tes,status,created_at
0,4,U00016,Part-Time Offline English Teacher,2,"<h5 class=""t-20 mb3"" style=""box-sizing: border...",<p>Info Jam Kerja dan Gaji :</p>\r\n<p>&nbsp;<...,<p>1. Mengisi form dan test melalui link: http...,<p>Mempersiapkan bahan micro teaching (MT) onl...,Diterima,2023-06-16 17:02:47
1,8,U00014,Magang Sales & Marketing,1,<p>1. Background pendidikan apa saja</p>\r\n<p...,<p>1. Komitmen kapan bisa mulai dan lama magan...,<p>1. Seleksi administrasi</p>\r\n<p>2. Probin...,<p>1. Buatlah desain poster sederhana program ...,Diterima,2023-07-04 13:52:25
2,10,U00014,Volunteer LeapXperience,1,<p>1. Mahasiswa dari berbagai jurusan (tingkat...,<p>1. Apakah bisa hadir offline ke Leap setiap...,<p>Seleksi Administrasi &amp; Skill :</p>\r\n<...,<p>Tes sudah terintegrasi dalam tahap administ...,Diterima,2023-07-18 10:11:14
3,11,U00012,Karyawan IT Support serta GA,1,<p>- Pendidikan minimal SMK atau Sarjana (S1) ...,<p>1. Berikan contoh pengalamanmu dalam menyel...,<p>Tahap 1: Pengumuman lowongan dan penerimaan...,<p>Pertanyaan ini mencakup 10 pertanyaan esai<...,Diterima,2023-07-18 11:24:24
4,12,U00016,Instruktur Aplikasi Perkantoran,2,"<p><span class=""selectable-text copyable-text""...","<p class=""selectable-text copyable-text iq0m55...",<p>Tahap 1: Pengumuman lowongan dan penerimaan...,<p>detail test menyusul dan didiskusikan</p>,Diterima,2023-07-18 16:36:22
5,13,U00012,Freelance Guru Coding Scratch,1,<p>1. Penguasaan bahasa pemrograman Scratch se...,<p>Apakah kamu bisa menjelaskan beberapa blok ...,"<p style=""box-sizing: border-box; margin-top: ...",<p>Waktu Tes (60 Menit)<br />Soal 1 :<br />Bua...,Diterima,2023-07-20 13:59:46
6,14,U00012,Part Time Teacher,1,<p>- Menjadi lulusan S1 atau sedang menempuh s...,<p>1. Bagaimana kamu akan menunjukkan semangat...,"<p><span style=""box-sizing: border-box; color:...","<p><span style=""color: #212529; font-family: R...",Diterima,2023-08-08 16:55:25
7,15,U00020,Freelance TK Mitra,3,<p>wanita</p>\r\n<p>mahasiswa/ lulusan S1 bhs ...,"<p dir=""ltr"" style=""line-height: 1.2; margin-t...",<p>1. probing</p>\r\n<p>2. isi form lamar</p>\...,<p>....</p>,Diterima,2023-08-28 14:40:03
8,16,U00014,Freelance Desainer Grafis Edtech Conference,1,<p>1. Background pendidikan tidak dibatasi</p>...,<p>1. Apa saja pengalaman dalam membuat desain...,<p>1. Seleksi Administrasi</p>\r\n<p>2. Probin...,<p>1. Membuat 1 desain poster promosi Leap sec...,Diterima,2023-09-21 15:40:36
9,17,U00014,Freelance Artikel (SEO),1,<p>1. All backgrounds</p>\r\n<p>2. Berpengalam...,<p>1. Sudah berpengalaman berapa lama menulis ...,<p>1. Probing</p>\r\n<p>2. Seleksi admininstra...,<p>1. Tulis 1 buah artikel maksimal 1000 kata ...,Diterima,2023-10-13 17:00:40
10,18,U00012,Magang IT untuk RGI,1,<p>Kemahiran Teknis:<br />- Penguasaan dalam p...,<p>1. Bisa jelaskan arsitektur aplikasi web ya...,"<div class=""col-md-3 text-muted"" style=""box-si...",<p>Sebuah perusahaan menghadapi kesulitan dala...,Diterima,2023-11-29 12:25:37
11,19,U00014,Freelance Sosial Media (TikTok),1,<p>1. Minim S1 dari berbagai jurusan (dipriori...,<p>1. Apakah sudah pernah membuat konten TikTo...,<p>1. Seleksi administrasi</p>\r\n<p>2. Probin...,<p>Seleksi Teknis :<br /><br /></p>\r\n<p>1. B...,Diterima,2023-12-21 13:33:03
12,20,U00012,Magang IT dan GA,1,<p>- Lolos Tes Skill dari leap</p>,"<p style=""color: #212529; font-family: Roboto,...","<p style=""color: #212529; font-family: Roboto,...","<p style=""color: #212529; font-family: Roboto,...",Diterima,2023-12-21 16:58:02
13,21,U00018,Administrasi,2,<p>0</p>,<p>0</p>,<p>&nbsp;0</p>,<p>0</p>,Diterima,2024-03-01 11:57:07
14,22,U00018,Asisten Tenaga Pelatih Prakerja,2,"<p><span style=""font-size: 14px;"">1. Secara sk...","<p><span style=""font-size: 14px;"">Berikut bebe...",<p>1. Probbing</p>\r\n<p>2. Wawancara</p>\r\n<...,<p>Tes skill zoom dan moderator</p>,Diterima,2024-04-19 16:49:32
15,23,U00016,Edge Tutor,2,<p>LatBel Akademik:<br />1. Gaze: S1 Arsitek</...,<p>none</p>,<p>none</p>,<p>none</p>,Diterima,2024-05-14 13:24:41
16,27,U00012,Magang Programmer (bank soal),2,<p>Keterampilan dan Pengalaman yang Diperlukan...,<p>Pertanyaan 1: Jelaskan arsitektur MVC (Mode...,<p>Tahap 1: Pengumuman lowongan dan penerimaan...,<p>PRAKTEK</p>\n<p>STUDI KASUS: Pengajuan Pema...,Diterima,2024-05-15 10:08:51
17,28,U00012,Freelance Website wordpress,1,<p>Keterampilan dan Pengalaman yang Diperlukan...,<p>1. Apa itu WordPress?<br />2. Apa itu Eleme...,"<p style=""box-sizing: border-box; margin-top: ...",<p>Pertanyaan analisa website</p>\r\n<p>1. Men...,Diterima,2024-05-15 11:40:51
18,29,U00014,Magang Tim Sosial Media,1,<p>Tidak ada syarat khusus asal bisa menggunak...,<p>Sama seperti standar perekrutan tim sosmed ...,<p>Sama seperti standar perekrutan tim sosmed ...,<p>Sama seperti standar perekrutan tim sosmed ...,Diterima,2024-05-15 16:57:00
19,30,U00014,Freelance SEO Article Writer,1,<p>1. Bebas dari berbagai backgrund pendidikan...,<p>1. Apakah sudah pernah menulis artikel SEO ...,<p>1. Seleksi admininstrasi</p>\r\n<p>2. Probi...,<p>1. Tuliskan alur kebiasaanmu dalam menulis ...,Diterima,2024-05-27 17:12:48
20,31,U00014,Asisten Guru LeapXperience,1,<p>1. Background pendidikan apa saja</p>\r\n<p...,<p>1. Jadwal kegiatan harian apakah memungkink...,<p>1. Seleksi administrasi</p>\r\n<p>2. Probin...,<p>Tes tulis :</p>\r\n<p>1. Cari tahu apa itu ...,Diajukan,2024-06-04 14:26:30
21,32,U00012,Magang LMS Leap,1,<p>- Menguasai bahasa pemrograman PHP dan Lara...,<ul>\r\n<li><br />1. Apakah kamu tahu mengenai...,"<div class=""col-md-3 text-muted"" style=""box-si...",<ol>\r\n<li>Buatlah CRUD pembelian kelas mengg...,Sudah Revisi,2024-08-02 11:22:12
22,33,U00012,Input Data Landing Page,1,<p>-</p>,<p>-</p>,<p>-</p>,<p>-</p>,Diterima,2024-08-05 11:02:07
23,34,U00023,Instruktur Videografi,1,<p>1. Memiliki pengalaman min. 3 tahun dalam b...,<p>1. Apakah pernah mengajar sebelumnya? Jika ...,<p>Tahap 1: Pengumuman lowongan dan penerimaan...,<p>1. Membuat video profesional mulai dari pen...,Diterima,2024-08-13 10:08:59
24,35,U00012,Magang IT RGI 2024,1,<ul>\r\n<li><strong>Pengetahuan Teknis</strong...,<p>1. Apa yang Anda ketahui tentang Framework ...,"<p style=""box-sizing: border-box; margin-top: ...",<p><strong>Deskripsi Tugas: </strong></p>\r\n<...,Diterima,2024-11-22 11:48:47
25,36,U00016,Part-Time Online Premium English Teacher,1,"<p>1. Memiliki sertifikat <strong data-start=""...",<p>none</p>,<p>none</p>,<p>none</p>,Sudah Revisi,2025-03-05 14:16:55
26,37,U00014,Staf divisi IT,1,<p>S1 Informatika atau Sistem Informasi</p>\r\...,<p>1. Aktivitas selama kuliah?&nbsp;</p>\r\n<p...,<p>1. Seleksi administrasi</p>\r\n<p>2. Seleks...,<p>Menyusul setelah tahu bahasa pemrograman ya...,Diterima,2025-05-21 09:52:06
27,39,U00016,Pengajar Full Time Coding & APK,2,<p>1. Diutamakan Jurusan Sistem Informasi dan ...,<p>Info Jam Kerja: <br />1. Senin - Kamis 10.1...,<p>1. Mengisi form dan test melalui link: http...,<p>-</p>,Diterima,2025-05-21 12:45:01
28,40,U00016,Freelance English Teacher,1,<p>xx</p>,<p>&nbsp;xx</p>,<p>&nbsp;xx</p>,<p>&nbsp;xx</p>,Diterima,2025-07-21 15:43:54
29,41,U00014,Staf Kemitraan B2B (Sales & Marketing B2B),1,<p>S1 (Jurusan Bebas)&nbsp;</p>\r\n<p>Mampu be...,<p>Pekerjaan apa saja yang kamu bayangkan akan...,<p>1. Seleksi administrasi</p>\r\n<p>2. Probbi...,<p>Detail tes skill:</p>\r\n<p>Durasi : 1 hari...,Diterima,2025-09-30 16:07:40
30,42,U00016,Freelance Native English Teacher,1,"<p><span style=""font-size: 14px;"">1. Memiliki ...",<p>x</p>,<p>&nbsp;x</p>,<p>&nbsp;x</p>,Diterima,2025-10-01 16:24:08
31,43,U00014,Magang IT RGI,1,<p>1. Jurusan bebas diutamakan punya pengalama...,<p>1. Apakah siap bekerja di kantor Leap minim...,<p>1. Seleksi administrasi</p>\r\n<p>2. Seleks...,<p>Tes skill potensi pengajar digital (1 hari)...,Diterima,2025-11-06 15:24:10
32,44,U00023,Guru ekskul coding SMA Al Muslim,1,<p>1. Diutamakan jurusan Sistem Informasi dan ...,"<ul>\r\n<li data-start=""92"" data-end=""146"">\r\...",<p>1. Mengisi form dan test melalui link: http...,"<p dir=""ltr"" style=""line-height: 1.79999999999...",Diajukan,2026-02-11 11:13:41

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: HISTORI_PENGAJUAN
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79 entries, 0 to 78
Data columns (total 5 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id_verifikasi                79 non-null     int64
 1   id_pengajuan                 79 non-null     int64
 2   status_verifikasi_pengajuan  79 non-null     object
 3   catatan                      38 non-null     object
 4   created_at                   79 non-null     datetime64[ns]
dtypes: datetime64[ns](1), int64(2), object(2)
memory usage: 3.2+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

,id_verifikasi,id_pengajuan,status_verifikasi_pengajuan,catatan,created_at
0,11,4,Diajukan,None,2023-06-16 17:02:47
1,16,8,Diajukan,None,2023-07-04 13:52:25
2,17,8,Diterima,"Mbak, mohon diinfokan untuk tes ini harus dila...",2023-07-04 14:13:49
3,23,10,Diajukan,None,2023-07-18 10:11:14
4,24,10,Revisi,"Mbak Laksmi, ini kemarin infonya dibutuhkan 2 ...",2023-07-18 10:21:19
...,...,...,...,...,...
74,100,43,Diajukan,None,2025-11-06 15:24:10
75,101,43,Revisi,,2025-11-06 15:41:54
76,102,43,Sudah Revisi,None,2025-11-06 15:42:26
77,103,43,Diterima,,2025-11-06 15:42:41
78,104,44,Diajukan,None,2026-02-11 11:13:41

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: PELAMAR
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 43 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_pelamar           128 non-null    int64
 1   id_pengajuan         51 non-null     float64
 2   email_pelamar        128 non-null    object
 3   nama_lengkap         128 non-null    object
 4   nama_panggilan       128 non-null    object
 5   jenis_kelamin        128 non-null    object
 6   tempat_lahir         128 non-null    object
 7   tanggal_lahir        29 non-null     object
 8   alamat_ktp           128 non-null    object
 9   alamat_domisili      128 non-null    object
 10  nomor_wa             128 non-null    object
 11  akun_linkedin        112 non-null    object
 12  akun_instagram       128 non-null    object
 13  akun_facebook        128 non-null    object
 14  sosmed_lain          128 non-null    object
 15  spesifikasi_laptop   128 non-null    object
 16  internet             128 non-null    object
 17  kegiatan_sekarang    128 non-null    object
 18  rencana_karir        128 non-null    object
 19  mobilitas            128 non-null    object
 20  sumber_info          128 non-null    object
 21  siap_wfo             128 non-null    object
 22  tanggal_bergabung    84 non-null     object
 23  kategori_pelamar     128 non-null    object
 24  riwayat_kerja        128 non-null    object
 25  riwayat_pendidikan   128 non-null    object
 26  pengalaman_bidang    128 non-null    object
 27  wawasan              128 non-null    object
 28  riwayat_kesehatan    128 non-null    object
 29  status_pernikahan    128 non-null    object
 30  kemampuan_ajar       128 non-null    object
 31  penguasaan_aplikasi  128 non-null    object
 32  aplikasi_lainnya     128 non-null    object
 33  penggunaan_laptop    128 non-null    object
 34  skor_toefl           128 non-null    int64
 35  ekspektasi_gaji      128 non-null    int64
 36  tautan_berkas        128 non-null    object
 37  alasan_resign        128 non-null    object
 38  skor_iq              128 non-null    int64
 39  foto_iq              128 non-null    object
 40  foto_minat           128 non-null    object
 41  foto_kepribadian     128 non-null    object
 42  created_at           128 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(4), object(37)
memory usage: 43.1+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

,id_pelamar,id_pengajuan,email_pelamar,nama_lengkap,nama_panggilan,jenis_kelamin,tempat_lahir,tanggal_lahir,alamat_ktp,alamat_domisili,...,penggunaan_laptop,skor_toefl,ekspektasi_gaji,tautan_berkas,alasan_resign,skor_iq,foto_iq,foto_minat,foto_kepribadian,created_at
0,1,NaN,ditari@leapsurabaya.sch.id,,,,,None,,,...,Tidak Pernah,0,0,,,0,,,,2026-06-08 15:38:19
1,2,NaN,hartikaharahap95@gmail.com,Hartika Prawidaningrum Harahap,Tika,Perempuan,Sidoarjo,None,Perum Grand Surya Cluster Jupiter Blok D12/16 ...,Perum Grand Surya Cluster Jupiter Blok D12/16 ...,...,Pernah,507,4550000,https://drive.google.com/open?id=1Z_FpilagwmNd...,sedang tidak bekerja,100,1688095776_3de967eefe836d28e873.jpeg,1688095993_b75d248ce60436d0d4a1.jpg,1688096006_bf7b1c0e082c6aaf5e67.jpeg,2023-06-29 10:24:53
2,3,NaN,admin@gmail.com,sdasd,sadas,Perempuan,asd,None,asd,asda,...,Tidak Pernah,0,0,,,0,,,,2026-06-08 15:38:19
3,4,NaN,nirmalapradnyas@gmail.com,Ni Putu Jayanti Nirmala Pradnya Santosa,Nirmala,Perempuan,Surabaya,None,Bendul Merisi Permai blok C no 22 Surabaya,Surabaya,...,Tidak Pernah,517,0,,,0,,,,2026-06-08 15:38:19
4,6,4.0,rezaanandapratama017@gmail.com,Reza Ananda Pratama,Reza,,Makassar,2003-04-17,"Jl. Awikoen Tama, Gending, Sidomoro, Kec. Kebo...",Gresik,...,Pernah,0,2000000,https://drive.google.com/file/d/1kdNqm2NtvcNt6...,"tidak, karena saya sudah tidak bekerja",94,1690198645_d728f71f6d4b610f920e.jpg,1690199209_d36c1dd5177c67dc477a.jpg,1690200940_2be2b5e41efeb98ac8b2.jpg,2023-07-24 06:18:15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,173,41.0,zfatmarahmayanti@gmail.com,Zumrotul Fatma Rahmayanti,Rahma,Perempuan,Bojonegoro,1996-11-22,"Jl. Kalidami VIII/2, Kel. Mojo, Kec. Gubeng, S...",Surabaya,...,Pernah,550,4500000,https://drive.google.com/file/d/1-e-iKJa2R_ON_...,sedang tidak bekerja.,0,,1775447036_84815003ec6c143e63f5.png,1775447637_ddea0127066396cdbe46.png,2026-04-06 03:27:23
124,174,41.0,ardirusdiyansyah@gmail.com,Ardi Rusdiyansyah,Rusdi,,Sidoarjo,None,"Ds. Pekarungan, Sukodono, Sidoarjo, Jawa Timur",Sidoarjo,...,Pernah,590,4000000,https://drive.google.com/drive/folders/19kV4mk...,"Tidak, karena berbasis remote",0,,1775529536_b2067ea0b838608b8cda.png,1775530508_6916fcbb71059a4a91df.png,2026-04-07 02:20:46
125,175,41.0,putri.indahsyukriyah@gmail.com,putri indah syukriyah,Putri,Perempuan,Lamongan,None,Jalan Gunung Anyar Tambak No. 15,Surabaya,...,Pernah,0,5290000,https://drive.google.com/drive/folders/1AshhJV...,"Tidak, saat ini saya tidak memiliki kontrak ke...",0,,1775545667_9d01d73b717ce28f627d.png,1775546199_8c01303fdc903592068c.png,2026-04-07 06:19:41
126,176,41.0,ayupuspa892@gmail.com,NI KOMANG AYU PUSPA DEWI,PUSPA,Perempuan,GIANYAR,2004-04-26,Jalan Jambangan Persada No.8,SURABAYA,...,Pernah,0,5288778,https://drive.google.com/drive/folders/1KZ-08W...,Saat ini saya belum memiliki pekerjaan tetap,0,,1775711585_019048c9fa8466be9468.png,1775711857_2280ebd5c29fcb888b00.png,2026-04-09 04:54:13
127,178,NaN,kangmiswanto@gmail.com,Miswanto,Miswanto,,Kendal,None,Rumah Gemilang Indonesia Cabang Surabaya,Rumah Gemilang Indonesia Cabang Surabaya,...,Tidak Pernah,0,0,,,0,,,,2023-05-29 17:43:10

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: PELAMAR_KERJA
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_pelamar_kerja  67 non-null     int64
 1   id_pelamar        0 non-null      object
 2   nama_perusahaan   67 non-null     object
 3   periode           67 non-null     object
 4   jabatan           67 non-null     object
 5   deskripsi_kerja   67 non-null     object
dtypes: int64(1), object(5)
memory usage: 3.3+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

,id_pelamar_kerja,id_pelamar,nama_perusahaan,periode,jabatan,deskripsi_kerja
0,3,None,Coding Bee Academy,2021-2022,Educator,<p>- Membuat lesson plan</p>\r\n<p>- Membuat s...
1,4,None,Pusat Bahasa UINSA Surabaya,2011 - sampai sekarang,Tutor Bahasa Inggris,<p>Mengajar dua kelas pada semester 1 dan 2. D...
2,5,None,PT Aku Pintar Indonesia,2019-2021,Tutor Team Lead dan English Tutor,"<p><span style=""color: rgba(0, 0, 0, 0.9); fon..."
3,6,None,INFOMEDIA NUSANTARA,2018-2020,CALL CENTER BNI,<p>Melayani keluhan dan kebutuhan pelanggan BN...
4,7,None,LKP LEAP English & Digital Surabaya,2022-Sekarang,Part time pengajar Bahasa Inggris,<p>Mengajar Siswa</p>
...,...,...,...,...,...,...
62,66,None,The Ritz-Carlton Bali,12 Agustus 2024 – 12 Februari 2025,Food & Beverage Service Intern,"<p style=""text-align: justify;"">Memberikan lay..."
63,67,None,Kampus Mengajar (Kemendikbud),14 Agustus – 1 Desember 2023,Teaching Assistant,"<p style=""text-align: justify;"">Membantu guru ..."
64,68,None,Sproutgigs.com,14 Januari 2022 – 1 Juli 2024,Freelance Data Entry,"<p style=""text-align: justify;"">Memasukkan dat..."
65,69,None,Sunshine Learning Center,Juli 2025 - Desember 2025,Part time English Teacher,<p>Bertanggung jawab untuk mendukung proses be...
66,70,None,Restoran Makanan chinese,sehari,crew,<p>part time di resto chinese bantu bantu acar...

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: PELAMAR_SEKOLAH
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 265 entries, 0 to 264
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_pelamar_sekolah  265 non-null    int64
 1   id_pelamar          0 non-null      object
 2   nama_sekolah        265 non-null    object
 3   jenjang             265 non-null    object
 4   prodi               265 non-null    object
 5   tahun_lulus         265 non-null    int64
 6   ipk                 265 non-null    float64
 7   organisasi          265 non-null    object
dtypes: float64(1), int64(2), object(5)
memory usage: 16.7+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

,id_pelamar_sekolah,id_pelamar,nama_sekolah,jenjang,prodi,tahun_lulus,ipk,organisasi
0,1,None,SDN Ranggeh,SD,-,2011,89.00,-
1,2,None,UINSA Surabaya,Universitas (S1),Sastra Inggris,2004,3.16,PMII
2,3,None,UNIVERSITAS NEGERI SURABAYA,Universitas (S1),PENDIDIKAN BAHASA INGGRIS / BAHASA INGGRIS,2018,3.59,SKI (Sie Kerohanian Islam)\r\nKepanitiaan Faku...
3,4,None,UNIVERSITAS NEGERI SEBELAS MARET SURAKARTA,Akademi D3,KOMUNIKASI TERAPAN,2012,3.36,"BEM, KAMMI"
4,5,None,SMAK Kolese Santo Yusup Malang,SMA,Bahasa,2018,0.00,
...,...,...,...,...,...,...,...,...
260,261,None,Universitas Pendidikan Ganesha,Universitas (S1),S1 Pendidikan Bahasa Inggris/Bahasa Asing,2025,3.93,
261,262,None,Universitas Pendidikan Ganesha,Universitas (S1),Pendidikan Bahasa Inggris/Bahasa Asing,2025,3.99,
262,263,None,SMA Vita Surabaya,SMA,IPS,2024,94.62,OSIS SMA Vita Surabaya
263,264,None,SMA Dharma Putra,SMA,IPS,2024,85.00,
264,265,None,UIN Sunan Ampel Surabaya,Universitas (S1),Sastra Inggris,2026,3.74,"Himpunan Mahasiswa, FIFA, PSSI, etc"

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: PELAMAR_KURSUS
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_pelamar_kursus  50 non-null     int64
 1   id_pelamar         0 non-null      object
 2   nama_kursus        50 non-null     object
 3   tanggal            15 non-null     object
 4   deskripsi          50 non-null     object
 5   lokasi             50 non-null     object
 6   nomor_sertifikat   50 non-null     object
dtypes: int64(1), object(6)
memory usage: 2.9+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

,id_pelamar_kursus,id_pelamar,nama_kursus,tanggal,deskripsi,lokasi,nomor_sertifikat
0,3,None,Data Science,None,<p>Belajar python pemula</p>,Online,184617619842
1,4,None,Teachers development,2022-02-01,"<p>Teaching management, sistem TMS, cara menge...",UINSA Surabaya,000 - 756 - 458.
2,6,None,MAHIR MICROSOFT EXCEL DAN GOOGLE SHEET,None,<p>Persyaratan masuk kerja di LEAP</p>,"LEAP ENGLISH & DIGITAL, SURABAYA",TDK ADA
3,7,None,Online IELTS Writing Premium Batch 61,None,"<p>Workshop ""IELTS Writing"" yang diadakan oleh...",Zoom (Online),-
4,8,None,Diklat Samisanov 70,None,<p>Diklat 40 JP dengan judul:</p>\r\n<p>Memanf...,online,021.1/K21/11164/VI.2023
5,9,None,Pelatihan Appsmash Quizizz dan AI untuk Gamifi...,None,<p>42JP Diklat dengan judul:&nbsp;</p>\r\n<p>A...,online,004/DIKLAT/YPPI/PE/III/2023
6,10,None,DIKLAT 70 SAMISANOV,None,<p>Seminar meliputi pembuatan media pembelajar...,Online Via Zoom MEeting,No. 021.1 / K21 / 11173 / V / 2023
7,11,None,Basic Community Management,None,<p>Pelatihan dasar membangun dan mengelola kom...,GrandKemang Hotel Jakarta,-
8,12,None,MC Formal & Protokoler Spesial Hari Guru,2022-11-26,<p>Pelatihan diselenggarakan oleh Probest Prof...,Online (Via Zoom),1892/PB/TR/10.2022
9,13,None,HOTS for Millennials: Integrating High-order T...,None,<p>HOTS for Millennials:</p>\r\n<p>Integrating...,Widya Mandala Catholic University Surabaya Gra...,-
10,14,None,Akta 4,None,<p>https://drive.google.com/file/d/1rxlx2w7jZo...,Surabaya,0000651
11,15,None,PROPELL Teacher Workshop for the TOEIC listeni...,None,<p>PROPELL adalah pelatihan bagi pengajar meng...,ONLINE,-
12,16,None,-,None,<p>-</p>,-,-
13,17,None,Engaging Learners in CALL: Research and Practice,None,<p>Webinar nasional yang diselenggarakan oleh ...,Fakultas Ilmu Budaya Universitas Airlangga,70/UN3.1.11/DL/2021
14,18,None,Kompetensi - TOEFL ITP,2023-09-08,<p>Mengikuti TOEFL ITP di LKP Texas Jember seb...,Online via Zoom,12827527
15,19,None,UJI KOMPUTER MUDA,None,<p>No. 62090 3511 3 0069147 2023</p>\r\n<p>No....,Online via Zoom,No. 62090 3511 3 0069147 2023
16,20,None,Design Thinking for Educators: Merancang Proje...,None,<p>Basic design thinking dan basic menggunakan...,online zoom,tdk ada nomer
17,21,None,DIKLAT RUMAH GEMILANG INDONESIA,None,"<p>Pelatihan Pemrograman Front-End, Back-End, ...","Gang Tanjung, Tanah Kali Kedinding Kec.Kenjera...",2329080407
18,22,None,NAATIQ (International Arobiyyah),None,"<p>Belajar bahasa arab, Gaya bahasa, Debat, Mu...",Kampung Inggris Pare,Belum Rilis
19,23,None,Social media analytic,2020-12-12,<p>Webinar Online social media analytic yang m...,Surabaya,-
20,27,None,Sololearn Course Certificate CSS,2019-07-03,<p><strong>Course Certificate CSS</strong> aka...,Surabaya,-
21,28,None,Akta IV,None,<p>Akta ini diberikan setelah yang bersangkuta...,PGRI Adi Buana Surabaya,15.1.5.32333
22,29,None,MMembangun Karakter Anak melalui Permainan Tra...,None,<p>Membangun Karakter Anak melalui Permainan T...,FAKULTAS PSIKOLOGI UNIVERSITAS SURABAYA,-
23,30,None,Sertifikat kompetensi,2016-09-11,<p>dinyatakan KOMPETEN sebagai Pendidik Kursus...,Lembaga Sertifikasi dan kompetensi Pendidik kursu,01291/35/065/LSK
24,31,None,IELTS,2022-02-24,<p>Dokumen di drive file upload</p>,IDP,21ID0015RONG405A
25,32,None,Sertifikat Operator Komputer Muda,2023-09-25,<p>Aplikasi Perkantoran</p>,Lembaga Sertifikasi Profesi Teknologi Digital,620903511300685582023
26,33,None,Speaking,None,<p>Kursus speaking 2 minggu</p>,Jago Bahasa Pare,2882/JS2/XII/2021
27,34,None,penulisan kesejarahan,None,<p>mempelajari teknis penulisan kesejarahan ya...,Malang,405/E.E5/KP/2018
28,35,None,Merancang RPP Merdeka Belajar,None,<p>program pelatihan merancang RPP Merdeka Bel...,online,3131093
29,36,None,Bimtek Guru Belajar Asesmen Kompetensi minimum,None,<p>bimbingan teknis tentang konsep asesmen nas...,Surabaya,0028/B/KP/2021
30,37,None,Ragam Teknologi dalam pembelajaran,None,<p>Mempelajari beragam perangkat dan aplikasi ...,online,110574
31,38,None,Kesepakatan Kelas Merdeka Belajar,2020-09-28,<p>Mempelajari bagaimana membuat kesepakatan b...,online,1764635
32,39,None,English Acquisition 8,2020-09-21,<p>mempelajari teknik pembelajaran bahasa ingg...,online,1123274
33,40,None,Sekolah Guru anti korupsi,None,"<p>pengertian korupsi, cara menghindari dan me...",zoom meeting,05/serasi/peserta/II/2021
34,41,None,Penyusunan Perangkat Ajar Kurikulum Merdeka ba...,None,"<p>bimbingan mulai kebijakan, kurikulum operas...",Universitas Katolik Widya Mandala Surabaya,854/WM02/T/2022
35,42,None,GCED For Educator,None,<p>merancang modul GCED untuk guru se Asia&nbs...,Online Internasional,APCEIU-CL002-2022-101-E7
36,43,None,"Workshop Kelas Menulis ""Kertas dan Peradaban"" ...",None,<p>belajar teknis menulis dari narasumber seor...,Surabaya,tidak ada nomor
37,44,None,Web Development Certificate,2025-01-01,"<p>Hard-Skill: HTML, CSS, JS, PHP, MySQL, Lara...",Surabaya,LAZ-RGI/MMXIV31080405
38,45,None,Festival Kurikulum Merdeka,2024-05-01,<p>Mempelajari praktik baik mengajar para guru...,Online,35/KPM/FKM4/IV/2024
39,46,None,AJGuru - 21st Century Education,2023-05-01,<p>Mempelajari kurikulum merdeka</p>,Online,9116881
40,47,None,Contenr Creator,None,<p>Pelatihan Content Creator dengan tujuan unt...,Surabaya,2684/PR/TR/V/2024
41,48,None,Komunikasi Efektif,None,<p>Pelatihan terkait komunikasi efektif untuk ...,Surabaya,29449/PR/TR/VI/2024
42,49,None,Pelatihan Front Office,None,<p>Pelatihan berbasis kompetensi kejuruan pari...,BLK Banyuwangi,05511 4224 0001171 2021
43,50,None,"Seminar Online "" Increasing Indonesia's Global...",2022-09-21,"<p>seminar online dengan judul&nbsp; "" Increas...",Universitas PGRI Banyuwangi,076/DK/D.7/FBS/UNIBA/IX/2022
44,51,None,Pelatihan Perhotelan,None,"<p>Has completed for Hotel training on "" FRONT...",Hotel Santika Banyuwangi,25/HS/BWI/FBS-CERTIFICATE/III/2023
45,52,None,Program Kreativitas Mahasiswa tahun 2023,2023-11-15,"<p>Sebagai peraih pendanaan bidang PKMK ""BITTE...",Universitas PGRI Banyuwangi,7308/E2/DT.01.00/2023
46,53,None,Program Kampus Mengajar Angkatan 7 Tahun 2024,None,<p>Sebagai peserta program kampus mengajar ang...,SDN 3 Grajagan,-
47,54,None,Sekolah Ciputra's School to School Conference,None,<p>Link sertifikat:&nbsp;https://drive.google....,Sekolah Ciputra,-
48,55,None,Workshop “From Classroom to Connection” Linked...,None,<p>Link Sertifikat:&nbsp;https://drive.google....,LEAP English & Digital Class,No : 001/TLPB/II/2526/17
49,56,None,Digital competences for teaching English,None,<p>https://drive.google.com/file/d/1Rv7iQJrIgA...,Online via British Council Website,-

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: PROGRES_PELAMAR
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 288 entries, 0 to 287
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id_progres_pelamar      288 non-null    int64
 1   id_pelamar              288 non-null    int64
 2   id_user                 288 non-null    object
 3   status_progres_pelamar  288 non-null    object
 4   catatan                 288 non-null    object
 5   tautan_file             288 non-null    object
 6   pertanyaan              288 non-null    object
 7   created_at              288 non-null    datetime64[ns]
dtypes: datetime64[ns](1), int64(2), object(5)
memory usage: 18.1+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

,id_progres_pelamar,id_pelamar,id_user,status_progres_pelamar,catatan,tautan_file,pertanyaan,created_at
0,14,178,U00001,Tahap Test,<p>interview</p>,https://drive.google.com/drive/folders/1WYB9iR...,,2023-05-29 17:45:09
1,15,178,U00001,Interview,,,,2023-05-30 06:21:30
2,18,178,U00011,Interview,<p>haha</p>,,,2023-06-12 14:09:10
3,19,2,U00018,Baru,<p>Pelamar bersedia melaksanakan tugas dan jad...,,<p>Pelamar bersedia melaksanakan tugas dan jad...,2023-07-02 19:45:07
4,25,2,U00018,Interview,<p>jadi jawabnya seperti ini</p>,,<p><strong>Informasi dasar yang perlu digali (...,2023-07-02 20:46:56
...,...,...,...,...,...,...,...,...
283,456,174,U00018,Tahap Test,,https://drive.google.com/drive/folders/1e7QK2s...,,2026-04-08 08:22:57
284,457,175,U00018,Tahap Test,,https://drive.google.com/drive/folders/1Ofqg2q...,,2026-04-08 08:24:43
285,458,176,U00018,Tahap Test,,https://drive.google.com/drive/folders/1fYg26w...,,2026-04-13 09:24:34
286,459,176,U00018,Ditolak,,,,2026-04-17 10:44:29
287,460,175,U00018,Ditolak,,,,2026-04-17 10:44:38

================================================================================

================================================================================
✅ [STATUS: AMAN IDENTIK] TABEL: REKRUTMEN_PELAMAR
================================================================================
📋 1. Karakteristik Wadah Pandas Dataframe (.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_rekrutmen  205 non-null    int64
 1   id_pelamar    193 non-null    float64
 2   id_user       205 non-null    object
dtypes: float64(1), int64(1), object(1)
memory usage: 4.9+ KB

------------------------------------------------------------
🔍 2. [TABEL REAL & FINAL] Arsitektur Fisik Kolom pada DB_NEW:

------------------------------------------------------------
✨ INDICATOR: [ DB_NEW ] & [ DB_FUTURE ] STRUKTUR SUDAH IDENTIK SAMA PERSIS 100% ✨
ℹ️  Tabel DB_FUTURE otomatis disembunyikan untuk kenyamanan pemandangan layar monitor.

------------------------------------------------------------
📸 3. Sampel Isi Data Real di DB_NEW:

     id_rekrutmen  id_pelamar id_user
0              12         2.0  U00014
1              13         2.0  U00023
2              20        12.0  U00014
3              21        12.0  U00016
4              24         NaN  U00020
..            ...         ...     ...
200           370       173.0  U00015
201           371       173.0  U00018
202           372       176.0  U00014
203           373       176.0  U00015
204           374       176.0  U00018

[205 rows x 3 columns]

================================================================================