In [3]:
import sys
import os
import mysql.connector
import pandas as pd
sys.path.append(os.path.abspath('..'))
from config import get_db_config
import warnings
warnings.filterwarnings('ignore')
import json
import pickle
import numpy as np
import datetime
from IPython.display import display, HTML

In [4]:
# Connect ke database config
config = get_db_config()
# Ambil host dari salah satu config (misal db_old)
print(f'Database config loaded: {config["db_old"]["host"]}')

# Connect ke DB Lama
db_old = mysql.connector.connect(**config['db_old'])
cursor_old = db_old.cursor(dictionary=True)
print(f'Connected to old database: {config["db_old"]["database"]}')

# Connect ke DB Baru
db_new = mysql.connector.connect(**config['db_new'])
cursor_new = db_new.cursor(dictionary=True)
print(f'Connected to new database: {config["db_new"]["database"]}')

Database config loaded: localhost
Connected to old database: dataleap_v5_example
Connected to new database: dataleap_v5_migration

In [9]:
print("================================================================================")
print(" 🚀 SETUP INSERT HANDLER GLOBAL - FASE 3 (SALING SILANG & AUTO-SKIP) 🚀 ")
print("================================================================================")

# ================================================================================
# TAHAP 1: MEMUAT SE LURUH BERKAS PICKLE DAN MERGE JADI SATU PINTU
# ================================================================================
all_fase_3_data = {}

# 1. Load File Cimut
try:
    with open('fase_3_cimut.pkl', 'rb') as f:
        all_fase_3_data.update(pickle.load(f))
    print("✓ Berhasil memuat data hasil konversi Cimut.")
except Exception as e:
    print(f"⚠️ Gagal memuat file pkl Cimut: {e}")

# 2. Load File Afrida
try:
    with open('fase_3_afrida.pkl', 'rb') as f:
        all_fase_3_data.update(pickle.load(f))
    print("✓ Berhasil memuat data hasil konversi Afrida.")
except Exception as e:
    print(f"⚠️ Gagal memuat file pkl Afrida: {e}")

# 3. Load File Hanif (Jika ada file terpisah, opsional)
try:
    if os.path.exists('fase_3_hanif.pkl'):
        with open('fase_3_hanif.pkl', 'rb') as f:
            all_fase_3_data.update(pickle.load(f))
        print("✓ Berhasil memuat data hasil konversi Hanif.")
except:
    print(f"⚠️ Gagal memuat file pkl Hanif: {f}")
    pass

================================================================================
 🚀 SETUP INSERT HANDLER GLOBAL - FASE 3 (SALING SILANG & AUTO-SKIP) 🚀
================================================================================
✓ Berhasil memuat data hasil konversi Cimut.
✓ Berhasil memuat data hasil konversi Afrida.
⚠️ Gagal memuat file pkl Hanif: <_io.BufferedReader name='fase_3_hanif.pkl'>

In [10]:
# ================================================================================
# TAHAP 2: ATUR URUTAN STRATEGIS SALING SILANG (CIMUT, AFRIDA, & HANIF)
# ================================================================================
# Susunan di bawah ini diatur ketat lintas personel agar Foreign Key aman masuk ke MySQL!
tables_to_insert_ordered = [
    # --- BLOK A: PENDAFTARAN & SDM (Karya Hanif) ---
    'pelamar',                  # Induk data pelamar kerja/kursus
    'pelamar_kerja',            # Detail pelamar posisi kerja
    'pelamar_sekolah',          # Riwayat sekolah pelamar
    'pelamar_kursus',           # Riwayat kursus pelamar
    'progres_pelamar',          # Log catatan tahapan seleksi
    'rekrutmen_pelamar',        # Keputusan akhir rekrutmen pelamar
    'pengajuan_karyawan',       # Form pengajuan penambahan staff baru
    'histori_pengajuan',        # Log alur persetujuan pengajuan staff

    # --- BLOK B: SURAT-MENYURAT & SOP (Karya Afrida) ---
    'sop',                      # Standar operasional prosedur instansi
    'surat_keluar',             # Log keluar dokumen/surat resmi
    'verifikasi_surat_keluar',  # Log persetujuan surat keluar oleh atasan
    'surat_tugas',              # Surat perintah penugasan formal
    'surat_tugas_anggota',      # Anggota staff yang terikat di dalam surat tugas

    # --- BLOK C: MARKETING & ADMISI CALON SISWA (Karya Cimut) ---
    'kontak_prospek',           # Database mentah leads / prospek marketing
    'calon_siswa',              # Formulir profil utama calon siswa baru
    'calon_siswa_ortu',         # Data wali / orang tua calon siswa
    'calon_siswa_akademik',     # Riwayat background akademik calon siswa
    'calon_siswa_bayar',        # Log transaksi pembayaran formulir/DP awal
    'calon_siswa_jadwal',       # Plotting jadwal tes/interview calon siswa
    'calon_siswa_kursus',       # Pilihan program kursus yang diminati calon siswa
    'calon_siswa_proses',       # Jalur perkembangan dokumen admisinya
    'calon_siswa_status_logs',  # Log perubahan status akhir (Diterima/Ditolak/Pending)

    # --- BLOK D: LOGISTIK & OPERASIONAL INTERNAL (Karya Cimut) ---
    'pengadaan',                # Form pengajuan belanja/pengadaan aset barang
    'peminjaman',               # Log pinjam pakai sarana prasarana oleh staff
    'problem'                   # Log laporan kerusakan/kendala teknis fasilitas
]

In [11]:
import pandas as pd
import datetime
import numpy as np
import mysql.connector

# ================================================================================
# TAHAP 3: FUNGSI UTAMA INSERT DENGAN RINGKASAN DI ATAS & DIAGNOSTIK ERROR DI BAWAH
# ================================================================================
def insert_data_with_preview_and_skip_v2(db_connection, cursor, tables_data, ordered_list):
    results = {}
    
    print("="*80)
    print("🎬 MEMULAI EKSEKUSI PENYUNTIKAN DATA KE MYSQL BARU (SISTEM RINGKASAN ATAS)")
    print("="*80)
    
    # ----------------------------------------------------------------------------
    # SUB-LANGKAH A: PROSES INSERT KE MYSQL DI BELAKANG LAYAR
    # ----------------------------------------------------------------------------
    for table_name in ordered_list:
        if table_name not in tables_data:
            results[table_name] = {
                'status': 'not_found', 
                'rows': 0, 
                'msg': f'⚠️  {table_name}: Tidak ditemukan di file pkl'
            }
            continue
            
        df_target = tables_data[table_name]
        
        if df_target is None or df_target.empty:
            results[table_name] = {
                'status': 'empty', 
                'rows': 0, 
                'msg': f'ℹ️  {table_name}: DataFrame kosong (0 baris)'
            }
            continue
            
        try:
            # Bersihkan kolom kosong murni agar tidak merusak placeholder query
            df_to_push = df_target.dropna(axis=1, how='all')
            
            columns_str = ', '.join([f'`{col}`' for col in df_to_push.columns])
            placeholders_str = ', '.join(['%s'] * len(df_to_push.columns))
            
            # Gunakan INSERT IGNORE untuk auto-skip duplikat primary key
            insert_query = f"INSERT IGNORE INTO `{table_name}` ({columns_str}) VALUES ({placeholders_str})"
            
            # Konversi DataFrame ke Native List Python (Hancurkan tipe data NumPy)
            raw_numpy_list = df_to_push.to_numpy().tolist()
            clean_data_tuples = [
                tuple(None if pd.isna(x) or str(x).strip() in ["NaT", "NaN"] else x for x in row) 
                for row in raw_numpy_list
            ]
            
            # Eksekusi massal
            cursor.executemany(insert_query, clean_data_tuples)
            db_connection.commit()
            
            total_rows = len(clean_data_tuples)
            results[table_name] = {
                'status': 'success', 
                'rows': total_rows, 
                'msg': f'✓ {table_name}: Sukses diproses! Sebanyak {total_rows} baris sukses dimasukkan / di-skip aman.'
            }
            
        except Exception as e:
            db_connection.rollback()
            results[table_name] = {
                'status': 'failed', 
                'rows': 0, 
                'msg': f'✗ {table_name}: Gagal total saat insert - Alasan: {e}'
            }

    # ----------------------------------------------------------------------------
    # 📊 CETAK PAPAN RINGKASAN DI PALING ATAS (SUMMARY BOARD)
    # ----------------------------------------------------------------------------
    print("\n================================================================================")
    print(" 📊 PAPAN RINGKASAN STATUS MIGRATION DATA (SUMMARY BOARD) 📊")
    print("================================================================================")
    
    # 1. Cetak yang sukses dulu biar rapi
    print("🟢 TABEL YANG SUKSES MASUK:")
    success_exist = False
    for table_name in ordered_list:
        if table_name in results and results[table_name]['status'] == 'success':
            print(f"  {results[table_name]['msg']}")
            success_exist = True
    if not success_exist: print("  (Tidak ada tabel yang sukses)")

    print("\n🔴 TABEL YANG BERMASALAH / GAGAL MASUK (MOHON DIANALISA):")
    failed_exist = False
    for table_name in ordered_list:
        if table_name in results and results[table_name]['status'] in ['failed', 'not_found', 'empty']:
            print(f"  {results[table_name]['msg']}")
            failed_exist = True
    if not failed_exist: print("  🎉 LUAR BIASA! Semua tabel bersih tidak ada yang gagal.")
            
    print("================================================================================\n")


    # ----------------------------------------------------------------------------
    # 📸 CETAK PREVIEW HISTORI & DIAGNOSTIK ERROR DI BAGIAN BAWAH
    # ----------------------------------------------------------------------------
    print("="*80)
    print("📸 MEMULAI LOG VISUALISASI PREVIEW & DIAGNOSTIK TABEL")
    print("="*80)
    
    for table_name in ordered_list:
        if table_name in results:
            # Taktik A: Jika Sukses, tampilkan preview standard 5 baris teratas
            if results[table_name]['status'] == 'success':
                print(f"\n📂 [🟢 PREVIEW TABEL SUKSES: {table_name.upper()}]")
                print("-" * 50)
                display(tables_data[table_name]) 
                print("-" * 80)
                
            # Taktik B: Jika GAGAL, tembak dan kuliti struktur datanya secara transparan!
            elif results[table_name]['status'] == 'failed':
                print(f"\n🚨 [🔴 DIAGNOSTIK TABEL ERROR: {table_name.upper()}] 🚨")
                print(f"Alasan MySQL Menolak: {results[table_name]['msg']}")
                print("-" * 50)
                print("Berikut 5 baris sampel data yang gagal dikirim, cek tipe datanya (apakah ada .0 atau string aneh):")
                display(tables_data[table_name])
                print(f"\nTipe data kolom internal DataFrame untuk tabel '{table_name}':")
                # Menampilkan tipe data internal pandas agar ketahuan mana float ghaib / objek aneh
                print(tables_data[table_name].dtypes)
                print("-" * 80)
            
    print("\n" + "="*80)
    print("🏁 PROSES INSPEKSI SELESAI. SILAKAN CEK HASIL DIAGNOSTIK DI ATAS 🏁")
    print("="*80)
    return results

In [12]:
# ================================================================================
# TAHAP 4: MENJALANKAN EKSEKUSI DATA REAL (MENGGUNAKAN VERSI RINGKASAN ATAS)
# ================================================================================
results_fase_3 = insert_data_with_preview_and_skip_v2(
    db_connection=db_new, 
    cursor=cursor_new, 
    tables_data=all_fase_3_data, 
    ordered_list=tables_to_insert_ordered
)

================================================================================
🎬 MEMULAI EKSEKUSI PENYUNTIKAN DATA KE MYSQL BARU (SISTEM RINGKASAN ATAS)
================================================================================

================================================================================
 📊 PAPAN RINGKASAN STATUS MIGRATION DATA (SUMMARY BOARD) 📊
================================================================================
🟢 TABEL YANG SUKSES MASUK:
  ✓ sop: Sukses diproses! Sebanyak 4 baris sukses dimasukkan / di-skip aman.
  ✓ surat_keluar: Sukses diproses! Sebanyak 213 baris sukses dimasukkan / di-skip aman.
  ✓ verifikasi_surat_keluar: Sukses diproses! Sebanyak 477 baris sukses dimasukkan / di-skip aman.
  ✓ surat_tugas: Sukses diproses! Sebanyak 135 baris sukses dimasukkan / di-skip aman.
  ✓ surat_tugas_anggota: Sukses diproses! Sebanyak 304 baris sukses dimasukkan / di-skip aman.
  ✓ kontak_prospek: Sukses diproses! Sebanyak 214 baris sukses dimasukkan / di-skip aman.
  ✓ calon_siswa: Sukses diproses! Sebanyak 214 baris sukses dimasukkan / di-skip aman.
  ✓ calon_siswa_ortu: Sukses diproses! Sebanyak 214 baris sukses dimasukkan / di-skip aman.
  ✓ calon_siswa_akademik: Sukses diproses! Sebanyak 214 baris sukses dimasukkan / di-skip aman.
  ✓ calon_siswa_bayar: Sukses diproses! Sebanyak 214 baris sukses dimasukkan / di-skip aman.
  ✓ calon_siswa_jadwal: Sukses diproses! Sebanyak 214 baris sukses dimasukkan / di-skip aman.
  ✓ calon_siswa_kursus: Sukses diproses! Sebanyak 214 baris sukses dimasukkan / di-skip aman.
  ✓ calon_siswa_proses: Sukses diproses! Sebanyak 214 baris sukses dimasukkan / di-skip aman.
  ✓ pengadaan: Sukses diproses! Sebanyak 110 baris sukses dimasukkan / di-skip aman.
  ✓ peminjaman: Sukses diproses! Sebanyak 194 baris sukses dimasukkan / di-skip aman.
  ✓ problem: Sukses diproses! Sebanyak 160 baris sukses dimasukkan / di-skip aman.

🔴 TABEL YANG BERMASALAH / GAGAL MASUK (MOHON DIANALISA):
  ℹ️  pelamar: DataFrame kosong (0 baris)
  ℹ️  pelamar_kerja: DataFrame kosong (0 baris)
  ℹ️  pelamar_sekolah: DataFrame kosong (0 baris)
  ℹ️  pelamar_kursus: DataFrame kosong (0 baris)
  ℹ️  progres_pelamar: DataFrame kosong (0 baris)
  ℹ️  rekrutmen_pelamar: DataFrame kosong (0 baris)
  ℹ️  pengajuan_karyawan: DataFrame kosong (0 baris)
  ℹ️  histori_pengajuan: DataFrame kosong (0 baris)
  ℹ️  calon_siswa_status_logs: DataFrame kosong (0 baris)
================================================================================

================================================================================
📸 MEMULAI LOG VISUALISASI PREVIEW & DIAGNOSTIK TABEL
================================================================================

📂 [🟢 PREVIEW TABEL SUKSES: SOP]
--------------------------------------------------

,judul_sop,link_dokumen_sop,created_at,id_sop_kategori
0,Akhir Penggunaan Kelas English (19.15 WIB),https://drive.google.com/file/d/1V0MpB7ctzPHe6...,2023-07-07 08:52:48,1
1,Penerimaan Surat Masuk,https://drive.google.com/file/d/1G8lO33yU7MufC...,2023-11-22 15:27:06,2
2,Pengajuan Surat Keluar,https://drive.google.com/file/d/14I7wYSk62WJAv...,2023-11-22 15:27:55,2
3,Pengajuan Surat Tugas,https://drive.google.com/file/d/1R-wKFqQeVSz62...,2023-11-22 15:28:27,2

--------------------------------------------------------------------------------

📂 [🟢 PREVIEW TABEL SUKSES: SURAT_KELUAR]
--------------------------------------------------

,id_sk,id_user,keterangan_sk,link_dokumen_sk,status_sk,nomor_sk,catatan_sk,created_at
0,24,U00011,Surat Permohonan Uji Kompetensi dan Penggunaan...,https://docs.google.com/document/d/1xyhc4T-FlR...,Sudah Revisi,090A/LEAP/IX/2023- 090B/LEAP/IX/2023,Lengkapi Tanggal Pelaksanaan dengan tanggal ya...,2023-09-11 17:57:49
1,26,U00011,Beasiswa Siswa GE,https://docs.google.com/document/d/1jMTK_3b57e...,Disetujui,101/LEAP/BD/X/2023,,2023-10-25 16:57:38
2,27,U00011,PERJANJIAN KERJASAMA / MEMORANDUM OF UNDERSTAN...,https://docs.google.com/document/d/1Edeb7hWaBq...,Disetujui,102/LEAP/BD/X/2023,,2023-10-26 17:37:59
3,28,U00026,Sertifikat / Sertifikat Kelas APK Private / 1 ...,https://drive.google.com/drive/folders/1JMrPJF...,Disetujui,Sertif 002a/APEX/XI/2324/02 (Page 1) dan 002b/...,,2023-11-10 16:10:04
4,29,U00011,Penawaran Pelatihan Business English ke PT. La...,https://docs.google.com/document/d/1wBK62noEJw...,Disetujui,105/LEAP/BD/XI/2023,,2023-11-13 15:41:58
...,...,...,...,...,...,...,...,...
208,248,U00016,Jurnal Siswa & Laporan Akhir Community Service...,https://docs.google.com/document/d/1QJOQCHDN3j...,Disetujui,,,2026-04-07 14:44:54
209,250,U00033,Pelaporan Hasil Ujian Susulan Semester Genap K...,https://drive.google.com/file/d/14MFeTQ6SsupYk...,Disetujui,042/PDDK/SKET/LEAP/IV/2026,,2026-04-14 13:51:55
210,251,U00023,MoM Rupin (Mid Semester Evaluation & Next Batc...,https://docs.google.com/document/d/1s3G_jzBIlH...,Disetujui,043/PDDK/MoM/LEAP/IV/2026,,2026-04-16 08:51:31
211,252,U00034,Surat Izin Uji Coba Proyek SMPN 13,https://docs.google.com/document/d/14r8_bXEJjl...,Disetujui,046/PDDK/PM/LEAP/IV/2026,,2026-04-17 15:38:24
212,253,U00034,Surat Izin Uji Coba Proyek SMPN 35,https://docs.google.com/document/d/1tleVpLUO0j...,Disetujui,045/PDDK/PM/LEAP/IV/2026,,2026-04-17 16:01:39

--------------------------------------------------------------------------------

📂 [🟢 PREVIEW TABEL SUKSES: VERIFIKASI_SURAT_KELUAR]
--------------------------------------------------

     id_sk status_verifikasi_sk catatan_verifikasi_sk          created_at
0     <NA>             Diajukan                   NaN 2023-06-12 13:32:50
1     <NA>             Diajukan                   NaN 2023-06-12 13:33:07
2     <NA>             Diajukan                   NaN 2023-06-12 14:28:56
3     <NA>             Diajukan                   NaN 2023-06-30 15:30:35
4     <NA>             Diajukan                   NaN 2023-07-01 20:35:43
..     ...                  ...                   ...                 ...
472    251            Disetujui                   NaN 2026-04-16 15:23:32
473    252             Diajukan                   NaN 2026-04-17 15:38:24
474    253             Diajukan                   NaN 2026-04-17 16:01:39
475    252            Disetujui                   NaN 2026-04-17 16:13:16
476    253            Disetujui                   NaN 2026-04-17 16:13:32

[477 rows x 4 columns]

--------------------------------------------------------------------------------

📂 [🟢 PREVIEW TABEL SUKSES: SURAT_TUGAS]
--------------------------------------------------

,id_st,id_user,acara,undangan,waktu_acara,lokasi_acara,jenis_kegiatan,status_st,nomor_st,catatan_st,link_st,link_laporan,catatan_laporan,keterangan_st,catatan_pembatalan,created_at
0,20,U00015,Pertemuan rutin di bulan Juli 2023 forum Laras...,Larasdikdudi,2023-07-27,SMK Teknik PAL Surabaya Jalan Ujung Surabaya,Offline,Disetujui,023/LEAP/ST/VII/2023,,https://docs.google.com/document/d/1rILu6FE8Bd...,https://docs.google.com/document/d/1IAhWT4XjbX...,done/laporan sudah diisi,,,2023-07-25 09:56:19
1,21,U00015,Temu Warga RT 01 RW 08,Pengurus RT 01/ RW08,2023-08-23,Balai RW,Offline,Disetujui,024/LEAP/ST/VIII/2023,,https://docs.google.com/document/d/1OQxpdKYfDF...,https://docs.google.com/document/d/1XrvRmYckBw...,,,,2023-08-22 17:43:48
2,22,U00016,TEDxSurabaya Translators:\r\n\r\n1. Simulasi C...,TEDxSurabaya,2023-09-15,Topic: Connect to TEDxSurabaya Join Zoom Meeti...,Online,Disetujui,025/LEAP/ST/VIII/2023,,https://docs.google.com/document/d/10Zi6g0R9RR...,https://docs.google.com/document/d/1pa9G3E3eUa...,laporan kegiatan done,,,2023-09-13 13:01:52
3,23,U00015,Pertemuan Rutin Larasdikdudi bulan September 2023,https://drive.google.com/drive/u/3/folders/1OI...,2023-09-27,AULA SMK Negeri 2 Surabaya Jalan Tentara Genie...,Offline,Disetujui,028/LEAP/ST/IX/2023,,https://docs.google.com/document/d/1wMOD-N6oMQ...,https://docs.google.com/document/d/1xMv7AK2L9S...,done,,,2023-09-19 13:54:26
4,24,U00015,Sosialisasi Kerjasama LKP dan PKBM dengan Seme...,Dinas Pendidikan Kota Surabaya (bu Hilda),2023-09-20,"Tempat : Ruang Bung Tomo, Dinas Pendidikan Kot...",Offline,Disetujui,027/LEAP/ST/IX/2023,,https://docs.google.com/document/d/1LBx4WpqXcY...,https://docs.google.com/document/d/1jJdGMkonp_...,,,,2023-09-19 13:55:50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,163,U00016,TEDx,TEDx,2026-04-19,Surabaya Intercultural School. Jalan HR Muhammad,Offline,Disetujui,030/HR/ST/LEAP/III/2026,,https://docs.google.com/document/d/1yLNtt2uchj...,https://docs.google.com/document/d/1yoA9gDLRwT...,,,,2026-03-03 11:52:40
131,164,U00016,Supervisi Tengah Semester,Yayasan BSI - Banyuwangi,2026-04-10,Pesanggaran - Banyuwangi,Offline,Disetujui,039/HR/ST/LEAP/IV/2026,,https://docs.google.com/document/d/1ymoUqyKfLG...,https://docs.google.com/document/d/1ONn9G_Detj...,done,,,2026-04-06 10:49:15
132,165,U00016,Indonesia Youth Debate Summit,Sekolah Ciputra Surabaya,2026-04-23,"Ciputra Hall, Sekolah Ciputra Surabaya",Offline,Disetujui,040/HR/ST/LEAP/IV/2026,,https://docs.google.com/document/d/1CRncv0KVgX...,https://docs.google.com/document/d/1Z7RSXw0696...,,,,2026-04-08 12:56:00
133,166,U00016,Student Appreciation (Shining Beyond Limits) S...,SD Al Muslim,2026-04-18,Politeknik Pelayaran Surabaya,Offline,Disetujui,032/HR/ST/MIM/IV/2026,,https://docs.google.com/document/d/1Jfx39xH2pj...,https://docs.google.com/document/d/1lFTezKhCkA...,,,,2026-04-17 15:39:08
134,167,U00016,Student Appreciation (Shining Beyond Limits) S...,SD Al Muslim,2026-04-18,Politeknik Pelayaran Surabaya,Offline,Disetujui,044/HR/ST/LEAP/IV/2026,,https://docs.google.com/document/d/1PzlRtvydlt...,https://docs.google.com/document/d/1VCs1Bp7XeP...,,,,2026-04-17 16:01:07

--------------------------------------------------------------------------------

📂 [🟢 PREVIEW TABEL SUKSES: SURAT_TUGAS_ANGGOTA]
--------------------------------------------------

     id_st id_user
0        6  U00012
1        6  U00003
2        7  U00026
3        7  U00012
4        8  U00026
..     ...     ...
299    165  U00034
300    164  U00016
301    164  U00023
302    166  U00060
303    167  U00052

[304 rows x 2 columns]

--------------------------------------------------------------------------------

📂 [🟢 PREVIEW TABEL SUKSES: KONTAK_PROSPEK]
--------------------------------------------------

,id_kontak_prospek,kode_kontak,nama_penanya,nomor_telepon,email,sumber_informasi,catatan_awal_fo,id_admin_fo,status_kontak,tanggal_kontak_pertama,tanggal_kontak_terakhir,created_at,updated_at
0,76,BJ2CRSF9J6,None,,42234234234432@gmail.com,Teman/kerabat/saudara,None,None,,2026-01-08 16:50:38,None,2026-01-08 16:50:38,2026-05-26 01:13:34.404362
1,169,RSDUQQDWZU,None,,fransisca_angilia@yahoo.co.id,Website,None,None,done,2025-09-24 17:40:39,None,2025-10-03 11:51:36,2025-10-16 10:44:02.000000
2,208,BDQE3OGKQK,None,,None,None,None,None,follow up another time,2025-10-24 15:27:54,None,2025-10-24 15:27:54,2025-10-24 15:27:54.000000
3,151,A04YSLOZ0C,Bu Lita,087765283592,melisnifuku@gmail.com,None,None,None,done,2025-09-17,None,2025-09-17 16:49:20,2025-10-03 09:49:15.000000
4,114,8LXPEP6UKT,None,,achmadryanivansyah@gmail.com,Tiktok,None,None,,2026-02-17 01:21:36,None,2026-02-17 01:21:36,2026-05-26 01:13:34.404741
...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,127,B6WH4YWNGS,None,,zeinstyles74@gmail.con,Tiktok,None,None,,2026-03-08 04:57:09,None,2026-03-08 04:57:09,2026-05-26 01:13:34.419363
210,103,S2ISCIRBOQ,None,,almasazzilah02@gmail.com,Website,None,None,1,2026-02-04 15:05:56,None,2026-02-04 15:05:56,2026-05-26 01:13:34.419491
211,91,LIW4Z07L60,None,,zufarzakka@gmail.com,Teman/kerabat/saudara,None,None,,2026-01-20 10:45:40,None,2026-01-20 10:45:40,2026-05-26 01:13:34.419633
212,153,38J0SBN4YH,Ibu Fitri,083849241708,chyzryth@gmail.com,None,None,None,done,2025-09-16,None,2025-09-17 17:32:16,2025-10-03 09:48:34.000000
213,1,LKOQ92Z6KN,None,083849241708,chyzryth@gmail.com,Lainnya,None,None,1,2025-09-17 11:34:19,None,2025-09-17 11:34:19,2026-05-26 01:13:34.419965

--------------------------------------------------------------------------------

📂 [🟢 PREVIEW TABEL SUKSES: CALON_SISWA]
--------------------------------------------------

,id_calon,kode_unik,nama_lengkap,id_kontak_prospek,nama_panggilan,jenis_kelamin,tempat_lahir,tanggal_lahir,kewarganegaraan,email,...,status_pipeline,status_updated_at,assigned_fo,assigned_akademik,catatan_awal_fo,link_form_sent_at,form_completed_at,deleted_at,created_at,updated_at
0,76,BJ2CRSF9J6,42234234234432,76,42234234234432,Laki-laki,None,None,Australia,42234234234432@gmail.com,...,0,2026-05-26 01:13:34.536989,None,None,None,None,2026-01-08 16:50:38,None,2026-01-08 16:50:38,2026-05-26 01:13:34.536989
1,169,RSDUQQDWZU,Abigail Caitlyn Wijaya,169,Caitlyn,Perempuan,None,None,Indonesia,fransisca_angilia@yahoo.co.id,...,done,2025-10-16 10:44:02.000000,None,None,None,None,2025-09-24 17:40:39,None,2025-10-03 11:51:36,2025-10-16 10:44:02.000000
2,208,BDQE3OGKQK,Aca,208,None,None,None,None,None,None,...,follow up another time,2025-10-24 15:27:54.000000,None,None,None,None,2025-10-24 15:27:54,None,2025-10-24 15:27:54,2025-10-24 15:27:54.000000
3,151,A04YSLOZ0C,Achmad Naufal Albiruni,151,Albi,Laki-laki,None,None,None,melisnifuku@gmail.com,...,done,2025-10-03 09:49:15.000000,Bu Lita,None,None,None,2025-09-17,None,2025-09-17 16:49:20,2025-10-03 09:49:15.000000
4,114,8LXPEP6UKT,Achmad Ryan,114,ryan,Laki-laki,None,None,Indonesia,achmadryanivansyah@gmail.com,...,0,2026-05-26 01:13:34.537970,None,None,None,None,2026-02-17 01:21:36,None,2026-02-17 01:21:36,2026-05-26 01:13:34.537970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,127,B6WH4YWNGS,zein achmat alghifari,127,zein,Laki-laki,None,None,Indonesia,zeinstyles74@gmail.con,...,0,2026-05-26 01:13:34.559149,None,None,None,None,2026-03-08 04:57:09,None,2026-03-08 04:57:09,2026-05-26 01:13:34.559149
210,103,S2ISCIRBOQ,zila,103,zila,Perempuan,None,None,Indonesia,almasazzilah02@gmail.com,...,1,2026-05-26 01:13:34.559230,None,None,None,None,2026-02-04 15:05:56,None,2026-02-04 15:05:56,2026-05-26 01:13:34.559230
211,91,LIW4Z07L60,Zufar Tazakka Hanif,91,Zakka,Laki-laki,None,None,Indonesia,zufarzakka@gmail.com,...,0,2026-05-26 01:13:34.559310,None,None,None,None,2026-01-20 10:45:40,None,2026-01-20 10:45:40,2026-05-26 01:13:34.559310
212,153,38J0SBN4YH,Zulfa Bari'atur Rahma,153,Zulfa,Perempuan,None,None,Indonesia,chyzryth@gmail.com,...,done,2025-10-03 09:48:34.000000,Ibu Fitri,None,None,None,2025-09-16,None,2025-09-17 17:32:16,2025-10-03 09:48:34.000000
213,1,LKOQ92Z6KN,Zulfa Bariatur Rahma,1,Zulfa,None,None,None,Indonesia,chyzryth@gmail.com,...,1,2026-05-26 01:13:34.559469,None,None,None,None,2025-09-17 11:34:19,None,2025-09-17 11:34:19,2026-05-26 01:13:34.559469

--------------------------------------------------------------------------------

📂 [🟢 PREVIEW TABEL SUKSES: CALON_SISWA_ORTU]
--------------------------------------------------

,id_calon_ortu,id_calon,nama_ayah,pekerjaan_ayah,pendidikan_ayah,penghasilan_ayah,nama_ibu,pekerjaan_ibu,pendidikan_ibu,penghasilan_ibu,nama_wali,pekerjaan_wali,pendidikan_wali,penghasilan_wali
0,None,76,None,None,None,None,None,None,None,None,None,None,None,None
1,None,169,None,None,None,None,None,None,None,None,None,None,None,None
2,None,208,None,None,None,None,None,None,None,None,None,None,None,None
3,None,151,None,None,None,None,None,None,None,None,None,None,None,None
4,None,114,None,None,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,None,127,None,None,None,None,None,None,None,None,None,None,None,None
210,None,103,None,None,None,None,None,None,None,None,None,None,None,None
211,None,91,None,None,None,None,None,None,None,None,None,None,None,None
212,None,153,None,None,None,None,None,None,None,None,None,None,None,None
213,None,1,None,None,None,None,None,None,None,None,None,None,None,None

--------------------------------------------------------------------------------

📂 [🟢 PREVIEW TABEL SUKSES: CALON_SISWA_AKADEMIK]
--------------------------------------------------

,id_calon_akademik,id_calon,nama_sekolah,jenjang_kelas_1,jenjang_kelas_2,kurikulum_sekolah,id_kursus,id_periode,id_level,preferensi_metode_belajar,...,kemampuan_kustom,kemampuan_komputer,kemampuan_software,penggunaan_gadget,sumber_info,referensi,alasan_daftar,alasan_program,harapan_program,lampiran_file
0,None,76,42234234234432,kelas 1,None,Nasional,K00010,None,None,online,...,None,None,None,None,Teman/kerabat/saudara,None,None,None,None,1767865838_81c8d6404cc32b728d1a.png
1,None,169,Caitlyn,TK B,None,Nasional,K00010,None,None,offline,...,None,None,None,None,Website,None,None,None,None,None
2,None,208,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,None,151,SD Khadijah Wonorejo Surabaya,SD kelas 5,None,CAMBRIDGE,K00010,None,SD,offline,...,None,None,None,None,None,None,None,None,None,None
4,None,114,None,None,None,None,K00005,None,None,offline,...,None,None,None,None,Tiktok,None,None,saya ingin menguasai aplikasi excel,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,None,127,None,None,None,None,K00004,None,None,offline,...,None,None,None,None,Tiktok,None,None,ingin belajar bahasa inggris,None,None
210,None,103,None,None,None,None,K00004,None,None,online,...,None,None,None,None,Website,None,None,learn english,None,None
211,None,91,None,None,None,None,K00005,None,None,offline,...,None,None,None,None,Teman/kerabat/saudara,None,None,Biar bisa kerja,None,None
212,None,153,SMAN 17 Surabaya,None,None,NASIONAL,None,None,SMA/SMK,None,...,None,None,None,None,None,None,None,UPSKILLING,None,None
213,None,1,SMAN 17 Surabaya,X,None,None,K00014,None,None,online,...,None,sudah pernah,Acode,"Handphone,Laptop",Lainnya,None,None,None,Berharap agar dapat mahir dalam memprogram sua...,None

--------------------------------------------------------------------------------

📂 [🟢 PREVIEW TABEL SUKSES: CALON_SISWA_BAYAR]
--------------------------------------------------

,id_calon_bayar,id_calon,nomor_invoice,bank_pembayaran,tanggal_konfirmasi_bayar,bulan_mulai_belajar,lokasi_belajar,status_siswa
0,None,76,None,None,None,None,None,None
1,None,169,None,Mandiri,2025-09-25,September,Sby,done
2,None,208,None,None,None,None,None,None
3,None,151,None,None,None,None,None,None
4,None,114,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...
209,None,127,None,None,None,None,None,None
210,None,103,None,None,None,None,None,None
211,None,91,None,None,None,None,None,None
212,None,153,None,None,None,None,None,None
213,None,1,None,None,None,None,None,None

--------------------------------------------------------------------------------

📂 [🟢 PREVIEW TABEL SUKSES: CALON_SISWA_JADWAL]
--------------------------------------------------

,id_calon_jadwal,id_calon,tanggal_kontak_awal,tanggal_wawancara,konfirmasi_tes,konfirmasi_trial,tanggal_pembayaran,tanggal_masuk,tanggal_keluar
0,None,76,2026-01-08 16:50:38,None,42234234234432,None,None,None,None
1,None,169,2025-09-24 17:40:39,None,Tidak ada,21 BALLOONS SR1 (QORIN),2025-09-25,None,None
2,None,208,2025-10-24 15:27:54,None,None,None,None,None,None
3,None,151,2025-09-17,2025-09-17,Ada,None,None,2025-09-25,None
4,None,114,2026-02-17 01:21:36,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...
209,None,127,2026-03-08 04:57:09,None,None,None,None,None,None
210,None,103,2026-02-04 15:05:56,None,None,None,None,None,None
211,None,91,2026-01-20 10:45:40,None,None,None,None,None,None
212,None,153,2025-09-16,None,None,None,None,None,None
213,None,1,2025-09-17 11:34:19,None,None,None,None,None,None

--------------------------------------------------------------------------------

📂 [🟢 PREVIEW TABEL SUKSES: CALON_SISWA_KURSUS]
--------------------------------------------------

    id_calon_kursus  id_calon urutan nama_kursus jenis_program
0              None        76   None        None          None
1              None       169   None     English          None
2              None       208   None        None          None
3              None       151   None     English            GE
4              None       114   None        None          None
..              ...       ...    ...         ...           ...
209            None       127   None        None          None
210            None       103   None        None          None
211            None        91   None        None          None
212            None       153   None     Digital           COD
213            None         1   None        None          None

[214 rows x 5 columns]

--------------------------------------------------------------------------------

📂 [🟢 PREVIEW TABEL SUKSES: CALON_SISWA_PROSES]
--------------------------------------------------

,id_calon_siswa_proses,id_calon,admin_pengontak,penanggung_jawab,jenis_trial,hasil_trial,waktu_trial_1,waktu_trial_2,tanggal_trial,laporan_trial,...,followup_2,followup_3,akun_leapverse,wa_grup_leapverse,catatan_admin,catatan_penting,keterangan_tambahan,detail_lainnya,created_at,updated_at
0,None,76,None,None,None,None,NaT,NaT,None,None,...,None,None,None,None,None,None,None,None,2026-01-08 16:50:38,2026-05-26 01:13:35.216441
1,None,169,None,None,None,None,0 days,0 days 15:45:00,2025-09-24,None,...,None,None,None,None,None,None,None,None,2025-10-03 11:51:36,2025-10-16 10:44:02.000000
2,None,208,None,None,None,None,NaT,NaT,None,None,...,None,None,None,None,None,None,None,None,2025-10-24 15:27:54,2025-10-24 15:27:54.000000
3,None,151,Bu Lita,None,None,None,NaT,NaT,2025-09-17,None,...,None,None,None,None,None,None,None,None,2025-09-17 16:49:20,2025-10-03 09:49:15.000000
4,None,114,None,None,None,None,NaT,NaT,None,None,...,None,None,None,None,None,None,None,None,2026-02-17 01:21:36,2026-05-26 01:13:35.217062
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,None,127,None,None,None,None,NaT,NaT,None,None,...,None,None,None,None,None,None,None,None,2026-03-08 04:57:09,2026-05-26 01:13:35.240981
210,None,103,None,None,None,None,NaT,NaT,None,None,...,None,None,None,None,None,None,None,None,2026-02-04 15:05:56,2026-05-26 01:13:35.241092
211,None,91,None,None,None,None,NaT,NaT,None,None,...,None,None,None,None,None,None,None,None,2026-01-20 10:45:40,2026-05-26 01:13:35.241192
212,None,153,Ibu Fitri,None,None,None,NaT,NaT,None,None,...,None,None,None,None,None,None,None,None,2025-09-17 17:32:16,2025-10-03 09:48:34.000000
213,None,1,None,None,None,None,0 days,0 days 00:00:00,None,None,...,None,None,None,None,None,None,None,None,2025-09-17 11:34:19,2026-05-26 01:13:35.241386

--------------------------------------------------------------------------------

📂 [🟢 PREVIEW TABEL SUKSES: PENGADAAN]
--------------------------------------------------

,id_pengadaan,deskripsi,url_produk,id_user,status_pengajuan,catatan_admin,tanggal_pengajuan,tanggal_selesai,url_pembelian
0,18,"<p><span style=""font-family: Arial; font-size:...",https://docs.google.com/spreadsheets/d/1B0sVeV...,U00012,Diajukan,None,2023-07-06 11:14:15,NaT,https://docs.google.com/spreadsheets/d/15Xuh2Z...
1,20,"<p>""KABEL TELEPON</p>\r\n<p>kabel roset telepo...",https://docs.google.com/spreadsheets/d/1B0sVeV...,U00012,Diajukan,None,2023-08-03 09:36:19,NaT,https://docs.google.com/spreadsheets/d/15Xuh2Z...
2,21,<p>15 pcs Sarung kursi untuk Lab Komputer (10 ...,https://docs.google.com/spreadsheets/d/1Onr3rr...,U00001,Diajukan,None,2023-08-22 09:58:34,NaT,https://docs.google.com/spreadsheets/d/15Xuh2Z...
3,22,<p>Pembelian 48 pcs Landyard</p>,https://docs.google.com/spreadsheets/d/1Onr3rr...,U00001,Diajukan,None,2023-08-22 10:42:37,NaT,https://docs.google.com/spreadsheets/d/15Xuh2Z...
4,23,"<p>1 ""HEADPHONE JACK</p>\n<p>MBOISGET - PREMIU...",https://docs.google.com/spreadsheets/d/1B0sVeV...,U00012,Diajukan,None,2023-08-28 16:03:09,2023-09-10,https://docs.google.com/spreadsheets/d/15Xuh2Z...
...,...,...,...,...,...,...,...,...,...
105,124,"<p><img src=""data:image/png;base64,iVBORw0KGgo...",https://docs.google.com/spreadsheets/d/1pYJ0oJ...,U00043,Diajukan,None,2026-03-02 16:23:47,NaT,https://docs.google.com/spreadsheets/d/15Xuh2Z...
106,125,"<p><img src=""data:image/png;base64,iVBORw0KGgo...",https://docs.google.com/spreadsheets/d/1pYJ0oJ...,U00043,Diajukan,None,2026-03-09 11:43:19,NaT,https://docs.google.com/spreadsheets/d/15Xuh2Z...
107,126,"<p><img src=""data:image/png;base64,iVBORw0KGgo...",https://docs.google.com/spreadsheets/d/1pYJ0oJ...,U00043,Diajukan,None,2026-03-30 17:40:43,NaT,https://docs.google.com/spreadsheets/d/15Xuh2Z...
108,127,"<p><img src=""data:image/png;base64,iVBORw0KGgo...",https://docs.google.com/spreadsheets/d/1pYJ0oJ...,U00043,Diajukan,None,2026-03-31 10:45:15,NaT,https://docs.google.com/spreadsheets/d/15Xuh2Z...
109,128,"<p><img src=""data:image/png;base64,iVBORw0KGgo...",https://docs.google.com/spreadsheets/d/1pYJ0oJ...,U00043,Diajukan,None,2026-04-01 15:32:25,NaT,https://docs.google.com/spreadsheets/d/15Xuh2Z...

--------------------------------------------------------------------------------

📂 [🟢 PREVIEW TABEL SUKSES: PEMINJAMAN]
--------------------------------------------------

,id_pinjam,tanggal_pinjam,keperluan,id_user,status_pinjam,catatan_sarpras,created_at
0,2,2023-06-11,<p>pinjam kamera - fun class tk mitra - 1 - 11...,U00026,Diajukan,None,2023-06-12 13:20:39
1,3,2023-06-11,<p>1. kamera - fun class TK mitra - 1 - 11 Jun...,U00026,Diajukan,None,2023-06-12 13:21:35
2,5,2023-08-21,<p>1. Tablet Leap - 1 - Jaga-jaga untuk Mid Te...,U00026,Diajukan,None,2023-08-16 15:01:55
3,6,2023-08-23,<p>Pinjam kamera untuk rekaman video checklist...,U00033,Diajukan,None,2023-08-23 10:19:12
4,7,2023-10-11,<p>1. Tablet Leap - 1 - Jaga-jaga untuk Final ...,U00026,Diajukan,None,2023-10-10 15:30:53
...,...,...,...,...,...,...,...
189,192,2026-04-10,"<p><span style=""color: #212529; font-family: R...",U00060,Diajukan,<p>Sudah dikembalikan</p>,2026-04-09 11:40:52
190,193,2026-04-10,"<p><span style=""color: #212529; font-family: R...",U00041,Diajukan,None,2026-04-10 16:26:19
191,194,2026-04-17,<p>List Peminjaman barang kegiatan student app...,U00060,Diajukan,None,2026-04-15 16:06:08
192,195,2026-04-17,"<p><span style=""color: #212529; font-family: R...",U00060,Diajukan,None,2026-04-16 15:22:28
193,196,2026-04-17,"<p><span style=""color: #212529; font-family: R...",U00041,Diajukan,None,2026-04-17 16:22:59

--------------------------------------------------------------------------------

📂 [🟢 PREVIEW TABEL SUKSES: PROBLEM]
--------------------------------------------------

,id_problem,detail_masalah,id_user,status_perbaikan,tanggal_lapor,tanggal_selesai,catatan_teknisi,gambar_problem
0,43,AC Kelas Miss Erika kurang dingin ( belakang,U00012,Diajukan,2023-06-28 16:07:52,NaT,"sudah info ke Pak Irawan,\r\nTukang AC masih l...",None
1,58,Boya/mic untuk kelas hybrid tidak berfungsi (,U00026,Diajukan,2023-07-06 10:45:03,2023-07-17,None,None
2,60,tegangan listrik di ruang kelas belakang dapur...,U00033,Diajukan,2023-07-13 16:59:57,2023-08-10,pemberian stabilizer,None
3,61,ac brisik,U00033,Diajukan,2023-07-14 09:24:29,2023-07-25,sudah tidak berisik,None
4,62,Kabel power monitor PC room 2 longgar. Saat me...,U00036,Diajukan,2023-07-17 15:04:01,2023-07-17,None,None
...,...,...,...,...,...,...,...,...
155,251,"AC room 6 tidak dingin, dan ada air menetes da...",U00050,Diajukan,2026-04-08 16:55:36,2026-04-13,None,None
156,252,AC Ruang 6 (miss Peni) kondisi saat ini di OFF...,U00020,Diajukan,2026-04-09 16:31:44,2026-04-13,AC sudah diperbaiki,/storage/sarpas_images/sarpas_69d772008efe9.jpeg
157,253,Sesi 3. Hybrid. Guru menggunakan mic unt hybri...,U00026,Diajukan,2026-04-13 19:02:53,2026-04-15,None,/storage/sarpas_images/sarpas_69dcdb6dd7663.jpg
158,254,"Bracket TV kurang kenceng, suka geser kedepan ...",U00019,Diajukan,2026-04-16 16:58:21,2026-04-17,None,None
159,255,Baut kursi luluk copot,U00016,Diajukan,2026-04-17 13:14:29,2026-04-17,None,/storage/sarpas_images/sarpas_69e1cfc5c079c.jpg

--------------------------------------------------------------------------------

================================================================================
🏁 PROSES INSPEKSI SELESAI. SILAKAN CEK HASIL DIAGNOSTIK DI ATAS 🏁
================================================================================

In [7]:
# print("================================================================================")
# print(" 🧹 MEMULAI PROSES TRUNCATE DATA GLOBAL - FASE 3 (SISTEM RINGKASAN ATAS) 🧹 ")
# print("================================================================================")

# def truncate_tables_with_summary(db_connection, cursor, ordered_list):
#     truncate_results = {}
    
#     try:
#         # 🔥 SAKTI 1: Matikan benteng Foreign Key checks agar MySQL tidak memblokir penghapusan
#         cursor.execute("SET FOREIGN_KEY_CHECKS=0")
#         db_connection.commit()
#         print("🔓 Sensor Foreign Key Checks berhasil DIMATIKAN sementara.\n")
#     except Exception as e:
#         print(f"✗ Gagal mematikan Foreign Key Checks: {e}")
#         return
        
#     # ----------------------------------------------------------------------------
#     # SUB-LANGKAH A: PROSES EKSEKUSI TRUNCATE DI BELAKANG LAYAR
#     # ----------------------------------------------------------------------------
#     for table_name in ordered_list:
#         try:
#             truncate_query = f"TRUNCATE TABLE `{table_name}`"
#             cursor.execute(truncate_query)
#             db_connection.commit()
            
#             truncate_results[table_name] = {
#                 'status': 'success',
#                 'msg': f"✓ {table_name}: Sukses dibersihkan total! Seluruh baris data amblas."
#             }
#         except Exception as e:
#             db_connection.rollback()
#             truncate_results[table_name] = {
#                 'status': 'failed',
#                 'msg': f"✗ {table_name}: Gagal dikosongkan! Alasan: {e}"
#             }

#     try:
#         # 🔥 SAKTI 2: Wajib nyalakan kembali benteng Foreign Key checks setelah selesai
#         cursor.execute("SET FOREIGN_KEY_CHECKS=1")
#         db_connection.commit()
#         print("🔒 Sensor Foreign Key Checks berhasil DIHIDUPKAN kembali dengan aman.")
#     except Exception as e:
#         print(f"⚠️ Peringatan: Gagal menghidupkan kembali Foreign Key Checks: {e}")

#     # ----------------------------------------------------------------------------
#     # 🔥 CETAK PAPAN RINGKASAN TRUNCATE DI PALING ATAS (ANTI-SCROLL BOARD)
#     # ----------------------------------------------------------------------------
#     print("\n================================================================================")
#     print(" 📊 PAPAN RINGKASAN STATUS TRUNCATE DATABASE (CLEANUP SUMMARY BOARD) 📊")
#     print("================================================================================")
#     for table_name in ordered_list:
#         if table_name in truncate_results:
#             print(truncate_results[table_name]['msg'])
#         else:
#             print(f"⚠️  {table_name}: Lewat dari antrean pembersihan.")
#     print("================================================================================")
    
#     return truncate_results

# # === JALANKAN EKSEKUSI PEMBERSIHAN MENGGUNAKAN DAFTAR TABEL SALING SILANGMU ===
# results_truncate_fase_3 = truncate_tables_with_summary(
#     db_connection=db_new, 
#     cursor=cursor_new, 
#     ordered_list=tables_to_insert_ordered  # Otomatis memakai list urutan saling silang yang kita buat tadi
# )